### ISSUE TITLE
clipboard module, any interest?

### ISSUE THREAD

**Issue by quicknir** [sorin-ionescu/prezto#1000]
I have some code in my personal zsh setup that implements simple clipboard functionality; that is it links zsh's clipboard to the system clipboard. This makes pasting and especially copying much more painless. The code I use is along these lines: http://unix.stackexchange.com/questions/51933/zsh-copy-and-paste-like-emacs. It uses xclip. For a while I just had it in a pile in my preztorc, but eventually I moved it into its own simple module. Would there be interest in this? Would it be necessary to support other command line copy/paste tools other than xclip to get this in, or perhaps start with xclip and add others?

**Comment by sorin-ionescu** [comment]
It may make more sense to be an enhancement to the existing editor module.
Submit a pull request, and we'll look at it. 
Add `pbcopy` and `pbpaste` for Mac OS X.
