### ISSUE TITLE
Custom prompt theme in Linux TTY

### ISSUE THREAD

**Issue by computergeek125** [sorin-ionescu/prezto#1005]
I noticed that in .zprezto/modules/prompt/init.zsh, the shell checks if it is in a dumb terminal and turns any custom prompt off.  I understand the logic in this for a serial terminal type scenario, but why also apply this to the Linux TTY?  I believe this is what is going on in #927 and #754

Bypassing this, I have had no issues running my custom prompt in the TTY.  Would it be possible to add additional options to choose whether to either enable the custom theme on the TTY, or select a second theme to use on the TTY?

This worked for me:

.zpreztorc:

    ...
    # Set the prompt theme to load.
    # Setting it to 'random' loads a random theme.
    # Auto set to 'off' on dumb terminals.
    zstyle ':prezto:module:prompt' theme 'powerlinerds'
    zstyle ':prezto:module:prompt-linux' theme 'clint'
    ...

modules/prompt/init.zsh:

    # Load and execute the prompt theming system.
    autoload -Uz promptinit && promptinit
    
    # Load the prompt theme.
    zstyle -a ':prezto:module:prompt' theme 'prompt_argv'
    zstyle -a ':prezto:module:prompt-linux' theme 'prompt_linux_argv'
    
    if [[ "$TERM" == (dumb|*bsd*) ]] || (( $#prompt_argv < 1 )); then
      prompt 'off'
    elif [[ "$TERM" == "linux" ]];then
      prompt "$prompt_linux_argv[@]"
    else
      prompt "$prompt_argv[@]"
    fi
    unset prompt_argv
    unset prompt_linux_argv

Tested on Ubuntu 14.04.3 LTS with ZSH 5.0.2 from apt-get.

**Comment by sorin-ionescu** [comment]
Why does it identify as dumb and works? If Linux TTY supports xterm-256color, UTF-8, etc., it should not identify as dumb.

**Comment by computergeek125** [comment]
The terminal shows up as "linux".  It's not an xterm.  I got to it from Ctrl+Alt+F1.

**Comment by sorin-ionescu** [comment]
It's [disabled on purpose](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/init.zsh#L13). Link me to the list of capabilities of the LINUX terminal emulator, and when it got them; so, I can write a better check, or you write a better check and open a pull request.

**Comment by computergeek125** [comment]
ok, will do

**Comment by sorin-ionescu** [comment]
It's [disabled on purpose](https://github.com/sorin-ionescu/prezto/issues/1005#issuecomment-152741852) the most likely answer.

**Comment by indrajitr** [comment]
Also cf: #713

**Comment by sorin-ionescu** [comment]
@indrajitr minimal is not the only simple theme available. That's your personal preference.

**Comment by indrajitr** [comment]
Agreed, just kept a reference of similar discussion here.
