### ISSUE TITLE
fpath being clobbered?

### ISSUE THREAD

**Issue by ariscn** [sorin-ionescu/prezto#1007]
I'm adding a directory to my fpath in `.zprofile`:

```
fpath=(
  ~/.zsh/functions
  $fpath
)
```

This works as expected, until I open a sub-shell. When I do that, $fpath reverts to the original prezto version. I have $path defined in the same way in the same file, and sub-shells retain those changes - why is $fpath different?

**Comment by sorin-ionescu** [comment]
Why not make a Prezto module for your custom functions?

**Comment by Eriner** [comment]
`.zprofile` is sourced in the same way `.zlogin` is. Put that in your `.zshenv`. It's an environment assignment.

**Comment by sorin-ionescu** [comment]
You can put it in **zprofile** at line 43.

**Comment by ariscn** [comment]
Yes, I am changing `fpath` in `.zprofile` as I said:

```
typeset -gU cdpath fpath mailpath path

fpath=(
  ...
  $fpath
)

path=(
  ...
  $path
)
```

Per my comments, if I open a subshell with the above config, my $path change is retained, but my $fpath change is overwritten. Is this correct behavior for zsh or a bug in Prezto?

**Comment by sorin-ionescu** [comment]
It's correct behavior. Subshells won't execute shell init scripts. Try to put it in zshrc.
