### ISSUE TITLE
I miss these directory aliases from Oh-my-zsh.

### ISSUE THREAD

**Issue by JesseLeite** [sorin-ionescu/prezto#1018]
I miss these directory aliases from Oh-my-zsh.

```
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
```

Open to implementing this or similar in Prezto?

**Comment by jedahan** [comment]
Something really close, and imho better:

https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zpreztorc#L44-L45

try it out!

**Comment by sorin-ionescu** [comment]
What @jedahan said.

**Comment by JesseLeite** [comment]
Thanks @jedahan
