### ISSUE TITLE
Prompt characters in xterm on OSX

### ISSUE THREAD

**Issue by mjinks** [sorin-ionescu/prezto#1020]
This is less a "feature request" and more a plea for education, but I've looked and failed.

My primary login shell is xterm on X11 on OSX, and depending on the theme I use, most of the characters in my command prompts fail to render, the dreaded "karat-a" display or similar.  ssh to another host doesn't help; switching to Terminal does help; existing environment copied to a Linux desktop looks dandy.

I found some indication that my TERM environment variable might be the culprit.  Switching from 'xterm' to 'xterm-256color' didn't make any difference.

I got somewhere with setting LANG to 'en_US.UTF-8', but all it did was change karat-a to colored rectangles.  'XTERM_LOCALE=en_US.UTF-8' was set when I started all this. 

Cribbing XTerm defaults files from that functional Linux box into my .Xdefaults hasn't made any difference either, which is weird... Maybe I have other missing bits somewhere?

And with that, all my X11 voodoo is pretty well tapped out.

I know the cool kids use Terminal or a third-party term, but I am uncool.  I've shopped, and I always come back home.  So far.

**Comment by sorin-ionescu** [comment]
What does `locale` say?

**Comment by mjinks** [comment]
On Sun, Nov 08, 2015 at 11:15:35PM -0800, Sorin Ionescu wrote:
> What does `locale` say?

Okay, I see (part/most of) my problem.

I knew that my locale was at least part of the issue.  At first, in
xterm:

  ~ âââ locale
  LANG=
  LC_COLLATE="C"
  LC_CTYPE="C"
  LC_MESSAGES="C"
  LC_MONETARY="C"
  LC_NUMERIC="C"
  LC_TIME="C"
  LC_ALL=

And in Terminal,

  ~ ❯❯❯ locale
  LANG="en_US.UTF-8"
  LC_COLLATE="en_US.UTF-8"
  LC_CTYPE="en_US.UTF-8"
  LC_MESSAGES="en_US.UTF-8"
  LC_MONETARY="en_US.UTF-8"
  LC_NUMERIC="en_US.UTF-8"
  LC_TIME="en_US.UTF-8"
  LC_ALL=

But when I started an xterm with those settings, all that changed was
the "âââ" turned to squares, so I didn't think that I had a solution...
But, just now when I pasted those squares here in order to write my
answer (in a Terminal window), they render correctly.

So I understand now.  Once I get my LANG settings straightened out, I
still need to find a different font table.

Thanks.
