### ISSUE TITLE
Overrides/alias diff with git-diff

### ISSUE THREAD

**Issue by sonarforte** [sorin-ionescu/prezto#1023]
Hi, I was just using the diff utility in zsh in iterm (not having modified the zprezto configs at all) and I realized that 

>$ diff foo bar

actually invokes 

>$  git diff foo bar

This can be seen because the above commands actually produce the same output:
```
diff --git a/foo b/bar
index 8270dbc..1e988ad 100755
--- a/foo
+++ b/bar
@@ -13,5 +13,5 @@ different line
another different line
 done
```

I tested this by running a diff command in a bash shell and the output was different from both ```diff``` and ```git diff```:

```
16c16
<
---
> different line
> another different line
```

I have searched through the prezto files by running all manner of ```grep -r 'git diff' .```,```grep -r 'alias diff' .``` commands and I have not been able to find where this is aliased.

Any help would be appreciated.

**Comment by sorin-ionescu** [comment]
Disable `diff` color or install `colordiff`; see https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/functions/diff.
