### ISSUE TITLE
Clone of 'https://gist.github.com/3712874.git' into submodule path 'modules/prompt/external/agnoster' failed

### ISSUE THREAD

**Issue by kaluzki** [sorin-ionescu/prezto#1027]
git clone --recursive https://github.com/sorin-ionescu/prezto

see https://github.com/sorin-ionescu/prezto/blob/master/.gitmodules#L15

**Comment by felixjung** [comment]
Same issue here.

**Comment by Eriner** [comment]
dupe of https://github.com/sorin-ionescu/prezto/issues/940
