### ISSUE TITLE
Sorin theme Git unmerged indicator causes rendering bug in iTerm2

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#1030]
The Unicode character ═ causes the cursor to shift right in iTerm2. It does not happen in Terminal.app. Replace the character as a workaround.

**Comment by gnachman** [comment]
Please file an issue at iterm2.com/bugs and include a debug log reproducing the issue.

**Comment by sorin-ionescu** [comment]
@gnachman Why isn't iTerm2 on GitHub? Forcing users to make GitLab accounts, even though they do not use the product, is an unnecessary barrier to filing bugs. When iTerm2 used Google Project Hosting, at least people had Google Accounts due to Gmail popularity.

**Comment by gnachman** [comment]
Because github doesn't allow people to attach their config files and 90% of bugs require them for me to be able to help.

**Comment by DanyC97** [comment]
@sorin-ionescu fyi you can sign in on GitLab using your GitHub account (i've been doing this on @gnachman project for ages and no problem at all)

**Comment by sorin-ionescu** [comment]
@DanyC97 I did not know. Thank you.

**Comment by belak** [comment]
As far as I can tell this isn't an issue with the latest versions of iTerm2. Please feel free to open another issue (or ping me to reopen this one) if you're still having this problem.
