### ISSUE TITLE
CONTROL-C -ing a django manage.py process outputs that % char and also the ⏎ symbol is not displayed

### ISSUE THREAD

**Issue by danechitoaie** [sorin-ionescu/prezto#1038]
Notice how CONTROL + C looks like when I close a manage.py process vs any other process (sleep in this example).

```bash
(VirtualEnv)~/W/O/app ❯❯❯ python manage.py runserver          develop
Performing system checks...

System check identified no issues (0 silenced).
November 24, 2015 - 17:09:45
Django version 1.8.6, using settings 'fb.settings_dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C%
(VirtualEnv)~/W/O/app ❯❯❯ sleep 10                                           develop
^C
(VirtualEnv)~/W/O/app ❯❯❯                                                     ⏎ develop
```

**Comment by sorin-ionescu** [comment]
It means that no new line is output. It also means that it's returning a 0 return value. Open manage.py and take a peek on how it handles SIGINT.

**Comment by danechitoaie** [comment]
Is there maybe a way prezto can check if string does not end with a new line and add it?
Same seems to be happening if I do `cat file.txt` that doesn't have a new line.

Or is this the intended behavior?

**Comment by sorin-ionescu** [comment]
It's `manage.py` intended behaviour.

**Comment by danechitoaie** [comment]
Regarding Django manage.py yes. But I was saying that I noticed this issue also when using `cat file.txt` if file.txt does not have a new line at the end.

So this happens everywhere where there's no new line outputted at the end.

I was asking if this is the intended behavior of prezto (or the module that does syntax highlight - as I assume this is the module that outputs that % sign) of outputting `%` if there is no line for every output.

**Comment by sorin-ionescu** [comment]
There a shell option that turns it off, as in no `%` is output, but it doesn't insert a newline character for you. I don't remember what's it called.

**Comment by danechitoaie** [comment]
That would be fine also. So outputting that `%` it's intended behaviour to let you know and make it clear that there's no new line? Or it's just an artefact because the script is always expecting a new line and when it doesn't see it something breaks?

**Comment by sorin-ionescu** [comment]
It's an indicator, not an artifact.

**Comment by danechitoaie** [comment]
ok, good to know. thanks.
