### ISSUE TITLE
git module overwrite `ls` when prezto is sourced

### ISSUE THREAD

**Issue by joshuakarjala** [sorin-ionescu/prezto#1039]
If I go into an active Git directory and re-source zsh and type `ls` or `l` I get put into an interactive mode where I can see my git log with detailed information about each commit.

Is this expected?

**Comment by joshuakarjala** [comment]
It seems like these aliases are overriding normal `l` `ls`

```bash
alias gl='git log --topo-order --pretty=format:"${_git_log_medium_format}"'
alias gls='git log --topo-order --stat --pretty=format:"${_git_log_medium_format}"'
```

**Comment by sorin-ionescu** [comment]
I don't see how those can override ls. Don't resource Zsh, `exec zsh` instead.

**Comment by joshuakarjala** [comment]
Same happens with `exec zsh`

**Comment by sorin-ionescu** [comment]
It's something you've changed then. I don't know.
