### ISSUE TITLE
history only going up to 1000, despite module/history/init.zsh setting it to10,000

### ISSUE THREAD

**Issue by esn89** [sorin-ionescu/prezto#1041]
Like the title says, I am having this issue.
I have saw that that's how it is set on the file.  However, whenever I look inside my .zhistory folder, I see that it goes as high as 1153 and that's about it. 

Worst yet, is that my history | grep command seems to only be 50 lines deep, meaning that despite my history file being 1,000 lines long, somehow, history grep can only find the most recent 10-15

**Comment by sorin-ionescu** [comment]
Were you able to fix this? My *~/.zshistory* works fine. It's at 11822.
