### ISSUE TITLE
/bin/zsh exits with [1] segfault after installing Prezto

### ISSUE THREAD

**Issue by prashcr** [sorin-ionescu/prezto#1042]
Running it as a login shell, on a VPS over SSH.  
I'm not sure what else to mention, so let me know.  
  
Clarification: `zsh` didn't exit after installation. It exited whenever I tried running it subsequently.
  
Related question: http://superuser.com/questions/1006722/tmux-exits-with-exited-on-ubuntu-14-04

**Comment by prashcr** [comment]
I just uninstalled Prezto and switched to oh-my-zsh, and everything works now.

I'd still like to try and help pin down the issue if possible.

**Comment by mgee** [comment]
What version of zsh do you have installed? A similar thing happened to me. However, after upgrading zsh from `5.0.2` to a newer version it works. I suspect it was something related to the async feature of the sorin prompt theme.

**Comment by prashcr** [comment]
Hey, yep I was using `5.0.2`, which is the latest in apt.  
Did you compile the latest zsh from source or add a PPA?

**Comment by mgee** [comment]
I installed zsh `5.1.1` using [linuxbrew](https://github.com/Homebrew/linuxbrew) which compiled it from source.

**Comment by prashcr** [comment]
Got it, thanks!

**Comment by bentruyman** [comment]
Just wanted to chime in and say I also experienced this on a vanilla 14.04.3 install. The latest version of zsh on this platform is 5.0.2. But installing 5.2 doesn't experience this issue. Could be something to consider in documentation (unless I missed something).
