### ISSUE TITLE
question regarding zshenv and prezto

### ISSUE THREAD

**Issue by AlJohri** [sorin-ionescu/prezto#1044]
I have a script I would source into my ~/.zshenv before I started using prezto https://github.com/AlJohri/dotfiles/blob/gh-pages/templates/commonenv

but it would generally be pretty slow and I'm pretty sure most of it is in the wrong file

I sourced it in zshenv because some linters from sublime text wouldn't find the command (especially if it was a gem or python package) unless I established pyenv rbenv my path etc.

As I'm moving to prezto, where do you recommend I move most of this? It's just a bunch of environment variables (some with if statements) and some alises.

Thanks!

**Comment by sorin-ionescu** [comment]
Put it in zprofile for now. Then see which parts can be moved to modules. If it's in zshenv, it will be sourced on every shell start as well in every subshell. Hence why it's slow.
