### ISSUE TITLE
ZSH does not load my prezto profile with "sudo -s"

### ISSUE THREAD

**Issue by papiveron** [sorin-ionescu/prezto#1047]
Hi,

I have a little issue with one of my systems.

In fact I've install zprezto there as usual, from my home directory and configure my favorite prompt (bigfade).

It works when I login with my current user account.

But when I make **sudo -s** to become root, my profile is not loaded as in other systems. I look everywhere and didn't see anything, my **/etc/zsh/zshrc** file is configured fine as you can see attached.

The attached picture show how my shell behaves 
![zsh_profile](https://cloud.githubusercontent.com/assets/5762296/11689468/7b01e77e-9e92-11e5-95e2-fd0302b8c7e7.png)

And the txt file is my **/etc/zsh/zshrc** file 
[zshrc.txt](https://github.com/sorin-ionescu/prezto/files/56972/zshrc.txt)

I'm using debian jessie on this only system, the others with wheezy and unbuntu work.

Thank you for your help.

Regards.

**Comment by papiveron** [comment]
Hi I'll close this issue as I can see the solution is to install zprezto in the root home directory.

Regards.

**Comment by sorin-ionescu** [comment]
`sudo -s` works fine here. I would not run Prezto as root. I know not why this happens, but I bet it's Debian-related. Is there an /etc/zprofile?
