### ISSUE TITLE
theme function for non provided theme functions

### ISSUE THREAD

**Issue by papiveron** [sorin-ionescu/prezto#1048]
Hi,

I have a little question.

I saw prezro comes with a set of theme functions available here : **.zprezto/modules/prompt/functions**

But there is not yet a function for all themes, so my question is :
- where **themes** whose set functions setup are not not in the above directory are set up?
- Typically I use and like the **bigfade theme** but for example it doesn't display the git branch in my prompt. I then inspect the code and saw that using **sorin** theme is different as it loads all **git module functions**
- I tried to copy the **prompt_sorin_setup** file to **prompt_bigfade_setup**, and modified it, it works but changes my prompt style (for example the bar color of my bigfade prompt)
- So I would like my bigfade theme to load git module functions too, but keeping the prompt style. Should I absolutely write a **prompt_bigfade_setup** function? Is there a there a default theme function I can customize (maybe **prompt_minimal_setup**)?

Thanks.

Regards

**Comment by sorin-ionescu** [comment]
Some themes come with Zsh and are in its functions directory, for example,  */usr/share/zsh/5.2/functions/*. If you wish to modify a Zsh-supplied theme, copy it to the Prezto themes directory first.
