### ISSUE TITLE
Function `diff` has confusing/inconsistent implementation

### ISSUE THREAD

**Issue by bensaufley** [sorin-ionescu/prezto#1049]
As noted at [StackExchange](http://unix.stackexchange.com/questions/248874/what-is-causing-diff-to-run-git-diff), running `diff` without `colordiff` installed will redirect the user to `git diff`, even if the user's machine has basic `diff` built in. Suggest checking for core `diff` if `colordiff` isn't present, rather than simply falling back to a different functionality.

**Comment by simonbcn** [comment]
I agree. This function is quite annoying. I also don't understand the need for this function.
I have defined `zstyle ':prezto:*:*' color 'yes'` and I have installed `colordiff` in `/usr/bin/colordiff` but when I execute `diff` zsh always executes `git diff`.
```
$ which diff
diff () {
        # undefined
        builtin autoload -XUz
}
```

**Comment by sorin-ionescu** [comment]
It's an autoloaded function; so, it's undefined until you first run it. I agree that its implementation is not ideal.

**Comment by oblitum** [comment]
I was trying do diff a directory here and realized my diff was not the `/usr/bin/diff` that can do the job. I think this issue can be reopened as a bug or feature request. The current behaviour is really not intuitive/expected.

**Comment by oblitum** [comment]
Documenting about installing `colordiff` to solve this seems to also be an option.
