### ISSUE TITLE
prompt -l does not match modules/prompt/functions/

### ISSUE THREAD

**Issue by wdeer** [sorin-ionescu/prezto#1052]
Setting up a fresh CentOS server:
* Installed latest zsh (5.2)
* Installed fresh .zprezto in user's home directory
* Created symlinks to all the setup files to the files in runcoms
* Verified that sorin is specified as default theme in .zpreztorc

but when I try to run `$ prompt -l` I all I get is:
```
Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram
```
which doesn't match at all what is in modules/prompt/functions/ which is:
agnoster cloud damoekri giddie kylewest minimal nicoulaj paradox peepcode powerline pure skwp smiley sorin steeef

When I try to run `$prompt -p sorin` i get:
```
Unknown theme: sorin
```

**Comment by sorin-ionescu** [comment]
Those are Zsh-shipped themes. What does `print -l $fpath` say? It should be like bellow.

```
/Users/sorin/.zprezto/modules/helper/functions
/Users/sorin/.zprezto/modules/completion/external/src
/Users/sorin/.zprezto/modules/utility/functions
/Users/sorin/.zprezto/modules/git/functions
/Users/sorin/.zprezto/modules/archive/functions
/Users/sorin/.zprezto/modules/osx/functions
/Users/sorin/.zprezto/modules/python/functions
/Users/sorin/.zprezto/modules/ruby/functions
/Users/sorin/.zprezto/modules/prompt/functions
/usr/local/share/zsh/site-functions
/opt/homebrew/share/zsh/site-functions
/opt/homebrew/Cellar/zsh/5.2/share/zsh/functions
```

**Comment by hedefalk** [comment]
Have the same issue. I get:

```
viktor@viktors-mbp  ~/dev/projects/kostbevakningen   master  print -l $fpath
/Users/viktor/.zprezto/modules/helper/functions
/Users/viktor/.zprezto/modules/completion/external/src
/Users/viktor/.zprezto/modules/utility/functions
/Users/viktor/.zprezto/modules/prompt/functions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.8/functions
```

**Comment by hedefalk** [comment]
Or similar issue that is. There are question marks or just nothing on my prompt: 
<img width="593" alt="screen shot 2016-01-11 at 14 21 03" src="https://cloud.githubusercontent.com/assets/116520/12234646/c94ff880-b86e-11e5-8098-da4627bb364d.png">

**Comment by alh84001** [comment]
@hedefalk you probably didn't install powerline patched fonts from https://github.com/powerline/fonts
(you can also install them from cask - https://github.com/caskroom/homebrew-fonts)

**Comment by jl4347** [comment]
I ran the `print -l $fpath`, I only get the following:
```
/usr/local/share/zsh/site-functions
/Users/jialunliu/.oh-my-zsh/plugins/autojump
/Users/jialunliu/.oh-my-zsh/plugins/git
/Users/jialunliu/.oh-my-zsh/functions
/Users/jialunliu/.oh-my-zsh/completions
/usr/local/Cellar/zsh/5.0.6/share/zsh/functions
```
How do I add `.zprezto` path into $fpath?

**Comment by sorin-ionescu** [comment]
Why are you using Oh-My-Zsh with Prezto? Delete Oh-My-Zsh. Failure to see Prezto themes is due to a bad installation.
