### ISSUE TITLE
`sudo -s` breaks completion cache

### ISSUE THREAD

**Issue by nfirvine** [sorin-ionescu/prezto#1053]
Not sure if this is YADR's fault, prezto's fault, zsh's fault, homebrew's fault, or my fault but it sure sucks and I can't believe no one has hit it yet.

If you run `sudo -s` to run a shell as root, prezto runs `compinit -i` (skip insecure dirs). Since we're skipping insecure dirs, we skip everything and get no completion as root. Next session as a normal user, .zcompdump is still empty and needs regeneration. AFAIK, zsh will never invalidate its cache by itself; the user needs to do it.

#1010 fixes this, but I'm not totally convinced it's the right way to do it. Perhaps specifying the location of zcompdump to root's home instead?

**Comment by sorin-ionescu** [comment]
I cannot confirm this. Completion works for me as root and **~/.zcompdump** is not empty.

**Comment by nfirvine** [comment]
@sorin-ionescu What are the permissions/owner on the completion files in `$fpath`? All of mine are owned by me, not root, so would therefore not load with `compinit -i`. 

Frankly, I think the security model is flawed. `compinit` treats `$fpath`s as insecure if they're owned by others, but trusts the cache even when it's not. I'll take this up with zsh.

A workaround for prezto would be to force `compinit` to use `~$USER/.zcompdump` as the cache path rather than `$HOME/.zcompdump`.

**Comment by nfirvine** [comment]
Actually, I found out that [a recently fixed bug in awscli's zsh completion](https://github.com/aws/aws-cli/commit/a2498c41b5bb7bbc189d3251081df1971597a510) was causing compinit to run *again*. Updating that looks like its basically fixed the issue. Or at least, I can't repro now :p

Closing.

**Comment by nfirvine** [comment]
Actually, after some more discussion, I've come to the conclusion that default path for zsh should really be `$HOME/.zcompdump.$USER` or something. There should be a separate cache for each (`$USER`, `$SUDO_USER`) pair since that should uniquely map to an `$fpath` set.

As a workaround, I'm doing this: `-d "${ZDOTDIR:-$HOME}/.zcompdump.$USER"` and probably won't bother to fix it beyond that.

**Comment by sorin-ionescu** [comment]
I'll consider this vs #1010. As far as I know, there have been no attacks using completions.
