### ISSUE TITLE
Add option to ignore specific git directories.

### ISSUE THREAD

**Issue by Tmplt** [sorin-ionescu/prezto#1058]
I have a git repo for `~/` which includes config files I want to backup, but I don't want to prezto to list `~/` in the prompt as a git repo (and thus all sub-directories). Could an option to ignore specific directories be added?

**Comment by sorin-ionescu** [comment]
You can edit whatever theme you use to not run `git-info` or `vcs_info` in `$HOME`.

**Comment by sorin-ionescu** [comment]
I forgot since I have not used this in a long time. The feature is there. Execute `git-info off` in your home directory if you use a `git-info` theme.
