### ISSUE TITLE
Setting `TERM` to `tmux-256color` disables color output.

### ISSUE THREAD

**Issue by MaikuMori** [sorin-ionescu/prezto#1059]
I believe when `tmux-256color` is used prezto fails to detect that it's color capable terminal and falls back to colorless command output.

`tmux-256color` is a valid terminfo as of ncurses 6 and is based on `screen-256color`.

This is also causing #957. The mentioned workaround works, but it should be handled correctly.

**Comment by sorin-ionescu** [comment]
Prezto turns off colours for `"$TERM" == (dumb|linux|*bsd*)`.

**Comment by MaikuMori** [comment]
You're right. Just tried with `bash` and I get the same result when doing `ls --color` - works with `TERM=screen-256color`, doesn't work with `TERM=tmux-256color`

So the issue is in the commands themselves. Closing.

**Comment by MaikuMori** [comment]
For anyone else wondering the bug is in `coreutils` and the fix will be in `coreutils-8.25`. It's tracked [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=791921).
