### ISSUE TITLE
Sorin theme has some spaces between cursor and prompt on SSH+tmux

### ISSUE THREAD

**Issue by lamnk** [sorin-ionescu/prezto#1061]
Prezto with sorin theme works on my local machine (OS X 10.11.2 El Capitan).

However on my server (Archlinux) there are some glitches. Please see the screenshots below

EDIT: maybe it has something to do with encoding, because when I changed $LANG to *en_US.UTF-8* then the cursor is placed correctly

Another question: why the color of my username in tmux is different than in SSH?

Prezto with SSH:
![Prezto with SSH](http://i.imgur.com/CGOKka8.png)

Prezto with SSH + tmux:
![Prezto with SSH + tmux](http://i.imgur.com/RPiTGfl.png)

**Comment by slester** [comment]
I can confirm the same thing happening, and it gives very strange results with autocomplete as well.

`cat (tab)` gives me the following:

![image](https://cloud.githubusercontent.com/assets/104014/12311581/e00ebfbc-ba0c-11e5-9553-e807b24804a4.png)

**Comment by orrsonn** [comment]
I had the same issue on various machines with and sometimes without ssh.
I tracked it down to problems with wrongly set LANG variable.

try ```locale``` if something only says "C" thats the problem

I fixed it with following lines in .zprofile

```
# fixes strange cursor position / formating bug
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by chikitulfo** [comment]
I can confirm the same problems with glitch and autocomplete on a custom theme under Arch.

And the fix suggested by @orrsonn solved it (although in my case I fixed it set a system wide locale)
