### ISSUE TITLE
key conflict eg. ctrl+p , ctrl+a

### ISSUE THREAD

**Issue by imdecoder** [sorin-ionescu/prezto#1062]
when I try to use ctrl+p or ctrl+n to go through the command history, it will output `^P` or `^N`
then I have to use up/down

my module list
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'homebrew' \
  'archive' \
  'fasd' \
  'git' \
  'osx' \
  'ruby' \
  'rails' \
  'node' \
  'tmux' \
  'syntax-highlighting' \
  'history-substring-search' \
  'ssh' \
  'prompt'
```

And the key ctrl+p, ctrl+n or ctrl+a works after I removed `editor`, `fasd`, `osx` and `history-substring-search` (i tried different combinations , it seems I must delete all those four to let it work)

anyone has any same issues ?

**Comment by jrgarcia** [comment]
@imdecoder What is `':prezto:module:editor'` set to in your `.zpreztorc` file? My guess would be that it's set to `vi` rather than `emacs`.

**Comment by sorin-ionescu** [comment]
Ensure `zstyle ':prezto:module:editor' key-bindings 'emacs'`.
