### ISSUE TITLE
zsh + tmux  loses history substring search functionality

### ISSUE THREAD

**Issue by esn89** [sorin-ionescu/prezto#1065]
noticed that that seems to happen, despite enabling the tmux module.  I have set my $TERM to rxvt-unicode-256color, is there something i am missing out on?

**Comment by sorin-ionescu** [comment]
This seems to be a duplicate of #1059.

**Comment by sorin-ionescu** [comment]
What does tmux have to do with history-substring-search?

**Comment by Ulu2005** [comment]
Met same issue when I have $TERM=screen256-color and "tmux-256color" in tmux default-terminal option. Then resolved this by setting default-terminal in tmux to "screen-256color".

**Comment by neverfox** [comment]
> What does tmux have to do with history-substring-search?

Probably issue with terminfo key bindings.
