### ISSUE TITLE
Prompt theme does not auto-load

### ISSUE THREAD

**Issue by huijing** [sorin-ionescu/prezto#1066]
When I start up iTerm2, this is how it looks. 
<img width="564" alt="1_____zsh__and_new_issue_ _sorin-ionescu_prezto" src="https://cloud.githubusercontent.com/assets/1461498/12526573/ab343b4c-c1a9-11e5-9c6d-cb5694bf2f36.png">
I need to run `prompt paradox` for the theme to display. 
<img width="559" alt="1_____zsh__and_runcoms_and_new_issue_ _sorin-ionescu_prezto" src="https://cloud.githubusercontent.com/assets/1461498/12526601/06911672-c1aa-11e5-85c7-39bdf1f65ebf.png">
I already set this line in my .zpreztorc. 

    zstyle ':prezto:module:prompt' theme 'paradox'
Is there anything else I need to do for it to work?

**Comment by jl4347** [comment]
Why don't you try adding `prompt paradox` into the `.zshrc` config file?

Just saying, it might work.

**Comment by huijing** [comment]
@jl4347 I already have that line in my `.zshrc` file

**Comment by jl4347** [comment]
@huijing I installed the latest version and did not find this problem.

I switched from OMZ to zprezto lately so I have to completely uninstall OMZ first and then do the rest of the thing like discussed in the repo's issue. I am not sure if that applies to you or not.

Also I am using Terminal instead of iTerm2.

**Comment by sorin-ionescu** [comment]
You have code that's overwriting theme selection. Then you overwrite it again manually.

**Comment by arunvelsriram** [comment]
Hi. Am facing this issue. I changed the theme name in `~/.zpreztorc` file. But its not applying the theme. Am using iTerm.

**Comment by osrocha** [comment]
@huijing if you use YARD (https://github.com/skwp/dotfiles), there are a file named theme.zsh in the ~/.yard/zsh directory which overwrites the original configuration.
