### ISSUE TITLE
git-info never counts deletions, but overcounts additions

### ISSUE THREAD

**Issue by totycro** [sorin-ionescu/prezto#1067]
If you delete a file in git via `git rm`, the function `git-info` in `modules/git/functions/git-info` will count that file under `added` and not under `deleted`.

The output of `git status --porcelain` however shows:
`D  deleted_file`

The problem is that in line 340 of the file `git-info`, the pattern for deletions is as follows:
`[[ "$line" == [\ ACMRT]D\ * ]] && (( deleted++ ))`
Hence it requires a character in front of "D". A possible fix would be the following line (check [here](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Operators) for documentation on globbing):
`[[ "$line" == [\ ACMRT]#D\ * ]] && (( deleted++ ))`

Moreover, additions are counted in line 340 as follows:
`[[ "$line" == ([ACDMT][\ MT]|[ACMT]D)\ * ]] && (( added++ ))`
Hence lines starting with "D", followed by a space, are also counted as `added`, which IMO is wrong in the given case. Here, one might just remove the first occurrence of "D".

I can provide a pull requests for the fix if required.

**Comment by sorin-ionescu** [comment]
Added means **added to the index**. It has caused confusion in the past. This is a duplicate of #740.
