### ISSUE TITLE
Enable "Alternate Screen Mode" in OSX

### ISSUE THREAD

**Issue by ivancuric** [sorin-ionescu/prezto#1069]
Ok, how do you enable the alternate screen modes in less / man and similar outputs (enables scrolling with the mouse wheel)? 
The best I could find is setting `export LESS='-g -i -M -R -w -z-1'` in `.zshrc`

**Comment by sorin-ionescu** [comment]
You'll have to read the LESS man page. That variable is set in `zprofile`.
