### ISSUE TITLE
TMPDIR sets environment variable, messes with system services

### ISSUE THREAD

**Issue by bax-** [sorin-ionescu/prezto#1074]
TMPDIR, as it's set in .zprofile, creates an environment variable which is then used by services like mktemp in FreeBSD.
If I log in as user XY and then `su - root`, the wrong directory (/tmp/XY) is then being used…

**Comment by sorin-ionescu** [comment]
Why are you using `su` instead of `sudo`? You're changing users; so, it should use the temp directory of your new user as experienced.

**Comment by bax-** [comment]
Why wouldn't I?
The problem is the point where presto overrides the TMPDIR variable so that it overrides system defaults I think…

**Comment by sorin-ionescu** [comment]
I added that variable for OS X. It's what I use. As far as I recall no one has raised a issue with it before you. What's the default on your system? You can always modify your fork to suit you.

**Comment by bax-** [comment]
I'm on FreeBSD, normally it is just `/tmp`
https://docs.freebsd.org/info/cvs/cvs.info.Environment_variables.html
