### ISSUE TITLE
Set prompt color while in vi-mode

### ISSUE THREAD

**Issue by breerly** [sorin-ionescu/prezto#1077]
Looking to change the cursor color to red while in vi-mode, something like [this](http://ivyl.0xcafe.eu/2013/02/03/refining-zsh/#vi_mode_status_indicator). 

I'm using the minimal theme.

Is this possible?

Thanks

**Comment by sorin-ionescu** [comment]
It is, but you'll have to either edit the ZLE functions inside **editor/init.zsh** or dynamically inside the minimal theme with, for example, `functions[zle-line-init]="<change cursor here>; $functions[zle-line-init]`. Essentially you are prepending code to the function body.
