### ISSUE TITLE
Custom Expansion of Prompt Sequences?

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#1079]
I want my iTerm tab title to match my prompt. Is it possible to do something like:

```
zstyle ':prezto:module:terminal:tab-title' format '%m: ${${${${(@j:/:M)${(@s:/:)PWD/#$HOME/~}##.#?}:h}%/}//\%/%%}/${${PWD/#$HOME/~:t}//\%/%%}'
```
Format taken from:

https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L35-L44

This sort-of works but only when the tab originally opens. `cd`ing around doesn't update the tab title.

So I think something linke a "custom expansion" is needed? Kind of feeling around in the dark here because I am really not sure. Thanks for any insights.

**Comment by sorin-ionescu** [comment]
Search *zpreztorc* for **auto-title**.

**Comment by leoj3n** [comment]
Thanks, I found [these docs](http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#index-builtins_002c-utility):

<dl compact="compact">
<dt><tt>zstyle</tt> [ <tt>-</tt> | <tt>-</tt><tt>-</tt> | <tt>-e</tt> ] <var>pattern</var> <var>style</var> <var>string</var> ...</dt>
<dd><a name="index-reply_002c-use-of-4"></a>
<p>Defines the given <var>style</var> for the <var>pattern</var> with the <var>string</var>s as
the value.  If the <tt>-e</tt> option is given, the <var>string</var>s will be
concatenated (separated by spaces) and the resulting string will be
evaluated (in the same way as it is done by the <tt>eval</tt> builtin
command) when the style is looked up.  In this case the parameter
‘<tt>reply</tt>’ must be assigned to set the strings returned after the
evaluation.  Before evaluating the value, <tt>reply</tt> is unset, and
if it is still unset after the evaluation, the style is treated as if
it were not set.
</p>
</dd>
</dl>

And ended up doing the following in `runcoms/zpreztorc`:

```
#
# Set the tab title format.
#

function tab_title {
  local pwd="${PWD/#$HOME/~}"

  if [[ "$pwd" == (#m)[/~] ]]; then
    echo "$MATCH"
    unset MATCH
  else
    echo "${${${${(@j:/:M)${(@s:/:)pwd}##.#?}:h}%/}//\%/%%}/${${pwd:t}//\%/%%}"
  fi
}

zstyle -e ':prezto:module:terminal:tab-title' format 'reply=$(tab_title)'
```

👍
