### ISSUE TITLE
http-serve does not work in Arch Linux

### ISSUE THREAD

**Issue by m45t3r** [sorin-ionescu/prezto#1080]
In Arch Linux, `/usr/bin/python` points to Python 3.x and not Python 2.x. So using `http-serve` results in the following error:

```
/usr/bin/python: No module named SimpleHTTPServer
```

I think there should be a way to select which Python interpreter to use, so Arch Linux users could set it to `/usr/bin/python2`. Another user case: some distros may not install Python by default, and the user may install Python in their home directory or `/opt`.

**Comment by m45t3r** [comment]
An alternative would be to do something like below:

    alias http-serve='python -m SimpleHTTPServer 2> /dev/null || python -m http.server 2> /dev/null

This would work in all cases, Python 2/3 and even installations in custom paths.

**Comment by grandchild** [comment]
Just set all occurrences of python to python2? Usually things are symlinked that way...

**Comment by m45t3r** [comment]
@grandchild can't do this in Arch. Packages in Arch expect `/usr/bin/python` to point to Python 3, so doing what you say would break almost all Python programs.

And while `/usr/bin/python` is generally Python 2, [PEP394](https://www.python.org/dev/peps/pep-0394/) recognizes that the behavior in Arch Linux is not wrong, and scripts that point directly to `/usr/bin/python` should run on both (there is a **recomendation** that `/usr/bin/python` points to python2, however this is not mandatory).

I think my fix is pretty simple and should work in all cases. Another option would be to change the alias to explicit point to either Python 2 or Python 3:

    alias http-serve='python3 -m http.server' # or alias http-serve='python2 -m SimpleHTTPServer'

This would break only old distros that does not ship Python 3 by default, and in the second case it would break distros that does not follow PEP394 (so there is no `python2`, only `python`). In either case, the distro in simple too old (Debian 6 and CentOS 5.x comes in mind).

Remember that new distros are pushing Python 3 as the only Python installed by default (see [Ubuntu 16.04](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#Python_3) and [Fedora 23](https://fedoraproject.org/wiki/Changes/Python_3_as_Default)), so http-serve would be broken in default install if `python2` is used. However with `python3`, Mac OSX would be broken by default (I think? I don't have Mac OSX).

**Comment by grandchild** [comment]
Oh I think you misunderstood. I meant changing the python command in here, in prezto. This would not break anything for any other system, as long as they have a `/usr/bin/python2`.
I run Arch myself. ;)
