### ISSUE TITLE
~RVM_PROJECT_PATH is shown in the path

### ISSUE THREAD

**Issue by shineycode** [sorin-ionescu/prezto#1081]
I have the latest & greatest (commit 7227c4f0bef5f8ae787c65150d7a7403394fff48) and after installing and configuring zprezto to use 'minimal' for prompt, my command line reports ~RVM_PROJECT_PATH - [branch-name●] instead of the current working directory. It doesn't matter which prompt I change to, I see the same result.

I'm running Mac OS 10.11.3

**Comment by sdomula** [comment]
I have the same effect when using test-kitchen. After some time the prompt changes to:
~_kitchen_instances_cache_dir (branch-name).

I am also running Mac OS 10.11.3

**Comment by sorin-ionescu** [comment]
Add `unsetopt AUTO_NAME_DIRS` to zshrc.
