### ISSUE TITLE
tab completion does not work for .. (dir up)

### ISSUE THREAD

**Issue by dpkshrma** [sorin-ionescu/prezto#1083]
On a usual bash terminal typing `..` , and hitting tab changes it to `'../'` which is very convenient. On pressing tab second time, bash looks up in parent directory.
But on prezto, it says `-- no matches found --`. Any chances prezto can re-enable that feature?

**Comment by sorin-ionescu** [comment]
I cannot reproduce. It works as expected. I type `../[tab]`, and it works fine.

**Comment by Graunephar** [comment]
I think the OP just meant ".."[tap] not "../" [tap]

At lest i'm very annoyed that I cannot just type" .." and then hit tap, but have to type"../"

Not sure if this specific to prezto, but if there is a fix I would love to know about it.

**Comment by Graunephar** [comment]
For anyone else finding this issue via Google as I did, searching for the answer to "autoslashing" the dot dot dir.

The answer is described here: https://github.com/robbyrussell/oh-my-zsh/issues/3775

Just set the following in your .zrpreztorc file: 
zstyle ':completion:*' special-dirs true

Worked for me :)
