### ISSUE TITLE
Last Command beggining with

### ISSUE THREAD

**Issue by Swoorup** [sorin-ionescu/prezto#1085]
On zsh,

Suppose I ran `tmux a -d`. Next time, I am able to just type `t` and press the up arrow key and it brings up the last command that beginned with `t` which is `tmux a -d`. 

On prezto, it simply brings back the previous command without any considerations for the keys typed. 

Is it possible to recreate or restore this behaviour?

**Comment by nasenatmer** [comment]
You want `history-substring-search` enabld in `.zproztorc`

**Comment by Swoorup** [comment]
Do you mean these?
`
# Set the query found color.
zstyle ':prezto:module:history-substring-search:color' found ''

# Set the query not found color.
zstyle ':prezto:module:history-substring-search:color' not-found ''

# Set the search globbing flags.
zstyle ':prezto:module:history-substring-search' globbing-flags ''
`

Doesn't seem to still work.

**Comment by nasenatmer** [comment]
I quote from the README:

> ## Modules
> 1. Browse /modules to see what is available.
> 2. Load the modules you need in ~/.zpreztorc then open a new Zsh terminal window or tab.

**Comment by Swoorup** [comment]
Sorry, my bad.

**Comment by Igor10k** [comment]
`history-substring-search` works diferently. It matches the whole string, not just the beginning. So in case with `tmux` if I ran for example `cd /tmp` after `tmux -a -d` and after that I'll try to type `t` and press up I'll get `cd /tmp` because it has a `t` in it.

**Comment by Igor10k** [comment]
Got the wanted behavior by disabling `history-substring-search` module and adding to `.zshrc`:

```bash
# Keybindings
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi

if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi
```
