### ISSUE TITLE
remove use of .zprofile

### ISSUE THREAD

**Issue by axsk** [sorin-ionescu/prezto#1090]
According to the [official zsh introduction](http://zsh.sourceforge.net/Intro/intro_3.html#SEC3)

> '.zprofile' is meant as an alternative to `.zlogin' for ksh fans; the two are not intended to be used together, although this could certainly be done if desired.

To make it even worse .zprofile currently contains the lines 
```
path=(
  /usr/local/{bin,sbin}
  $path
)
```
leading to some unexpected behaviour when using the `.zshenv`, the file which should actually be used for environment variables, c.f.
> It should contain commands to set the command search path, plus other important environment variables.

When setting the path in it it will get prefixed by the later invokation of `.zprofile`, which prohibited me from starting the right python version for quite some time :(

I think the contents of `.zhenv` should be replaced by `.zprofile`, and the latter should be removed.
As far as I can tell this does not change any behaviour but goes in line with the zsh documentation.

**Comment by sorin-ionescu** [comment]
It is the way it is to work around the Mac OS X [`path_helper`](https://github.com/sorin-ionescu/prezto/search?q=path_helper&type=Issues&utf8=%E2%9C%93).

**Comment by PaBLoX-CL** [comment]
`.zprofile` is used in arch linux too.
