### ISSUE TITLE
Weird message at shell startup

### ISSUE THREAD

**Issue by jl4347** [sorin-ionescu/prezto#1091]
I have recently switch from OMZ to prezto because I really loved the paradox theme.

After struggling for a whole day, I managed to get the paradox theme working. However, there is always a bunch of weird message display when new terminal opens:
```
ln: /Users/jialunliu/.zlogin: File exists
ln: /Users/jialunliu/.zlogout: File exists
ln: /Users/jialunliu/.zpreztorc: File exists
ln: /Users/jialunliu/.zprofile: File exists
ln: /Users/jialunliu/.zshenv: File exists
ln: /Users/jialunliu/.zshrc: File exists
```

I could not figure out what is happening since all the files mentioned above has already been linked.
```
lrwxr-xr-x     1 jialunliu  staff      40 Feb 28 15:38 .zlogin@ -> /Users/jialunliu/.zprezto/runcoms/zlogin
lrwxr-xr-x     1 jialunliu  staff      41 Feb 28 15:38 .zlogout@ -> /Users/jialunliu/.zprezto/runcoms/zlogout
drwxr-xr-x    10 jialunliu  staff     340 Feb 28 15:34 .zprezto/
lrwxr-xr-x     1 jialunliu  staff      43 Feb 28 15:38 .zpreztorc@ -> /Users/jialunliu/.zprezto/runcoms/zpreztorc
lrwxr-xr-x     1 jialunliu  staff      42 Feb 28 15:38 .zprofile@ -> /Users/jialunliu/.zprezto/runcoms/zprofile
lrwxr-xr-x     1 jialunliu  staff      40 Feb 28 15:38 .zshenv@ -> /Users/jialunliu/.zprezto/runcoms/zshenv
-rw-r--r--     1 jialunliu  staff    2711 Feb 28 16:29 .zshrc
```

It does not affect zsh functions that I could notice so far. But it is super annoying, could anyone please help me solve the problem?

Thank you!

**Comment by jl4347** [comment]
Sorry, I found the answer in the closed issues.

This is due to the installation code pasted on repo's homepage, simply rewrite `ln -s` to `ln -fs` to force overwrite.

**Comment by robbie8709** [comment]
How did you solve it?

**Comment by yushangakki** [comment]
in the .zshrc you replace `ln -s` to `ln -fs`
