### ISSUE TITLE
Git icons not loading properly and unsure how to fix

### ISSUE THREAD

**Issue by rbatta** [sorin-ionescu/prezto#1092]
Hi, I've got a fairly recent version of prezto, but am using an older prompt module because I liked that better than the new one (and don't really know how to change the new one to look like the old one).

The prompt module is the default sorin one, but it's a previous version where the git:branch was part of the prompt and not on the far right side as it is/was in the newer version. However, just recently I noticed that my git icons are not displaying and instead come up with the icon name, like `:arrow_up:` instead of the up-arrow/ :arrow_up: .

```~/D/n/forms git:document-forms ❯❯❯ gs                                                     :arrow_up: ✚ ✱ :black_medium_square:```

I assume it's an incompatibility between my old prezto vs newer one (or rather, using ASCII? vs icons.) Here is the prompt module snippet for the git icons:

```  # Set git-info parameters.
  zstyle ':prezto:module:git:info' verbose 'yes'
  zstyle ':prezto:module:git:info:action' format ':%%B%F{yellow}%s%f%%b'
  zstyle ':prezto:module:git:info:added' format ' %%B%F{green}✚%f%%b'
  zstyle ':prezto:module:git:info:ahead' format ' %%B%F{yellow}:arrow_up:%f%%b'
  zstyle ':prezto:module:git:info:behind' format ' %%B%F{yellow}:arrow_down:%f%%b'
  zstyle ':prezto:module:git:info:branch' format ':%F{green}%b%f'
  zstyle ':prezto:module:git:info:commit' format ':%F{green}%.7c%f'
  zstyle ':prezto:module:git:info:deleted' format ' %%B%F{red}:heavy_multiplication_x:%f%%b'
  zstyle ':prezto:module:git:info:modified' format ' %%B%F{blue}✱%f%%b'
  zstyle ':prezto:module:git:info:position' format ':%F{red}%p%f'
  zstyle ':prezto:module:git:info:renamed' format ' %%B%F{magenta}➜%f%%b'
  zstyle ':prezto:module:git:info:stashed' format ' %%B%F{cyan}✭%f%%b'
  zstyle ':prezto:module:git:info:unmerged' format ' %%B%F{yellow}═%f%%b'
  zstyle ':prezto:module:git:info:untracked' format ' %%B%F{white}:black_medium_square:%f%%b'
  zstyle ':prezto:module:git:info:keys' format \
    'prompt' ' %F{blue}git%f$(coalesce "%b" "%p" "%c")%s' \
    'rprompt' '%A%B%S%a%d%m%r%U%u'```

Should I simply override the `:arrow_up:` and put in the equivalent symbol instead?  Thanks.

**Comment by sorin-ionescu** [comment]
What defines `:arrow_up:`, `:black_medium_square:`, etc? Those have never been part of my theme.

**Comment by rbatta** [comment]
To be honest I have no idea! This computer is rather new so I wasn't sure if it was the computer that did it or the copy paste of the older code or what.  The `:arrow_up:` is what showed up in my zsh. 

In any case I ended up checking your prompt module and swapping them for the actual icons, like ➜ which seemed to have worked, so I'm closing this.

Thanks for an awesome zsh config!

**Comment by sorin-ionescu** [comment]
It looks like emoji. If you type ':' in the GitHub comment box, it shows emoji with those names. I have never used emoji in my theme.
