### ISSUE TITLE
Capture output from last command

### ISSUE THREAD

**Issue by joshjordan** [sorin-ionescu/prezto#1098]
Hi all!

This is something I've been looking for for awhile. It may exist, and I am just being ignorant. Alternatively, it may be easy to implement, and I'm happy to do so myself. Or maybe it's a stupid idea and you know better. I would appreciate your guidance.

Is there any simple way to refer to the output of the last command? There is `!!`, and many other such macros, but those actually cause us to rerun the last command. My use case is this (and I feel like it is a common one, but I may be wrong):

1. Run a long-running command
2. Realize there was too much output, or the output needed to be transformed
3. Re-run the command, but now piped to `grep`, `sed`, etc. This may happen multiple times.

Am I crazy?

**Comment by joshjordan** [comment]
To be clear, I am looking for something that is common in many REPLs, wherein the last output is captured as a variable. For example, in `irb`, the last value can be referred to by `_`

**Comment by sorin-ionescu** [comment]
As far as I know, there is not.

**Comment by joshjordan** [comment]
Thanks, @sorin-ionescu. Can you point me at an example to work from?

**Comment by sorin-ionescu** [comment]
I don't know of an example. Write a wrapper function to append `>! foo.log` to a command. Then read it with `print < foo.log`. Use aliases to make them shorter.

**Comment by joshjordan** [comment]
Understood. The actual functions to write are quite simple. I was hoping for an example of a wrapper function that hooked in at the right time. It appears that there is not a good hook that allows us to either 1) rewrite the command after history has been written, so that the use never has to see the logging commands or 2) capture the output buffer. The closest I found was getting in front of `zle accept-line`, but that unfortunately precedes history so the user actually sees their command turned into `original-cmd >! foo.log` on the command line.

**Comment by sorin-ionescu** [comment]
Maybe iTerm2 has some features you want.

**Comment by arizzubair** [comment]
@joshjordan , this might interest you:
https://unix.stackexchange.com/a/9032/341650
