### ISSUE TITLE
CDPATH stopped working

### ISSUE THREAD

**Issue by ChiliConSql** [sorin-ionescu/prezto#1100]
my .zprezto/runcoms/zpropfile has the following:
cdpath=(
  $cdpath
  $HOME/Documents:$HOME/Documents/Projects
)

```
echo $CDPATH
```
produces the expected result.
However:
```
cd Projects
```
doesn't work, but
```
export CDPATH=$CDPATH
cd Projects
```
does work.
I am using zsh version 5.1.1 on Fedora 23

**Comment by sorin-ionescu** [comment]
It's an array; so, it should be the following.

```zsh
cdpath=(
  $cdpath
  $HOME/Documents
  $HOME/Documents/Projects
)
```

**Comment by ChiliConSql** [comment]
You are awesome!!
Thank you.
