### ISSUE TITLE
Provide option to automagically switching node version

### ISSUE THREAD

**Issue by wadkar** [sorin-ionescu/prezto#1102]
#### What

Could we provide an option to _automagically_ switch node version based on `.nvmrc` file in current directory?
#### How

[NVM documentation discusses](https://github.com/creationix/nvm#zsh) a `zsh-hook` to be called on `chpwd` to read and change node version based on `.nvmrc` file:

``` zsh
# Call nvm use automagically when entering a directory containing .nvmrc
load-nvmrc() {
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
  fi
}
add-zsh-hook chpwd load-nvmrc
```
#### Why

The `ruby` module [provides an option](https://github.com/sorin-ionescu/prezto/blob/f2a826e963f06a204dc0e09c05fc3e5419799f52/modules/ruby/init.zsh#L29) `zstyle ':prezto:module:ruby:chruby' auto-switch 'yes'` for a similar functionality for changing `ruby` version.
It might be a good idea to provide a similar option for `nvm`, given that both work similarly.
#### Who

I am willing to provide a PR, by simply slapping the code from the above section inside an if conditional after [this line](https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/node/init.zsh#L21). Look:

``` zsh
if (( $+commands[nvm] )); then
  if zstyle -t ':prezto:module:node:nvm' auto-switch; then
    # Call nvm use automagically when entering a directory containing .nvmrc
    load-nvmrc() {
      if [[ -f .nvmrc && -r .nvmrc ]]; then
        nvm use
      fi
    }
    add-zsh-hook chpwd load-nvmrc
  fi
fi
```

However, I am not sure if `load-nvmrc()` is in the right place (maybe inside `functions` directory? IDK!)

**Comment by fa7ad** [comment]
+1 because I like the idea.
But I think "n" (available on npm) is a better way to change versions (as opposed to nvm)

just my personal opinion.

**Comment by wadkar** [comment]
@sorin-ionescu let me know if you're interested in picking this up.
I rather not create a PR for something trivial like this. Would you mind pulling this in yourself in the next release of prezto?

**Comment by wadkar** [comment]
@fa7ad I am not familiar with `n` but I think the option `zstyle -t ':prezto:module:node:nvm' auto-switch` passed to `prezto` makes it pretty clear the option is for nvm specific hook available for zsh.

**Comment by mmintel** [comment]
open since 3 years, any news on this? :D

**Comment by wadkar** [comment]
@mmintel I had it in my .zshrc for a long time but I recently started using `nodenv` instead of `nvm`.

If there is sufficient interest, I won't mind creating a PR and asking maintainers to review and merge it. The following code snippet will work just fine if you slap it at the end of your .zshrc:

```
    load-nvmrc() {
      if [[ -f .nvmrc && -r .nvmrc ]]; then
        nvm use
      fi
    }
    add-zsh-hook chpwd load-nvmrc
```

**Comment by srijanshetty** [comment]
I use [autoenv](https://github.com/Tarrasch/zsh-autoenv) which allows me to have a .autoenv file to run arbitrary shell scripts in any folder I cd into. It also adds integrity checks using checksums to ensure that we don't load any untrusted shell code which is a great security feature.

**Comment by mosauter** [comment]
Just wanted to provide my solution as well here, in case someone comes around.

The loading of the module is not required by me and it takes between 0.5-1 seconds on my machine. Therefore I wanted something I can enable when needed but not active all the time. 

```
function enableNode() {
    pmodload 'node'
    export RPROMPT='$node_info[version]'
    zstyle ':prezto:module:node:info:version' format '%v'
    node-info

    load-nvmrc() {
        if [[ -f .nvmrc && -r .nvmrc ]] ; then
            nvm use
            node-info
        fi
    }
    add-zsh-hook chpwd load-nvmrc
}
```

If you are using a right prompt in your theme you probably need to change that a little :)
