### ISSUE TITLE
after adding module syntax-highlighting, it shows broken pipe.

### ISSUE THREAD

**Issue by funnyEagle** [sorin-ionescu/prezto#1103]
adding the module before prompt, and restart iterm2, it shows message ''broke pipe''.

Any idea what happened here?

Thanks a lot.

**Comment by beanaroo** [comment]
did you possibly forget to escape the new line? Like so:

```
  'syntax-highlighting' \
  'prompt'
```

**Comment by belak** [comment]
Duplicate of #1026
