### ISSUE TITLE
Autocomplete of `cd` picks up random functions

### ISSUE THREAD

**Issue by ChrisJefferson** [sorin-ionescu/prezto#1106]
In an empty directory, type: `cd pr` and types tab completing, I get: `cd _prompt_sorin_precmd_async_data/`

Obviously, I don't really want that :) If that doesn't appear for other people, I can try and track down exactly what combination of packages is causing it.

**Comment by stefanosc** [comment]
I just tried it and it does happen for me if tab completion doesn't find 
anything in the current folder that begins with pr
However if I am in folder that contains other folders beginning with pr 
it will offer those and won't complete with the function

**Comment by belak** [comment]
I can't reproduce this... can you provide any additional information about your setup?

**Comment by sorin-ionescu** [comment]
Completion bug? `cd` overriden?

**Comment by jeffwidman** [comment]
nudge @ChrisJefferson / @stefanosc:
> I can't reproduce this... can you provide any additional information about your setup?

**Comment by belak** [comment]
There hasn't been an update from the original poster in over a year. I'm closing this for now, but please feel free to open another issue if you're still seeing it and have a method of reproducing it.
