### ISSUE TITLE
Using autosuggestion module, quite slow when paste a long command into the zsh

### ISSUE THREAD

**Issue by yunqing** [sorin-ionescu/prezto#1108]
Hi everyone! I am using prezto with the module **autosuggestions**. I try to paste a long command into the zsh shell, and I find that it's quite slow for zsh to finish this input. Anybody can try it, just paste the command below into the zsh shell, of course with the module **autosuggestions** enabled:

`echo autosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestionsautosuggestions`

It takes me **more than 2 seconds** to finish this input!

The modules enabled in my ~/.zpreztorc is as below:

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'git' \
  'ssh' \
  'tmux' \
  'completion' \
  'syntax-highlighting' \
  'history-substring-search' \
  'autosuggestions' \
  'prompt'
```

Can anybody find the reason? Thx!

**Comment by sorin-ionescu** [comment]
Report performance issues to [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions).
