### ISSUE TITLE
Terminal Module: "Auto titling is disabled inside terminal multiplexers"

### ISSUE THREAD

**Issue by tjharman** [sorin-ionescu/prezto#1111]
Is it possible to have this as a configurable setting?  I miss this from oh-my-zsh, it would auto-title all my tmux windows and I really liked that feature.

I've found that changing TMUX to TMX on line 114 of ~/.zprezto/modules/terminal/init.zsh makes this work - but I'm not sure if that's a terrible hack or the correct thing to do.

Thanks!

**Comment by oohlaf** [comment]
Check out PR https://github.com/sorin-ionescu/prezto/pull/599

**Comment by tjharman** [comment]
Seems others have already put in a pull request for this. Closed issue.
