### ISSUE TITLE
 'completion'  module cause press multi times `tab`got iterm2 tab closed

### ISSUE THREAD

**Issue by MarloweW** [sorin-ionescu/prezto#1112]
In OS X iTerm2, enable completion module **after** utility module, when I press tab first, I got completion list, I press tab again and again to chose from the list, the third time I press tab, the **iTerm2** tab closed.

If I disable completion module, things works fine.

I record a video:

![2016-03-30 11_10_10](https://cloud.githubusercontent.com/assets/9361073/14130780/fe412b72-f667-11e5-8211-84a8c125d34d.gif)

**Comment by belak** [comment]
Are you still seeing this problem? If you are, what version of iTerm and zsh are you using?

**Comment by MarloweW** [comment]
No, I have create my own configs, its been so long, I'll try to reproduce it.

**Comment by MarloweW** [comment]
Not able to reproduce this.

**Comment by belak** [comment]
Thanks for following up!
