### ISSUE TITLE
History substring search broken after terminal reset

### ISSUE THREAD

**Issue by FrenchBen** [sorin-ionescu/prezto#1114]
I'm using the `history-substring-search` module and after an iTerm reset (clear screen via cmd+R) the substring search doesn't work.
Press `enter` once and it works again.

**Comment by sorin-ionescu** [comment]
Does it happen without Prezto? https://github.com/zsh-users/zsh-history-substring-search

**Comment by beanaroo** [comment]
Not reproducible on Linux, using Termite.

**Comment by FrenchBen** [comment]
haven't had a chance to check it without prezto. I'll try to do it on a sub-account to confirm

**Comment by belak** [comment]
I can't reproduce this with iTerm2. Are you still seeing this issue?

**Comment by FrenchBen** [comment]
Seems that the latest iterm hasn't caused the issue - I'll close this until I see it happen again. 
Thanks for the ping.
