### ISSUE TITLE
git completion not working in non-bare repos

### ISSUE THREAD

**Issue by alexconst** [sorin-ionescu/prezto#1119]
I'm using vcsh which kind of acts as a wrapper to git and splits GIT_DIR and GIT_WORK_TREE into two different folders.
The problem is when I try to run a command such as `vcsh mydotfiles add <TAB>` zsh simply prints the message `-- not a git repository --` and doesn't complete with any file. 
Note: the vcsh command works if I manually type the filename.
Note: curiously enough zsh completes `vcsh` commands, such as my vcsh-created repo `dotfiles` and the `add` argument. But after that it "dies".

I'm using zgen with the following modules:
```
    # prezto options
    zgen prezto editor key-bindings 'vi'
    zgen prezto prompt theme 'agnoster'
    zgen prezto utility:ls color 'yes'
    zgen prezto '*:*' color 'yes'

    # prezto and modules
    zgen prezto
    zgen prezto command-not-found
    zgen prezto syntax-highlighting
    zgen prezto editor
    zgen prezto prompt
```

Any workaround to this?

Thanks

**Comment by sorin-ionescu** [comment]
`vcsh` needs to have its own completion.

**Comment by alexconst** [comment]
@sorin-ionescu 
But is there a way to enable completion to fallback to existing files instead of "blocking"?
And I mean it in general terms, not just for vcsh.

**Comment by alexconst** [comment]
BTW, `vcsh` does have some completion. It lists commands and is aware of existing repos.
```
 vagrant@nostromo  ~  vcsh <TAB>
 -- vcsh sub-commands --
clone            -- clone an existing repository
commit           -- commit in all repositories
delete           -- delete an existing repository
enter            -- enter repository; spawn new <$SHELL>
help             -- display help
init             -- initialize an empty repository
list             -- list all local vcsh repositories
list-tracked     -- list all files tracked by vcsh
list-tracked-by  -- list files tracked by a repository
list-untracked   -- list all files not tracked by vcsh
pull             -- pull from all vcsh remotes
push             -- push to vcsh remotes
rename           -- rename a repository
run              -- run command with <$GIT_DIR> and <$GIT_WORK_TREE> set
status           -- show statuses of all/one vcsh repositories
upgrade          -- upgrade repository to currently recommended settings
version          -- print version information
which            -- find <substring> in name of any tracked file
write-gitignore  -- write .gitignore.d/<repo> via git ls-files
 -- repositories --
mydotfiles
```

**Comment by sorin-ionescu** [comment]
```zsh
foo() {}
foo[tab] # Lists files.
```

Load the `vcsh` completion with a minimal zshrc, no Prezto. If it completes files, then it's a conflict with Prezto or a Prezto misconfiguration in the completion module.

**Comment by alexconst** [comment]
FYI as suggested I tested it with a minimal zshrc and it looks like the problem is with `vcsh` instead.

Thanks

**Comment by ryukinix** [comment]
@alexconst I have a similar problem to setup my dotfiles using `zprezto` and a alias for bare-repo `dot` to git as I think you did. You fixed that?

**Comment by ryukinix** [comment]
Fixed here, sorry for ping this. For anyone to get in trouble this again:

Don't do that:
```
alias dot='git --git-dir=<dir1> --work-tree=<dir2>'
```

Do this:
```
alias dot='GIT_DIR=<dir1> GIT_WORK_TREE=<dir2> git'
```

For some reason I lost the autocompletion on first case, but not on the second.
