### ISSUE TITLE
What is the best way to override ENV variables set by modules?

### ISSUE THREAD

**Issue by ahmedelgabri** [sorin-ionescu/prezto#1121]
I'm trying to override `HISTSIZE` but it doesn't seem to be working, I tried in `zprofile`, `zshenv` & `zshrc` and it's always is set to `10000` which comes from [here](https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/history/init.zsh#L14)

So what is the best way to do this?

**Comment by sorin-ionescu** [comment]
Modify it in place or at the bottom of zshrc.
