### ISSUE TITLE
NPM completion cache file location

### ISSUE THREAD

**Issue by k2s** [sorin-ionescu/prezto#1122]
if prezto is installed system-wide, for example with https://aur.archlinux.org/packages/prezto-git/ I get error:

`/usr/lib/prezto/modules/node/init.zsh:28: permission denied: /usr/lib/prezto/modules/node/cache.zsh`

Couldn't the cache file be created in /tmp folder ?

**Comment by sorin-ionescu** [comment]
Prezto is not designed to be installed system-wide but in the user directory and modified in place. The idea behind the cache file is to generate it once. It will be erased on reboot if you create it in the temporary directory.

**Comment by k2s** [comment]
could the cache file path be configurable ?

using system wide installation (https://aur.archlinux.org/packages/prezto-git/) for long time and without any issues

thank you

**Comment by sorin-ionescu** [comment]
I suppose. It's not the only module with a cache file though.

**Comment by belak** [comment]
We should start using TMPDIR for cache files, as they are segmented off by user.
