### ISSUE TITLE
How to remove prezto

### ISSUE THREAD

**Issue by chirag7jain** [sorin-ionescu/prezto#1123]

**Comment by beanaroo** [comment]
If you used your package manager to install it, use it to uninstall it. Example for `pacman` based distros:

    # pacman -R prezto-git

If you used the guide in the README, simply remove the cloned git folder and the symlinks created.

**Comment by sorin-ionescu** [comment]
How can I make Prezto better?

**Comment by chirag7jain** [comment]
I moved to prezto hoping that would be faster than oh my zh.

For me the load time seems to be almost the same
and second the search for previous command by using up and down arrow keys isn't as great as it was in oh my zh

my prezto config modules
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'git' \
  'prompt'

**Comment by sorin-ionescu** [comment]
I don't know if OMZ has done a recent cleanup but Prezto has always been faster. As for history search, enable **history-substring-search**; it's even better.

**Comment by fa7ad** [comment]
+1 for the uninstall script. Not that I want to remove Prezto, I just think it should be an option. OMZ has `uninstall_oh_my_zsh` command for that, why not add something similar for Prezto.

@sorin-ionescu this is not related to the issue, but would you consider making a post or something about how to use OMZ plugins in Prezto (if it is at all possible). I made the switch recently and still tend to mess up the git aliases :frowning: , so I'd like to swap out this git module for something similar to OMZ's one.

**Comment by ebsen** [comment]
Wow. Just wanted to point out that the `history-substring-search` module achieves what I missed from the up and down arrows in my Oh My Zsh prompt, plus better highlighting.

**Comment by sorin-ionescu** [comment]
As for how to remove it, just delete all the .z* files and directories in your home that are related to prezto. See the runcoms directory.

**Comment by ConstantFun** [comment]
Thanks

**Comment by brandon-fryslie** [comment]
hey I think Prezto is great and I've been using it for years.  Appreciate the work
