### ISSUE TITLE
can't (easily) disable noglob on scp

### ISSUE THREAD

**Issue by ChrisJefferson** [sorin-ionescu/prezto#1125]
I was confused for a while why I couldn't type:

`scp *.pdf remotehost.com:dir/`

Until I discovered that zprezto does a 'noglob' unconditionally on scp. That seems like slightly strange behaviour to me -- I can't think why I'd want that disabling?

I could (and will) maintain my own branch without the noglob, but I was wondering about the reasoning.

**Comment by sorin-ionescu** [comment]
I don't use `scp` often. So, this may be a relic from OMZ. `noglob` is for programs that do their own globbing like `find`, which allows the user to use it without quotes.

**Comment by ChrisJefferson** [comment]
Ah, this is annoying (I think I know where it comes from)

You wouldn't want globbing for ```scp remotehost.com:dir/* .``` But you do want globbing for ```scp *.pdf remotehost.com:dir/```. I'll have a think / google, to see if there is a cleverer option.

**Comment by ChrisJefferson** [comment]
This stackoverflow answer has a clever answer, to check which parameters are remote, and which are local:

http://unix.stackexchange.com/questions/106980/scp-command-working-in-bash-doesnt-work-in-zsh

Would you (in principle) accept a patch which tidied this up / applied it to other commands (like rsync for example)

**Comment by sorin-ionescu** [comment]
We can turn it into a function. Try that function, see if it works for you.

**Comment by trustlix** [comment]
Here's a workaround I use:

`\scp *.txt remote:~/`

It will bypass the alias and call the scp command directly.

**Comment by samcv** [comment]
This may be the same thing causing this, but I am getting an issue where using scp on *another* machine causes the command to fail. Because the computer i'm rsyncing **to** has zprezto installed on it…

```
$ rsync -az --chown=www-data:www-data --chmod=644 myfolder user@computer:/loc/ation  ✘ 127
zsh:1: no matches found: --usermap=*:www-data
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

**Comment by samcv** [comment]
I've made a pull request which fixes this bug 😄 

https://github.com/sorin-ionescu/prezto/issues/1356

**Comment by belak** [comment]
This should be fixed (in a slightly different way) thanks to @samcv.

Remote paths have glob disabled, while local paths should have them enabled.
