### ISSUE TITLE
Off by one when using auto complete

### ISSUE THREAD

**Issue by borissmidt** [sorin-ionescu/prezto#1127]
when i use autocomplete on the zsh it will copy the characters to a and mess up the command, But it seems that not all themes are having this issue,
for example 
~ » cd D
becomes when pressing auto complete and when pressing backspace it reverts to normal 
~ » ccd D
I can use the off theme without this problem.

**Comment by sorin-ionescu** [comment]
Which theme is this? It could be a font issue.

**Comment by borissmidt** [comment]
Yea i have reinstalled linux, (just trying some distros), so i will install presto again in the near future and maybe it is solved. But If i remember correctly it was with most themes except for 'off' and some other. I mostly use inconsolata or inconsolata-g whenever possible.

**Comment by borissmidt** [comment]
Well the new linux install solved it for some reason... so i will close this.
