### ISSUE TITLE
Prompt "forgets" part until I run prompt -p

### ISSUE THREAD

**Issue by RickCogley** [sorin-ionescu/prezto#1128]
Thank you very much for prezto. I just migrated today from oh-my-zsh, and it's turning out to be quite snappy. 

When I start my terminal (iterm2 and os x terminal on OSX 10.11.4), after I enter any command, like `ls` or something, the prompt "forgets" part of itself. To wit: after I enter the command, for example with both sorin or garrett, I get only the small `>` at the very left and not the colorful, large `>>>`. 

Then, if I enter `prompt -p` and preview all the prompts, it consistently fixes the problem. The colorful large `>>>` comes back and stays until I exit the session. By the way, `prompt -l` or `-c` have no effect. 

This phenomenon does _not_ happen when I reset all the prezto-related rc files back to their defaults, but, rather only when I add in some various variables and commands to the config files. So it must be something I have in my rc files. 

One way to troubleshoot it is going to be going through each line of my rc files, commenting out, and testing again. However I just wanted to ask if anyone had seen this problem before, and if perhaps you could point me in the right direction, regarding anything that _might_ be a culprit. 

Sincerely,
Rick 

<img width="1133" alt="jrc screenshot 2016-04-17 at 5 19 28 pm" src="https://cloud.githubusercontent.com/assets/512328/14585880/9f1c707c-04c0-11e6-9268-b50409e6a8f7.png">

<img width="1120" alt="jrc screenshot 2016-04-17 at 5 28 05 pm" src="https://cloud.githubusercontent.com/assets/512328/14585909/d1db5edc-04c1-11e6-9e99-86d203b44f95.png">

**Comment by sorin-ionescu** [comment]
I don't think it's Prezto. It's iTerm2. Try a different build. Try Terminal.app.

**Comment by RickCogley** [comment]
I don't think it's Prezto either. Apologies for the general question. Same thing happens for both your default theme and the garrett theme, in both iTerm2 3 and the latest Terminal.app. 

I'll test by commenting settings, and upgrading iTerm2 as well.

**Comment by RickCogley** [comment]
Ok, this was related to iTerm, @sorin-ionescu. 

When I installed iTerm2 3 it offers to install command line integration, which it appends to your `.zshrc` in this format: 

     test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

For reference the file is copied up to this gist: 

https://gist.github.com/RickCogley/6e0104cc5109cff8bd7616e8b9339aeb

It's obviously messing with things, so I have disabled it for now.

**Comment by RickCogley** [comment]
Thanks for your patience.
