### ISSUE TITLE
Update the readme for setting a prompt theme on startup (new terminal session)

### ISSUE THREAD

**Issue by sadeqzadeh** [sorin-ionescu/prezto#1129]
The current instruction in readme.md for setting a prompt theme as "default" is outdated. I think with the current version of zprezto, it's done like this:

zstyle ':prezto:module:prompt' theme 'agnoster'

Please update the readme.md.

**Comment by sorin-ionescu** [comment]
What? This has not changed since forever.

**Comment by sadeqzadeh** [comment]
Weird! Now it works! Adding "prompt prompt-name" in .zpreztorc used to throw an error indicating that the "prompt" is not known. And the line I mentioned was already in my .zpreztorc with a different prompt (default value that came with the installation), I just changed the prompt name and it worked fine. Now the prompt command works fine in the config file!

**Comment by sadeqzadeh** [comment]
No! It is not working again as soon as I restart my terminal session! I'm getting this error:
.zpreztorc:172: command not found: prompt

**Comment by sadeqzadeh** [comment]
This works: 
`zstyle ':prezto:module:prompt' theme 'agnoster'`

This does not:
`prompt agnoster`

**Comment by sorin-ionescu** [comment]
Internally Prezto does that in the prompt module. Just set it in zpreztorc.

**Comment by sadeqzadeh** [comment]
Why did you close this issue? The "prompt" module doesn't work for me when used in zpreztorc, although it works fine in my shell session. I load the module before using it in my zpreztorc:

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'homebrew' \
  'osx' \
  'ssh' \
  'git' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt'
```
