### ISSUE TITLE
Awscli autocomple is not working

### ISSUE THREAD

**Issue by voanhduy1512** [sorin-ionescu/prezto#1142]
Hi, I am using prezto with zsh 5.2 on OSX. When i install awscli using homebrew, they copy an autocomplete file to `/usr/local/share/zsh/site-functions/_aws`. But look like prezto not source it by default, i need to manually run `source /usr/local/share/zsh/site-functions/_aws` to make it working. 
I already enable module `completion`, other command like `git` and `brew` have autocomplete correctly.
Can you help me see where is the problem?

**Comment by rakkesh** [comment]
add the following line to your `~/.zshrc` file, 
```fpath=(/usr/local/share/zsh/site-functions $fpath)```

and then execute the following commands,
```
% rm -f ~/.zcompdump; compinit
```

**Comment by voanhduy1512** [comment]
Tried it but it isn't working. I already have `/usr/local/share/zsh/site-functions` in my `fpath`, other completion in that folder works fine except for `aws`.

**Comment by sorin-ionescu** [comment]
Submit it to https://github.com/zsh-users/zsh-completions.
