### ISSUE TITLE
Overwriting content of Runcoms?

### ISSUE THREAD

**Issue by joedaniels29** [sorin-ionescu/prezto#1153]
I've used Prezto for a while now, and i've updated a few times, but I am starting to wonder why something works this way:
Because the install instructions say to symlink, If I want to change configuration like `.zpreztorc`, I'm updating a file in Runcoms. Because of this, I've dirtied the repo and now can't pull. Why should this be this way? is it intentional?

**Comment by jeffcox** [comment]
The "correct" way to maintain a custom version of Prezto is to fork it and merge upstream changes as you see fit.

**Comment by joedaniels29** [comment]
not true. From the docs: 
```
Configuration Files
===================

Zsh has several system-wide and user-local configuration files.

Prezto has one user-local configuration file.

System-wide configuration files are installation-dependent but are installed
in */etc* by default.

User-local configuration files have the same name as their global counterparts
but are prefixed with a dot (hidden). Zsh looks for these files in the path
stored in the `$ZDOTDIR` environmental variable. However, if said variable is
not defined, Zsh will use the user's home directory.

File Descriptions
-----------------

The configuration files are read in the following order:

  01. /etc/zshenv
  02. ~/.zshenv
  03. /etc/zprofile
  04. ~/.zprofile
  05. /etc/zshrc
  06. ~/.zshrc
  07. ~/.zpreztorc
  08. /etc/zlogin
  09. ~/.zlogin
  10. ~/.zlogout
  11. /etc/zlogout
```

The "correct" way to work with the configuration files is to create a new config in `~/`.  But then the instructions in the ReadMe say to create simlink. thus, when I went to edit it i was editing the Project's zpreztorc instead of creating .zpreztorc. i think that 99 percent of users don't want to have to deal with file conflicts when they upgrade zprezto

i would think that on install, we should stub out new ` ~/.zlogout ~/.zlogin ~/.zlogin  ~/.zpreztorc ~/.zshrc . ~/.zprofile  ~/.zshenv` files and source `~/.zprezto/runcoms/.z*` as a default

**Comment by rakkesh** [comment]
> not true.

What @jeffcox suggested is the way I ( and others whom I know ) manage their configuration to keep up with this repo.

I had personally used a local git branch approach, where I would rebase the latest changes from `master` branch.

**Comment by jeffcox** [comment]
> i think that 99 percent of users don't want to have to deal with file conflicts when they upgrade zprezto

If you're struggling with symlinks and git repos I think this may not be the project for you...

**Comment by rakkesh** [comment]
@joedaniels29 this issue is similar to https://github.com/sorin-ionescu/prezto/issues/1131, which suggests a way to include personal configuration. If you could, please discuss further over at the other issue.
