### ISSUE TITLE
tmux module disable nested remote sessions

### ISSUE THREAD

**Issue by stfl** [sorin-ionescu/prezto#1155]
I am running tmux locally or on a server via ssh.
I connect from one server to another and I don't want tmux to autostart when connected from another tmux session.
Is there a way to disabling the autostart in this situation?

**Comment by rakkesh** [comment]
Looking at the [code](https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/tmux/init.zsh#L26-L29) for loading `tmux`, there is no straight forward way to fix this issue. 

Not an elegant solution but I would probably use an environment variable (`LC_*`, as most ssh servers accept such env vars) in `tmux.conf` and check for it on the server before starting `tmux` server.

e.g., On client side, add the following line to your `tmux` configuration 
```
$ vim ~/.tmux.conf

setenv -g LC_TMUX 1
```

And on server side, check for `[ -z "$LC_TMUX" ]`.

**Comment by stfl** [comment]
Thanks for your input.

If you connect from a tmux session through ssh this environment variable will not be present on the remote host. To disallow nested sessions locally the `$TMUX` variable is checked already.
How would you expose/forward this variable to the remote host?

**Comment by rakkesh** [comment]
Uh, I missed out on the last detail.

You need to add `SendEnv` in your `ssh/config` file, on per host or for all.

For sending this env var to all hosts, edit `~/.ssh/config`,

```conf
$ vim ~/.ssh/config

Host *
  SendEnv LC_TMUX
```

**Comment by stfl** [comment]
I see. Thank you.
I would then do that with $TMUX, because this variable is already checked on tmux start..

**Comment by rakkesh** [comment]
If you wish to use `"$TMUX"`, then you would have to allow it on all your ssh servers. 

```sh
$ vim /etc/ssh/sshd_config
...
AcceptEnv LANG LC_* TMUX
...
```

**Comment by stfl** [comment]
good to know, thank you.
the `module/tmux/init.sh` could instead be extended to check for `$LC_TMUX`
