### ISSUE TITLE
support gitsome

### ISSUE THREAD

**Issue by kepbod** [sorin-ionescu/prezto#1156]
I found [gitsome](https://github.com/donnemartin/gitsome) is an awesome git command line tool with deep GitHub integration. Although it offers some [supports](https://github.com/donnemartin/gitsome#for-zsh-users) for zsh, I think it would be better to be integrated into prezto. Thanks!

**Comment by sorin-ionescu** [comment]
This is awesome. It looks like `hub` and `ghi` and a few other commands integrated imbued with steroids.

**Comment by srijanshetty** [comment]
Closing this as we are keeping the core of Prezto small 😄
