### ISSUE TITLE
home key not working in vi mode

### ISSUE THREAD

**Issue by triebefx** [sorin-ionescu/prezto#1160]
steps to reproduce:
1. enable vi mode in .zpreztorc: `zstyle ':prezto:module:editor' key-bindings 'vi'`
2. open shell and press ESC to enter vi 'normal' mode
3. press home key will not jump to the begin of line but print an H character

some environment info:
- Mac OS X with iterm, `TERM=xterm-256color`
- output of currently mapped key

```
# bindkey -L | grep begin
bindkey "^[OH" beginning-of-line
```

I'm happy with any response or hints, can provide more info if needed.

**Comment by belak** [comment]
Are you still seeing this issue?

**Comment by triebefx** [comment]
Yes, even after updating to commit fb37539.
