### ISSUE TITLE
What's the rationale behind BRACE_CCL ON by default? Can it be turned off?

### ISSUE THREAD

**Issue by oblitum** [sorin-ionescu/prezto#1162]
Hi, thanks for maintaining Prezto. I'm a user for a long time.

These days I finally got annoyed enough about having to escape `{` and `}` when using git that I joined #zsh on freenode to learn a bit about why I had to escape and how to disable it, and whether that would be wise to do so.

I've then learned from the channel that turning `BRACE_CCL` on is not an usual default, and that stock Zsh doesn't have it on by default, nor do people on the channel were using it. By debugging I learned it's enabled by Prezto.

I have some questions:
- How is it useful being the default behaviour, does it adds more usability than it takes? (For my simple Zsh usage it just serves for forcing me to have to escape braces, afaik)
- Can it be considered to be turned off in stock Prezto, so to avoid these kind of issues like being unfriendly to git and conflicts with themes as I've checked in the issue list?
- If it's not gonna change on upstream Prezto, is it ok to disable it locally after Prezto loads? Will there be any conflicts? Will I lose anything useful that Prezto offers because of that?

**Comment by belak** [comment]
Yeah this is a weird setting... It's definitely worth looking at disabling by default

**Comment by sorin-ionescu** [comment]
It's enabled for http://zsh.sourceforge.net/Doc/Release/Expansion.html#Brace-Expansion. You can use quotes for Git: `'{0}'`.

**Comment by sorin-ionescu** [comment]
I use it a lot; example:`mv foo{,.bak}`. @belak, don't disable it. Git is the primary annoyance, and I think I saw once a way to disable it for Git only. It just did not bother me too investigate it further.

**Comment by belak** [comment]
As far as I can tell, brace expansion is normal but this is a nonstandard extension on that which interacts strangely with dashes in some corner cases. Your example would still work with BRACE_CCL off. BRACE_CCL allows for character classes in brace expansions (`{a-c}` would expand to `a b c` with BRACE_CCL rather than the more expected `a-c`).

I use brace expansion quite a bit as well but this seems like a strange option to have on by default.

**Comment by belak** [comment]
I'm reopening this because I'm not sure we're talking about the same thing. This isn't about disabling brace expansion, but a modifier on how it works.

**Comment by sorin-ionescu** [comment]
Some options may be relics from Oh-My-Zsh. Or, I enabled it for loops to generate indexes, arrays?

**Comment by belak** [comment]
I'll try to make sure it's not used anywhere in the codebase and look at possibly disabling it. This specific feature seems like it could cause more confusion than help, so turning it off and letting the user pick may be best.

**Comment by sorin-ionescu** [comment]
I don't thinks it's used. I think I used it interactively to get around `seq` in for-loops.

**Comment by oblitum** [comment]
Just wish to say I'm happy there's new development in this project :)
