### ISSUE TITLE
meta: is prezto sleeping?

### ISSUE THREAD

**Issue by kontrafiktion** [sorin-ionescu/prezto#1163]
Looks like there is not much happening in this project. 103 open pull requests — and no commit for 4 months. Is this project still alive or just in some kind of 'hibernation'?

ping @sorin-ionescu

**Comment by kress95** [comment]
He's active on twitter, but not on github hmm :crying_cat_face:

**Comment by ezintz** [comment]
I thought the same already a few days, not to say month, ago... I already wanted to have a look on all the pull requests to see if I am going to merge some of the to my personal fork...

However, it would be nice if we can keep the activity since there is already a lot going on :)

**Comment by kontrafiktion** [comment]
I moved back to oh-my-zsh. Fast enough now

**Comment by kress95** [comment]
Well I moved to zim.

**Comment by ericbn** [comment]
> He's active on twitter, but not on github hmm 😿

@kress95, I don't think so, his last tweet is from Jun 5.

**Comment by fuadsaud** [comment]
@kress95 how did your migration processo to zim go? I'm thinking of moving to it, been seeing many conversations going on at their issue tracker.

**Comment by kress95** [comment]
@fuadsaud [It's really really simple to setup](https://github.com/kress95/dotfiles/blob/master/.zimrc), but it comes with less themes.

**Comment by stefanosc** [comment]
The few features I miss the most are the super handy git symbols on the
right prompt giving you an idea of the repo status. In this regard sorin
theme is the best I found

**Comment by facastagnini** [comment]
Guys prezto found a new home at https://github.com/zsh-users/prezto

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

I started merging some PRs, your contribution is greatly appreciated!

**Comment by belak** [comment]
We're going through and starting to manage this again. Hopefully you'll see more activity in the future!
