### ISSUE TITLE
Upgrading zpresto moves git information

### ISSUE THREAD

**Issue by MichaelJAndy** [sorin-ionescu/prezto#1166]
I upgraded zprezto and kept all of these original files:
- zlogin
- zpreztorc
- zprofile
- zshrc

I'm still using the same and modules theme as I was before - sorin. 

For some reason why Git information has moved
It used to be this:
`~/c/s/apps git:master ❯❯❯`

Now it's this:
`~/c/s/apps ❯❯❯                                                                                                                    master`

Can the default please be reinstated?

**Comment by belak** [comment]
As sorin is the owner of this repo and the maintainer of this theme, I don't think there are any intentions to move it back.

It appears to have been moved when the git info got moved to async (in a1dea6ae43f5a1f5e5dfabac49766bda67983ea0). I would assume that keeping it on the left would have caused a weird reflow when the git info was refreshed.

**Comment by sorin-ionescu** [comment]
It's necessary for async to not have the left prompt jump after `git-info` returns. It's not moving back.
