### ISSUE TITLE
Inconsistent .zprofile documentation

### ISSUE THREAD

**Issue by andreas-h** [sorin-ionescu/prezto#1170]
I'm confused by the README file in the `runcoms/` folder:
- in the entry for `.zprofile`, it says

> See the description of zlogin below for what it may contain.
- in the entry for `.zlogin`, it says

> This is not the file to define aliases, functions, shell options, and key bindings. It should not change the shell environment.
- in the file `zprofile` in the `runcoms/` folder, you change the shell environment quite a bit

What is the _correct_ way of doing things, here?  The docs in this file give advice which contradicts the files in this directory ...

**Comment by sorin-ionescu** [comment]
That file is commonly used for showing login messages.
