### ISSUE TITLE
git-info broken again

### ISSUE THREAD

**Issue by michaelaye** [sorin-ionescu/prezto#1171]
Similar to #566 and #219 the git-info is currently broken for me.

I have confirmed that only the 'sorin' and 'garrett' theme (both using git-info instead of vcsinfo) are hit by this issue (with garrett my favorite prompt):

``` bash
$ prompt garrett
git-info:165: bad math expression: operator expected at `0'
git-info:173: bad math expression: operator expected at `0'
─❱❱❱ prompt steeef                                                                   +6075 17:34 ❰─┘

klay6683 at macd2860 in ~/Dropbox/src/planet4 (master●●)
```

Above I show that `steeef` doesn't have this issue.
My versions:
zsh: 5.2
prezto: 4f197009
git: 2.9.2

How could I debug this? Thanks for any help...

**Comment by belak** [comment]
Are you seeing this with all repos and branches or only some?

**Comment by michaelaye** [comment]
I moved on with my software in the meantime.

**Comment by belak** [comment]
Alright, thanks for the response.
