### ISSUE TITLE
Example of how to use slit function?

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#1175]
Can I get an example of how and when to use `slit`?

From the utility module:
https://github.com/sorin-ionescu/prezto/commit/d15f45ac288e6ff7801d91c131e957bf289aeb3c#diff-2f77df36e3cb37e96b53730eca1e92dbR45

**Comment by joech4n** [comment]
+1 :)

**Comment by sorin-ionescu** [comment]
It prints the columns you want. `slit 3` is like `cut -d ' ' -f3`.
