### ISSUE TITLE
Why Prezto?

### ISSUE THREAD

**Issue by nntoan** [sorin-ionescu/prezto#1179]
Hello @sorin-ionescu and the contributors,

I was using Oh My Zsh since 1969, then suddenly in a shiny day, I found people are talking about Prezto because it's faster than Oh My Zsh.
I did fews of researching and still have no idea why it is better than Oh My Zsh, regarding to a topic on OMZ official repo, you said Prezto follow KISS principle.

Could you please defining what is "Simple" here?

I'd love to use Zsh and OMZ, I created a repo like this https://github.com/nntoan/oh-my-zsh-custom to quickly install all my customisation and OMZ whenever I install new server. I think that is simple enough but I still want more, I am a kind of guy who will write a bash script to handle a task which will take more than 30 seconds of my life!

Looking for your response.
Toan.

**Comment by kepbod** [comment]
[This](https://github.com/robbyrussell/oh-my-zsh/issues/377) is the origin post on OMZ about why prezto was created. Hope it would be helpful.

**Comment by nntoan** [comment]
@kepbod I created this issue after read that bro. Still confusing me.

**Comment by leoj3n** [comment]
Prezto has no install or uninstall scripts. There is no update script. You need to know how to use git because unlike OMZ there is no file-override directory; in Prezto you edit the files directly.

**Comment by sthtodo** [comment]
Is presto still under maintenance and update?

**Comment by kepbod** [comment]
It seems like it did not under maintenance and update.

**Comment by danielbayerlein** [comment]
@sorin-ionescu Is Prezto still maintained?

**Comment by mgee** [comment]
@danielbayerlein see #1239
