### ISSUE TITLE
Curly braces expanded

### ISSUE THREAD

**Issue by dmdque** [sorin-ionescu/prezto#1181]
Curly braces are being expanded. How can I disable this? (I often use commands like `git show stash@{1}`.)

Apologies if this has been covered, but I couldn't find anything related apart from this [comment](https://github.com/sorin-ionescu/prezto/issues/219#issuecomment-6984781).

**Comment by leoj3n** [comment]
I've noticed that as well. I just quote the thing.

**Comment by leoj3n** [comment]
http://doc.xarli.net/zsh-doc/Options.html#index-IGNOREBRACES

I would only set that after prezto has fully loaded (at the end of `~/.zshrc`) or just on the command-line when you need it:

```
setopt IGNORE_BRACES
```

**Comment by dmdque** [comment]
Thanks @leoj3n, it works to run it in terminal when needed.

Strangely enough, it conflicts with something in my `~/.zshrc` even when it's at the end, but that's another issue.

**Comment by leoj3n** [comment]
@dmdque Great! Sounds like you got it figured out then (don't forget to close the issue, if it's resolved).
