### ISSUE TITLE
Why must utility come before completion?

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#1184]
It's not clear to me why the `utility` module [must come before](https://github.com/sorin-ionescu/prezto/tree/master/modules/completion#completion) the `completion` module.

Can anyone explain?

I thought maybe it had something to do with adding the (many) utility aliases to the completion dump, but I don't see references to the aliases when searching through the generated dump.

Any insight as to the reason for this dependency ordering would be appreciated.

**Comment by leoj3n** [comment]
Is it because the external completions should take precedence, by being higher in the `fpath`?

**Comment by belak** [comment]
As far as I can tell, it's so LS_COLORS will be set properly on certain systems, otherwise the colors won't work with the completion system.

**Comment by belak** [comment]
It may be worth autoloading utility if this module is loaded

**Comment by belak** [comment]
Can you clarify this @sorin-ionescu? Would it be worth calling pmodload utility at the top of the completion module?

**Comment by sorin-ionescu** [comment]
It has to do with completion directory/file colors if I recall correctly. If there is no error, loading it is optional. So, I would not force load it.
