### ISSUE TITLE
Was there a design decision for autoloading all modules functions up front?

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#1187]
I'm just curious if there was an explicit reason behind why Prezto loads all module's functions at once, ahead of sourcing the modules, as seen [here](https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/init.zsh#L33-L46) in the main `init.zsh` script.

Is this because it has been decided that the functions of all enabled modules should be available to all other modules up front, possibly before a module has been sourced, so that any module can begin using other module's functions regardless of order?

**Comment by leoj3n** [comment]
Is the possibility of sharing functions between modules a side effect, or was it a design decision?

**Comment by sorin-ionescu** [comment]
Code in init.zsh can depend on loadable functions.

**Comment by leoj3n** [comment]
@sorin-ionescu Okay, thanks for the reply.
