### ISSUE TITLE
Proper way to override default highlighter settings (underline paths)?

### ISSUE THREAD

**Issue by nick-s-b** [sorin-ionescu/prezto#1189]
All,
I like default settings of pretty much everything in prezto and have kept most of it stock. Things I didn't like I managed to override with iTerm2 so they never bothered me. I've also abstained from modifying most of the files in prezto and have only changed init.zh so it loads my own .zshrc.custom which doesn't cause many conflicts when upgrading prezto.

I've installed prezto on a Linux box and now that I don't have access to iTerm2, I can't easily modify things I don't like and have to actually find ways to override them within the scripts.

So what is the proper way to override highlighter settings? I want to get rid of underlined text completely because it's not that readable. I see that "underline" declarations appear in:
`modules/spectrum/init.zsh` and `modules/syntax-highlighting/external/highlighters/main/main-highlighter.zsh`

What's the best way to override `path` and `path_prefix` so I don't create too many headaches when it comes time to update prezto?

Thanks!

**Comment by MeisterP** [comment]
To switch do bold instead of underline, I have the following in my `.zpreztorc`

```
# Set syntax highlighting styles.
zstyle ':prezto:module:syntax-highlighting' styles \
  'path' 'bold' \
  'path_prefix' 'bold'
```

**Comment by nick-s-b** [comment]
@MeisterP Works! Thank you!
