### ISSUE TITLE
Autosuggestions don't seem to work with tab completions

### ISSUE THREAD

**Issue by LandonSchropp** [sorin-ionescu/prezto#1204]
Autosuggestions are awesome! Unfortunately, they don't seem to work with tab completions. For example, if I type out `git com`, it autosuggests `git compact-log`, one of my custom commands. However, if I hit tab, it expands out into `git commit`, which isn't what I'd expect.

<img width="332" alt="screen shot 2016-10-05 at 4 07 48 pm" src="https://cloud.githubusercontent.com/assets/361591/19134948/19a7ef48-8b16-11e6-9b3e-e586bed6c8c8.png">

<img width="327" alt="screen shot 2016-10-05 at 4 09 49 pm" src="https://cloud.githubusercontent.com/assets/361591/19134955/299dfe38-8b16-11e6-8c81-e397b2a968fe.png">

**Comment by ratheesh** [comment]
This is default behavior.
Alternately you can use `Ctrl-SPACE` to complete auto suggestions.
I have following in my `.zshrc` file.

`bindkey '^ ' autosuggest-accept`
