### ISSUE TITLE
Install prezto without git?

### ISSUE THREAD

**Issue by antonshiryaev** [sorin-ionescu/prezto#1208]
Is it possible to install prezto on a server that has zsh, but no git, no root access and no ability to install software? If there is an alternative for git in this case, I can check if that's available. The machine in question is my university's remote server.

**Comment by stevenspasbo** [comment]
Yes, you will just need to replace the 2nd step in the installation directions with downloading the archive using wget. [Here is the link to the archive.](https://github.com/sorin-ionescu/prezto/archive/master.zip).

**Comment by belak** [comment]
Prezto is designed to be installed with git, especially because we haven't focused on versioned releases... so I don't think this is something we'll end up adding to the readme... but you can install prezto from the github archive downloads as mentioned above.
