### ISSUE TITLE
Started getting the issue with autocompleting files for opening them with vim

### ISSUE THREAD

**Issue by nikitavoloboev** [sorin-ionescu/prezto#1212]
I have this issue when typing 'vim ' followed by something and pressing a tab. It gives me this error : 

![2016-10-20 at 19 51](https://cloud.githubusercontent.com/assets/6391776/19571495/a67b8076-96fe-11e6-8006-fb5437fa6efc.png)

I found [this](https://github.com/robbyrussell/oh-my-zsh/issues/518) thread online but doing the commands there did nothing for me. I still get the error. Does anyone know what might be causing this and how I can solve this?

Thank you for any help.

**Comment by belak** [comment]
I'm guessing this may have been upstream in the completions module. Can you confirm if this is still happening?

**Comment by nikitavoloboev** [comment]
It doesn't :)
