### ISSUE TITLE
Do not display git prompt for selected repositories

### ISSUE THREAD

**Issue by radim** [sorin-ionescu/prezto#1213]
Git prompt, being useful as it is, can be quite slow when it comes to some large repos. Is there an option to selectively disable it?

**Comment by radim** [comment]
ok, learned it's a matter of prompt theme, so override in my config

```
prompt_agnoster_alt() {
  RETVAL=$?
  CURRENT_BG='NONE'
  prompt_status
  prompt_context
  prompt_dir
  prompt_end
}

prompt_agnoster_precmd() {
  if [ `git config prompt.hide` ]; then
    PROMPT='%{%f%b%k%}$(prompt_agnoster_alt) '
  else
    vcs_info
    PROMPT='%{%f%b%k%}$(prompt_agnoster_main) '
  fi
}
```

**Comment by sorin-ionescu** [comment]
`$ git-info off` does what you want.

**Comment by jahagirdar** [comment]
> `$ git-info off` does what you want.
can you please provide an Example of how to do it?
e.g. I have a large repo under '/prj/repo/largerepo' and a small one at '/prj/repo/small' 
I want the git bell and whistles activated for the small repo but want to turn it off when I am in the large one...

**Comment by FelipeLema** [comment]
`git-info off` configures the repo you're currently standing on with an "off" value for showing prompt info (default is "on")

not sure if formally documented anywhere, I just read `modules/git/functions/git-info`

**Comment by FelipeLema** [comment]
> > `$ git-info off` does what you want.
> 
> can you please provide an Example of how to do it? e.g. I have a large repo under '/prj/repo/largerepo' and a small one at '/prj/repo/small' I want the git bell and whistles activated for the small repo but want to turn it off when I am in the large one...

`git-info off` configures the repo you're currently standing on with an "off" value for showing prompt info (default is "on")

not sure if formally documented anywhere, I just read `modules/git/functions/git-info`
