### ISSUE TITLE
which make returns wrong output

### ISSUE THREAD

**Issue by ruipacheco** [sorin-ionescu/prezto#1215]
I executed `which make` trying to find the path to the make executable and instead the console printed what seems to be shell function:

```
ruihpacheco at descartes in ~/chi/databaseclient/cpp (default)
$ which ssh
/opt/local/bin/ssh

ruihpacheco at descartes in ~/chi/databaseclient/cpp (default)
$ which make
make () {
    # undefined
    builtin autoload -XUz
}

ruihpacheco at descartes in ~/chi/databaseclient/cpp (default)
$ 
```

`which ssh` is left to show `which` works. Firing up bash I got this:

```
ruihpacheco at descartes in ~/chi/databaseclient/cpp (default)
$ bash
bash-3.2$ which make
/usr/bin/make
bash-3.2$
```

**Comment by jeffcox** [comment]
[~/.zprezto/modules/utility/functions/make](https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/functions/make)

**Comment by ruipacheco** [comment]
That's pretty unfortunate.

**Comment by belak** [comment]
If you're specifically looking for the command you can use one of the following:

```
echo $commands[make]
type -p make
echo =make
```

However, this isn't a bug in prezto, so I'm going to close this for now
