### ISSUE TITLE
diff -y does not work

### ISSUE THREAD

**Issue by texttheater** [sorin-ionescu/prezto#1231]
The useful `-y` option for column-based diff seems to be unavailable in prezto’s `diff` function:

     ~  diff -y a.txt b.txt
    diff: conflicting output style options
    diff: Try 'diff --help' for more information.

**Comment by ezintz** [comment]
You have probably Git installed on your host, in this case the diff command will use `git diff`.

See https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/functions/diff and it is also described in this issue https://github.com/sorin-ionescu/prezto/issues/1215

**Comment by texttheater** [comment]
Yes, `colordiff` is installed. The problem seems to be that prezto calls it with `--difftype diffu` even though `-y` is given, which specifies a different output style.

**Comment by ezintz** [comment]
Yes, you are right. It should use the arguments you're passing to it. Needs to be fixed I would say.

**Comment by lauzi** [comment]
The problem is `diff` doesn't accept -y and --unified at the same time.

The easiest way to solve this is to remove the --unified on [this line](https://github.com/sorin-ionescu/prezto/blob/40853f23c2658f63105e3d8c72e510f95ef98fbe/modules/utility/functions/diff#L11), but I'm not sure why the option's there in the first place.

**Comment by belak** [comment]
I think it's there to match up with `git diff` but it's not worth keeping it there if it's going to break options when actually using the command.

**Comment by belak** [comment]
I've removed --unified from the diff function (as well as the workaround which uses git because it doesn't support --unified or -y in the same way) because this breaks things. There has also been a new alias added (diffu) which will give a unified diff, similar to before.

**Comment by texttheater** [comment]
Great, thanks!
