### ISSUE TITLE
How to make completion case-sensitive?

### ISSUE THREAD

**Issue by paddor** [sorin-ionescu/prezto#1233]
I'm really annoyed by having `li<tab>` not complete to `lib/`, but instead giving me a selection between `lib/` and `LICENSE.txt`. How to make it more intuitive?

**Comment by ezintz** [comment]
You can edit your .zpreztorc to achieve this, see https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zpreztorc#L13

**Comment by belak** [comment]
There's already information in the preztorc about how to accomplish this, so I'm closing this issue.
