### ISSUE TITLE
Where is the source code for zefram theme

### ISSUE THREAD

**Issue by pushparajxa** [sorin-ionescu/prezto#1234]
Hello,

I couldn't find source code for the prompt theme zefram in .zprezto/modules/prompt/ folder, but there is code in that directory corresponding to other themes like giddy. I want to customize zefram but couldn't find its location.

**Comment by belak** [comment]
zefram is built into zsh itself, not prezto. On my system it can be found at /usr/share/zsh/functions/Prompts/prompt_zefram_setup but it may be different for you.
