### ISSUE TITLE
Still seeing user name in prompt when using sorin theme

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#1237]
I currently have set the theme to sorin, but still am seeing the current user name in the prompt. According to screenshots about the sorin theme, there shouldn't be one.

Where is this coming from? It's a bug or a configuration from somewhere else?

**Comment by ezintz** [comment]
The username is shown because the prompt is configured like this for SSH connections. See https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L134

**Comment by binarykitchen** [comment]
ah cool, that's fine - i've been wondering why it is looking different on my local machine than on my server when both are using the same config ...
