### ISSUE TITLE
READ ME BEFORE OPENING AN ISSUE: Is this an abandoned project.

### ISSUE THREAD

**Issue by facastagnini** [sorin-ionescu/prezto#1239]
Hi guys,

It seems that @sorin-ionescu is not active anymore. There is a pile of useful PRs and no one with merge rights. Just take a look at the [code-frequency](https://github.com/sorin-ionescu/prezto/graphs/code-frequency)... 

When a cool project like prezto is abandoned by the repo owner and no one else has commit rights the community should find the way to orderly move forward. Is there a well maintained fork that we can move to or someone willing to do it?

CCing some contributors that I have seen active around here... @rtfpessoa @ezintz @ericbn @joaosa @sectioneight @leoj3n @toogley

PD: @sorin-ionescu are you there? Please drop a line here so we can figure out what to do next!

**Comment by rtfpessoa** [comment]
I only did a fork and started merging some prs but only for private use.

To be fair, I know very few bits of the project so I do not think I would be a good maintainer alternative.

Though, I would not mind helping.

**Comment by ericbn** [comment]
Also CCing everyone from https://github.com/sorin-ionescu/prezto/issues/1163: @kontrafiktion, @kress95, @ezintz, @fuadsaud, @stefanosc.

**Comment by toogley** [comment]
I would also be interested in helping. (Although i have little software development experience)

Am 28. November 2016 16:03:31 MEZ, schrieb Federico Ariel Castagnini <notifications@github.com>:

**Comment by toogley** [comment]
(Just for reference: I have currently no interest in this project - I Initially, answered with the opposite, because I thought i was tagged for another project i'm interested in. Sorry.)

**Comment by ezintz** [comment]
Yes, sure let's see how we can make progress. As most of you probably did, I also merged some of the pull requests which made sense to me. Let me know how I can contribute and support you.

However I will need to keep a separate project as I've integrated it to my dotfiles to take my configuration always with me.

**Comment by stefanosc** [comment]
Thank you for this conversation. Unfortunately, I have not been active at all in development for almost 18 months. I am still using prezto and the sorin theme despite the lack of commits / merged pull requests.
I would have already moved to zim if it wasn't for this:  https://github.com/Eriner/zim/issues/82
I don't know how helpful I could be, however if others are interested I could try. To me it makes more sense to move to zim and integrate the missing pieces.

**Comment by stefanosc** [comment]
@rjcoelho this sums it up (first paragraph from readme):

> Zim is a Zsh configuration framework with [blazing speed](https://github.com/Eriner/zim/wiki/Speed) and modular extensions.
> 
> Zim is very easy to customize, and comes with a rich set of modules and features without compromising on speed or functionality!

It seems to me zim is trying to bring prezto back to the origin or even take it further, in terms of simplicity and speed, which were among the main reasons sorin moved away from omzsh.
It is actively developed and is a little more than a plugin manager (zgen or antigen)

What is your take?

**Comment by jeffcox** [comment]
I've had no issues running a personal fork and perusing the discussions and PRs here.  What do people expect to see?  Changing dotfiles for the sake of it doesn't make sense to me.

**Comment by dvcrn** [comment]
It's a shame @sorin-ionescu doesn't just add some of the people here as contributors. 

Given the MIT license, how about we move it into a org and add all people here interested in maintaining as initial members? I created a test-org to play with settings and it seems to be feasible.

- Are there people here willing to take over the wheel of this project?
- Does the MIT license permit publicly distributing a fork under the same name? 
- Would the name-clash be a problem? New users would very likely be confused about this

**Comment by ezintz** [comment]
@dvcrn nice to meet you here (; However I like your idea about moving to an organisation.

I just had a short look at the zim source code and I have to say it looks pretty similar to prezto.

**Comment by stefanosc** [comment]
@ezintz zim started as a fork of prezto due to sorin lack of activity: take a look at @eriner fork:
https://github.com/Eriner/prezto (read the NOTICE at the beginning of the readme)

**Comment by facastagnini** [comment]
I also like @dvcrn 's idea. I just created one here https://github.com/prezto-users and forked the repo.
Lets make this a community effort, so far I am the only one there, please let me know if any of you wants to be a contributor.

**Comment by Eriner** [comment]
For those curious about [zim](https://github.com/Eriner/zim), @stefanosc nailed it. I've been busy at work recently, but I'm going to carve out time this weekend to wrap up moving the project into an organization (which requires some additional code, hence the delay). I've been putting off doing that for far too long now. This will ultimately end up in [this](https://github.com/zimframework/zim) organization/repository. The change to an organization should facilitate better project growth and management.

That said, I think [zim](https://github.com/Eriner/zim) is a great choice for most people currently looking for a prezto alternative/replacement. When the change happens, I will do my best to make the transition to the new repository/organization/structure as seamless as possible.

@stefanosc, if you'd be interested in beginning work on providing the changes for the issue you mentioned, I'd be glad to merge them into the project.

**Comment by ryankask** [comment]
It would be great to learn more about how to transition from prezto to zim.

Is zim meant to be forked? For example, I have a custom prompt theme -- where do I put that? I just added it to modules/prompt/functions in my prezto fork.

Also, how do the contents of prezto's runcoms directory map to zim's templates directory? Clearly zimrc is zpreztorc and zshrc is the same but what about zprofile? In prezto this sets up paths and exports important variables like EDITOR. Where should the contents of that file go in zim? Is zshenv necessary?

Thanks!

**Comment by dvcrn** [comment]
@ryankask from what I can see, zshrc is sourcing zim (and therefore zimrc). So zimrc would be zpreztorc and zshrc is your normal zshrc. 
It's almost identical to prezto in that you can fork it - implying the occasional upstream commit merging, or just go with the upstream version. 

@Eriner if you ever need a helping hand with zim, I would love to help 😊

**Comment by facastagnini** [comment]
@nicoulaj https://github.com/zsh-users sounds like the appropriated organization to keep a project under the zsh community, can we fork this repo into it?
I would like to be a maintainer if you dont mind.
Thanks a lot!

**Comment by nicoulaj** [comment]
It looks like @sorin-ionescu was active one week ago, and this issue is only 6 days old, can you guys give him some time to answer before forking ?
If he wants to move the project to zsh-users, of course it is welcome here.
He also is an administrator of the zsh-users organization anyway.

I'm idling on IRC (`#zsh-users`) if any help is needed.

**Comment by stefanosc** [comment]
@Eriner thank you for your work and offer. I see @ericbn already submitted a cool PR https://github.com/Eriner/zim/pull/104 
I don't think I can do better / more at this time. Thank you both very much

**Comment by facastagnini** [comment]
@nicoulaj sure, lets wait one week to give @sorin-ionescu an opportunity

**Comment by rjcoelho** [comment]
I vote for 1) moving prezto modules into git to https://github.com/zsh-users, and 2) when possible convert prezto modules into external zsh-users repos to be used outside prezto and to avoid "add xpto module PR".

**Comment by phretor** [comment]
👍

**Comment by facastagnini** [comment]
@nicoulaj should we make the move? We are a handful of contributors waiting for a resolution to start reviewing the accumulated PRs :)

**Comment by nicoulaj** [comment]
OK, I created the fork at https://github.com/zsh-users/prezto and invited the people from this thread who expressed interest in helping.

If you need anything, please let know.

**Comment by facastagnini** [comment]
Thanks @nicoulaj for providing a home for this project, and thanks to all those who participated in the conversation!

Now its time to work. The holidays are going to keep me distracted, but I will spend some time in the next couple weeks reviewing the old PRs and submitting them in the new repo.

**Comment by facastagnini** [comment]
Reopening so people can find this easily

**Comment by binarykitchen** [comment]
Read through this thread and I am a bit lost. 

Now that this repo is not maintained anymore and the bug https://github.com/sorin-ionescu/prezto/issues/1249 is a pain in the arse, I wonder to which one repo I should switch?

https://github.com/Eriner/zim or https://github.com/zsh-users/prezto ??

What are their differences and how can I switch/migrate best?

**Comment by antoineco** [comment]
@binarykitchen if you are happy with prezto and want to stick with it choose the second option. The new maintainers of the project are making sure major bugs are fixed.

Zim is a different project, it may share some pieces of code with prezto here and there but it's essentially a completely new framework rewritten for simplicity and performance. Configurations are not compatible, default modules are different, etc.

**Comment by Eriner** [comment]
@antoineco as a small aside, one of these days I'll get around to re-benchmarking zim and zsh-users/prezto instead of this (Sorin) project to make a more fair comparison between the two.

@binarykitchen I'm the author of Zim, so take my suggestion FWIW, but if you haven't heavily customized or invested lots of time into tweaking prezto, I'd suggest taking a look at [zim](https://github.com/Eriner/zim), but I'm biased. ;)

**Comment by binarykitchen** [comment]
ok, thanks guys - think i ll just stick with the new repo of prezto for now and will move the bug report https://github.com/sorin-ionescu/prezto/issues/1249 there

**Comment by nicoulaj** [comment]
Related: zsh-users/prezto#26

**Comment by sorin-ionescu** [comment]
@facastagnini I welcome your enthusiasm for this project, and I thank you for picking up the slack. I wish you had sent me an email directly instead of relying on GitHub notifications. If you did, I did not see it. I would have given you access or moved the repository to zsh-users myself since it has become big enough.

@Eriner What happened to the author list comment at the top of files in Zim?

**Comment by Eriner** [comment]
@sorin-ionescu zim has never had an "author list" at the top of files, so I don't know what you're talking about. I think this is a silly practice; IMO people should simply use git, as that's how the rest of the project is managed.

**Comment by antoineco** [comment]
@eriner Sorin actually meant "you copied my code and didn't mention its original author", I think.

**Comment by Eriner** [comment]
@antoineco I didn't copy prezto code, aside from places where [attribution has been given](https://github.com/Eriner/zim/blob/master/modules/git/README.md). I did adopt the code/file structure used by prezto; it's the optimal way to organize the project.

**Comment by antoineco** [comment]
@Eriner I was not giving my opinion just trying to clarify the message which got apparently misunderstood. Sorry if it sounded otherwise!

**Comment by sorin-ionescu** [comment]
The rationale behind having the author list at the top of files in Prezto,   since nobody bothers to check the Git log to see who submitted a module first,   is that users would contact the authors of a module directly via the issue system, which would respond faster than me.  
 
 
 
 Since   Zim is Prezto-inspired, not a fork, and your turf, manage it however you please. I'm not imposing my views on you.  
 
 
 
 Prezto and Zim should keep a dialogue open.
 
 
 
 
>  
>  
>  
>    
>    
>  

 ]]>

**Comment by Eriner** [comment]
> @Eriner I was not giving my opinion just trying to clarify the message which got apparently misunderstood. Sorry if it sounded otherwise!

Nope, I got it, just wanted to clear everything up :+1:

> The rationale behind having the author list at the top of files in Prezto,   since nobody bothers to check the Git log to see who submitted a module first,   is that users would contact the authors of a module directly via the issue system, which would respond faster than me.

This makes sense, and is semi-related to one of the reasons we're in the process of transitioning zim to it's own organization, that way modules can be assigned to specific authors/maintainers, and the issue tracker can be used directly without overwhelming anyone. :)

> Since Zim is Prezto-inspired, not a fork, and your turf, manage it however you please. I'm not imposing my views on you.
> Prezto and Zim should keep a dialogue open.

Cool, appologies if my statement came off as too direct; I had just addressed the same comment a few days ago and felt as if I was repeating myself :P

Cheers

**Comment by belak** [comment]
I'm going to close this now because there have been a number of additional maintainers added and we've started managing pull requests.

**Comment by Po-Hsuan-Huang** [comment]
Can someone change the title of the issue ? It is quite confusing for new comers. It is not necessary to read this before opening a issue anymore.

**Comment by belak** [comment]
It shouldn't show up for most people, as it's been closed. I changed the title to make it clearer though.

**Comment by sorin-ionescu** [comment]
Yes, we keep the repository. The project has maintainers and is getting
commitments. We must prioritize bug fixes over new features.
