### ISSUE TITLE
syntax-highlighting module breaks '%_' in PS2 (continuation prompt)

### ISSUE THREAD

**Issue by mdemierre** [sorin-ionescu/prezto#1246]
When adding the syntax-highlighting module, the `%_` expansion (current constructs) doesn't work in PS2/PROMPT2.

Steps to reproduce:

1. Clone prezto repo, init submodules and setup symlinks
2. Add `syntax-highlighting` to modules, second to last like docs say
3. Open a new terminal
4. Try starting a for statement and continuing on next line
5. PS2 is `>` instead of `for>`

This screenshot illustrates the issue. The first command is done without syntax-highlighting and the second with it:
![prezto_issue_ps2_highlighting](https://cloud.githubusercontent.com/assets/459125/21542737/5f655cd6-cdc0-11e6-97ef-c660ac9df841.png)

This was tested on all vanilla prezto, with no other module added and no change to .z* files. I use zsh 5.3.1 on Arch Linux.

**Comment by mdemierre** [comment]
@chauncey-garrett This seems to work in the GIFs demonstrating your prompt, did you encounter this issue by any chance?

**Comment by mdemierre** [comment]
@facastagnini This also affects the community fork. Should I duplicate the issue there?

**Comment by facastagnini** [comment]
That will be great!

I saw that @danielbayerlein is active on the community fork zsh-users/prezto , we will take a look at it.

**Comment by mdemierre** [comment]
Closed, this issue is tracked there: https://github.com/zsh-users/prezto/issues/4

**Comment by johnpneumann** [comment]
Re-opening in case there needs to be discussion here vs the PR.

**Comment by johnpneumann** [comment]
For anyone who wants the ps prompt context, see [here](https://github.com/sorin-ionescu/prezto/tree/master/modules/editor#ps-context) on how to enable it.
