### ISSUE TITLE
Segmentation Fault (core dumped) if the git module is loaded

### ISSUE THREAD

**Issue by MatrixManAtYrService** [sorin-ionescu/prezto#1248]
It is possible that this is out of your hands, but I thought it best to write it up just in case you can help.

I am using the [Windows Linux Subsystem](https://msdn.microsoft.com/en-us/commandline/wsl/about).  For the most part, prezto is working just fine.  However, when I enable the git module, I get a segfault on startup:

```
$ # zsh launches without error if 'git' is not among the modules
$ cat -n .zpreztorc | grep pmodule -A 12
    26  zstyle ':prezto:load' pmodule \
    27    'environment' \
    28    'terminal' \
    29    'editor' \
    30    'history' \
    31    'directory' \
    32    'spectrum' \
    33    'utility' \
    34    'completion' \
    35    'syntax-highlighting' \
    36    'history-substring-search' \
    37    'prompt'
    38
$ zsh
 ❯❯❯ echo behold!
behold!
 ❯❯❯ exit
$ # but if we enable that module
$ sed -i "35i\  'git' \\\\" .zpreztorc
$ cat -n .zpreztorc | grep pmodule -A 12
    26  zstyle ':prezto:load' pmodule \
    27    'environment' \
    28    'terminal' \
    29    'editor' \
    30    'history' \
    31    'directory' \
    32    'spectrum' \
    33    'utility' \
    34    'completion' \
    35    'git' \
    36    'syntax-highlighting' \
    37    'history-substring-search' \
    38    'prompt'
$ zsh
 ❯❯❯ Segmentation fault (core dumped)
```

**Comment by facastagnini** [comment]
Hey @MatrixManAtYrService this repo is not being maintained, see #1239

The community fork is here https://github.com/zsh-users/prezto, please move this issue to zsh-users and we will be able to help you!

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

**Comment by MatrixManAtYrService** [comment]
Thanks for the heads up.

**Comment by CWSpear** [comment]
What a wild ride... now that we're back to _this_ repo... has this been addressed? I am still seeing it, but I don't think I'm on latest (checking into that, but figured this ticket could use an update either way).

**Comment by dijikul** [comment]
I too am seeing this issue on Redhat when trying to enable the git module.

**Comment by CWSpear** [comment]
I had some luck with updating the Windows Linux Subsystem. My config appeared to work without any need to modify anything after I was running Ubuntu 16.04 (specifically, I read they improved a lot of the Windows bindings, not that it is necessarily a newer Ubuntu)
