### ISSUE TITLE
Override alias by the Git module

### ISSUE THREAD

**Issue by ravishchawla** [sorin-ionescu/prezto#1254]
The Git module overrides the actual `git` script in `/usr/bin`. Calling `which git` prints the following for me:

```
git () {
	cd "$1"
	pwd
	ls -G
}

```

I want to know where this function definition is defined, because it only gets overridden when the Git module is activated.

**Comment by facastagnini** [comment]
Hey @ravishchawla  this repo is not being maintained, see #1239

The community fork is here https://github.com/zsh-users/prezto, please move this issue to zsh-users and we will be able to help you!

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

**Comment by belak** [comment]
We're pretty careful in prezto to not override system commands, especially ones used as much as git. The alias you mentioned isn't in prezto, so I'm going to close this for now.

If you need help debugging this, posting a link to your dotfiles would help.
