### ISSUE TITLE
[Idea] Optional module for Powerpill.

### ISSUE THREAD

**Issue by KoolDude214** [sorin-ionescu/prezto#1256]
I think that it would help me, as well as others who use the Powerpill script. This is basically a pacman frontend that uses rsync and aria2 to download. My idea is to have an optional completion module for powerpill that requires the module pacman.

**Comment by Neo2SHYAlien** [comment]
You should suggest your idea here - https://github.com/zsh-users/prezto. For more information checkout this issue https://github.com/sorin-ionescu/prezto/issues/1239

**Comment by sorin-ionescu** [comment]
Pacman front-ends should go into the pacman module. Open a pull request if that front-end is popular.
