### ISSUE TITLE
powerline theme with broken fonts on debian

### ISSUE THREAD

**Issue by alvesadrian** [sorin-ionescu/prezto#1261]
![screenshot_20170309_025829](https://cloud.githubusercontent.com/assets/1500347/23737909/a7cfb9f4-0474-11e7-847f-3ede0fe6ae08.png)

symbols looks broken

**Comment by belak** [comment]
This is almost definitely not an issue with prezto, as we just shell out to powerline directly.

There are some additional installation and font instructions on https://github.com/powerline/powerline that may be useful for you.
