### ISSUE TITLE
Complains about missing powerline.conf

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#1262]
Each time I SSH into my server, I am seeing this one error

![selection_001](https://cloud.githubusercontent.com/assets/177641/23831052/ee932266-077d-11e7-8371-a8df4a06ea06.png)

And then I am just seeing this plain theme where powerline and sorin theme are missing
![selection_003](https://cloud.githubusercontent.com/assets/177641/23831059/0fbe0ae6-077e-11e7-8258-69e18f51366a.png)

Any clues what this could be?

**Comment by belak** [comment]
I'm fairly sure this is an issue with the upstream powerline theme. Which theme are you using? Are you still running into this issue?

**Comment by sorin-ionescu** [comment]
You don't have Powerline installed on that server. Powerline should check for that.
