### ISSUE TITLE
gnu-utility module should not override shell builtins

### ISSUE THREAD

**Issue by danielkza** [sorin-ionescu/prezto#1263]
As per title, the gnu-utility module should not create alias functions for commands that exist as GNU binaries, but also as ZSH builtins, such as `kill` and `which`, since that behaviors does not exist in the original systems nor in a GNU-native system such as Linux.

**Comment by sorin-ionescu** [comment]
I would need a list of shell built-ins to correct that behavior.
 

 
Installing GNU Coreutils on BSD and using this module is more of a novelty item.
 
 
 
>  
>  
>  
>    
>    
>  

 ]]>

**Comment by danielkza** [comment]
It's not necessary to keep a list, it can be checked at run time in the
`$builtins` associative array. I'm actually using it in OS X.

Em seg, 13 de mar de 2017 11:52, Sorin Ionescu <notifications@github.com>
escreveu:
