### ISSUE TITLE
I wonder how should I put vim in background when I'd like to switch to the terminal

### ISSUE THREAD

**Issue by junhan-z** [sorin-ionescu/prezto#1270]
I used to use vim and press `Ctrl-z` to put vim in background and do some stuff in terminal. Once I'm done, I will type `fg` in terminal to come back to vim.

However, after I installed prezto, this workflow is gone. Anyone could provide advice on this issue? 

Thanks!

**Comment by jostyee** [comment]
Weird, the workflow is working here.

**Comment by crivotz** [comment]
workflow works for me too. I tried with and without tmux enabled

**Comment by junhan-z** [comment]
@jostyee @crivotz weird.. I tried both on my dev box and Mac, it doesn't work! 

In the vim it says "No errors"

Attached the screenshot

![image](https://cloud.githubusercontent.com/assets/5921660/24576360/9adc8d78-166f-11e7-99c3-98966c35891f.png)

**Comment by junhan-z** [comment]
oh wait.. I think I made a mistake.

I installed my prezto via yadr, which is only one part of the yadr, I believe it is yadr's vim configuration that breaks this workflow.

Thanks for all the help, guys!

**Comment by jiahut** [comment]
comment out  `prezto:module:terminal`
 it will cause `Ctrl-z` not working.
