### ISSUE TITLE
Port improvements from oh-my-zsh version of agnoster

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1274]
https://github.com/sorin-ionescu/prezto/pull/1168#issuecomment-291533192

Some of these changes are really useful so it may be worthwhile looking into this.

**Comment by sorin-ionescu** [comment]
This is an external theme. You'll have to do it upstream.

**Comment by belak** [comment]
They don't merge much upstream, even leaving security fixes for multiple months... I'm skeptical they would be merged. 

However that's fair enough. I'll close this.

**Comment by sorin-ionescu** [comment]
Complicated themes are often a nightmare to debug. I prefer to keep it external. Someone should fork it.

**Comment by belak** [comment]
Yep that's fair enough.
