### ISSUE TITLE
Ping PR authors to re-open their PRs

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1279]
A bunch of PRs have been closed by the original authors because they assumed this project was abandoned. 

Be good to go through those and ping the authors to see if they're okay if re-open and merge the valid ones.

OTOH, some of this might just as easily be handled by cherry-picking those changes out of the https://github.com/zsh-users/prezto/ temporary fork.

**Comment by paulmelnikow** [comment]
I'm happy to help comb through the changes from the fork and re-open them here. The bugfixes should be proactively reopened but I'm not sure all the additions need to be. Some triage and discussion may be needed.

If PRs here simply need to be reopened, a maintainer can do that.

**Comment by belak** [comment]
@paulmelnikow Would you be willing to make a list of what went into the fork, so we can start checking those off here? I've merged quite a few of them, but some of them didn't make it in (or they need a review) so it would be nice to track them somewhere.

**Comment by paulmelnikow** [comment]
Yea, for sure. Might take me a few days. Will aim for next week.

By the way, the community fork has been moved:
https://github.com/prezto-inactive-community-fork/prezto

**Comment by sorin-ionescu** [comment]
Please label unlabeled issues for easier identification. I don't think it's necessary to ping them unless the PR requires work. Many times I've modified patches instead of waiting for their original authors then signed them with `gift commit -s` to mark them as such.

**Comment by paulmelnikow** [comment]
I made a list of everything that was merged in the community fork.

https://docs.google.com/spreadsheets/d/1m2uVuRwx6lSGmEY2R3X67NF64691N6NBcSidgov3Kt0/edit#gid=0

I skipped submodule updates. The next step is to identify what has and hasn't been merged here. I'm happy to keep working on this, though I wanted to share my progress.

**Comment by sorin-ionescu** [comment]
@paulmelnikow Thanks for the spreadsheet.

From a quick glance, there are some changes there I don't like:
- Messing with `$TMPDIR` for no reason and breaking themes.
- `$ZPREZTODIR`, I believe, I named something else in one of my work branches. 
- Deer is too new, and its known issues are extensive. I don't want buggy stuff in Prezto.

**Comment by indrajitr** [comment]
I am not a fan of `maven` plugin [prezto-inactive-community-fork/prezto#22] in its current form either. We should probably have:

* `_mvn` is already available as part of [zsh-users/zsh-completions](https://github.com/zsh-users/zsh-completions) which we pull in anyway.
* The technique applied for colorizing (`sed` for every line might slow down `mvn`'s output even further). We should force this on user -- at least not by default.
* Instead of being too specific, we can consider a more general purpose java plugin (being consistent along the lines of ruby, node, python plugin) which addresses basic java stuff as well as `mvn`, `gradle` etc.)

**Comment by paulmelnikow** [comment]
> - Messing with $TMPDIR for no reason and breaking themes.

Agreed, I think. The change in prezto-inactive-community-fork/prezto#6 doesn't make sense, though the one merged here in #1209 does.

> - $ZPREZTODIR, I believe, I named something else in one of my work branches.

This has already been merged, though the name could be changed. So far I think only Antigen is using it.

> - Deer is too new, and its known issues are extensive. I don't want buggy stuff in Prezto.

👍 

> I am not a fan of maven plugin [prezto-inactive-community-fork/prezto#22] in its current form either.

Certainly the completions shouldn't be merged. The colorized implementation is turned off by default, which makes it extra pointless. I'd agree about making a java plugin instead.

**Comment by indrajitr** [comment]
> Certainly the completions shouldn't be merged. The colorized implementation is turned off by default, which makes it extra pointless. I'd agree about making a java plugin instead.

Have a minimal java plugin around in [my fork](https://github.com/indrajitr/prezto/tree/master/modules/java). In case there is an interest I can do some spring cleaning and make a PR.

**Comment by doppioandante** [comment]
> > Messing with $TMPDIR for no reason and breaking themes.
> Agreed, I think. The change in prezto-inactive-community-fork/prezto#6 doesn't make sense, though the one merged here in #1209 does.

I don't remember why I did that PR exactly, but I recall it was a program that used the $TMPDIR directory to store data for session persistency and having the value of TMPDIR change every time a new zsh instance is spawned makes no sense to me anyway.

This could be related to #1319 (pretty sure it wasn't tmux in my case though)

**Comment by belak** [comment]
I might end up reverting #1209 because I think it breaks some default functionality, but it could still be a useful change. :/

**Comment by jeffwidman** [comment]
Can this be closed?

**Comment by belak** [comment]
I think so. We might not have gotten everything, but it's pretty clear all development has moved back to this repo.
