### ISSUE TITLE
customise Dash prefix for mand in the osx module

### ISSUE THREAD

**Issue by nstCactus** [sorin-ionescu/prezto#1291]
I use Dash's manpages docset but for the sake of convenience, I shortened the default **manpages:** prefix to just **man:**.

When I use the `mand` command, Dash opens on a web search instead of searching the manpages docset (https://www.dropbox.com/s/e0uobdmmghiapic/Screenshot%202017-04-11%2010.17.42.png?dl=0)

Digging through the mand function code, I found how to change it but I'd like to make it configurable. What's the best way to achieve this: 
  * environment variable
  * zstyle
  * something else?

**Comment by belak** [comment]
zstyle is generally the preferred way of doing settings in prezto. Feel free to submit a PR and I can take a look. Thanks!

**Comment by indrajitr** [comment]
@nstCactus would be interested in knowing more about what doesn't work for you with `mand` and what you did to fix it.
FWIW, I keep using it from time to time and Dash shows up the man page as expected.

**Comment by nstCactus** [comment]
Here is my Dash config (notice that I changed the default **manpages:** prefix to just **man**): 

![Dash config](https://www.dropbox.com/s/7v7fzmbjv083alu/Screenshot%202017-07-21%2015.15.38.png?raw=1)

Now when I use `mand curl`, Dash does open but here's what I get:

![Dash search](https://www.dropbox.com/s/vmb5rk2zdo9orrp/Screenshot%202017-07-21%2015.21.06.png?raw=1)

I didn't do anything to fix it yet, I forgot about this issue. I mainly use Dash with its system-wide hotkey anyway.

**Comment by indrajitr** [comment]
#1399 is all that you'd need :)

**Comment by indrajitr** [comment]
closed in #1399
