### ISSUE TITLE
Define contributor guidelines

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1296]
This would include things like a style guide (two space indents, `then` on the same line as the conditional, etc seems to be standard), what we like to see in commit messages, and what sort of things we're actually looking for (what sorts of modules we want to include/deny).

**Comment by sorin-ionescu** [comment]
[CONTRIBUTING.md](https://github.com/sorin-ionescu/prezto/blob/master/CONTRIBUTING.md) serves this.

**Comment by belak** [comment]
I'll add some of the more common code style issues to CONTRIBUTING.md

**Comment by wadkar** [comment]
Hey! Happy to oblige with linespacing (maybe add a modeline to help contributors?) and help with anything. Long time user here, and happy to contribute :)

**Comment by belak** [comment]
I added a basic code style guide to CONTRIBUTING.md. Please feel free to amend and/or improve it if you see any mistakes or holes.
