### ISSUE TITLE
Add new issue template

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1297]
Many of the issues I've been going back to don't have good steps to reproduce it... they're missing what platform, what version of zsh, etc... it would be good to have an issue template so we don't have to ask for it on every issue.

**Comment by sorin-ionescu** [comment]
That's a good idea. Which project has a relevant one we can embrace and extend?

**Comment by belak** [comment]
I've added initial versions based off these: https://github.com/stevemao/github-issue-templates/tree/master/simple

It may be worth adding check boxes and including common mistakes people make but this seemed like a good (if a bit minimal) start. Please feel free to tweak and improve them.
