### ISSUE TITLE
Docker aliases don't work for Docker for Mac

### ISSUE THREAD

**Issue by astyagun** [sorin-ionescu/prezto#1298]
It seems, that only `docker-machine` is supported. And when it is not found, then at least some aliases are not defined. I've tried `dkce` (it's not defined).

**Comment by belak** [comment]
I'm currently using the aliases with docker for mac and it's working for me. Do you have any information about your setup, like what your preztorc and/or zshrc looks like?

**Comment by astyagun** [comment]
Oops, sorry, I've forgotten, that you need to enable modules manually. Closing the ticket.

**Comment by belak** [comment]
Thanks for following up! Glad you got it figured out. :)

**Comment by astyagun** [comment]
Thank you! :)
