### ISSUE TITLE
Determine what to do with less popular modules

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1299]
There are a number of open PRs which add external modules which would fit better elsewhere. Do we want to point people to awesome-zsh or have a separate file in the repo with additional plugins people maintain externally?

I don't know what the right solution is, so I figured it would be good to start a discussion.

**Comment by sorin-ionescu** [comment]
I usually reject unpopular modules. They won't be maintained. I don't want Prezto to be a code repository.

**Comment by belak** [comment]
I have no problems rejecting the modules themselves, but would it be worthwhile having a list somewhere or should we just send people to awesome-zsh?

**Comment by sorin-ionescu** [comment]
If they are not awesome; they won't make it onto that list. It's the responsibility of authors to promote their code, not ours.

**Comment by belak** [comment]
Sounds good. I'll start closing them later today.

**Comment by sorin-ionescu** [comment]
Add the Module and Rejected labels to not confuse them with merged ones. Thank you.
