### ISSUE TITLE
Completion module is very slow (startup time)

### ISSUE THREAD

**Issue by mateuszlewko** [sorin-ionescu/prezto#1309]
### Description

After I enabled completion module, my startup time increased from 0.75s to 3.45s, which is very unusual for a single module. Should it be that way or is it possible to speed things up?

### Steps to Reproduce

0. `/usr/bin/time zsh -i -c exit`
1. `zstyle ':prezto:load' pmodule ... 'completion'`
2. `/usr/bin/time zsh -i -c exit`

### Versions

  - Prezto commit: latest 
  - ZSH version: latest 
  - OS information: Ubuntu 16.04 on Windows 10

**Comment by belak** [comment]
Could you take a look at https://github.com/sorin-ionescu/prezto/pull/1314 and see if the caching improves the startup time (after caching) for you?

**Comment by mateuszlewko** [comment]
Yeah it improved my startup time from ~3.4s to ~2.15s (which is still high, I'll investigate it later). I guess compinit restores .zcompdump file, but what is the difference between `compinit -i -C` and `compinit -i`?

**Comment by belak** [comment]
The -C option specifies that the cache should not be recreated even if the completion files changed.

http://zsh.sourceforge.net/Doc/Release/Completion-System.html
