### ISSUE TITLE
Can't find sorin theme

### ISSUE THREAD

**Issue by devin42r** [sorin-ionescu/prezto#1313]
I used to have sorin theme as seen on main page, but I can't figure out how to get it after a new image.  Doesn't show in prompt -l.  Can someone remind me how I can enable that and the green/red command validation?

**Comment by devin42r** [comment]
Ah I see it goes in .zpreztorc

zstyle ':prezto:module:prompt' theme 'sorin'
but doesn't seem to update?

**Comment by devin42r** [comment]
Added 
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" to bottom of .zshrc in ~ 
and it seems to work, but that is not best config, if I understand correctly

**Comment by belak** [comment]
The red/green for commands which don't exist is in the syntax-highlighting module.

Are you sure you have prezto set up properly? There are setup instructions in the README. All the runcoms need to be in place (at the very least prezto needs to be loaded in your zshrc). sorin (and all the other prompt themes) should show up in prompt -l if configured properly.

**Comment by devin42r** [comment]
@belak thanks.  Yeah I followed the README to the best of my ability but am confused.  I have a .zshrc in ~ to which I appended the setopt EXTENDED_GLOB etc that is in step three of installation guide.  After executin "zsh" once, it failed the second time saying it couldn't create symlinks because they already exist, so I removed the code from step three.  

My question is, what exactly should I do to accomplish step three.  Where do I create a new zsh config and put the code snippet such that my sorin theme will always work without having to put source change at bottom of .zshrc?

**Comment by belak** [comment]
The extended glob portion isn't intended to be added to your zshrc. That's the portion of the setup which tries to set up the proper symlinks. 

As it says in the readme:

```
If you already have any of the given config files, ln will error. In simple cases you can add source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" to the bottom of your .zshrc to load prezto but keep your config intact.
```

So, you had the right idea, adding that to the bottom of your zshrc. :)

I'm going to close this now because it's explained in the readme what to do and that sounds like it fixed the issue for you, but feel free to ping me if you have any further problems and I can reopen the issue.
