### ISSUE TITLE
sorin broken symbols on urxvt

### ISSUE THREAD

**Issue by alvesadrian** [sorin-ionescu/prezto#1318]
![2017-05-10-025305_1366x768_scrot](https://cloud.githubusercontent.com/assets/1500347/25885004/60f2db22-352c-11e7-9c8d-b793d54b0901.png)
as you can see in the attached file the sorin symbols are broken running zsh and prezto on urxvt

**Comment by belak** [comment]
What font are you using and can you post your Xresources file?

**Comment by alvesadrian** [comment]
I tried several fonts like Monaco and Monospace and the same issue happens, but right now am using Mononoki, here is my Xresources:
 urxvt*termName:  rxvt-256color
 URxvt.buffered:           true
 urxvt*loginShell:         true
 urxvt*scrollBar:         false
 urxvt*secondaryScroll:    true
 urxvt*saveLines:         65535
 urxvt*cursorBlink:        true
 urxvt*urgentOnBell:       true
 !urxvt*override-redirect:false
 !urxvt*borderLess:       false
 !urxvt*internalBorder:       0
 !urxvt*externalBorder:       0
 urxvt*perl-lib:        /usr/lib/urxvt/perl/
 urxvt*perl-ext-common: default,matcher,searchable-scrollback
 urxvt*urlLauncher:     /usr/bin/firefox
 urxvt*matcher.button:  1
 URxvt*font:       xft:Mononoki:size=18:antialias=true
 !urxvt*boldFont:    -xos4-Mononoki-bold-*-*-*-18-*-*-*-*-*-*-*
 !urxvt*cursorColor: #DCDCCC
 urxvt*cursorColor: green
 !urxvt*shading:    20
 !urxvt*transparent:true
 urxvt.background:  #000000
 urxvt.foreground:  #EBEBFF
 URxvt.depth: 32
 URxvt*background: rgba:0000/0000/0200/c800
 !urxvt*color0:     #3f3f3f
 urxvt*color0:      #000000
 urxvt*color1:      #e01010
 urxvt*color2:      #00AA00
 urxvt*color3:      #FFFF00
 urxvt*color4:      #112037
 urxvt*color5:      #A020F0
 urxvt*color6:      #5B5BC7
 urxvt*color7:      #fefefe
 urxvt*color8:      #6a6a6a
 urxvt*color9:      #FF5555
 urxvt*color10:     #90EE90
 urxvt*color11:     #ffff2f
 urxvt*color12:     #5B5BC7
 urxvt*color13:     #e628ba
 urxvt*color14:     #7D7DFB
 urxvt*color15:     #ffffff
 Xcursor.theme: Adwaita

**Comment by diraol** [comment]
Adrian, which theme are you using?

**Comment by crivotz** [comment]
I don't have this problem, similar configutation (you can take a look at my [dot_files](https://github.com/crivotz/dot_files))
As font I use [Hack](http://sourcefoundry.org/hack/)

**Comment by adrian-gluu** [comment]
URVT with the default font is failing, is not a font issue

**Comment by adrian-gluu** [comment]
the theme am using is "sorin"

**Comment by alvesadrian** [comment]
@crivotz tried your .Xdefaults and .Xresources with no luck still broken symbols

**Comment by alvesadrian** [comment]
by the way this just happens on arch linux on debian works fine urxvt

**Comment by crivotz** [comment]
I'm on Debian, explained the difference
Take a look at this link from [Arch forum](https://bbs.archlinux.org/viewtopic.php?id=165724)

**Comment by alvesadrian** [comment]
this is probably an issue with arch and powerline fonts because the same issue of broken symbols happens on xterm

**Comment by alvesadrian** [comment]
@crivotz tried all the forum options but didn't work

**Comment by diraol** [comment]
@cemsbr, can you add some refs here about it?

**Comment by cemsbr** [comment]
urxvt does not support double-width characters. There are at least 3 ways to solve this problem:
- If your distro is Archlinux, there's a [patched urxvt in AUR](https://aur.archlinux.org/packages/rxvt-unicode-wcwidthcallback);
- [Nerd-fonts](https://github.com/ryanoasis/nerd-fonts) does not use double-width glyphs. They are smaller, but play nice with official urxvt;
- Use another terminal (e.g. terminator).

**Comment by belak** [comment]
Thanks for the info @cemsbr.

I'm not sure how to proceed with this, as I'm fairly sure this isn't an issue with prezto (we use the same unicode characters for powerline and other things as everyone else) and may be an issue with urxvt or a font configuration.

**Comment by samcv** [comment]
**Also** urxvt you *must* explicitly list your fallback fonts. It won't automatically fall back to other fonts on your system which contain the glyph you need. Keep that in mind. You may want to use:
```
fc-scan -f 'Charset: %{charset}' font.ttf
```
And see if the symbol you need is listed. Note you need at least fontconfig (freetype) v2.11.91 or greater for charset to work with fc-scan.
.XResources line to configure multiple fonts: `URxvt*font: xft:tewi2a-medium:pixelsize=11:antialias=false,xft:Noto Emoji:pixelsize=6:minspace=False:antialias=false,xft:Symbola:pixelsize=6:minspace=False:antialias=False`
For an explaination see my config file here: https://github.com/samcv/dot-files/blob/master/.Xresources#L2-L6

I don't use urxvt but the config is from back when I did use it for a period of time.

**Comment by belak** [comment]
Thanks for clearing that up! This definitely doesn't seem like it's an issue with prezto and there are instructions for fixing it so I'm closing this now. Thanks everyone!
