### ISSUE TITLE
Setting TMPDIR using mktemp disrupts tmux use

### ISSUE THREAD

**Issue by mworkentine** [sorin-ionescu/prezto#1319]
This commit: https://github.com/sorin-ionescu/prezto/commit/3a6ae0fc6c73963e5f6b0b77f32d219677c840b5 disrupts tmux use.  Because each login session gets a unique `$TMPDIR` when you logout and login again tmux can't find it's socket file as tmux uses `$TMPDIR` if it's set.

My solution for now is to set `$TMPDIR` in `.zshrc` but I'm wondering if there is a better fix for this?

**Comment by avsmith** [comment]
Also seeing this. For the moment, I am reverting to the old behavior with the following in `.zshrc` 

    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"`

**Comment by belak** [comment]
Yeah, it looks like we need a way to get a consistent TMPDIR. I'm open to any changes or even a revert at this point because I'm not 100% sure if the change was to fix anything or just clean it up.

**Comment by fd0** [comment]
I also stumbled upon this. I wonder, what was the intention of the original commit?

At least the `sorin` theme writes data to a non-unique file within `TMPDIR`:
```
modules/prompt/functions/prompt_sorin_setup:

[...]
function prompt_sorin_setup { 
  setopt LOCAL_OPTIONS
  unsetopt XTRACE KSH_ARRAYS
  prompt_opts=(cr percent subst)
  _prompt_sorin_precmd_async_pid=0
  _prompt_sorin_precmd_async_data="${TMPPREFIX}-prompt_sorin_data"
[...]
```

I think we can just use a unique temp file here, no need for a static path.

**Comment by belak** [comment]
Ah that makes sense. Because the sorin prompt uses a file in the tmpdir, if you have multiple shells open with a static tmpdir, the git data can bleed between them.

**Comment by fd0** [comment]
But that should IMHO be corrected for the sorin theme, not by globally setting a `TMPDIR`...

**Comment by belak** [comment]
I agree. Preferably, the sorin prompt wouldn't dump to a file the way it does right now... It's very error prone and doesn't handle special characters properly.

Anyway, if anyone wants to submit the revert and a fix for sorin, I'd accept them.

**Comment by fd0** [comment]
I3ve given it a shot in #1330, let me know what you think.
