### ISSUE TITLE
SSH module asks for passphrase (ksshaskpass)

### ISSUE THREAD

**Issue by flying-sheep** [sorin-ionescu/prezto#1320]
With `SSH_ASKPASS=/usr/bin/ksshaskpass`, get asked for my passphrase. The SSH module currently invokes ssh-add like that, so i open a shell to the “Enter passphrase” prompt with it active:

```console
$ ssh-add
Enter passphrase for ~/.ssh/id_rsa:
```

But when invoked without a terminal attached to stdin, `ssh-add` invokes ksshaskpass:

```console
$ ssh-add </dev/null
```

**Comment by belak** [comment]
I may be misunderstanding something, but if you set SSH_ASKPASS and call ssh-add, it should use that program. Any additional variables can be set in `~/.zpreztorc` to make sure they're set before any modules are loaded.

If that's not the case, some clarification about what you're hoping for would be helpful... in the future using the issue template provided would be a big help so we have more information and don't need to ask for as much clarification. :)

**Comment by flying-sheep** [comment]
> if you set SSH_ASKPASS and call ssh-add, it should use that program.

sadly not:

> [ssh-add(1)](https://linux.die.net/man/1/ssh-add):  
> If ssh-add needs a passphrase, it will read the passphrase from the current terminal if it was run from a terminal. If ssh-add does not have a terminal associated with it but DISPLAY and SSH_ASKPASS are set, it will execute the program specified by SSH_ASKPASS and open an X11 window to read the passphrase.

**Comment by belak** [comment]
Not a problem. Thanks for clarifying... that's odd behavior for ssh-add. I'm really not sure how to fix this then, as this would require input redirection (which with my basic testing still seems to work with normal terminal input somehow... I assumed it wouldn't) and would also require setting DISPLAY.

I'm open to any suggestions!

**Comment by flying-sheep** [comment]
why not just like that?

**Comment by belak** [comment]
Oh, I'm an idiot. I was playing around with it on OSX where display wouldn't be set by default, but this is used more often on Linux where it would be... makes sense. I'll take another look in a bit.
