### ISSUE TITLE
tmux can not determine current working directory

### ISSUE THREAD

**Issue by skjbulcher** [sorin-ionescu/prezto#1327]
Please check if a similar issue already exists or has been closed before before opening your issue.

### Description

tmux' variable "`#{pane_current_path}`" doesn't appear to work
e.g., when using byobu `tmux new-window -c "#{pane_current_path}"` results in a window with the path set to the user's home directory, regardless of the path the user was in before. If I were to conjecture, I would say that tmux is unable to load #{pane_current_path}, but I can't figure out how to debug this.

*Notes:*

- I do use a custom prompt, but I was able to reproduce the issue using the "suse" prompt.
- Removing the call to `.zprezto/init.zsh` in `.zshrc` causes tmux to act as expected.
- Reducing the loaded modules to `zstyle ':prezto:load' pmodule prompt` did not affect behavior.

### Expected behavior

New windows open in the cwd

### Actual behavior

New windows open in $HOME

### Steps to Reproduce

1. `byobu`
2. `cd ..`
3. `F2` / `tmux new-window -c "#{pane_current_path}"`

### Versions

  - Prezto commit: 7ae7a0266c04f2645bdf9917378645fc505e7461
  - ZSH version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
  - OS information:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by belak** [comment]
This may be related to the TMPDIR settings. If you set TMPDIR to something like /tmp in your preztorc do you still see this issue?

**Comment by skjbulcher** [comment]
Adding `TMP=/tmp` to the end of `~/.preztorc` did not alter the behavior

**Comment by ezintz** [comment]
I can confirm this issues, which is one of the reasons I dropped tmux :( I've been using it with iTerm2 on the latest Mac OS.

**Comment by belak** [comment]
I've tried to reproduce this, unfortunately with no real success. I've tried with both byobu and plain tmux and haven't seen the behavior mentioned.

@ezintz Out of curiosity, are you using the latest version of prezto? It looks like your dotfiles repo has you pinned to a custom fork which is a year or so out of date... it's also worth noting that prezto can be loaded out of any directory now, so your main reason for forking may not be needed any more. ;)

@skjbulcher Can you provide any more information about your setup? I don't see any public dotfiles for you, so I don't really have a lot to go on in trying to reproduce this.

**Comment by ezintz** [comment]
@belak you are right, it is probably a "bit" out of date since I did do much house cleaning over there. Thanks for the hint as soon as I find some time I will give it a try and report back.

**Comment by skjbulcher** [comment]
My problem was an errant `cd $HOME` in `.zshrc`. Now that I think about it, I added that line to overcome an issue where WSL didn't dump me into my home directory. >_< I think this issue can be closed.

WSL does has a problem, though, where new windows open at the root directory (`/`) instead of the cwd, but I can't imagine that is prezto related.

**Comment by belak** [comment]
Thanks for investigating! Glad you figured it out. :)
