### ISSUE TITLE
Sign git commits (& releases)

### ISSUE THREAD

**Issue by rugk** [sorin-ionescu/prezto#1329]
You should consider signing git commits & releases.
Then, we can securely download/update the scripts with `git pull --verify-signatures`.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/signing-commits-with-gpg/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases ([and here is a script for that](https://github.com/rugk/gittools/blob/master/signrelease.sh))

**Comment by belak** [comment]
I don't have a problem with doing this for my own commits but I think requiring this for any contributor will greatly reduce the number of contributions we get, which isn't something I'd like to do. The other possibility is signing releases, but we don't currently tag releases (maybe we should) and I'm not sure what the plans are for that in the future.

**Comment by rugk** [comment]
Actually contributors with no direct push access do not need to sign commits. It's is sufficient if you sign the merge commit (or how else you commit it). This way everything is signed and that's enough… :smiley:

**Comment by belak** [comment]
I've opened #1354 in favor of this to discuss a full release strategy, in addition to possibly signing commits. Discussion will continue there.

Thanks for the idea!
