### ISSUE TITLE
prompt sorin theme broken on FreeBSD TMPDIR doesn't get set

### ISSUE THREAD

**Issue by samcv** [sorin-ionescu/prezto#1331]
### Description
The problem is that TMPDIR does not get set. I added a print inside `modules/prompt/functions/prompt_sorin_setup` to print out `TMPDIR`, and it ended up being empty.
I made a folder ~/tmp and then added a line at the top of `modules/prompt/functions/prompt_sorin_setup` to set `TMPDIR="$HOME/tmp"` this resolved the errors.

### Expected behavior

No error.

### Actual behavior

```
mktemp: mkstemp failed on /sorin-prompt-async-2sa6cJ5bWe: Permission denied`
prompt_sorin_precmd_async:4: no such file or directory:`
```

### Steps to Reproduce

1. Use zprezto with sorin theme
2. No further steps required
3. Message shows after every command, or display of prompt (pressing enter with no text entered)

### Versions

  - Prezto commit: 2f20a80f7255bffcf878de70192f6df126c6069f
  - ZSH version: zsh 5.3.1
  - OS information: FreeBSD 11.0

**Comment by belak** [comment]
Do you have all the runcoms set up? TMPDIR is currently set in zprofile, so if you're only using zshrc it may not be getting set properly.

However, this seems a bit error prone so I'll look at improving it, maybe by falling back to /tmp in the prezto theme.

**Comment by samcv** [comment]
Yes, I have .zpreztorc, .zshrc, and it's all setup and loading. So maybe the problem is not specifically in that theme, but everything except TMPDIR being set are working fine.

**Comment by belak** [comment]
I've updated the sorin theme to default to /tmp if it isn't set, though I'm not sure why it wouldn't be getting set properly in .zprofile.
