### ISSUE TITLE
Sorin theme on OS X does not show <name>@<host> but other themes do.

### ISSUE THREAD

**Issue by unphased** [sorin-ionescu/prezto#1336]
### ubuntu 14.04 on the left, OS X on the right

![image](https://user-images.githubusercontent.com/1542910/27356024-06e3bd8e-55db-11e7-8b4d-120d00146ead.png)

  - Prezto commit: 1c041c0
  - ZSH version: 5.3.1
  - OS information: El Cap 10.11.6

I also confirmed that their `$PS1` are identical (as they must, because I have the same prezto code checked out)

**Comment by ezintz** [comment]
Is it possible that on the right, Mac OS, is your local environment and the left, Ubuntu, is a remote connection? See https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L123

**Comment by unphased** [comment]
Ah... That makes a lot of sense now. So you're basically saying that this field only pops up if we're on an SSH session!

Excellent, everything is functioning as intended then.
