### ISSUE TITLE
new editor init.zsh: init.zsh:292: unknown file attribute

### ISSUE THREAD

**Issue by ChromeHearts** [sorin-ionescu/prezto#1373]
Please check if a similar issue already exists or has been closed before before opening your issue.

### Description

[Description of the bug or feature]
The latest Editor module split out an error message as following:
~/.zprezto/modules/editor/init.zsh:292: unknown file attribute

### Expected behavior

[What you expected to happen]
No error message

### Actual behavior

[What actually happened]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

  - Prezto commit:3f99519
  - ZSH version:
  - OS information:

**Comment by belak** [comment]
I don't see this with my setup. Can you provide any additional information about settings?

**Comment by belak** [comment]
Additionally, as this may be a zsh version-specific issue, please fll out the rest of the information (at least zsh version and os information)

**Comment by andsens** [comment]
Same here:
zsh version: 4.3.17
OS: Debian 7.11 (64-bit)

e3520b737f8f6b908e3fc62934ede1a75a16e32b is the culprit, reverting that commit fixes it, though I am not exactly sure where the error is.

**Comment by belak** [comment]
Odd. Looks like we need to be more careful about our array initialization. I'll try to get a fix out in an hour or two, but for whatever reason I still haven't run into this so it may be hard to test.

https://stackoverflow.com/questions/14917501/local-arrays-in-zsh

**Comment by andsens** [comment]
Yup, fix confirmed 👍 
Thanks for the quick response @belak !

**Comment by belak** [comment]
I've pushed a fix, as you noticed. It looks like older versions of zsh (pre 5.1) don't define local or typeset as keywords, so there's some oddities there and we need to define the variable as an array separate to initializing it with data.

Thanks for reporting this and sorry for the inconvenience!

**Comment by ChromeHearts** [comment]
@belak it's fixed for me as well!  Thanks for the prompt fix!!!!!
