### ISSUE TITLE
Speeding up completion when /etc/hosts is big with many blacklisted domains

### ISSUE THREAD

**Issue by matrixik** [sorin-ionescu/prezto#1387]
### Description

Speeding up completion when /etc/hosts is big.
I want to use https://github.com/StevenBlack/hosts for blacklisting many domains but this will make autocompletion slow.

https://github.com/imanel/hosts_updater/#slow-auto-complete
> As a lot of hosts are added to your system, autocomplete might slow down. To solve this in zsh prezto one could replace `cat /etc/hosts (|)(N)` with `sed /0\.0\.0\.0/d`. This prevents the domains to be loaded for completion.

This change could be made in https://github.com/sorin-ionescu/prezto/blob/6e1f4ddd19dca2a02a79658fc8b9f8d230b591d0/modules/completion/init.zsh#L108

I don't know if you would like to make this change globally for all users?
And if not maybe some configuration option would be nice.
Personally I don't want to have any changes in prezto itself, only in runcoms.

### Expected behavior

Do not autocomplete domains blacklisted in `/etc/hosts` (`0.0.0.0 domain.com`).

### Actual behavior

Autocompletion is working for all domains in `/etc/hosts`.

### Steps to Reproduce

1. sudo vim /etc/hosts
2. Add `0.0.0.0 domain.com`
3. Restart terminal
4. `ssh dom<Tab>`

### Versions

  - Prezto commit: 18c96095f6df204efc6b2c69a0b6733d6de27ea6
  - ZSH version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
  - OS information:
           Kernel: 4.8.0-58-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3)
           Distro: Linux Mint 18.1 Serena

**Comment by indrajitr** [comment]
StevenBlack/hosts is a great project! While I personally don't modify `/etc/hosts` at system level, this the default recommendation there.

Couple of options I can think of:
* Allow a configurable pattern to ignore (note that hardcoding `0.0.0.0` doesn't solve the problem because that can be configured to a different IP address when building the `hosts` file)
* Allow a configurable flag to ignore `/etc/hosts` altogether.

**Comment by indrajitr** [comment]
So this is a rough approximation of what I am looking at:

```sh
zstyle -e ':completion:*:hosts' hosts 'reply=(
  ${=${=${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) 2>/dev/null)"}%%[#| ]*}//\]:[0-9]*/ }//,/ }//\[/ }
  ${=${(f)"$(cat /etc/hosts(|)(N) <<(ypcat hosts 2>/dev/null))"}%%(\#|0.0.0.0)*}
  ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2>/dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'
```
@matrixik, I don't have a large _/etc/hosts_ to try out right now. Would you mind giving this a quick spin?
This is just a draft. I am actually considering a configurable array of _patterns_ that can be evicted.

**Comment by matrixik** [comment]
@indrajitr Tested, and it's working beautifully.

Thank you!
