### ISSUE TITLE
prompt_sorin_precmd:5: command not found: prompt-pwd

### ISSUE THREAD

**Issue by unjello** [sorin-ionescu/prezto#1401]
### Description

Sorin prompt displays `prompt_sorin_precmd:5: command not found: prompt-pwd` and current directory is not show before `>>>` (e.g. minimal prompt works fine).

### Expected behavior

it should not display error message

### Actual behavior

it displays an error message, and does not show current folder before `>>>`

### Steps to Reproduce

1. checkout prezto/master
2. prompt sorin

### Versions

  - Prezto commit: ever since 60c433d4ce680ddb2ca899b460e3714728cb221c
  - ZSH version: zsh 5.3.1 (x86_64-apple-darwin16.6.0)
  - OS information: macos 10.12.15

**Comment by indrajitr** [comment]
Likely that #1390 wasn't fully applied in your case.
Can you please verify that `modules/prompt/functions/prompt-pwd` exists and restart `zsh`?

**Comment by unjello** [comment]
yeah... something went wrong with fetch/checkout I guess. Cloned brand new and it works. Thanks.
