### ISSUE TITLE
Temporary maintainer vacation

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1405]
This isn't a bug in the standard sense. I just wanted to give some people a heads up that I'll be stepping away for a few weeks to destress a bit. I've got quite a bit going on at the moment and I'd like some time to focus on real life commitments. I want to make it clear that this should only be temporary and that there are still other maintainers around to handle things.

I will still be available if absolutely necessary but all the high-priority bugs I know of have been fixed and I trust @indrajitr (and the other maintainers) to run things (he's been doing great at stepping up these past few weeks which is why I'm explicitly mentioning him). You don't need to hold off on anything for me, unless you really want my review for something.

Hopefully filing an issue for this sort of thing won't be needed in the future, but I'd like to make it clear that the project is still active even if one of the main maintainers needs to disappear for a while.

Feel free to close this issue if you want, or I can close it when I'm back.

Cheers,
Kaleb

PS - First priority when I'm back will probably be #1354 (unless someone wants to get it done before then ;)) so we can make breaking changes a bit more safely. The sorin prompt async change has been pretty painful.

**Comment by indrajitr** [comment]
@belak, enjoy your time off. Not much will probably change when you are back.

I am assigning this to you and you can close this when you are back (as if _personal de-stressing_ is the task which stands completed when you are back :))

**Comment by johnpneumann** [comment]
Enjoy your break man. As a note, I've been gone for a bit due to changing jobs. I'm available to pick up any issues or pr's that need a look if someone needs something. Just tag me and I'll check them at night and do what I need with them, the following morning.

**Comment by belak** [comment]
Well, I've been half around for a few weeks and I think that's been enough of a break. Thanks to everyone for your patience and especially helping out a bit. I may still be unavailable for random weekends (like this one) but in general, I'm back. :)

**Comment by diraol** [comment]
I hope you have had a nice break ;)
