### ISSUE TITLE
How to enable completions installed by brew

### ISSUE THREAD

**Issue by jeeftor** [sorin-ionescu/prezto#1412]
I'm wondering for the best way to enable completions installed by home-brew.

For example I have a set of completion in `/usr/local/share/zsh/site-functions`

I've managed to get the `_aws` one working by sourcing the file directly.  It didn't seem to work correctly when i added it to the `fpath`.

Is there a best way of doing this?

**Comment by indrajitr** [comment]
> For example I have a set of completion in /usr/local/share/zsh/site-functions

Usually these are automatically added to `fpath` by zsh. You can verify that by checking out your `fpath` as so:
```
print -l $fpath
```

> I've managed to get the _aws one working by sourcing the file directly. It didn't seem to work correctly when i added it to the fpath.

For now, you'll have to explicitly source the file in till some adjustments are made [upstream](https://github.com/aws/aws-cli/pull/2708).

**Comment by jeeftor** [comment]
So it turns out the `_aws` completion module actually needs to be sourced in the current version.  Found a GitHub issue about it : https://github.com/aws/aws-cli/pull/2708
