### ISSUE TITLE
When developing - how to handle merge conflicts in runcoms/z...

### ISSUE THREAD

**Issue by jeeftor** [sorin-ionescu/prezto#1419]
I'm wondering how folks who are working on the code handle merge conflicts with 

	modified:   runcoms/zlogin
	modified:   runcoms/zpreztorc
	modified:   runcoms/zshrc

Every time i pull from upstream I have a conflict with these guys.  Whats the best practice to use for these guys?

**Comment by diraol** [comment]
There is no best practice for it for now, despite handling git conflicts by hand.

Here is a proposal to deal with it:
https://github.com/sorin-ionescu/prezto/pull/1346

Yet under discussion.

**Comment by jeffwidman** [comment]
Closing, let's continue the discussion in #1346
