### ISSUE TITLE
Github broke submodule updating to specific hash IDs

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1431]
Updating my install of prezto and hit the following issue:

    ~/.zprezto ❯❯❯ git submodule update --init --recursive                                                                                                                                                   
    error: Server does not allow request for unadvertised object 3ad94b659910c775a6560c45b1524d23d8c83b09
    Fetched in submodule path 'modules/prompt/external/agnoster', but it did not contain 3ad94b659910c775a6560c45b1524d23d8c83b09. Direct fetching of that commit failed.

Poking around the internet turned up this discussion: https://news.ycombinator.com/item?id=14552172

If I'm understanding this correctly, then Github has disabled fetching submodules by hashID, you can only fetch tags, or tips of branches. 

There's nothing in the `prezto` issue tracker about this, which surprised me, I would have thought someone would have hit this before. Perhaps it's something unique to my setup? I rarely work with submodules, so I'll have to refresh my memory a bit...

For context, I just finished rebasing my fork on top of the latest changes, which I hadn't updated in nearly two years, so currently my copy prezto is up to date, but the submodules that haven't updated yet are quite old.

**Comment by belak** [comment]
Hm, that's really weird. Not being able to specify a specific hash breaks quite a few things... I'll try to look at this later... but 3ad94b659910c775a6560c45b1524d23d8c83b09 is the tip of agnoster.

**Comment by jeffwidman** [comment]
Appears this was something in my environment. Running `git submodule sync` fixed this somehow and allowed me to then run the normal `git submodule update --init --recursive` successfully.

**Comment by belak** [comment]
Maybe the wrong url was specified in the agnoster submodule, so the submodule sync updated it to the correct value. Anyway, glad you got it figured out.
