### ISSUE TITLE
Ambiguous pronouns in module READMEs

### ISSUE THREAD

**Issue by foochuanwei** [sorin-ionescu/prezto#1441]
### Description

In module READMEs, some pronouns may be ambiguous. For example, in the [autosuggestions module](https://github.com/sorin-ionescu/prezto/tree/master/modules/autosuggestions)'s README.md:

> If this module is used in conjuncture with the syntax-highlighting module, it must be loaded after it.

Some people may not be able to tell what the first 'it' refers to.
For example, does the sentence mean:

> If this module is used in conjuncture with the syntax-highlighting module, this module must be loaded after it.

Or is the sentence supposed to mean:

> If this module is used in conjuncture with the syntax-highlighting module, it must be loaded after this module.

Fixing this issue will minimize confusion and prevent configuration mistakes.

**Comment by gpanders** [comment]
Unrelated, but while we're making changes to this README, `conjuncture` should be `conjunction`.
