### ISSUE TITLE
rsync with parens causes erroneous error about noremoteglob

### ISSUE THREAD

**Issue by chrisjohnson** [sorin-ionescu/prezto#1443]
### Description
Running the following command:

`mkdir /tmp/a && rsync -zvruP '/tmp/a' '/tmp/(c)'`

Gives an error rather than copying the data. Specifying rsync as /usr/bin/rsync works fine

### Expected behavior

I expect it to rsync `/tmp/a` to `/tmp/(c)`

### Actual behavior

I get the following output:

`noremoteglob:5: number expected`

And for another example (the one that I experienced the behavior originally):

```
$ rsync -zvruP 'The Black Dahlia Murder - Abysmal (Deluxe Edition) (2015) V0' '/data/music/Metal & Rock/The Black Dahlia Murder/'
noremoteglob:7: no matches found: The Black Dahlia Murder - Abysmal (Deluxe Edition) (2015) V0
```

### Steps to Reproduce

Outlined above

### Versions

  - Prezto commit: 83ab314b77d7e6bd92b7aed6275ad03018b378c1
  - ZSH version: zsh 5.4.1 (x86_64-unknown-linux-gnu)
  - OS information: Arch, fully updated as of 2 days ago

**Comment by chrisjohnson** [comment]
After a bit more experimentation it appears that noremoteglob:7 is the result of parens in the source, and noremoteglob:5 is the result of parens in the destination

**Comment by belak** [comment]
Well, I'm an idiot. I ran into this again in #1507 and forgot there was an open issue.

**Comment by belak** [comment]
This has been driving me bonkers and I'm nor really sure how to fix it... I may just end up reverting the noremoteglob stuff at some point if I can't get it figured out.

**Comment by chrisjohnson** [comment]
Thank you very much @belak
