### ISSUE TITLE
command-not-found module is super slow

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1451]
While working on https://github.com/sorin-ionescu/prezto/pull/1450, I noticed that enabling the `command-not-found` added ~2 seconds to shell startup time for an interactive session. This is on macOS using Homebrew.

However, directly calling `brew command command-not-found-init` seems to take only ~1 second.

Looking at https://github.com/sorin-ionescu/prezto/commit/b0c85eddf6bee4d75ca9920c9c6180ab7ff1962a, I'm wondering if the section:

    && brew command command-not-found-init > /dev/null 2>&1;

is actually running the command just to check its existence? If so, then this is running a very slow script twice on every shell startup...  Very possible I'm misreading this, as I'm very much a n00b when it comes to ZSH scripting.

@indrajitr am I reading this code correctly? Is it possible to change this to only run the script once?

**Comment by indrajitr** [comment]
@jeffwidman, this is closely following the official installation [instruction](https://github.com/Homebrew/homebrew-command-not-found#install).

`brew` subcommands are admittedly slow these days (particularly the `tap`ped ones). I haven't thought much about a way to work around it in this particular case but am certainly open to advice.

**Comment by jeffwidman** [comment]
Can you clarify first whether that code is actually running the script once or twice? We can figure out optimizations if it's twice, if just once there's not much to do about it...

**Comment by indrajitr** [comment]
Twice

**Comment by belak** [comment]
We could either removed the second call to brew or cache the output. Unfortunately, I don't know how best to expire the cache, since there isn't a static place command-not-found-init will be found

**Comment by sassanh** [comment]
I changed it in my `config.fish` to:
```
    # brew command command-not-found-init > /dev/null 2>&1; and . (brew command-not-found-init)
    source /usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.fish
```
and it's super fast now.

**Comment by belak** [comment]
Thanks for the workaround! I've switched prezto to use the .sh version of that file until we have a better solution.

**Comment by jeffwidman** [comment]
Thanks for fixing this @belak, much appreciated.

**Comment by indrajitr** [comment]
Hopefully #1611 would address this in an idiomatic way.
