### ISSUE TITLE
Should we set default architecture for macOS?

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1456]
There are a number of python packages that use C extensions and need to know which architecture they're running on in order to compile properly. 

I fixed this by setting `export ARCHFLAGS="-arch x86_64"` in my `zshenv` file:
https://github.com/jeffwidman/dotfiles/blob/eb5c8725a46229bf31510652602b37a95b0d0dbe/zsh/.zprofile#L6-L12

I was wondering whether we should pull this into prezto's OS X / macOS module as a default value unless the user overrides it?

It would have saved me an hour of debugging on at least two occasions (I didn't remember the root cause the second time). Downside is that anyone running OS X on 32 bit architectures will have to dig deep to figure out the problem, but the number of people running prezto + OS X on 32 bit is probably quite small.

Alternatively, perhaps there's another test we could do that guarantees we're on 64 bit architecture before setting that flag?

**Comment by diraol** [comment]
Can't you get the arch from `uname` command?

**Comment by jeffwidman** [comment]
On Mac that gives only the OS name, not the architecture:

    ~ ❯❯❯ uname
    Darwin

**Comment by diraol** [comment]
@jeffwidman try `uname -m` =)

**Comment by jeffwidman** [comment]
FWIW, I ended up running into issues with hardcoding the value and had to pull it out. Details in https://github.com/jeffwidman/dotfiles/commit/ad9dd97ba718396342a4e04f71e6dd03a9b41360

So even `uname -m` isn't deterministic enough for the purposes of setting `ARCHFLAGS`...
