### ISSUE TITLE
Aliases should expand to their full commands

### ISSUE THREAD

**Issue by AndrewSB** [sorin-ionescu/prezto#1463]
##### Bug 

I wanted to be able to complete aliases to their full commands. i.e. if I have an alias which is `alias gco = git checkout`, 

```
> gco <TAB>
```

should be completed to

```
> git checkout
```

scmbreeze talks about how to enable it using oh_my_zsh, I wasn't sure how to enable the same behaviour in prezto https://github.com/scmbreeze/scm_breeze#zsh

### Expected behavior

```
> gco <TAB>
```

should be completed to

```
> git checkout
```

### Actual behavior

```
> gco <TAB>
```

becomes

```
> gco 
 -- external command --
gcomm  gcore  gcov 
 -- alias --
gco
```

### Versions

  - Prezto commit:3faaffe7e9de25d5c05b3b88c3d65d29b914139e
  - ZSH version: zsh 5.2 (x86_64-apple-darwin16.0)
  - OS information: macOS 10.12.6
  - zprezto modules: environment', terminal', 'editor', 'history', 'directory', 'completion','syntax-highlighting', 'autosuggestions
  - complete dotfiles: https://github.com/AndrewSB/dotfiles

**Comment by belak** [comment]
I believe this may have been fixed by https://github.com/sorin-ionescu/prezto/pull/1500

You can use Control-Space to expand aliases now if you have the editor module enabled.

**Comment by stereokai** [comment]
@belak As of Dec 2023, Control-Space is problematic when MacOS has more than one input language available, as it conflicts with the native keybinding. How can I simply enable `Tab` to expand aliases? Thanks
