### ISSUE TITLE
Readline eats typed text when typing `| ` in `$()`

### ISSUE THREAD

**Issue by seletskiy** [sorin-ionescu/prezto#1468]
### Description

When using prezto with latest zsh (5.4.2-1), readline eats user typed text `<text>` when user types `| ` (pipe and space) inside `$()` when editing buffer contains `$() <text>`.

### Expected behavior

Readline does not eat user typed text.

### Actual behavior

See description.

### Steps to Reproduce

0. create fie `~/.zshrc.prezto` with following configuration:
```zsh
zstyle ':prezto:load' pmodule 'editor'

source ~/.zsh/.zprezto/init.zsh
```

Make sure, that `~/.zpreztorc` is empty or doesn't exist.

1. git clone prezto;
2. start zsh as `zsh -df`;
3. type `$() xxx`, move cursor inside `$()`, type `| `, buffer will contain `$(| ) xxx`;
4. `source ~/.zshrc.prezto`
5.  type `$() xxx`, move cursor inside `$()`, type `| `, buffer will contain `$(|`;

It also reproduces when `:prezto:load` line in `~/.zshrc.prezto` is loading `history-substring-search` instead of `editor`.

### Versions

  - Prezto commit: `00f1d92`
  - ZSH version: `5.4.2`
  - OS information: `Linux archlinux 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux`

**Comment by kovetskiy** [comment]
ping @sorin-ionescu

**Comment by belak** [comment]
I'm also seeing this on macOS with zsh 5.4.1... this is really strange.

**Comment by belak** [comment]
It's related to the `magic-space` bind set in the editor module. It's intended to perform history expansion on space in certain situations.

I believe you can workaround it with this:

```
bindkey-all ' ' self-insert
```

Or, if you don't want to use bindkey-all you can use the following snippet:

```
bindkey -M emacs ' ' self-insert
bindkey -M viins ' ' self-insert
```

These reset space to only insert itself and not do the magical history expansion.

**Comment by seletskiy** [comment]
@belak: Magic :sparkles: is appropriate word for that bug.

Nice catch, your workaround works. How did you find it?

**Comment by belak** [comment]
I added a `return` to the start of the file and kept moving it lower until the bug started happening again... then I looked in that block of code for anything that messed with the space.

I'm glad the workaround works for you... I'm not sure if we'll end up removing that key bind because it was added by sorin ages ago, presumably for a reason, so I guess it counts as "expected" behavior.

**Comment by seletskiy** [comment]
@belak: It starts to happen only after recent zsh update (not sure which version), so probably it's some changes in zsh defaults.

**Comment by belak** [comment]
I didn't see anything in the recent zsh changelogs relating to history or magic-space, and I don't have many versions installed to test this with... if you manage to narrow down what might have caused this, feel free to let me know and I'll see if I can come up with a workaround.
