### ISSUE TITLE
Iterm2 prompt (default) not rendering text correctly ?

### ISSUE THREAD

**Issue by appsolutegeek** [sorin-ionescu/prezto#1469]
Hi,

I have recently installed Prezto and the prompt is being displayed as if its not using UTF-8 or similar

here is an example on my iterm2

`ian@CTEST  ~ `

I tried changing the font, but still displayed question marks instead of what it should be displaying the correct font icons/colors..

Anybody has been successful in setting up in iterm2?

**Comment by belak** [comment]
Please provide the version information requested in the issue template:

```
### Versions

  - Prezto commit:
  - ZSH version:
  - OS information:
```

I'm running macOS 10.12.6 with iTerm2 3.0.15 and it's rendering fine for me out of the box.

**Comment by appsolutegeek** [comment]
Hi @belak,

Sorry, yes here is some more information.

> ### Versions
> 
>   - Prezto commit: commit 00f1d92ed838fe7b75949c5eba19419728961b34
>                                Author: Damien Pollet <damien.pollet@gmail.com>
>                                Date:   Fri Sep 8 16:07:48 2017 +0200
> 
>                                Fix typo in zprezto-update function
>   - ZSH version: zsh 5.4.1 (x86_64-apple-darwin16.7.0)
>   - OS information:   ProductName:	Mac OS X
>                                   ProductVersion:	10.12.6
>                                   BuildVersion:	16G29

iterm version is ITerm2 Build 3.0.15

**Comment by appsolutegeek** [comment]
A little more information, I have using the following in my .zpreztorc file, the theme is powerline although the problem also appears on other themes that try and display the small icons.

> zstyle ':prezto:load' pmodule \
>   'environment' \
>   'terminal' \
>   'editor' \
>   'history' \
>   'directory' \
>   'spectrum' \
>   'utility' \
>   'completion' \
>   'git' \
>   'syntax-highlighting' \
>   'history-substring-search' \
>   'prompt'
> 
> zstyle ':prezto:module:prompt' theme 'powerline'

**Comment by belak** [comment]
Ah, I wasn't aware you were using the powerline theme.

Have you followed the instructions in https://powerline.readthedocs.io/en/latest/installation.html#fonts-installation to ensure you have a working font? I believe iTerm2 needs a patched font to work (they are available [here](https://github.com/powerline/fonts))

**Comment by appsolutegeek** [comment]
Thanks! Yes that was it, it was a font issue. It was weird why it worked in my IDE. Anyway, all fixed now. Thanks for the help.
