### ISSUE TITLE
printing string without newline

### ISSUE THREAD

**Issue by hpcsc** [sorin-ionescu/prezto#1473]
### Description
prezto doesn't print out string without newline character, even with `setopt no_prompt_cr` on
In bash or in zsh without prezto installed, when I type `echo -n "some message"`, I'll see the message printed out on the same line with next prompt like this:

<img width="341" alt="screen shot 2017-09-22 at 3 51 13 pm" src="https://user-images.githubusercontent.com/5293047/30734517-10f4035c-9fae-11e7-89bd-37c04bafe97e.png">

### Expected behavior

I expect zsh to behave the same, at least when `setopt no_prompt_cr` is on

### Actual behavior

It doesn't print out anything:

<img width="391" alt="screen shot 2017-09-22 at 3 53 37 pm" src="https://user-images.githubusercontent.com/5293047/30734550-39f02cae-9fae-11e7-9587-d0a66784830f.png">

### Steps to Reproduce

1. execute `echo -n "some message"`

### Versions

  - Prezto commit: 4f19700
  - ZSH version: zsh 5.4.1 (x86_64-apple-darwin16.7.0)
  - OS information: MacOS Sierra

**Comment by hpcsc** [comment]
sorry, seem like it's already fixed in latest version
I updated to latest prezto and it's working now

**Comment by belak** [comment]
Not a problem! I honestly feel like this is a regression in zsh, but we worked around it here. :) Glad you figured it out.

**Comment by ysoftman** [comment]
I had the same problem, and i resolved it.
Thank you~ 😄
