### ISSUE TITLE
Completion via TAB broken - how to examine best?

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#1474]
(Already have searched but couldnt find any hints to the following problem:)

### Description
Completion via TAB seems not to work and I wonder how to examine this best. No idea why it suddenly stopped working.

### Expected behavior
In my directory, I have another sub-directory called something like "node_modules". When I type `cd` with some initial letters like

$ cd node_

and hit `TAB` (tabulator), I expect it to autocomplete to 

$ cd node_modules

but it doesn't

### Actual behavior
As mentioned above, nothing happens and it's just `cd node_` in red.

### Steps to Reproduce
Maybe my .zpreztorc file can indicate the problem or make it reproducible? Not sure. But have a look here
https://gist.github.com/binarykitchen/e877a02e0dee57265fc81f9758f5c10d

### Versions

Have git pulled latest version from master

  - Prezto commit:

```
commit d3a768b3ba29257613e0cc2ef61689ed549e43a7 (HEAD -> master, origin/master, origin/HEAD)
Author: Paul Melnikow <email@paulmelnikow.com>
Date:   Tue Apr 4 11:10:08 2017 -0400

    Add deprecation notice
```

  - ZSH version:

```
└─❱❱❱ zsh --version                                                                                                                                                    130 ⏎  +5085 13:28 ❰─┘
zsh 5.4.2 (x86_64-apple-darwin16.7.0)
```

  - OS information:

macOS Sierra 10.12.6

**Comment by belak** [comment]
It looks like you're pointing at the old deprecated fork: https://github.com/prezto-inactive-community-fork/prezto (originally at zsh-users/prezto which is probably where you cloned from).

A while back there was some work done to fork prezto and work on it separately, but sorin came back and added some maintainers so that repo was shut down.

**Comment by binarykitchen** [comment]
Me pointing to the old fork? Can't be. Have this line in the git config 

```
remote.origin.url=https://github.com/zsh-users/prezto.git
```

the latest git commit message i can see is

``
commit d3a768b3ba29257613e0cc2ef61689ed549e43a7 (HEAD -> master, origin/master, origin/HEAD)
Author: Paul Melnikow <email@paulmelnikow.com>
Date:   Tue Apr 4 11:10:08 2017 -0400

    Add deprecation notice
```

any clues? suggestions what to do?

**Comment by belak** [comment]
Yes, that is the old fork. If you visit that page in a browser, it redirects you to the inactive fork.

I would recommend re-cloning prezto from `https://github.com/sorin-ionescu/prezto.git`. The latest commit on this repo is https://github.com/sorin-ionescu/prezto/commit/25d8db301d5939040ff4aa6e7211d27e74f2d0d9

I've also worked with the people who own the deprecated repo to add a notice about the location change for anyone who pulls (it was just merged earlier today).

**Comment by binarykitchen** [comment]
well, i am not keen to do a `rm -rf .zprezto` and to `git clone ...` otherwise i am loosing some changes i made in few modules ...

**Comment by belak** [comment]
I don't remember where they diverged (I'm guessing https://github.com/sorin-ionescu/prezto/commit/4f19700919c8ebbaf75755fc0d03716d13183f49), but there's a chance you'd be able to checkout the last commit that appears in both repos, change the remote to point to the correct place, and then pull and update to the latest commit on master.

**Comment by binarykitchen** [comment]
that worked, thanks

**Comment by belak** [comment]
Glad to hear it! Sorry it took so long for me to realize what was going on.
