### ISSUE TITLE
Why the  ✘ 1 error mark?!

### ISSUE THREAD

**Issue by stvhwrd** [sorin-ionescu/prezto#1477]
I'm sorry that I have to create an issue for this, as it's probably just a quick fix.  I cannot for the life of me figure out why I'm getting this error mark:

<img width="762" alt="screen shot 2017-09-30 at 10 48 57 pm" src="https://user-images.githubusercontent.com/4117011/31052192-be68220a-a631-11e7-9e52-b5ad8f802457.png">

The red   ✘ 1  on the right side occasionally changes to     ✘ 127 or     ✘ 130  but it seems to appear every few commands.  It's driving me nuts because I just can't figure it out.  Any ideas?

**Comment by belak** [comment]
This is expected behavior. When a command returns a non-zero error code, the x will display along with the error code. There is a way to disable the number but not the x.

**Comment by stvhwrd** [comment]
Thanks for your time @belak, I'm just wondering specifically how to disable this or what this may indicate.  I've been using Prezto for a couple of years and this is the first I've seen of this.  Does it indicate a problem in my `.zshrc`?  As you can see in the screenshot above, I'm getting the error even on opening a new window.

**Comment by belak** [comment]
The previous symbol used for this was ⏎ and that's existed for quite some time. The symbol was changed to ✘ as it's a little clearer what it means.

The number itself can be disabled with `zstyle ':prezto:module:prompt' show-return-val false` but that won't hide the ✘.

**Comment by stvhwrd** [comment]
Thanks for the info!  Again, though - any idea why this would have suddenly started appearing for me?  As mentioned, I've been a Prezto user for a couple of years, and have not changed my config.

**Comment by belak** [comment]
Just for clarification, as far as I know, this isn't a problem. My prompt also displays an error for the first command.

**Comment by stvhwrd** [comment]
Puzzling... New machine with identical config, including font, terminal emulator, color scheme, etc.

Anyway, I appreciate your time and effort in looking into this - thanks!  I guess I'll just have to swallow this jagged ✘ 1 pill and move on with my life.

**Comment by crivotz** [comment]
In my case it appeared after the latest updates.

**Comment by belak** [comment]
The commit where this changed was 2cfd366ba6fafbbb47215a45bc9629f709376e94. The previous commit is 808d9d3579270898b17b7dbf9d1ec91145aefd03 if you want to see what it looked like before that.

However, there should have still been a red symbol before that change (it's existed for at least 6 years - see https://github.com/sorin-ionescu/prezto/blame/448cda2a57a1a234aed84cda0937b7283f3ae181/themes/sorin/prompt_sorin_setup#L30).

Before:

![screen shot 2017-10-02 at 11 09 09 am](https://user-images.githubusercontent.com/107097/31092143-51042006-a762-11e7-94ac-69f89f43753e.png)

After:

![screen shot 2017-10-02 at 11 08 52 am](https://user-images.githubusercontent.com/107097/31092160-5c4f5cbe-a762-11e7-8651-17f7d5be96f1.png)

**Comment by crivotz** [comment]
Yes, I remember the arrow. I understood the appearance of the ✘
Thansk for deep explanation

**Comment by belak** [comment]
As this is expected behavior, I'm going to close this. Hope the explanation helped!
