### ISSUE TITLE
Add support for loading plugins in other formats

### ISSUE THREAD

**Issue by belak** [sorin-ionescu/prezto#1484]
Depends on #1458, copied from https://github.com/sorin-ionescu/prezto/pull/1458#issuecomment-336082264

Most zsh plugins (see https://github.com/sindresorhus/pure for example) use <module>.plugin.zsh as the entry source file to be sourced instead of init.zsh. This way i can git submodule include zsh plugins.

So we could
```
if [[ -s "$ZPREZTODIR/modules/$pmodule/init.zsh" ]]; then
   source "$ZPREZTODIR/modules/$pmodule/init.zsh"
elif [[ -s "$ZPREZTODIR/modules/$pmodule/$pmodule.plugin.zsh" ]]; then
    source "$ZPREZTODIR/modules/$pmodule/$pmodule.plugin.zsh"
fi
```

Other known extensions used are 
```
.zsh-theme
.theme.zsh
.zshplugin
```

**Comment by Neal** [comment]
`$ZPREZTODIR/modules/$pmodule` should now be `$pmodule_location` instead after #1458.

**Comment by ajax77777** [comment]
im happy for you

**Comment by belak** [comment]
Note that I decided to not support .zsh-theme or .theme.zsh because these are very non-standard and have a fairly high likelyhood of causing strange behaviors when switching themes.
