### ISSUE TITLE
Autocomplete is not including tab completion of file paths for long options that are followed by =.

### ISSUE THREAD

**Issue by hardkrash** [sorin-ionescu/prezto#1492]
### Description
When performing tab completion of my programs when I have. a `--longopt=` tab completion will not work.  if I use `--longopt ` then tab completion works with file paths.

### Expected behavior

I expect that a `--longopt` would not care if the `=` is present or not for completing a path.

### Actual behavior

`--longopt=` does not work with tab completion of paths, but does with a space as opposed to a `=`

### Versions

  - Prezto commit: 25d8db301d5939040ff4aa6e7211d27e74f2d0d9
  - ZSH version: zsh 5.4.2 (x86_64-apple-darwin16.7.0)
  - OS information: Mac OS X 10.12.6

**Comment by belak** [comment]
Do you have a specific example? I'm pretty sure this is an upstream issue with whichever completion script you're using.

**Comment by belak** [comment]
There hasn't been a follow up on this in a few months, so I'm closing this for now. Please feel free to comment with more information if you'd like us to follow up. Thanks!
