### ISSUE TITLE
Themes (e.g. powerline) cause graphical glitches (e.g. "[?]"-like characters)

### ISSUE THREAD

**Issue by kylemart** [sorin-ionescu/prezto#1495]
### Description

Although I think the screenshot (provided below) speaks for itself, using themes such as paradox or powerline causes weird "[?]"-like characters to appear. It would seem things aren't being decoded properly on my machine?

### Steps to Reproduce

1. `brew install zsh zsh-completions`
2. `git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"`
3. Ran the following script: 
```
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
```
4. `chsh -s /bin/zsh`
5. Updated the .zpreztorc. (I've only showed the changed parts below; everything else is default.):

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'git' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt'

zstyle ':prezto:module:prompt' theme 'powerline'
```

### Screenshot

https://image.ibb.co/gCaNy6/Screen_Shot_2017_10_24_at_3_10_31_PM.png

### Versions

  - Prezto commit: 109864429cea5763e57c77f060835bfcdbefb09f
  - ZSH version: zsh 5.4.2 (x86_64-apple-darwin17.0.0)
  - OS information: 10.13

**Comment by belak** [comment]
This is almost definitely not an issue with prezto. Powerline requires special fonts to be installed.

There's info on font installation here: https://powerline.readthedocs.io/en/latest/installation.html#fonts-installation

This has some info on the different font features supported by terminal emulators: http://powerline.readthedocs.io/en/master/usage.html#terminal-emulator-requirements

**Comment by belak** [comment]
I've also added some basic troubleshooting information to the prompt module in cbcbedd6 so we hopefully don't run into this again.

Thanks for reporting!
