### ISSUE TITLE
Cursor disappears with syntax-highlighting plugin in the embedded terminal of Jetbrain IDEs

### ISSUE THREAD

**Issue by wiesson** [sorin-ionescu/prezto#1497]
### Description
A Jetbrains IDE offers an embedded terminal which I use quite often. If I enable `syntax-highlighting` and use the arrow keys to navigate, the cursor disappears and will only be visible when it blinks/flashes. 

I don't know if this is an error of prezto (because it does work perfectly without the embedded terminal) or from Jetbrains - I guess Jetbrains. 
I'm trying to find help to isolate the problem to raise an issue within the Jetbrains Bugtracker.

![little gif](https://i.stack.imgur.com/pA25O.gif)

### Steps to Reproduce

1. Enable the syntax-highlighting plugin
2. Start a Jetbrains IDE and open the embedded Terminal
3. Use arrow keys to navigate

### Versions

  - Prezto commit: latest
  - ZSH version:  5.3 (x86_64-apple-darwin17.0)
  - OS information: OSX 10.13

I also asked on [Stackoverflow](https://stackoverflow.com/q/46642594/2050629) but anybody has replied yet.

**Comment by wiesson** [comment]
I did not make any heavy modifications. I enabled a few modules like git and syntax-highlighting:

from `.zpreztorc`
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'git' \
  'syntax-highlighting' \ <--
  'prompt'
```

and within the # Syntax Highlighting config area: 
```
zstyle ':prezto:module:syntax-highlighting' highlighters \
   'main' \
   'brackets' \
   'pattern' \
   'line' \
   'cursor' \
   'root'
```

That's it..

**Comment by belak** [comment]
Do you still see this issue if you disable the cursor highlighter? By default only the main highlighter is active... and I've seen a number of issues filed against the syntax highlighting module which seem similar to what you're seeing.

If you remove the `'cursor' \` line from the syntax highlighting config in your zpreztorc, this will disable the cursor highlighter and may fix this issue.

https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md

https://github.com/zsh-users/zsh-syntax-highlighting/issues/171

**Comment by wiesson** [comment]
Yes, that did work! :)

For others, my enabled highlighters:

```
zstyle ':prezto:module:syntax-highlighting' highlighters \
   'main' \
   'brackets' \
   'pattern' \
   'line' \
   'root'
```

**Comment by fuatto** [comment]
the same for me but in 'vi' editor - command mode, the cursor disappears, and removing the `'cursor' \` line in highlighters works great!

**Comment by liberninja** [comment]
I had the same issue and wasn't able to resolve it by taking out the cursor syntax highlighting option.
I was only able to get my cursor back after I disabled `zstyle ':prezto:*:*' case-sensitive 'yes'`

I'd prefer to have colors, but it's better than nothing. Not sure what that happens. I'm using xfce terminal btw.
