### ISSUE TITLE
Unable to init prezto with `ksharrays` option

### ISSUE THREAD

**Issue by AntonGitName** [sorin-ionescu/prezto#1499]
Feature suggestion/cry for help

### Description

I have to deal with some legacy scripts that have lines:
```
if [ -n "${ZSH_VERSION:-}" ] ; then
  # make zsh split on whitespace like everybody else does
  set -o shwordsplit
  # index arrays from 0 like bash does
  set -o ksharrays
fi
```
Option `ksharrays` messes up prezto (doesn't matter if you set it before or after sourcing ".zprofile").

Unfortunately, it is not a solution to guard those scripts with `set -o` and `set +o` because they export a lot of functions that all assume ksh-like arrays. 

Maybe someone could give me a hint what could I do about it?

### Expected behavior

That would be nice if prezto would have been independent of arrays numeration scheme.

### Actual behavior

If you try to start zsh with ksh-like arrays numeration, prezto fails to run its init scripts.

### Steps to Reproduce

1a. Add at the end of `.zshenv` a line with `set -o ksharrays`
2a. Suffer

1b. Add at the beginning of `.zshenv` a line with `set -o ksharrays`
2b. Suffer in Bash

### Versions

  - Prezto commit:
eb47b45a0d4a36545a2ed6cfb991d776cdcb0684
  - ZSH version:
zsh 5.3.1 (x86_64-debian-linux-gnu)
  - OS information:
Debian, 4.9.0-4-amd64

**Comment by belak** [comment]
The `ksharrays` option is pretty terrible for compatibility because it changes how arrays are numbered - there's almost no way to work around this globally.

The best way would be to use localoptions and ksharrays in all functions which need this functionality. Unfortunately, that probably isn't an easy fix, but as far as I know it's the only consistent one.

**Comment by belak** [comment]
Unfortunately, I don't think there's a great workaround aside from updating those legacy scripts. This isn't something it makes a lot of sense for prezto to support. If you still have any questions about workarounds I'd be happy to answer them, but I'm closing this issue for now.

**Comment by hlecuanda** [comment]
You could alias a function that wraps around the offending scripts when you need to run them, using alternative runcoms on vanilla zsh and then forks into a subshell while your ksh scripts are executing. I'm assuming you're using the scripts interactively, right? This way your environment and settings stay on saneland while the subshell interprets the scripts from kshizarro world...
