### ISSUE TITLE
Prepend `sudo` command doesn't appear to work

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1501]
I stumbled across [this line in `init.zsh`](https://github.com/sorin-ionescu/prezto/blame/752f64f0852d369ab0970301fa55a565805df21e/modules/editor/init.zsh#L369-L370):

    bindkey -M "$keymap" "$key_info[Control]X$key_info[Control]S" prepend-sudo

As best I read this, I can type <kbd>Control</kbd>+ <kbd>S</kbd> (or whatever is mapped to <kbd>Control</kbd>) and it prepends `sudo` to the beginning of the line.

However, when I try this in the `sorin` prompt, all I get is:

    ~ ❯❯❯ ls ^S

Is this a prezto bug, my misconfiguration, or am I simply misunderstanding something?

**Comment by belak** [comment]
`C-x C-s` Wonderful emacs style key binds. Definitely not the clearest though.
