### ISSUE TITLE
Support for spaceship-zsh-theme

### ISSUE THREAD

**Issue by lokesh-krishna** [sorin-ionescu/prezto#1504]
### Description
Could you please consider adding [Spaceship ZSH](https://github.com/denysdovhan/spaceship-zsh-theme) as a prompt theme?

**Comment by lokesh-krishna** [comment]
That looks really interesting for the future of Prezto. However, the oh-my-zsh dependency you're talking about has already been [dropped](https://github.com/denysdovhan/spaceship-zsh-theme/pull/147) or am I missing something?

**Comment by belak** [comment]
It was merged in the 3.0 branch but it doesn't look like there's been a release for it yet.

**Comment by belak** [comment]
I tried it out and submitted a few PRs: 

https://github.com/denysdovhan/spaceship-zsh-theme/pull/274

https://github.com/denysdovhan/spaceship-zsh-theme/pull/275

Once at least the second one is in, I'll look at adding it to the contrib repo.

**Comment by belak** [comment]
3.0 was recently released and so it's been added to the prezto-contrib repo. Thanks for suggesting this theme!
