### ISSUE TITLE
Error immediately after installation: async_job:zpty:12: no such pty command: async_sorin_git

### ISSUE THREAD

**Issue by davidmrdavid** [sorin-ionescu/prezto#1509]
### Description
I get an error immediately after installation

### Expected behavior
I expect no such error

### Actual behavior
When starting my terminal (iterm2) I receive the following error
async_job:zpty:12: no such pty command: async_sorin_git

That error shows up again after any given command is executed

### Steps to Reproduce

1. Install prezto as noted here: https://codurance.com/2015/03/16/installing-zprezto-a-quick-guide/
2. that's it!

### Versions

  - Prezto commit: latest
  - ZSH version: zsh 5.4.2 (x86_64-apple-darwin16.7.0)
  - OS information: MacOSX Sierra 10.12.4 (16E195)

**Comment by davidmrdavid** [comment]
By looking at the commit history, it seems that a commit was just made that dealt with async_sorin_git. Maybe that has to do with it

**Comment by belak** [comment]
Thanks for mentioning this. I wasn't paying attention and updated the sorin prompt with another one active... so I thought it was working but it was really broken.

Anyway, it should be fixed now. Sorry for the inconvenience.
