### ISSUE TITLE
completion on file path in general

### ISSUE THREAD

**Issue by liujoey** [sorin-ionescu/prezto#1511]
In PR #1307, it introduced pip auto-completion, when I run command:
`pip install -r requirements.txt` and tried to complete on the file path `requirements.txt`, it doesn't work. This leads to my question, for certain commands like `pip`, should we add file path completion at the end of the completion function?

### Expected behavior

type command `pip install -r req<TAB>` should complete the file path `requirements.txt` which is a file in my current working folder.

### Actual behavior

type `TAB` key doesn't complete the file name.

### Steps to Reproduce

1. cd to a folder which has a file e.g. "requirements.txt"
2. type `pip install -r req<TAB>`
3. see if it expands

### Versions

  - Prezto commit: 221c6cd
  - ZSH version: zsh 5.2 (x86_64-apple-darwin15.0.0)
  - OS information: MacOS High Sierra version 10.13.1 (17B48)

**Comment by liujoey** [comment]
This is not limited to `pip`. For any command if the auto-completion stop working on local file path expanding, it feels like the system is broken.

I just found one example for zsh pip completion, [dgladkov/zsh-pip-completion](https://github.com/dgladkov/zsh-pip-completion), it has files section at the end of the function.

**Comment by liujoey** [comment]
found an unmerged PR from pip upstream, https://github.com/pypa/pip/pull/4842
this issue should be closed.

**Comment by belak** [comment]
Thanks for following up on this. It may be possible to add this to the zsh-completions repo as well if we want them updated more frequently.
