### ISSUE TITLE
Already using prezto but still seeing the project deprecated warning 

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#1516]
When running latest `zsh` command manually, I see this warning

```
└─( 4 ) ❱❱❱ zsh
The community fork is being shut down because of new activity in the main repo.
It is recommended that you switch back to the main repo:

https://github.com/sorin-ionescu/prezto/

If you would like to continue using this fork (no new updates will be pushed)
copy and paste the following into your zpreztorc to disable this message:

zstyle ':prezto:project-deprecated-warning' disable 'yes'
```

But hey, I am already using zprezto. Why am I seeing this? Can I somehow debug and see what bad configuration caused this to be thrown?

**Comment by belak** [comment]
A while back, there was a community fork which used to live at https://github.com/zsh-users/prezto.

Now that maintainers have been added to this repo, the other fork was deprecated. To continue getting updates, you can either switch your git remote to this repo or re-clone prezto.

**Comment by binarykitchen** [comment]
ah yeah, right on - make sense now. works!

**Comment by belak** [comment]
Thanks for mentioning it though! I believe this is the first mention of the deprecation warning, so it's nice to know it's working. :)
