### ISSUE TITLE
Using oh-my-zsh plugins in contrib folders?

### ISSUE THREAD

**Issue by mb-3000** [sorin-ionescu/prezto#1518]
Is it possible to use an oh-mh-zsh plugin (mvn one specifically) in the contrib folder and load it as a module?

Wasn't any docs about it but I know antigen can do this, wondered if was a trivial thing to do or anyone had experience or knew how to do it.

**Comment by belak** [comment]
This should be possible, but I haven't explicitly tested it.

For now, it's probably easiest to use a combination of antigen and prezto (similar to what I do in my dotfiles) if you want to load a mixture, but if you want to test out the prezto module loader, it should be as simple as adding an oh-my-zsh plugin as a folder in contrib and loading that module as normal.

**Comment by belak** [comment]
I'm still holding off on docs until we finalize how this is going to look, but I'm closing this because it should be possible. If you've got any specific questions, please feel free to ask them and I'll do my best to answer. :)

**Comment by mb-3000** [comment]
Thanks I'm going to give it a shot in the next day or two and I'll report back my findings.
