### ISSUE TITLE
Do not guess Python version

### ISSUE THREAD

**Issue by hotpxl** [sorin-ionescu/prezto#1519]
This commit e021adeb4a628387e853004427e3ea373207ee5a tries to guess system Python version for using virtualenvwrapper. It breaks stuff relying on default system python.

I do not think it's a good idea. Even though Python 2 is deprecating and people should use Python 3, Python 2 is still the default on many systems. And on many systems, (people like me) use the system Python to bootstrap virtualenv and start from there. So virtualenvwrapper script is often invoked with system Python.

From the comment, it fixes the issue that homebrew does not shadow system python, so some people may need to override that. But apart from that, I would suggest sticking to system `python` command and not guess version.

**Comment by belak** [comment]
I just pushed a commit which should only fall back to homebrewed python if the brew command exists. This should prevent it from being set when it doesn't need to be but still fix the issue that commit was introduced for in the first place.

Please let me know if you have any other issues with this and I'll do what I can.

**Comment by jeffwidman** [comment]
Nice fix @belak, that's a good way to solve this problem

**Comment by hotpxl** [comment]
Cool. That solves my problem.

I have a secondary computer using homebrew. But on that machine I still use the system python to bootstrap everything else. But anyways I worked around by adding a `zstyle` line in `zpreztorc` file.

**Comment by belak** [comment]
Sorry for the disruption, but I've slightly changed how this works (We should really look at adding a `stable` branch soon).

Now, you can just use the environment variable provided by virtualenvwrapper to override this setting. If you set `VIRTUALENVWRAPPER_PYTHON` in your zshenv (or perhaps even zpreztorc, though I haven't tested that) we won't override it.
