### ISSUE TITLE
`VIRTUALENVWRAPPER_PYTHON` in `.zshenv` is being overridden

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1520]
I just updated prezto from last week. 

Now I suddenly find that `VIRTUALENVWRAPPER_PYTHON` in `.zshenv` is being overridden by prezto due to @belak 's changes in https://github.com/sorin-ionescu/prezto/commit/e021adeb4a628387e853004427e3ea373207ee5a and https://github.com/sorin-ionescu/prezto/commit/d8d6b4d70a09cb78eab6f524e1e448a2a84cc155.

I set the value for `VIRTUALENVWRAPPER_PYTHON` here: https://github.com/jeffwidman/dotfiles/blob/00a93ab62c1642eafddc81784bcb5d11fdd57c78/zsh/.zshenv#L34

On my work laptop, I set this as `/usr/local/bin/python2` so that any new virtualenv's default to python2 without my needing to specify it every time.  However, when I check the value, it's reported as `/usr/local/bin/python3`:

    ~ ❯❯❯ echo $VIRTUALENVWRAPPER_PYTHON                                                                                                                                            
    /usr/local/bin/python3

I don't know whether to classify this as a bug (in which case prezto should check `.zshenv`) or user error (I should somehow specify the value in `.zpreztorc` rather than `.zshenv`).

Related: #1519

**Comment by jeffwidman** [comment]
I suppose I could accomplish this by installing virtualenv/virtualenvwrapper into python3, but then specify 
`VIRTUALENVWRAPPER_VIRTUALENV_ARGS = --python=python2`. It's slightly problematic because then it hardcodes the python, and occasionally I want to create venv's that have a python3 interpreter.

http://virtualenvwrapper.readthedocs.io/en/latest/install.html#default-arguments-for-virtualenv

**Comment by belak** [comment]
This can be overridden with `:prezto:module:python:virtualenvwrapper:python-path` but I'll push a fix which will only override this envar if it isn't already set.

**Comment by belak** [comment]
Thanks for reporting! This should be fixed now. Edge cases are the bane of my existence.

**Comment by belak** [comment]
I'm not sure if it would be better to remove the zstyle option and have people set that environment variable manually, or just leave it in at this point... >_<

**Comment by jeffwidman** [comment]
Personally, I would remove the zstyle override option. Makes great sense to have a sensible default and I appreciate you adding it. But I do think it's confusing to have an override for a third-party tool that already has a documented override available. This zstyle option for prezto hasn't been out more than a few days, so should be safe to remove it if we do it quickly.
