### ISSUE TITLE
scp can not completion ssh host?

### ISSUE THREAD

**Issue by fcying** [sorin-ionescu/prezto#1521]
### Description
scp can not completion ssh host  like ssh.

### Expected behavior
scp can  completion ssh host  like ssh.

ssh:
![ssh](https://user-images.githubusercontent.com/106934/34079759-dd9fdb16-e36e-11e7-94c4-a47928d6fcfd.png)
scp:
![scp](https://user-images.githubusercontent.com/106934/34079761-dfcbd69c-e36e-11e7-85ae-bd1d79649be0.png)

### Actual behavior
scp can not completion ssh host.

### Steps to Reproduce

1> scp ser
2> tab

### Versions

  - Prezto commit:66bfe9be27a1e63c
  - ZSH version:zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
  - OS information:ubuntu 16.04

**Comment by sbadia** [comment]
Hi!

Same issue here, with:
* Prezto : `66bfe9be27a1e63cd4bf8ae1e802b10a3068bd07`
* Zsh: `5.4.2-2`

**Comment by belak** [comment]
This should be fixed with the latest commit. We've been having a number of issues relating to a workaround function, so I've disabled it for now.

**Comment by sbadia** [comment]
Thanks @belak !

**Comment by belak** [comment]
Thanks for reporting! We've had issues with this function in the past, so disabling it was something I was already considering.
