### ISSUE TITLE
Intergrate z please, some users prefer z .

### ISSUE THREAD

**Issue by skywind3000** [sorin-ionescu/prezto#1530]
oh-my-zsh has that plugin:

https://github.com/rupa/z

**Comment by belak** [comment]
I'm not sure what our plans are in regards to external things like this, but I seem to remember sorin wanting to do the opposite - remove most external deps from prezto-core.

That being said, it's pretty easy to load it using a plugin manager. That's what I've been doing. https://github.com/belak/dotfiles/blob/master/zshrc#L40

**Comment by skywind3000** [comment]
I see, antigen can have a parameter for a non-zsh-plugin repository thanks a lot

**Comment by belak** [comment]
Thanks for the idea. As you saw, I prefer z to fasd as well. Unfortunately, I'm going to close this for now, as it's fairly easy to include in your own config and we're trying to move away from external modules like this.
