### ISSUE TITLE
Remove `pacaur` from `pacman` module docs

### ISSUE THREAD

**Issue by jeffwidman** [sorin-ionescu/prezto#1531]
`pacaur` is now unmaintained as detailed in https://github.com/sorin-ionescu/prezto/commit/7cdde9b631fffd25ed0c91aaaf5180b86d832038#commitcomment-26964204:
> [2017-12-15] This project is now unmaintained. Users are encouraged to move to another solution (see wiki for alternatives).

**Comment by belak** [comment]
Darn. This means I need to find an alternative for myself... I was happy with pacaur, but if it's unmaintained I suppose we shouldn't recommend using it.

**Comment by jeffwidman** [comment]
Thanks for cleaning this up @belak
