### ISSUE TITLE
up arrow completion does not work

### ISSUE THREAD

**Issue by dagnachewa** [sorin-ionescu/prezto#1532]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

  - Prezto commit:
  - ZSH version:
  - OS information:

**Comment by belak** [comment]
Thanks for submitting an issue. Unfortunately, as there's no information to reproduce, I have no way to know what to fix. Please fill out the issue template so we know how to trigger this bug.

**Comment by dagnachewa** [comment]
I had a couple commands issued like , git add submodule or cd some/directory etc
before, I could just type the first word exemple : git and up arrow , I would have choices of previous commands, not anymore.

**Comment by belak** [comment]
Do you have the `history` submodule enabled?

What commit were you on before?

What commit are you on now?

Did you change anything in your config?

**Comment by dagnachewa** [comment]
Thanks for the fast response. 
I am at my work I will verify.

**Comment by dagnachewa** [comment]
am sorry it was not enabled

**Comment by belak** [comment]
Glad that fixed it! :)
