### ISSUE TITLE
Autosuggestions history lost everytime when I relogin zsh

### ISSUE THREAD

**Issue by skywind3000** [sorin-ionescu/prezto#1538]
### Description
Autosuggestion module lost its history everytime when I relogin zsh.

### Expected behavior

Autosuggestion is supposed to give me hint from command history not only in current login session, but also previous login session.

### Actual behavior

Autosuggestion module can only remember the history from current login session.

### Steps to Reproduce

1. login in zsh
2. type: "echo 1 2 3" press enter.
3. type: "echo", can I can see following suggestion "1 2 3" is displayed after cursor.
4. logout zsh
5. login zsh again
6. type: "echo", you can see no suggestions at all.

My zshrc:

https://github.com/skywind3000/vim/blob/94d062ded205ce01fef3431959a4d1912b6abe02/etc/prezto.zsh#L72

### Versions

  - Prezto commit: 282b478 (latest on 2018/2/1).
  - ZSH version: 5.3
  - OS information: debian 9 x64

**Comment by belak** [comment]
It looks like you don't have the history module enabled. That's needed to track history between sessions. If you're still having trouble after enabling that module, please feel free to comment and we can continue debugging.

**Comment by skywind3000** [comment]
It really works !!

**Comment by belak** [comment]
I've just pushed d7622624aaddab6ee34c66efba4f83860a6fa622 which adds some information about troubleshooting this issue. Glad that fixed it!
