### ISSUE TITLE
It seems that .zcompcache does not work

### ISSUE THREAD

**Issue by danilcha** [sorin-ionescu/prezto#1543]
I have `completion` module enabled, and it creates `.zcompdump` file. However, directly (file?) `.zcompcache` is not created. 

I'm trying to get the completion for `brew` for instance. It shows up after a second delay each time, no caching.

**Comment by hlecuanda** [comment]
HI! I remember having this issue a while ago. It had something to do with _where_ was the function `zrecompile` being called or whether it was being called at all 

if you have your _dotfiles_ in a repo, around here, just make sure it's synced with your local version and let me kow, i can look into it.

Also the output from [reporter](https://gist.github.com/hlecuanda/e49f5a55752ed87e06c567e1f6b4ee72) could be of help =)

**Comment by belak** [comment]
Thanks for reporting this. Unfortunately, I think this is an issue with homebrew and not prezto.

It looks like the `_brew` completion included with homebrew doesn't actually call any of the _store_cache, _retrieve_cache, or _cache_invalid functions (those are the functions which actually use the cache file you mentioned) so it makes sense that it wouldn't be created.

If you'd like improved zsh completions for homebrew, your best bet would be to file a bug against homebrew as we don't actually include any homebrew completion files with prezto.
