### ISSUE TITLE
Allow custom completion cache path

### ISSUE THREAD

**Issue by qrevel** [sorin-ionescu/prezto#1553]
### Description
In the [completion module](https://github.com/sorin-ionescu/prezto/blob/master/modules/completion/init.zsh#L49), allow the configuration of the cache path

### Expected behavior

`zstyle ':prezto:module:completion' cache-path 'your_path'`

**Comment by indrajitr** [comment]
`zstyle` configs are dynamic. So you can always overwrite it in your local `~/.zpreztorc` as so:

```shell
zstyle ':completion::complete:*' cache-path "${ZDOTDIR:-$HOME}/.my_zcompcache"
```

or for more specific command, say `foo`, as so:
```shell
zstyle ':completion::complete:foo:*' cache-path "${ZDOTDIR:-$HOME}/.zcompcache_foo" 
```

Hope this helps. Please feel free to re-open if this doesn't work for you.
