### ISSUE TITLE
prompt-pwd problem

### ISSUE THREAD

**Issue by astanciu** [sorin-ionescu/prezto#1559]
Seems like the function declaration here:
https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt-pwd#L8

should not be commented out. As is, I get this error on a fresh installation:
```sh
~ ❯❯❯ cd .zprezto
prompt_sorin_precmd:5: prompt-pwd: function definition file not found
```

after removing the comments, it works fine.

**Comment by belak** [comment]
These functions should be autoloaded and shouldn't need an explicit declaration. The comment is just to make grepping for it easier (otherwise it would be much harder to find where functions are declared in prezto).

Are your dotfiles posted anywhere so I can try to reproduce this?

**Comment by astanciu** [comment]
sorry, something hadn't loaded right, it's okay now

**Comment by belak** [comment]
Glad you got it figured out! Thanks for following up. 😄
