### ISSUE TITLE
Prompt fails to load in Termux

### ISSUE THREAD

**Issue by easyaspi314** [sorin-ionescu/prezto#1560]
### Description

Note: I am just making this bug to close it with my PR.

I am surprised this hasn't been reported before.

On the Android terminal emulator Termux, the default configuration breaks the shell prompt completely.

### Expected behavior

You see the pretty prompt on login like you do on desktop.

### Actual behavior

Instead of showing the prompt, zsh shows an error message and leaves the user with a fallback dollar prompt.

```
$ zsh --login
pmodload: no such module: prompt
$ # useless white dollar prompt
```

### Steps to Reproduce

1. Install Termux
2. `pkg install zsh`
3. Install prezto the normal way
4. `zsh --login` or `chsh -s zsh` and open a new window

### Versions

  - Prezto commit: 
    b3c27bb, but has existed for as long as I remember
  - ZSH version: 
    zsh 5.4.2 (arm-unknown-linux-androideabi)
  - OS information: 
    LG G3 d851
    Qualcomm Snapdragon 801 (armv7, 32-bit)
    Android 7.1.2 via Resurrection Remix 5.8.5
    Termux 0.60

**Comment by uudashr** [comment]
Any update on this issue?

**Comment by illtown** [comment]
Looks like some env or path issue, as prezto works fine under termux-chroot mode.
I haven't figured out the exact dependency yet.

**Comment by shubhsboson** [comment]
Termux has a styling addon , so probably that might have something to do with 'prompt not found'

**Comment by msdos** [comment]
Any news on this?

**Comment by belak** [comment]
I have no way of diagnosing this because I don't have a good way to run termux. PRs or any background information would be welcome.

**Comment by msdos** [comment]
Indeed is a really specific scenario.

What I know is that Termux project created a Docker image in https://github.com/termux/termux-docker. I've used in the past to test their package manager... Maybe it could be used to at least simulate this problem?

**Comment by easyaspi314** [comment]
I'm sorry, I was sleeping on the job. 🤦‍♂️

It still isn't working.

**Comment by easyaspi314** [comment]
I found the issue, and it appears to be a zsh issue. I will try to sort it out there.

**Comment by msdos** [comment]
@easyaspi314 can you give us more information about the issue being in zsh itself, or maybe a workaround?

**Comment by hut8** [comment]
Should this really be marked as completed? It seems impossible to run prezto on termux and I'm getting the same error as in #1561 which appears to have been closed without merging. The error I get is:

```
pmodload: no such module: history-substring-search
pmodload: no such module: prompt                           pmodload: no such module: git
pmodload: no such module: ruby
```

**Comment by anosnowhong** [comment]
For those who met the issue prompt or history-substring-search no such module, you can simply change the module load order in .zpreztorc, let **completion** be the last one should fix this issue.

**Comment by t3mb17z** [comment]
> For those who met the issue prompt or history-substring-search no such module, you can simply change the module load order in .zpreztorc, let completion be the last one should fix this issue.

Man, this fixed my problem too. Thanks @anosnowhong
