### ISSUE TITLE
apt completion is incomplete

### ISSUE THREAD

**Issue by fcying** [sorin-ionescu/prezto#1563]
### Description

apt completion is incomplete

### Expected behavior
apt completion is complete

`apt <tab>` have full completion.

in `bash`, `apt <tab>`
```
$ apt
autoclean     build-dep     clean         dist-upgrade  edit-sources  help          list          policy        rdepends      search        showsrc       update
autoremove    changelog     depends       download      full-upgrade  install       moo           purge         remove        show          source        upgrade
```
in `zsh`, `apt <tab>`
```
$ apt 
 -- action --
edit-sources  full-upgrade  install       list          remove        search        show          update        upgrade
```

if I use `apt-get`, it have same completion  in `bash` and `zsh`
in `bash`, `apt-get <tab>`
```
$ apt-get
autoclean        build-dep        check            dist-upgrade     dselect-upgrade  purge            source           upgrade
autoremove       changelog        clean            download         install          remove           update
```

in `zsh`, `apt-get <tab>`
```
$ apt-get  
 -- action --
autoclean        build-dep        check            dist-upgrade     help             markauto         remove           unmarkauto       upgrade
autoremove       changelog        clean            dselect-upgrade  install          purge            source           update
```

### Steps to Reproduce

1. `apt <space> <tab>`

### Versions

  - Prezto commit:  b3c27bb16460c677eabbe3d8e210f79fb5e8189b
  - ZSH version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
  - OS information: ubuntu 16.04

**Comment by belak** [comment]
Thanks for filing this. Unfortunately, this is an upstream issue. We don't provide any completion for `_apt` or `_apt-get`, so any existing completion must be provided by an OS package. 

Your best bet would be to file something upstream with debian or https://github.com/zsh-users/zsh-completions.
