### ISSUE TITLE
Known zsh issue impacting Ubuntu 17

### ISSUE THREAD

**Issue by binary132** [sorin-ionescu/prezto#1567]
### Description
Ubuntu 17 ships with an old version of zsh: https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/1734223 

Please leave this issue open to track the behavior since Ubuntu users might come looking.  It took me quite some time to identify the behavior.

Note that this is an unresolved issue because Ubuntu's zsh is a fork of Debian's and needs a patch.

### Expected behavior

Prompt rendering is correct.

### Actual behavior

Some prompts don't work correctly: https://github.com/sorin-ionescu/prezto/issues/1051

### Steps to Reproduce

1. Use Ubuntu 17.  It ships with zsh 5.2 until the bug is resolved.

### Versions

  - Prezto commit: latest
  - ZSH version: 5.2
  - OS information: Ubuntu 17.10 x64

**Comment by belak** [comment]
Both Ubuntu 17.04 and 17.10 have been EOLd so I'm closing this for now. Thanks for filing an update on this.
