### ISSUE TITLE
Issues with async after following prezto install instruction

### ISSUE THREAD

**Issue by richdel** [sorin-ionescu/prezto#1568]
I'm on OS X High Sierra with a homebrew install of zsh and when following the prezto install instructions everything goes fine until step 5 then I'm presented with the following:

---

async:1: no such file or directory: ../external/async/async.zsh
prompt_sorin_async_tasks:4: command not found: async_start_worker
prompt_sorin_async_tasks:5: command not found: async_register_callback
prompt_sorin_async_tasks:10: command not found: async_flush_jobs
prompt_sorin_async_tasks:13: command not found: async_job
~ ❯❯❯

---

And after every command:

---

prompt_sorin_async_tasks:10: command not found: async_flush_jobs
prompt_sorin_async_tasks:13: command not found: async_job
~ ❯❯❯

---

zsh version is  5.5 (x86_64-apple-darwin17.3.0)

zprezto cloned from master branch

---

fpath contains the following:

/Users/richard/.zprezto/modules/prompt/functions
/Users/richard/.zprezto/modules/completion/external/src
/Users/richard/.zprezto/modules/helper/functions
/Users/richard/.zprezto/modules/utility/functions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.3/functions

----

I'm new to zsh and zprezto so the above is all a little alien at the moment, will continue to research but any help is appreciated in the meantime.

**Comment by richdel** [comment]
On further inspection it seems that when I cloned the repo on OS X the async symlink wasn't preserved but instead just a file with a reference to the relative path, e.g. 

.zprezto/modules/prompt/functions/async should be a symlink to ../external/async/async.zsh

But instead it's just a file with the contents '../external/async/async.zsh' which is no good and obviously why the errors in the above message are appearing. It was only by looking at the file in the repo on github, https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt/functions, I discovered this is a symlinks, so a quick `cat async | pbcopy` to get the path to setup the symlink properly, `ln -s ../external/async/async.zsh async` resolves all the issues, but... then I discovered there are more files which are intended to be symlinks so actually it turns out that the issues are nothing to do with zprezto whatsoever but in fact the default (?) git core config which requires `core.symlinks` to be `true`.

So perhaps a note in the readme install instructions to make sure OS X users are aware that git needs to honour/preserve symlinks. The steps to resolve the above are simply:

1. run in shell `cd ~/ && rm -rf .zcompdump* .zhistory .zlog* .zprezto .zpreztorc .zprofile .zshenv .zshrc`
2. run in shell `git config --global core.symlinks true`
3. reinstall zprezto as per installation instructions
4. `hey prezto`

**Comment by yfang00** [comment]
If you are on Windows using Cygwin, please make sure that you use Cygwin Git, not Windows Git. Otherwise, 'git config --global core.symlinks true' would not be taken into account by Windows Git.

**Comment by belak** [comment]
According to the git-config man page, it looks like `core.symlinks` should be enabled by default (https://git-scm.com/docs/git-config#git-config-coresymlinks). If many other people run into this I'd be happy to add something to the README, but as it's a non-default setting I'm going to leave it for now. 

Thanks for mentioning it though, I didn't know that setting would cause an issue (though it makes sense).

**Comment by seriousm4x** [comment]
also just ran into this issue. unfortunately @richdel 's fix doesnt work for me.
deleted all files, set core.symlinks true and cloned again. still the same errors.
any update on this?

**Comment by ase1590** [comment]
you may need to pull in git submodules. 
Try: `git submodule update --init --recursive`
