### ISSUE TITLE
ssh hosts suggestions doesn't work for Manjaro latest update

### ISSUE THREAD

**Issue by IevgenSobko** [sorin-ionescu/prezto#1571]
### Description
ssh hosts suggestions doesn't work for Manjaro latest update.
Reverting zsh package to zsh-5.4.2-2-x86_64.pkg.tar.xz fixes this problem. I also have Antergos(also Arch derivative) system and this system also have the same issue with 5.5 version of zsh.
```
ssh _alternative:69: command not found: _ssh_hosts
_alternative:69: command not found: _ssh_hosts
_alternative:69: command not found: _ssh_hosts
```
![screenshot_20180416_123647](https://user-images.githubusercontent.com/14232100/38801785-7f0a244a-4173-11e8-8508-8106f5ec9dc3.png)

### Expected behavior

No errors and suggested hosts appear.

### Actual behavior

Some errors printed and no suggested hosts.
### Steps to Reproduce

1. Type ssh and press Tab Tab for host suggestion

### Versions

  - Prezto commit: 300102897a4710e1559e4435c686f794d126d3c3
  - ZSH version: 5.5
  - OS information: 
System:    Host: DzirT-LT Kernel: 4.9.94-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.12.4 
           Distro: Manjaro Linux 17.1.8 Hakoila

**Comment by belak** [comment]
Thanks for filing this! Unfortunately it looks like it is almost definitely a Manjaro issue and not a prezto issue. It looks like even the completions we do bundle don't include one for the ssh command, so that's provided by your OS.

**Comment by IevgenSobko** [comment]
@belak thx for clarification. But as I stated above this issue reproducible for all Arch derivatives. It is not just Manjaro
And what package/command provides autocompletion so I will try search/install it?

**Comment by gregseb** [comment]
I have been having this issue on a fresh archlinux installation as well.  I can verify that if I configure zsh normally without prezto, ssh completion works fine.  I don't know if I believe this is a 100% upstream issue.

**Comment by belak** [comment]
I haven't been able to reproduce this on a fresh install. Maybe it's related to the completion cache? You can test this by removing ~/.zcompdump and opening a new shell.

**Comment by gregseb** [comment]
That makes perfect sense!  And..... look at that, it worked. Thanks @belak!

**Comment by belak** [comment]
@tsabirgaliev @sklirg Are you still seeing this issue after clearing the completion cache? It should automatically when you open the shell after 20 hours, but you can remove ~/.zcompcache to manually clear it.

**Comment by tsabirgaliev** [comment]
I'm not sure @belak, probably you mis-mentioned me?

**Comment by IevgenSobko** [comment]
@belak On Manjaro it doesn't help.
![screenshot_20180421_095558](https://user-images.githubusercontent.com/14232100/39081654-fa84b88c-454d-11e8-94f9-ff6a56b0c12b.png)

On Antergos I reverted zsh few days ago and today after your comments updated back to verify this and for some reason it started working even without clearing zshatocompletion folder

**Comment by mkleucker** [comment]
I do have the same error on macOS (10.13.4, zsh 5.5.1, latest version of prezto). Also tried to delete the cache and use a default settings. 
Looks like a bug in zsh though. If I read it correctly https://github.com/zsh-users/zsh/commit/4977ec13982bc851668e85924e30a57c4e304b6e#diff-02f0b547c2779d25cff89672135f20e3 might have caused this. Will try to investigate it a bit more later.

**Comment by sklirg** [comment]
Removing `~/.zcompcache` solved the problem for me on archlinux with zsh 5.5.1. :+1:

**Comment by belak** [comment]
@IevgenSobko It looks like we use 2 cache files (I only mentioned one of those before) `.zcompdump` and `.zcompcache`. If you remove both of those and start a new shell, do you still see the error?

**Comment by IevgenSobko** [comment]
@belak your latest hint with removing both files helped me.
Thanks for you patience. Closing this issue.

**Comment by belak** [comment]
Thanks for following up! I'm glad it was a simple fix, though I wish it was easier to automate a fix.

**Comment by cmcginty** [comment]
Removing `.zcompdump` worked for me

**Comment by millisami** [comment]
Removing both `.zcompdump` and `.zcompcache` on Mac Catalina solved it. Muchas gracious.
