### ISSUE TITLE
Prezto prompt performance issues

### ISSUE THREAD

**Issue by cmcginty** [sorin-ionescu/prezto#1573]
I'm running the latest version of prezto. Last week it got really slow and still is an issue this week.

Is anyone else experiencing this?

**Comment by belak** [comment]
Hi! I'm not aware of any new changes in prezto which would have caused this... Could you please provide the following info to make this easier to debug? Thanks!

- Prezto commit (Current and previous, if possible - if you don't have the previous commit on hand it may be possible to grab it using git reflog)
- ZSH version
- OS information
- Enabled modules and/or your full zpreztorc

**Comment by cmcginty** [comment]
I think the issue is from `pyenv` module:

```
$ time (pyenv sh-activate --quiet)                                                            ✘ 1
false
( pyenv sh-activate --quiet; )  0.05s user 0.04s system 7% cpu 1.318 total
```

**Comment by cmcginty** [comment]
https://github.com/pyenv/pyenv/issues/784

**Comment by belak** [comment]
Yes, pyenv can be slow, but there are some ways to mitigate that.

I'd be happy to take a look if you could provide more info about your setup as requested above. Otherwise I'd be debugging pretty blindly.

**Comment by cmcginty** [comment]
Just wanted to report back the root cause of this was CarbonBlack daemon slowing down bash. This is a known issue in CarbonBlack and seem like it might be resolved in the future.

I guess when someone here reports performance issues, this should be one of the debug steps.

**Comment by belak** [comment]
Thanks for following up! Do you have any suggestions for what to add to the debug steps? I think specifically calling out Carbon Black would be a bit too specific.
