### ISSUE TITLE
Improve Prezto "command-not-found" module load time

### ISSUE THREAD

**Issue by cmcginty** [sorin-ionescu/prezto#1577]
If I disable the "`command-not-found`" module in my `zpreztorc` file the init time drops from 1.2s to 0.2s. It seems like this module takes a lot of time to initialize.

1) Are there any options to reduce this time
2) Can some of the initialization be delayed until after the prompt is available?

For reference I'm testing with the command:

    $ time (zsh -ic exit)

**Comment by belak** [comment]
Thanks for the report. I've added a workaround from #1451 which should make loading this module almost instant.
