### ISSUE TITLE
Does not support pacman's completion?

### ISSUE THREAD

**Issue by fcying** [sorin-ionescu/prezto#1580]
### Description
not support pacman's completion, I had add `pacman` into `pmodule`
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'autosuggestions' \
  'pacman' \
  'fasd' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt'
```
it can complete in bash
```
zsh
pacman -S aa<tab><tab>
 -- no matches found --

bash
pacman -S aa<tab><tab>
aalib                                aarch64-linux-gnu-gcc                aarch64-linux-gnu-glibc
aarch64-linux-gnu-binutils           aarch64-linux-gnu-gdb                aarch64-linux-gnu-linux-api-headers
```

### Expected behavior
support pacman's completion

### Steps to Reproduce
pacman -S aa<tab><tab>

### Versions

  - Prezto commit: 6e179f24ab606f5
  - ZSH version:zsh 5.4.2 (x86_64-unknown-linux-gnu)
  - OS information: manjaro

**Comment by fcying** [comment]
This is a version issue of zsh, zsh 5.4.2 is install by `brew`, it completion work error.
If I switch to `/usr/bin/zsh: zsh 5.4.2 (x86_64-unknown-linux-gnu)`, work fine

**Comment by belak** [comment]
Thanks for following up! Glad you were able to figure it out.
