### ISSUE TITLE
syntax-highlighting README.md has ambiguous description for load order

### ISSUE THREAD

**Issue by MaxwellBo** [sorin-ionescu/prezto#1584]
### Description

From [`prezto/modules/syntax-highlighting/README.md`](https://github.com/sorin-ionescu/prezto/blob/master/modules/syntax-highlighting/README.md):

> This module should be loaded second to last, where last is the prompt module, unless used in conjuncture with the history-substring-search module where it must be loaded before it.

### Expected behavior

The README should not make ambiguous references to 'it'. The current version could describe any possible load order of `history-substring-search`, `prompt` and `syntax-highlighting`. 

I'm assuming that the correct load order is `syntax-highlighting, prompt, history-substring-search`, but I could imagine someone putting `history-substring-search` before `syntax-highlighting` or before `prompt`. 

### Versions

  - Prezto commit: 2995b7d0c89d628a68ea789e21ea8f26ea8fa4d9

**Comment by mfontani** [comment]
YES! I've been looking _hard_ at the reason why my arrow-up for substring search wasn't working, and _this_ was *it*. Reading comprehension fail on my part, probably - but the README might want to be clearer.

Making the order be `'syntax-highlighting' 'prompt' 'history-substring-search'` indeed fixes the syntax highlighting + history substring search "not playing well together".

**Comment by belak** [comment]
I definitely agree that could be clearer. Thanks for bringing it up and for clarifying.

**Comment by belak** [comment]
Fixed in 0d6e7de0312366322bf7e7e1dbb41697b5bcd3b1. I reworded the syntax-highlighting module to match the phrasing in history-substring-search.
