### ISSUE TITLE
The paradox theme not showing git info

### ISSUE THREAD

**Issue by daiyanze** [sorin-ionescu/prezto#1585]
Was the git branch info deleted from paradox theme? The powerline theme seems fine.

<img width="457" alt="screen shot 2018-05-18 at 15 34 37" src="https://user-images.githubusercontent.com/14920529/40219630-2c71ca92-5ab1-11e8-9ef8-07f602194697.png">

**Comment by belak** [comment]
The paradox theme hasn't been changed in quite a few months? Can you please provide some of the information requested in the new issue template like ZSH version, prezto commit, and OS version? Without that I don't have enough information to help.

**Comment by daiyanze** [comment]
Thanks for your rapid reply!
It was because of the settings in `.zpreztorc`.
`git` was not added to the module list.

<img width="279" alt="screen shot 2018-05-18 at 16 03 23" src="https://user-images.githubusercontent.com/14920529/40220722-1c193668-5ab5-11e8-8928-08cde47adacc.png">

**Comment by daiyanze** [comment]
@belak closable

**Comment by belak** [comment]
Thanks for following up! Glad you got it figured out :D
