### ISSUE TITLE
brew cask search is deprecated

### ISSUE THREAD

**Issue by jedahan** [sorin-ionescu/prezto#1595]
### Description
when using the homebrew module, `casks` runs `brew cask search`, but according to homebrew as of 10 days ago, `Warning: Calling \`brew cask search\` is deprecated!`.

### Expected behavior

I'm not sure if we should remove the `casks` alias, or have it do the same thing as `brews`. I am leaning towards the former.

### Steps to Reproduce

1. run `casks whatever`
2. observe warning and no results shown

### Versions

  - Prezto commit: 0d6e7de0312366322bf7e7e1dbb41697b5bcd3b1 
  - ZSH version: zsh 5.5.1 
  - OS information: Darwin 17.6.0

**Comment by singularitti** [comment]
I have made a pull-request (#1597) to redirect `casks` to `brews`.

**Comment by hairuo** [comment]
I met the similar problem looks like this:
$ brew cask search wiznote
Warning: Calling `brew cask search` is deprecated!
Use `brew search` instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'

==> Casks
wiznote ✔                                       wiznote ✔                                       wiznote ✔

**Comment by belak** [comment]
I'm currently happy with the fix in #1623. Eventually we'll probably want to remove the deprecated aliases entirely, but that doesn't need to happen right now. Thanks for the feedback everyone!
