### ISSUE TITLE
Question on customisation / alias 

### ISSUE THREAD

**Issue by m67hoff** [sorin-ionescu/prezto#1596]
Hi sorry for opening an issue - I  tried to google / stackoverflow for it but did not find help.

What is the best / recommended way to customize aliases ?  
( In this case I want to unalias the  general from utility module  p='${(z)PAGER}' ) 
 
should I edit   modules/utility/init.zsh ?
or better add unalias p in  runcoms/zshrc
or ?

Thanks - and if there is a better/preferred  way to ask such question let me also know

**Comment by belak** [comment]
My personal preference is to add the unalias in your personal zshrc. The provided zshrc is very small and fairly simple, so I'd prefer copying over a symlink.

**Comment by belak** [comment]
I'm closing this for now, but there are other threads on customization, particularly #1535 

Hope this helped!
