### ISSUE TITLE
Terminal module does not show full command

### ISSUE THREAD

**Issue by cwfoo** [sorin-ionescu/prezto#1598]
### Description

The terminal module does not make the terminal display the full command that is running.

### Expected behavior

For example, if one runs `man cat`, one expects the terminal module to set the terminal title to `man cat`.

### Actual behavior

However, only `man` is displayed in the terminal title.

### Steps to Reproduce

1. In `~/.zpreztorc`, enable the terminal module.
2. In `~/.zpreztorc`, uncomment `zstyle ':prezto:module:terminal' auto-title 'yes'`.
3. Open a new terminal.
4. Run `man cat` and notice the terminal title (I see `man`).

### Versions

  - Prezto commit: 0d6e7de0312366322bf7e7e1dbb41697b5bcd3b1
  - ZSH version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
  - OS information: Ubuntu 18.04 LTS

**Comment by belak** [comment]
Can you please confirm what terminal you’re using so it’s easier for me to reproduce this? Thanks!

**Comment by foochuanwei** [comment]
Terminal (`gnome-terminal --version`): GNOME terminal 3.28.1 using VTE 0.52.1 +GNUTLS -PCRE2

**Comment by foochuanwei** [comment]
I think these are the relevant lines: https://github.com/sorin-ionescu/prezto/blob/cd7082299467a26d443e597f1fd2f02506a45a6a/modules/terminal/init.zsh#L59-L60
