### ISSUE TITLE
Feature request: Greg Hurrell's Zsh Prompt

### ISSUE THREAD

**Issue by oblitum** [sorin-ionescu/prezto#1601]
@wincent describes his great prompt setup [here (link with highlighted comment)](https://www.youtube.com/watch?v=yE9g-lVPrnY&lc=Ugyrb1hoga_OefinYXN4AaABAg). It would be nice if we got it wrapped up and integrated into Prezto.

I'm creating this issue just as a feature request as well as a note to self in case I find time to look how to wrap it up and create a pull request. If anyone is interested in it now though, feel free to implement it first.

**Comment by belak** [comment]
This seems like it would be a better fit for the [contrib repo](https://github.com/belak/prezto-contrib). Sorin is fairly opposed to new prompts in this repo (there have already been a number of instances where we’ve had to go and fix bugs in prompts that none of the maintainers use) but keeping them in contrib makes it clearer that they’re community maintained.

**Comment by oblitum** [comment]
That's fine, I didn't realize of that.

**Comment by belak** [comment]
Not a problem. I’d be happy to include it in contrib though! Thanks for bringing it up.

**Comment by oblitum** [comment]
@belak done! :)
