### ISSUE TITLE
Update Pure theme to 1.7.0

### ISSUE THREAD

**Issue by Icantjuddle** [sorin-ionescu/prezto#1610]
### Update Pure theme to 1.7.0
Sub-module currently points to 1.6.0. 

### Expected behavior
Could use the latest version, doesn't change a ton but does include some bug fixes and a few improvements. 

### Versions

  - Prezto commit:e149367445d2bcb9faa6ada365dfd56efec39de8
  - ZSH version: 5.4.1
  - OS information: MacOS high sierra

**Comment by belak** [comment]
PRs welcome!

**Comment by belak** [comment]
This was merged in #1615. Thanks for the report!
