### ISSUE TITLE
history-substring-search must come after editor module

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#1613]
In order for this to work:

https://github.com/sorin-ionescu/prezto/blob/dacef142144aaddd886a2a6898cba506a9ea01b9/modules/history-substring-search/init.zsh#L49

It must come ~~before~~ **after** this:

https://github.com/sorin-ionescu/prezto/blob/dacef142144aaddd886a2a6898cba506a9ea01b9/modules/editor/init.zsh#L266

None of the READMEs touch on this currently.

In my config I have just moved `bindkey -d` to the _environment_ module (which is always first) to avoid always worrying about the _editor_ module destroying upstream keybinds.

In `prezto/modules/environment/init.zsh`:

```zsh
  #
  # Reset to default key bindings.
  #

  if [[ "$TERM" != 'dumb' ]]; then
    bindkey -d
  fi
```

**Comment by belak** [comment]
Isn't it the exact opposite? `bindkey -d` should remove all keybinds so the additional call to bindkey should come after.

**Comment by leoj3n** [comment]
Not opposite, we agree about `bindkey -d`. However, just noticed `history-substring-search/init.zsh` uses `$key_info` which is set in the _editor_ module...

https://github.com/sorin-ionescu/prezto/blob/dacef142144aaddd886a2a6898cba506a9ea01b9/modules/history-substring-search/init.zsh#L43-L46

So would also have to move the `key_info` definition to the _environment_ module as well:

```zsh
# Use human-friendly identifiers.
zmodload zsh/terminfo
typeset -gA key_info
key_info=(
  'Control'         '\C-'
  'ControlLeft'     '\e[1;5D \e[5D \e\e[D \eOd'
  'ControlRight'    '\e[1;5C \e[5C \e\e[C \eOc'
  'ControlPageUp'   '\e[5;5~'
  'ControlPageDown' '\e[6;5~'
  'Escape'       '\e'
  'Meta'         '\M-'
  'Backspace'    "^?"
  'Delete'       "^[[3~"
  'F1'           "$terminfo[kf1]"
  'F2'           "$terminfo[kf2]"
  'F3'           "$terminfo[kf3]"
  'F4'           "$terminfo[kf4]"
  'F5'           "$terminfo[kf5]"
  'F6'           "$terminfo[kf6]"
  'F7'           "$terminfo[kf7]"
  'F8'           "$terminfo[kf8]"
  'F9'           "$terminfo[kf9]"
  'F10'          "$terminfo[kf10]"
  'F11'          "$terminfo[kf11]"
  'F12'          "$terminfo[kf12]"
  'Insert'       "$terminfo[kich1]"
  'Home'         "$terminfo[khome]"
  'PageUp'       "$terminfo[kpp]"
  'End'          "$terminfo[kend]"
  'PageDown'     "$terminfo[knp]"
  'Up'           "$terminfo[kcuu1]"
  'Left'         "$terminfo[kcub1]"
  'Down'         "$terminfo[kcud1]"
  'Right'        "$terminfo[kcuf1]"
  'BackTab'      "$terminfo[kcbt]"
)
```

**Comment by leoj3n** [comment]
> Isn't it the exact opposite? bindkey -d should remove all keybinds so the additional call to bindkey should come after.

Ah, I see what you are referring to, I said "before" when I meant "after", have updated the OP.

**Comment by leoj3n** [comment]
Well this might all be moot for prezto since there's no dependency hierarchy. Moving `bindkey -d` makes sense for my configuration since I've added a facility for managing dependencies, and so moving `bindkey -d` is all that I needed in addition to declaring the dependency.

Judging by the `if [[ -n "$key_info" ]]; then` check it looks like prezto is aiming to keep the modules more "grab and go" so they can essentially be copy-pasted to work on their own without the rest of the framework.

**Comment by leoj3n** [comment]
Yeah, I've not been making edits in my public fork of prezto for a while
now. I totally missed the pmload line when comparing. That is pretty much
how I am doing deps too, however mine is set up to have hard dependencies
throughout.

So I guess this leads to the question of why was the decision made in
prezto to have order matter for some modules while others have a hard
dependency?

I'm guessing that logicaliy it doesn't make sense to use X without using Y
in some cases, while in other cases it leans towards being more optional...?

Regardless of the reason why, as long as it is the case that there is hard
deps, it might be helpful to state that there is the "hard dependency" in
the module README (unless that is already there, and I missed that too!).

The final thought then is:

Can things be broken up, or the loader reworked in such a way, that the
user order of stock modules becomes not important?

In my opinion, at least, not having to worry about the load order would be
a superior user experience, because you don't really confront that as a new
user until you drill down into the individual module docs, which you might
not know to do after skimming the root README when just getting started.

I remember getting in trouble with order plenty of times in the past when
trying out various modules, but maybe that is just me... Does seem like
this should be possible to accomplish while still having optional deps be
optional, but I'm not sure at what added complexity for prezto. So maybe
just need a little improved docs here unless you think otherwise.

**Comment by belak** [comment]
I agree that not having to worry about the load order would be nice, but I'm not sure (at least under the current system) that would be possible. Might be something to consider if we ever start work on a next-gen version of prezto.
