### ISSUE TITLE
External modules are out of date.

### ISSUE THREAD

**Issue by soylens** [sorin-ionescu/prezto#1614]
The external module `zsh-completion`, `zsh-syntax-highlighting` etc. are almost 1a out of date.

The external modules, according to `README.md`s, are supposed to be synchronized with the projects, whereas they are actually on a old branch, approx. 1a since the last commit, demanding manual checkout after checking out as submodules.

  - Prezto commit:dacef14
  - ZSH version:5.1.1

**Comment by belak** [comment]
PRs would be welcome!

**Comment by diraol** [comment]
@belak is there any kind of recommendation to update submodules to tagged versions? Or can we go with the most current master?

**Comment by diraol** [comment]
(I'm asking because I have almost all submodules updated locally to the most recent version of each one, I can make this PR right now, just need to know if I go with master or the latest TAG - for the projects that have tags).

**Comment by belak** [comment]
I usually aim for latest tag.
