### ISSUE TITLE
howto: turn off all hostname completions?

### ISSUE THREAD

**Issue by donahchoo** [sorin-ionescu/prezto#1621]
Sorry, I'm stuck.  How do I turn off all hostname completions?  I have a [huge /etc/hosts](https://github.com/StevenBlack/hosts) file that I use to block sites and I'd rather just turn off completion... 

I tired this in runcoms/zpreztorc but it didn't help...

`zstyle ':completion:*' hosts off`

**Comment by ezintz** [comment]
Try using `zstyle ':completion:*:ssh:*' hosts off`, that works for me.

**Comment by ezintz** [comment]
You can add `zstyle ':prezto:module:completion:*:hosts' etc-host-ignores \
  '0.0.0.0' '127.0.0.1'` as described in the [Readme](https://github.com/sorin-ionescu/prezto/blob/master/modules/completion/README.md). Another option would be to override the completion e.g. 

```
zstyle -e ':completion:*:hosts' hosts 'reply=(
  ${=${=${=${${(f)"$(cat {/etc/ssh/ssh_,~/.ssh/}known_hosts(|2)(N) 2> /dev/null)"}%%[#| ]*}//\]:[0-9]*/ }//,/ }//\[/ }
  ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2> /dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'
```

**Comment by donahchoo** [comment]
Thanks @ezintz.  The zstyle command works great.  I had tired etc-host-ignores but it failed because I have ipv4 and ipv6 entries in my hosts file.  It seems like that only works with ipv4 entries?

**Comment by ezintz** [comment]
Your welcome. IPv6 addresses are not filtered because of the regular expression which is used, I guess. Pull requests are welcome since I would have to take some time to find out whats going on.

**Comment by belak** [comment]
It sounds like your question has been resolved so I'm closing this for now. However, I've also opened a separate issue to add support for IPv6 hostnames. Thanks for bringing it up!
