### ISSUE TITLE
do not set VIRTUAL_ENV_DISABLE_PROMPT=1 when using pure prompt

### ISSUE THREAD

**Issue by cih9088** [sorin-ionescu/prezto#1627]
I know `python` module explicitly set `VIRTUAL_ENV_DISABLE_PROMPT` to 1.
However, pure prompt do not show virtual env name if `VIRTUAL_ENV_DISABLE_PROMPT=1` since [this update](https://github.com/sindresorhus/pure/pull/381).

I have to unset `VIRTUAL_ENV_DISABLE_PROMPT` in `.zshrc` for now but there might be a cleaner way to handle this.

**Comment by belak** [comment]
I updated our python module to use the same magic value as pure, so this should be fixed. Thanks for the report!
