### ISSUE TITLE
Configurable way to modify prompt with lambda

### ISSUE THREAD

**Issue by twashing** [sorin-ionescu/prezto#1630]
I'm using the [steeef](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_steeef_setup) theme. I wanted to have a lambda (`λ`) at my prezto prompt. Like how [marszall87/lambda-pure](https://github.com/marszall87/lambda-pure) does it. 

I didn't see a configurable way to do this. So I went in and manually fudged the [code here](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_steeef_setup#L90). 

Didn't see anything [here](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt). Is there a more idiomatic way of doing this? 

<img width="1530" alt="screen shot 2018-10-10 at 9 00 33 pm" src="https://user-images.githubusercontent.com/239784/46780242-6e43c880-ccd0-11e8-8b9c-83338b4db89c.png">

### Versions

  - Prezto commit:
```
commit e00562e7cf20c48a255212a088ab134ea0c6a543
Author: bryndin <bryndin@gmail.com>
Date:   Fri Feb 23 13:39:45 2018 -0800

    python: autoload add-zsh-hook when needed (#1549)

    Fixes #1550
```
  - ZSH version: zsh 5.3 (x86_64-apple-darwin17.0)
  - OS information: MacOS HighSierra, 10.13.3

**Comment by johnpneumann** [comment]
That is the only way currently. However, you could abstract the end symbol out to a variable that could be overridden in zpreztorc for that prompt. That'd be more extensible and would be PR worthy.

**Comment by twashing** [comment]
@johnpneumann Ask and ye shall receive!

https://github.com/sorin-ionescu/prezto/pull/1633
