### ISSUE TITLE
history-substring-search behavior

### ISSUE THREAD

**Issue by sianhulo** [sorin-ionescu/prezto#1637]
### Description
When using uparrow to look for similar commands as my current terminal input I want to only get commands starting with my input.

### Expected behavior
let's say I input `sudo` (or anything else) and use uparrow I want every command that starts with `sudo` (to get sudo*).

### Actual behavior

I get every command that contains `sudo` anywhere in it (I get \*sudo\*).

### Versions

  - Prezto commit: 6c46804f
  - ZSH version: 5.6.2
  - OS information: Antergos

I apologize if this is already possible to configure, I couldn't find anything about this.

**Comment by jeffwidman** [comment]
Hmm... mine already works this way. I don't think I have anything special set either. What is the list of modules you have enabled and in what order?

**Comment by sianhulo** [comment]
I think what solved it for me was the following:

`autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down`

I no longer have the substring search behavior enabled as it isn't needed.
