### ISSUE TITLE
prompt issue on arch linux

### ISSUE THREAD

**Issue by alvesadrian** [sorin-ionescu/prezto#1644]
~ ❯❯❯ sudo su -
-bash: __git_ps1: command not found
-bash: __vte_osc7: command not found
[root@x230 ~]#

**Comment by belak** [comment]
It looks like you're having an issue running prezto in bash, which is not supported. If you're still having this issue with zsh, please feel free to open another issue using the provided issue template and we'll do our best to investigate.

**Comment by adrian-gluu** [comment]
am using zsh not bash as user root is using bash

**Comment by belak** [comment]
I'm not sure what your actual issue is. Both of the errors listed are prefixed with "bash" and the prompt in zsh looks like it's displaying properly.
