### ISSUE TITLE
customize "agnoster" theme

### ISSUE THREAD

**Issue by kud** [sorin-ionescu/prezto#1645]
On agnoster theme, is it possible to truncate the path like you've got on the default theme?

<img width="162" alt="image" src="https://user-images.githubusercontent.com/655838/49103226-10b50c80-f27b-11e8-9f6b-e53987914172.png">

vs

<img width="369" alt="image" src="https://user-images.githubusercontent.com/655838/49103252-1ad70b00-f27b-11e8-82a5-20caad9c3e90.png">

**Comment by belak** [comment]
This is not currently possible, as agnoster is an external theme https://github.com/agnoster/agnoster-zsh-theme

Though with an updated version of that, it may be possible to write a custom segment to do this.

**Comment by kud** [comment]
It's ok in fact.

I just added this into my `.zshrc`

```shell
prompt_context() {
  # local user=`whoami`

  # if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CONNECTION" ]]; then
  #   prompt_segment $PRIMARY_FG default " %(!.%{%F{yellow}%}.)$user@%m "
  # fi

  prompt_segment $PRIMARY_FG default  "  🌈  "
}

prompt_dir() {
  prompt_segment blue $PRIMARY_FG ' %c '
}
```

:D

**Comment by kud** [comment]
That's cute:

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/655838/49104451-50c9be80-f27e-11e8-85ed-bf1a407ef070.png">

**Comment by belak** [comment]
Glad you got something figured out!

**Comment by kud** [comment]
Indeed! Thank you @belak :)
