### ISSUE TITLE
python/pip cache file error: no matches found

### ISSUE THREAD

**Issue by diraol** [sorin-ionescu/prezto#1658]
This issue was introduced by #1650.

Every time I open a new terminal I receive the following message:

> /tmp/prezto-pip-cache.1000.zsh:11: no matches found: pip(|[23](|.[0-9]))

If I go back to the commit dc8e168 (the one before 9d3e2f0 that was introduced by #1650), and cleanup the cache file (`/tmp/prezto-pip-cache.1000.zsh`) the error disappear. If I reintroduce the commit 9d3e2f0 and clean the cache file, then the error is appears again.

The error happens with the command: `compctl -K _pip_completion pip(|[23](|.[0-9]))`

Before the command was: `compctl -K _pip_completion pip pip2 pip3`.

**Comment by indrajitr** [comment]
@diraol can you please share the OS variant (looks like Linux based on `$UID`) and zsh version? 

I validated this on macOS but something definitely isn't right based on what you are observing.

**Comment by diraol** [comment]
For sure @indrajitr 

`lsb_release -a`:
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux buster/sid
> Release:	testing
> Codename:	buster

`zsh --version`:
> zsh 5.6.2 (x86_64-debian-linux-gnu)

`python --version`:
> Python 3.7.1

```
> pyenv versions
  system
  2.7
  2.7.15
  2.7.15/envs/2.7
  3.4.9
  3.5.6
  3.6
  3.6.6
  3.6.6/envs/3.6
  3.7
  3.7.0
  3.7.0/envs/3.7
* 3.7.1 (set by /home/diraol/.pyenv/version)
```

`pip + <tab>`:
> pip              pip2.7           pip3.4           pip3.6           pipenv
> pip2             pip3             pip3.5           pip3.7           pipenv-resolver

If you need any other info that can be usefull please, let me know! =)

**Comment by indrajitr** [comment]
@diraol: Can you please try out #1660 and see if all the pip variants for you (and fixes the terminal error as well)?

**Comment by diraol** [comment]
Hi @indrajitr 

The message I was receiving was:

> /tmp/prezto-pip-cache.1000.zsh:11: no matches found: pip(|[23](|.[0-9]))

Now, with while in your branch (and after cleaning the cache file), I got:

> /tmp/prezto-pip-cache.1000.zsh:11: no matches found: pip[23]([.0-9])#

**Comment by gpanders** [comment]
Seeing the same thing here on Arch Linux.

`lsb_release -a`
> LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

`zsh --version`
> zsh 5.6.2 (x86_64-pc-linux-gnu)

Testing @indrajitr's fix gives me the following error:
> /tmp/prezto-pip-cache.1000.zsh:11: no matches found: pip[23]([.0-9])#

**Comment by indrajitr** [comment]
@diraol, @gpanders: Switching to pure brace expansion did the trick.
