### ISSUE TITLE
Confused by loading order requirements, can anyone explain it?

### ISSUE THREAD

**Issue by laggardkernel** [sorin-ionescu/prezto#1659]
### Description
After reading some `README.md` files, I noticed the existence of loading order requirements. Here is what I got:
- `utility > completion > syntax-highlighting > history-substring-search > autosuggestions`
- `utility > completion > syntax-highlighting > prompt`
- `utility > completion > fasd`

I'm not loading in this order strictly, but it seems modules still work. 

Besides, browsing through repos belonging to [zsh-users](https://github.com/zsh-users), I find the only requirement given by zsh-users is to source `zsh-syntax-highlighting` at last.
> `zsh-syntax-highlighting.zsh` wraps ZLE widgets. It must be sourced after all custom widgets have been created (i.e., after all `zle -N` calls and after running `compinit`). Widgets created later will work, but will not update the syntax highlighting.

Can anyone explain the reason?

Update:
- `completion` module is where you load and initialize the completion `autoload -Uz compinit`, so any internal comdef should be processed before it. This solves the `utility > completion` part, cause `utility` contains some completion definition files.
- [`fasd` completion initialization](https://github.com/sorin-ionescu/prezto/blob/master/modules/fasd/init.zsh#L29-L32) depends on function `compdef`, which is available after `compinit`. This solves the `completion > fasd` part.
- `syntax-highlighting` wraps ZLE widgets,  `history-substring-search` defines custom ZLE widgets. According to [usage guide of zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search#usage), `zsh-syntax-highlighting` should be loaded before `zsh-history-substring-search`

Some references:
- #1613 history-substring-search must come after editor module
- #1584 syntax-highlighting README.md has ambiguous description for load order
- #1184 Why must utility come before completion?

**Comment by belak** [comment]
Reference for syntax-highlighting before history-substring-search: https://github.com/zsh-users/zsh-history-substring-search#usage

**Comment by belak** [comment]
I believe autosuggestions needs to come after those two in order to properly override the zle widgets.
