### ISSUE TITLE
Scrolling in TMUX

### ISSUE THREAD

**Issue by danst0** [sorin-ionescu/prezto#1675]
Hi,

how would I configure zprezto with tmux to allow scrolling in the tmux window?

Daniel

**Comment by danst0** [comment]
Thanks. the tumx.conf option worked. ctrl-b [ is a pain to execute on a non-english keyboard layout...

**Comment by crivotz** [comment]
@danst0 You are welcome

**Comment by danst0** [comment]
It does have some caveats however, I do not know how I can copy and paste from the terminal in this setup...

**Comment by Herjar** [comment]
You have to hold shift while copying/pasting. A bit annoying, but I have not found a way around that.

**Comment by srijanshetty** [comment]
@danst0: I use vim bindings and a 'visual like interface to copy in a tmux session'

` 
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi 'v' send -X begin-selection

# For binding 'y' to copy and exiting selection mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'
 
# For binding 'Enter' to copy and not leave selection mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe 'xclip -sel clip -i' '\;'  send -X clear-selection
`

You can find my tmux.conf here https://github.com/srijanshetty/vcsh-tmux/blob/master/.tmux.conf
