### ISSUE TITLE
Update prompt pure to 1.9.0

### ISSUE THREAD

**Issue by yiminglin-ai** [sorin-ionescu/prezto#1677]
Please could you update Pure to version 1.9.0, which fixed a bug showing conda environment https://github.com/sindresorhus/pure/pull/440. Thank you very much.

**Comment by belak** [comment]
Currently blocked by #1641 until we figure out what to do there. Thanks for bringing this up!

**Comment by yl1991** [comment]
any updates?

**Comment by belak** [comment]
This was previously closed as not planned, but it was actually completed when Pure was upgraded to 1.20.0 in https://github.com/sorin-ionescu/prezto/pull/1987. Cheers!
