### ISSUE TITLE
how add zsh completion folder ?

### ISSUE THREAD

**Issue by souhaiebtar** [sorin-ionescu/prezto#1679]
i'm using mac, and every time i use brew to install a program,
zsh completion are put in `/usr/local/share/zsh/site-functions`

how we can use them ?

thanks

**Comment by souhaiebtar** [comment]
fpath=("/usr/local/share/zsh/site-functions" $fpath)

**Comment by thezjy** [comment]
@souhaiebtar Does it work for you? I added that path to fpath but the completion still doesn't work.

**Comment by souhaiebtar** [comment]
@thezjy  sorry for that, i think it does not work, i'm not quite sure, i will try to verify more

**Comment by souhaiebtar** [comment]
@thezjy it seem to be working, have you opened another tab after that,
maybe you need to type:
```bash
rm -f ~/.zcompdump; compinit
autoload -U compinit && compinit
exec zsh
```

**Comment by thezjy** [comment]
@souhaiebtar It works! Thanks so much!

**Comment by souhaiebtar** [comment]
@thezjy y r welcome, good for you
