### ISSUE TITLE
_zsh_highlight_call_widget:2: bracketed-paste-url-magic: function definition file not found

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#1683]
### Description
Happens when I type first something like `git commit -am '` and then paste in some contents.

### Expected behavior
Few weeks ago no such warning came up. Must come from a recent update.

### Actual behavior
This:

```
└─❱❱❱ git commit -am '                                                                                                                                                      130 ⏎  +9100 13:43 ❰─┘
_zsh_highlight_call_widget:2: bracketed-paste-url-magic: function definition file not found
└─❰❰❰ git commit -am 'Decouple code for error and info notificationS
```

### Steps to Reproduce

1. Add this to clipboard `Decouple code for error and info notifications`
2. Type `git commit -am '` and then paste from clipboard
3. Boooom, warning comes up

### Versions

  - Prezto commit:

```
Commit: 4abbc5572149baa6a5e7e38393a4b2006f01024f (HEAD -> master, origin/master, origin/HEAD)
Author: Yutian Li <hotpxless@gmail.com>
Date:   2019-01-04 13:05:37 -0500 (3 weeks ago)

remove mutually exclusive option
```

  - ZSH version:

```
└─❱❱❱ zsh --version                                                                                                                                                         141 ⏎  +9115 13:46 ❰─┘
zsh 5.7 (x86_64-apple-darwin17.7.0)
```

  - OS information: macOS High Sierra v10.13.6

**Comment by binarykitchen** [comment]
Anyone? This is bugging me ...

**Comment by andig** [comment]
Same here, probably better open issue with zsh_highlight plugin

**Comment by belak** [comment]
I've updated the syntax-highlighting module to the latest stable release. If you're continuing to have this issue after updating prezto, please let me know and I can re-open this.
