### ISSUE TITLE
How to enable multi dots paths?

### ISSUE THREAD

**Issue by FezVrasta** [sorin-ionescu/prezto#1684]
### Description
With OMZ I can write `...` as alias of `../..` (and also `....` etc), with Prezto I can't. How can I enable it?

### Expected behavior

`...` should work

### Actual behavior

It doesn't

### Steps to Reproduce

1. type `...`

**Comment by salmanulfarzy** [comment]
Please refer to the documentation before creating an issue, It's mentioned on module documentation and commented on runcom,

https://github.com/sorin-ionescu/prezto/blob/5d7c990eec21e83c0735f6b8e7d1d669102cbb4f/runcoms/zpreztorc#L62-L63 

[modules/editor/README.md#dot-expansion](https://github.com/sorin-ionescu/prezto/blob/5d7c990eec21e83c0735f6b8e7d1d669102cbb4f/modules/editor/README.md#dot-expansion)

> To enable the auto conversion of .... to ../.., add the following to zpreztorc.
>```
>zstyle ':prezto:module:editor' dot-expansion 'yes'
>```

**Comment by salmanulfarzy** [comment]
It's disabled by default. As mentioned on module documentation and commented on runcom,

https://github.com/sorin-ionescu/prezto/blob/5d7c990eec21e83c0735f6b8e7d1d669102cbb4f/runcoms/zpreztorc#L62-L63 

[modules/editor/README.md#dot-expansion](https://github.com/sorin-ionescu/prezto/blob/5d7c990eec21e83c0735f6b8e7d1d669102cbb4f/modules/editor/README.md#dot-expansion)

> To enable the auto conversion of .... to ../.., add the following to zpreztorc.
>```
>zstyle ':prezto:module:editor' dot-expansion 'yes'
>```

Also it would've been great if you referred to the documentation before creating an issue.

**Comment by FezVrasta** [comment]
Thanks, I'm sorry but I didn't even know there was documentation in that folder. I checked the readme: no "doc" links, checked the wiki: not available, and I thought everything was on the root README file.

**Comment by salmanulfarzy** [comment]
It's mentioned on [sorin-ionescu/prezto#usage](https://github.com/sorin-ionescu/prezto/tree/5d7c990eec21e83c0735f6b8e7d1d669102cbb4f#usage) section

> Prezto has many features disabled by default. Read the source code and accompanying README files to learn of what is available.

But agree on it's not prominent enough.
