### ISSUE TITLE
function definition file not found

### ISSUE THREAD

**Issue by FezVrasta** [sorin-ionescu/prezto#1685]
### Description
Most of the times, when I press "tab" to autocomplete a path, I get this error:

```
~/P/Q/a/web ❯❯❯ code no...
(eval):1: _code: function definition file not found
(eval):1: _code: function definition file not found
```

I tried to run `rm -fr ~/.zcompdump*` but I always end up getting the same error again.

### Expected behavior

The path should be completed correctly.

### Actual behavior

See description

### Steps to Reproduce

1. try to use autocompletion with tab

### Versions

  - Prezto commit: 4abbc5572149baa6a5e7e38393a4b2006f01024f
  - ZSH version: zsh 5.6.2 (x86_64-apple-darwin18.2.0)
  - OS information: macOS Mojave

**Comment by msilvestre** [comment]
It also happens to me. But it's gone once I removed autosuggestions module. 
Can it be a bug on autosuggestions?

**Comment by phearnot** [comment]
I've had this issue which turned out to be caused by the incomplete prezto update. After properly [updating](https://github.com/sorin-ionescu/prezto#updating), the issue was gone.

**Comment by indrajitr** [comment]
Looks like an effect of an incomplete update. Please retry after updating per the [instruction](https://github.com/sorin-ionescu/prezto#updating) and reopen if you still see an issue.
