### ISSUE TITLE
Vi bindings not working after setting in .zpreztorc

### ISSUE THREAD

**Issue by pdoak** [sorin-ionescu/prezto#1692]
### Description
Setting key bindings to vi in .zpreztorc does not set the key bindings as they are still emacs

### Expected behavior

In insert mode, pressing 'v' should invoke the vim to edit the command line

### Actual behavior

Nothing happens when 'v' is pressed. Pressing ^X^E invokes vim.

### Steps to Reproduce

As above

### Versions

  - Prezto commit: commit 5d7c990eec21e83c0735f6b8e7d1d669102cbb4f
  - ZSH version: 5.7 (x86_64-apple-darwin18.2.0)
  - OS information: OS X 10.14.3

**Comment by johnpneumann** [comment]
This is the desired behavior. The reason is that if we were to have `v` go to the editor it then stops you from being able to use `v` movements like you would in vim. I am not a huge fan of the amount of keys I have to hit to get to the editor, but there are tradeoffs for everything.
