### ISSUE TITLE
Proper way to add to PATH using array syntax

### ISSUE THREAD

**Issue by kylemart** [sorin-ionescu/prezto#1693]
Note: This is a discussion.

If I prepend to PATH (within .zshrc) using the array syntax shown here:

```zsh
path=(
  $GOPATH/bin
  $GOROOT/bin
  $path
)
```

Do I need to follow this up with an `export PATH`? 

It would seem that even without exporting the path both $GOPATH/bin and $GOROOT/bin are still visible to subprocesses in the PATH variable.

**Comment by belak** [comment]
As far as I know, if you update the path array, you shouldn't need to additionally export PATH. I believe they're kept in sync with each other.
