### ISSUE TITLE
Safe-ops aliases broken

### ISSUE THREAD

**Issue by brycekellogg** [sorin-ionescu/prezto#1699]
### Description
With `zstyle ':prezto:module:utility' safe-ops 'yes'` (the default) the safe-ops aliases such as `rmi`, `mvi`, `cpi`, and `lni` don't work. This isn't very noticeable because with safe-ops set to 'yes' you would normally use the aliased `rm`, `mv`, `cp`, and `ln` which become the safe versions as expected and work fine.

It looks to me like it's a recursive alias issue where `rmi` is aliased to `rm -i` and `rm` is aliased to `rmi`. Why this causes issues for `rmi` but not `rm` in unclear to me. The easiest fix looks to me to be changing each of the safe-ops aliases from 

```zsh
alias rm='rmi'
alias mv='mvi'
alias cp='cpi'
alias ln='lni'
```

to

```zsh
alias rm='$aliases[rmi]'
alias mv='$aliases[mvi]'
alias cp='$aliases[cp]i'
alias ln='$aliases[lni]'
```

### Expected behavior
```console
user@host:~$ rmi
rm: missing operand
Try 'rm --help' for more information.
```

### Actual behavior
```console
user@host:~$ rmi
zsh: command not found: rmi
```

### Steps to Reproduce

1. Set up a clean zprezto directory as described in in CONTRIBUTING.md
2. ```rmi```

### Versions

  - Prezto commit: 1f4601e
  - ZSH version: zsh 5.6.2 (x86_64-redhat-linux-gnu)
  - OS information: Fedora release 29 (Twenty Nine)

**Comment by bits01** [comment]
+1 for a fix please

**Comment by hotpxl** [comment]
This is very noticeably with the highlighter plugin enabled.
It'll highlight commands like `ln`, `cp` red (without the i suffix)

**Comment by belak** [comment]
I'm not sure what's going on here:

```
~/.antigen/bu/s/prezto master ?1 ❯ echo $aliases[rm]
rmi
~/.antigen/bu/s/prezto master ?1 ❯ echo $aliases[rmi]
nocorrect rm -i
```

However, you're right that it doesn't work. I'll take a look.

**Comment by belak** [comment]
Should be resolved now. Please let me know if you have any more issues!
