### ISSUE TITLE
sorin prompt + git = 100% cpu _zsh sub-process

### ISSUE THREAD

**Issue by sgtsquiggs** [sorin-ionescu/prezto#1701]
### Description

with the sorin prompt enabled, there are certain git repos I navigate to which cause a -zsh process to start and peg a core at 100%. It eventually stops after a minute or so. RPROMPT never populates w/ git-info when this happens.

### Expected behavior

Browse git repo without CPU pegging, and git-info displaying properly

### Actual behavior

-zsh process starts, pegs CPU at 100%, eventually stops. RPROMPT never updates w/ current branch & status.

### Steps to Reproduce

1. Fresh install
2. Enable 'git' module
3. Browse to git repo

This does not happen for me in every git repo... I'm not sure how to debug this.

### Versions

  - Prezto commit: 1f4601e44c989b90dc7314b151891fa60a101251
  - ZSH version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
  - OS information: Ubuntu 16.04
  - Git version: git version 2.19.1

**Comment by jeffwidman** [comment]
How big are these repo's? Are they massive and then timing out somehow?

**Comment by sgtsquiggs** [comment]
Fairly small. Average few thousand line golang project. Not committing vendored libs either :grimacing:

**Comment by oblitum** [comment]
I often have 100% CPU over zsh when idle which I can only solve by the offending instance. It doesn't block input  or anything, but a CPU core sticks to 100% when that bad zsh instance gets idle. [I still have no idea what causes it](https://github.com/sorin-ionescu/prezto/issues/879#issuecomment-441911190). Happens often when exiting a program, like Vim, then if that zsh at random starts taking 100% after that, it will have be at 100% when idle, so I have to kill it.

**Comment by c2h5oh** [comment]
I can reproduce this one quite often - I see it a couple times a week. 
After a while I get RPROMPT changed first to `✘ 1` and shortly after to `✘ 128` - exit codes I'm guessing - but 100% load on a single core continues even after that. 

Given how often I see it I might be able to debug this more - anything I should focus on?

**Comment by oblitum** [comment]
@c2h5oh I have no idea how to debug this but if you manage to find a fix please report back :)

**Comment by oblitum** [comment]
FWIW, I've moved to antigen + spaceship prompt and don't have this anymore. Another benefit is that, I don't know why, with prezto every zsh instance had an additional zsh subprocess in addition to any program I would be running in the terminal, this also doesn't happen anymore.

**Comment by hmnd** [comment]
Just had this happen too. Guess it's time to finally say goodbye to Prezto. 

Btw @oblitum would you mind sharing what you used to generate those graphics? :)

**Comment by oblitum** [comment]
@hmnd it's my configuration of [pscircle](https://gitlab.com/mildlyparallel/pscircle), it's actually my background, a screenshot was the easiest I had available to show the issue.

**Comment by oblitum** [comment]
Actually I moved to Antibody, not Antigen...
