### ISSUE TITLE
autocd not tab autocompleting directories without cd

### ISSUE THREAD

**Issue by aaparella** [sorin-ionescu/prezto#1705]
### Description
I was previously able to hit tab from a blank prompt and autocomplete directory names, i.e 

`$ Applic<TAB>` -> `$ Applications`

Now however directories are not being included, though I _am_ able to change into them by typing out the full name, and after a single directory is specified any subdirectories after that tab autocomplete as expected. I have also verified that `autocd` is set (Running `setopt` displays it).

Unfortunately I don't know what I may have changed recently to cause this, and cannot recall any significant changes I've made to my configuration. (My zshrc and related files are tracked in git, and show no relevant changes)

Let me know if there's any other information I can provide!

### Expected behavior

After typing half of a directory name, hitting TAB should complete the remainder of the directory name when unambiguous. 

### Actual behavior

```
~ Applic<TAB>
~ AppleFileServer                                                                          
 -- corrections (errors: 1) --
AppleFileServer             Apple_PubSub_Socket_Render
 -- original --
Appli
```

### Steps to Reproduce

1. Type portion of directory name
2. Press TAB

### Versions

  - Prezto commit: 1f4601e44c989b90dc7314b151891fa60a101251
  - ZSH version: 5.3 (x86_64-apple-darwin18.0)
  - OS information: macOS 10.14.4

**Comment by jeffwidman** [comment]
@aaparella Great issue description. It sounds like #1710 fixes this, can you confirm?

**Comment by aaparella** [comment]
Working like a charm! Thanks very much
