### ISSUE TITLE
Autocompletion via tab not working: "Command not found"

### ISSUE THREAD

**Issue by minddrive** [sorin-ionescu/prezto#1706]
### Description
Autocompletion with tab seems to be not functioning in my install due to a set of 'command not found errors'

### Expected behavior

'ls <tab>' should return a list of all the files/directories in the current directory

### Actual behavior

'ls <tab>' is showing the following error:

_normal:40: command not found: _dispatch
_normal:38: command not found: _set_command

(usually showing multiples of these, depending on how much I'm trying to expand)

### Steps to Reproduce

1. type 'ls'
2. hit the tab key

### Versions

  - Prezto commit: 1f4601e44c  (Mar 17 2019 commit by Chris Ewald)
  - ZSH version: 5.7.1
  - OS information: Debian 9 Testing (bionic)

**Comment by minddrive** [comment]
Closing issue, as a very old mailing list entry I came across mentioned deleting .zcompdump which resolved the problem.  Nothing to see here, move along...

**Comment by belak** [comment]
Glad you got this figured out. Thanks for following up!
