### ISSUE TITLE
[module] node: Should check if NVM is installed before loading it

### ISSUE THREAD

**Issue by muuvmuuv** [sorin-ionescu/prezto#1724]
#819 

### Description
I had a discussion with one NVM author ([here](https://github.com/nvm-sh/nvm/issues/2076)) where I asked for an option to disable automatically adding NVM to my `.zshrc` because this module already do this. So I would like to know what the purpose of this module is to not check if it is already loaded or what recommend way is to install NVM and use the module together without removing the lines added to my `.zshrc`?

### Expected behavior

Check if NVM is loaded, if not source it.

### Actual behavior

Sources it twice on clean install of NVM because NVM installer script adds the same lines to `.zshrc`.

### Steps to Reproduce

1. Clean install of NVM via install.sh script
2. Enable prezto module `node`

### Versions

  - Prezto commit: idk how to get this, I use the latest I guess
  - ZSH version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
  - OS information: 10.14.5

**Comment by belak** [comment]
The simplest solution is to just remove that line from your zshrc. Alternatively, it might be reasonable to add a check somewhere in prezto to only load nvm if it hasn't already been loaded. I don't use nvm, so I don't know the best way to check that. PRs would be welcome!

**Comment by muuvmuuv** [comment]
That is what I have done at that time, I just [installed it via git](https://github.com/nvm-sh/nvm/blob/master/README.md#git-install) and that worked for me. So I'll close this in favor of the issue I have opened on their side where they will keep it open to track it for future features.
