### ISSUE TITLE
[Question] How to disable underline on command found

### ISSUE THREAD

**Issue by kud** [sorin-ionescu/prezto#1729]
Hey,

I'm not sure where it comes, I think it's from `syntax-highlighting` but how do you get rid of the underline when the command is found?

<img width="276" alt="image" src="https://user-images.githubusercontent.com/655838/62134399-af997900-b2e0-11e9-830b-d524619162fd.png">

thank you :)

**Comment by kud** [comment]
weird thing, it doesn't always happen on command. I don't know where it comes from in fact.

**Comment by kud** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/655838/62134793-6bf33f00-b2e1-11e9-8dcc-740da808cbb8.png">

**Comment by Matir** [comment]
`shell-reload` is a function, `git` is a command.  See https://github.com/zsh-users/zsh-syntax-highlighting/tree/master/highlighters/main for information about the highlighters.

**Comment by kud** [comment]
Thank you @Matir !
