### ISSUE TITLE
What is the meaning of "✘ ..." in the default prompt?

### ISSUE THREAD

**Issue by clmay** [sorin-ionescu/prezto#1743]
When running commands, there is a red "✘" followed by a number that varies, at the right edge of the terminal prompt line. What does it mean?

**Comment by belak** [comment]
It's related to the return value of the previously run command. If there was an error, the X will show up and the return code should be displayed.

**Comment by clmay** [comment]
Is that documented anywhere?

**Comment by belak** [comment]
Not explicitly. And this isn't the first time someone has asked. I'm not sure where we'd put the documentation because I'd like to avoid writing something about every feature of every prompt.

**Comment by clmay** [comment]
Hmm, that does seem like an issue. Are the themes vendored in from other repos, or are they all maintained in prezto?

**Comment by belak** [comment]
It's a mix. Some of them are maintained in prezto, others are included as submodules.

**Comment by jeffwidman** [comment]
I think for now we should close this... documenting what all the themes do is a task that we are unlikely to ever do unless someone stepped up and really owned it. Even if we limit the scope to non-vendored ones, it's unlikely to happen.
For now just consider it a bunch of easter eggs where you discover over time what stuff means. It's how I learned (and am still learning) the sorin prompt myself.
