### ISSUE TITLE
Permission error with macOS Catalina

### ISSUE THREAD

**Issue by mkonikov** [sorin-ionescu/prezto#1745]
# Description
Getting this error message after every command
```
prompt_sorin_async_callback:4: can't create temp file for here document: permission denied
```

### Steps to Reproduce

1. Upgrade Catalina
2. Open terminal

### Versions

  - Prezto commit: 2873885
  - ZSH version: 5.7.1
  - OS information: macOS 10.15

**Comment by mkonikov** [comment]
Seems running `sudo chmod 777 /private/tmp` may fix this.

**Comment by srijanshetty** [comment]
@mkonikov: If the issue is fixed, should I close the issue?

**Comment by mkonikov** [comment]
Sure

**Comment by srijanshetty** [comment]
Thanks a lot @mkonikov
