### ISSUE TITLE
command not found: zprezto-update

### ISSUE THREAD

**Issue by xfq** [sorin-ionescu/prezto#1747]
### Description

I can execute `zprezto-update` in the interactive shell, but in a script like the following one:

```
#!/bin/zsh

zprezto-update
```

zsh emits the following error:

```
./update.sh:3: command not found: zprezto-update
```

I guess `zprezto-update` is only available for the interactive shell, but not shell scripts. How should I fix this issue? Thanks!

### Versions

  - Prezto commit: https://github.com/sorin-ionescu/prezto/commit/2873885d37e362ae9be8ff4cb93ae36739ac0067
  - ZSH version: zsh 5.7.1 (x86_64-apple-darwin19.0.0)
  - OS information: macOS 10.15

**Comment by lodagro** [comment]
See [zsh startup files](http://zsh.sourceforge.net/Intro/intro_3.html).

**Comment by belak** [comment]
Good question! It should be possible to source the prezto init file in a shell script. That would make zprezto-update available to that shell. Please let us know if you have any further questions.
