### ISSUE TITLE
change alias gs as it is executable for ghostscript (\usr\bin\gs)

### ISSUE THREAD

**Issue by mayanksuman** [sorin-ionescu/prezto#1762]
### Description
The alias of `git stash` is `gs`, however `\usr\bin\gs` is executable for `ghostscript`. 

### Expected behavior
With command `gs`, `ghostscript` (if installed) should open up.

### Actual behavior
With command `gs`, `git stash` is carried out.

### Steps to Reproduce

1. Install `ghostscript` and setup `prezto`
2. Issue `gc` command in terminal

**Comment by mayanksuman** [comment]
This is a known issue. I forgot to read REAME.md first. Closing it now.

**Comment by kud** [comment]
For those who read this issue and don't want to check the README, just use `/gs` to bypass the alias.
