### ISSUE TITLE
HISTFILE defaults to .zhistory rather than .zsh_history

### ISSUE THREAD

**Issue by tekumara** [sorin-ionescu/prezto#1766]
### Description

When migrating from oh-my-zsh I lost my history and didn't initially understand why.

oh-my-zsh uses `.zsh_history` for history, see [lib/history.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/history.zsh#L29)

### Expected behavior

By default, without configuration, I should be able to continue using my existing history file `.zsh_history`.

### Actual behavior

The prezto history modules defaults `HISTFILE` to `.zhistory`

### Versions

  - Prezto commit: 2d6205e71404704eecc4f402e5b09d7cbd19bab7
  - ZSH version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
  - OS information: macOS 10.14.6

**Comment by belak** [comment]
Thanks for the feedback! Unfortunately, I don't think we will end up doing this... it doesn't make sense to support an alternative default location for the HISTFILE because we're two different frameworks. If you want to use a different HISTFILE, you can set that variable manually. We honor that variable when it is manually set.

I'd also rather optimize for usage rather than setup... and I don't want to introduce either a dynamic HISTFILE variable that changes depending on which files exist... or change the default to something other than what our users have had for many years.

**Comment by tekumara** [comment]
Maybe a note in `modules/history/README.md` would help avoid surprises?

**Comment by belak** [comment]
That seems reasonable. Might even be good to have a “migrating from OMZ doc”.

**Comment by belak** [comment]
Added some basic documentation to `modules/history/README.md`. Thanks for the suggestion!

**Comment by tekumara** [comment]
Thanks @belak !

**Comment by tekumara** [comment]
FYI: `${ZDOTDIR:-$HOME}/.zsh_history` is also the default set on macOS in `/etc/zshrc`

**Comment by belak** [comment]
Ah, interesting, it might be worth changing then. Thanks for following up!

**Comment by tekumara** [comment]
👍 

I did a little more research and took a look at ubuntu. History saving isn't configured out of the box, but the recommendation is `~/.zsh_history` too, see [/etc/zsh/newuser.zshrc.recommended](https://www.apt-browse.org/browse/ubuntu/bionic/main/all/zsh-common/5.4.2-3ubuntu3/file/etc/zsh/newuser.zshrc.recommended)

**Comment by srijanshetty** [comment]
Now that I recall, this did trip me when I first installed prezto. Probably, because I was migrating from OMZ.

**Comment by indrajitr** [comment]
This has been clarified further in #1896 for macOS. However, given that `.zsh_history` is more prevalent (macOS, Debian variants), we might probably consider making `.zsh_history` the default in prezto as well (with a one-time migration path for `.zhistory` -> `.zsh_history`).

/cc @belak, @jeffwidman, @johnpneumann

**Comment by jeffwidman** [comment]
Who says peer pressure isn't a thing?! 😜 

When in Rome, do as the Romans do, so I'm also in favor of flipping to `.zsh_history`.

This one might be worth a deprecation message. 😉 

We could probably check for `.zsh_history` and use it if present. And then if it doesn't exist, check for `.zhistory` and if present us that after throwing a deprecation message along the lines of:
> `prezto` is changing the default history location to `.zsh_history` (rationale in issue 1766). Please migrate by renaming your `.zhistory` file to `.zsh_history`. 

And if neither is present, then assume it's a brand-new install and use `.zsh_history`...

Thoughts?

**Comment by indrajitr** [comment]
Yep, something along those lines. Additionally, we should check for recency.
