### ISSUE TITLE
file exists error when redirecting to an existing file

### ISSUE THREAD

**Issue by tekumara** [sorin-ionescu/prezto#1767]
### Description
file exists error occurs when redirecting outpout to an existing file

### Expected behavior

When redirecting output, overwrite any existing file (like the default zsh, and oh-my-zsh behaviour) 

### Actual behavior

```
$ echo foo > /tmp/delme
$ echo bar > /tmp/delme
zsh: file exists: /tmp/delme
```

### Versions

  - Prezto commit: 2d6205e71404704eecc4f402e5b09d7cbd19bab7
  - ZSH version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
  - OS information: macOS 10.14.6

Prezto modules loaded: 'environment' 'terminal' 'editor' 'history' 'directory' 'spectrum' 'utility' 'completion' 'prompt' 'git'

**Comment by srijanshetty** [comment]
If you look at 'directory' module, it configures `unsetopt CLOBBER`. This leads to a files exists error. You can use `setopt CLOBBER` to allow overwritting existing files.
