### ISSUE TITLE
no history search, history-incremental-search-backward

### ISSUE THREAD

**Issue by jassinm** [sorin-ionescu/prezto#177]
hi ,

first thanks for this version of oh-my-zsh

I m having problems with the history search. 

History search always falls back to fwd-i-search (failing fwd-i-search)

I tried this:
   zsh -f
   bindkey '^R' history-incremental-search-backward

and this works as expected.

doing:
   zsh -f 
   bindkey '^R' history-incremental-search-forward

behave like oh-my-zsh.

How can i get backward-search working?

I m using vi's keymap (//)

Thanks

uname -a:
11.4.0 Darwin Kernel Version 11.4.0: Mon Apr  9 19:32:15 PDT 2012; root:xnu-1699.26.8~1/RELEASE_X86_64 x86_64

zstyle ':omz:module:editor' keymap 'vi'
zstyle ':omz:module:editor' dot-expansion 'no'
zstyle ':omz:_:_' case-sensitive 'no'
zstyle ':omz:_:_' color 'yes'
zstyle ':omz:module:terminal' auto-title 'yes'
zstyle ':omz:load' omodule 'environment' 'terminal' 'editor' 'completion' \
  'history' 'directory' 'spectrum' 'alias' 'utility' 'prompt' 'osx' 'git' 'tmux'

**Comment by aeustace** [comment]
I have the same issue as @danielpcox.

My use case:

I have issued the command: "grails test-app -integration <SomeFile>" several times during the day, where <SomeFile> is different on each invocation.

I want to issue it again, but can't remember the exact name of <SomeFile>, but I'll recognise it when I see it.

So, I enter bck-i-search mode, type 'integ' which matches on the most recent invocation of the command. 

Next, I want to cycle through my history matching on 'integ' to find the invocation I want.

How do I do this in Vi mode?

**Comment by aeustace** [comment]
Sorted it, the following at least allows you to use ctrl R to search on incremental patterns:
 bindkey '^R' history-incremental-pattern-search-backward

**Comment by sorin-ionescu** [comment]
The history-substring-search module is superior. Use that.

**Comment by aeustace** [comment]
I'm using that module, but it doesn't seem to work for my use case in Vi mode.

**Comment by sorin-ionescu** [comment]
In vi, you have to go into command mode then press j/k.

**Comment by aeustace** [comment]
That doesn't work. 
My flow, step by step:
- in shell, enter command mode (with 'esc') and type '?'
- am presented with 'bck-i-search'
- start typing, e.g. 'git'
- now if I type j/k, the cursor jumps out of search mode, i.e. the prompt 'bck-i-search' disappears, and j and k just cycle through my recent command history, not through the results as filtered by the initial incremental search.

**Comment by fuadsaud** [comment]
Just type `git` then `<up-arrow>` while in insert mode.

**Comment by aeustace** [comment]
That doesn't work either, when I type `<up-arrow>` it just cycles through recent commands, rather than doing it based on the incremental search.

**Comment by jesk78** [comment]
It doesnt work for me either. When you insert your search string neither 'up/down'-arrows nor j/k works to jump to the next hit. In insert-mode j/k gets entered and arrows exit the search and in cmd-mode j/k just do nothing and arrows exit the search again.

**Comment by SinAHal** [comment]
If anyone finds this thread after having a similar issue like I did here are the steps I took:
- enter bck-i-search mode (press escape and then ?)
- after typing in search, press escape
- then you can press n and shift-n to browse results
