### ISSUE TITLE
Delete word behaviour differs from oh-my-zsh

### ISSUE THREAD

**Issue by tekumara** [sorin-ionescu/prezto#1774]
### Description

CTRL+W will erase to the previous space, but will not erase to the previous hyphen or dot. 

### Expected behavior

Like oh-my-zsh, `backward-kill-word` would erase to the previous hyphen or dot.

### Steps to Reproduce

1. Type `the quick-brown.fox`
2. Press CTRL+W and `quick-brown.fox`will be deleted.

In oh-my-zsh, only the word `fox` will be deleted, and then `brown.`, and then `quick` when pressing CTRL+W again.

### Versions

  - Prezto commit: `0b669d2`
  - ZSH version: `zsh 5.7.1 (x86_64-apple-darwin18.2.0)`
  - OS information: macOS

**Comment by tekumara** [comment]
prezto [uses](https://github.com/sorin-ionescu/prezto/blob/5566a9c7927ed1ee166e92f8ecb72aa7a2d0ce09/modules/editor/init.zsh#L24):
```
WORDCHARS='*?_-.[]~&;!#$%^(){}<>'
```

oh-my-zsh [uses](https://github.com/ohmyzsh/ohmyzsh/blob/547a6ce260362b06e86a9c366dc29984c0954124/lib/completion.zsh#L4):
```
WORDCHARS=''
```

**Comment by belak** [comment]
I unfortunately don't think this will change. Prezto was created as a set of defaults and convenient modules, not to be a direct clone of OMZ. Thankfully, it should be easy to override.
