### ISSUE TITLE
async_job:zpty:12 no such pty command: prompt_sorin

### ISSUE THREAD

**Issue by lhaus** [sorin-ionescu/prezto#1795]
Same issue as #1736 but on sorin prompt

  - Prezto commit: e9f281cd6f62983f44faaae0816866d13bc1474e
  - ZSH version: 5.8 (x86_64-pc-linux-gnu)
  - OS information: Arch Linux 5.5.3

**Comment by akullpp** [comment]
Same issue, same setup as @lhaus

**Comment by ackerleytng** [comment]
Same here,

+ Prezto commit 4bcbe2
+ zsh 5.8 (x86_64-pc-linux-gnu)
+ 5.5.4-arch1-1

**Comment by avivace** [comment]
Try https://github.com/sorin-ionescu/prezto/issues/1736#issuecomment-590056573

**Comment by belak** [comment]
Can you try the code in https://github.com/sorin-ionescu/prezto/pull/1805 and let me know if that fixes the issue for you? It's a brand new implementation which doesn't use zsh-async at all.
