### ISSUE TITLE
no such keymap `menuselect'

### ISSUE THREAD

**Issue by yanzhang0219** [sorin-ionescu/prezto#1798]
In my zshrc, I set

```
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
```

but I got `.zshrc:bindkey:84: no such keymap `menuselect'`

I tried to put these lines to different places of my zshrc, but it didn't work. Please help. 

Thank you.

**Comment by wadkar** [comment]
Not sure, but did you enable `zstyle ':completion:*' menu select` before that?

I am not sure if this is related to prezto but your specific configuration. A simple search on the internet would lead you [here](https://unix.stackexchange.com/a/323282) , and I am sure you can make use of those websites to help you resolve your issue quickly.

**Comment by yanzhang0219** [comment]
I just put these four lines into the zshrc which prezto generated and I don't have any other configurations. If I didn't use prezto, i.e., removed the top lines that prezto added, I wouldn't have this issue. 

Thanks.

**Comment by wadkar** [comment]
Huh? I am not aware if things changed recently, but prezto doesn't generate the zshrc file.

I just checked my config and I didn't need to put those lines. I just have [this line](https://github.com/wadkar/pseudo/blob/66a0e2af27dbbca7d71b0b73a0035a3e396e9b87/zsh/zpreztorc#L24) and `jk` works like up/down in normal mode for completion and I use `w/b` for completing words/erasing them.

I strongly suggest you find someone on chat/irc/gitter/reddit to clarify your situation. As the issue doesn't seem to be reproducible. I am afraid there's not much I can help you here.

**Comment by yanzhang0219** [comment]
Okay that's my fault. I have figured it out. Thank you! 
Closing this.

**Comment by spiritastir** [comment]
@rockyzhang24 I have same issue. What was your solution?

**Comment by rockyzhang24** [comment]
@spiritastir Sorry I truely can't recall what I did back then. I remember that shortly after, I quickly switched to using [zimfw](https://github.com/zimfw/zimfw). It's lightweight but powerful enough. If you're interested, please refer to [my zsh config](https://github.com/rockyzhang24/dotfiles/tree/master/.config/zsh). Thanks.

**Comment by brandon-fryslie** [comment]
I found this while trying to figure out why the heck prezto deletes all of a user's keymaps.  I can bet that's the root cause of this.  Specifically this line here: https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh#L271

I'm not asking a technical why, but moreso what motivation is behind this?  It certainly causes some issues if prezto manages to get loaded after user plugins.
