### ISSUE TITLE
Is setting up default shell on Catalina still necessary?

### ISSUE THREAD

**Issue by idkjs** [sorin-ionescu/prezto#1807]
Question about setup.

Is setting up default shell on Catalina still necessary per #4 on Readme instructions since the default shell is `zsh`?

Thank you

**Comment by wadkar** [comment]
Short answer: No, you can skip it.

Long answer: Executing the command should be a NOOP for Catalina users. It's fairly harmless to set the default shell back to the same value.

For users who `brew install zsh` they should set a default shell to `chsh -s /usr/local/bin/zsh`.

**Comment by idkjs** [comment]
Thank you, sir.
