### ISSUE TITLE
source command inside the .zpreztorc is not executed unless called explicitly

### ISSUE THREAD

**Issue by Pouya-moh** [sorin-ionescu/prezto#1809]
### Description
I have a line in my .zpreztorc: `source ~/.personal_setup`. In my most recent installation this file doesn't get executed. I have similar file in my other machines and there is no problem. Currently at the head of the master branch this doesn't work. If I do `source ~/.zpreztorc` manually, then it works. 

Note that I have other lines in `.zpreztorz` (e.g., adding to path) which are getting executed but not that `source` command.

### Versions

  - Prezto commit: d955fbdeb729ed038ffa7af16c1cf82dd68aff1e (the problem persists after `git pull`)
  - ZSH version: 5.7.1
  - OS information: Ubuntu 19.10

**Comment by belak** [comment]
Unfortunately, I'm not sure what's going on here. We make sure to execute the `.zpreztorc` file if it exists (https://github.com/sorin-ionescu/prezto/blob/d955fbdeb729ed038ffa7af16c1cf82dd68aff1e/init.zsh#L170-L172).

Is there any way you can post your zshrc?

**Comment by srijanshetty** [comment]
As a side note, I tend to keep all source commands in .zshrc or a custom module so that I can separate out prezto related settings from my own opinionated zsh setup.

**Comment by Pouya-moh** [comment]
Actually this is what I am trying to do. My personal settings, e.g., my aliases in a separate file. But that separate file is not getting soruced from the zpreztorc...

**Comment by srijanshetty** [comment]
Hey @Pouya-moh, I noticed some odd behaviour, can you use absolute pathname `source '/home/user/filename.zsh'` instead of `source '~/filename.zsh'`?

**Comment by Pouya-moh** [comment]
Hi @srijanshetty. Thanks for the suggestion. I tried all of the following and none worked:
```

source ~/.personal_stuf
source /home/myUser/.personal_setup
source $HOME/.personal_setup
source "${ZDOTDIR:-$HOME}/.personal_setup"
```
If I do `source ~/.zpreztorc` manually then all those commands work. My other commands in the `.zpreztorc` actually works automatically (e.g., setting path).

**Comment by Pouya-moh** [comment]
I think I found the source of my problems. Here it goes: `.personal_setup` consisted of mainly my aliases. It seems in `init.zsh`, after these lines:
https://github.com/sorin-ionescu/prezto/blob/d955fbdeb729ed038ffa7af16c1cf82dd68aff1e/init.zsh#L170-L172
prezto sets some other modules/functinos which overwrite my aliases. Which means, I cannot set any aliases in `.zpreztorc` which kinda sucks...

But thanks anyway for your time and support. I really appreciate (Y).

**Comment by srijanshetty** [comment]
I would suggest creating a module as [such](https://github.com/srijanshetty/cli-goodies). I place this module in .zpreto-contrib and load it at last which ensures that my personal aliases always override that of prezto.

**Comment by srijanshetty** [comment]
Also, if I understand correctly now, it's not a matter of not being able to source the file but your aliases being overriden?

**Comment by Pouya-moh** [comment]
> Also, if I understand correctly now, it's not a matter of not being able to source the file but your aliases being overriden?

That is correct. Actually I was able to identify the issue when I added bunch of meaningless `echo`s in my personal_stuff file and saw them appear in the command line.

> I would suggest creating a module as such.

Fair enough, although, I find it kinda awkward to go this length to have a simple alias. Also I can imaging other situations where this could become problematic...

**Comment by belak** [comment]
@Pouya-moh for simple tweaks like aliases, you can put them in your zshrc, after prezto is loaded. This will ensure they override whatever prezto has defined.

While we officially say to symlink the [runcoms](https://github.com/sorin-ionescu/prezto/tree/master/runcoms), these files do not get many changes, so it's generally fine to copy them. In particular, the zshrc is kept intentionally simple for this reason. This is actually what I do in my config. The old advice was to fork prezto and modify the runcoms directly, but it is generally much simpler to have your own zshrc.

**Comment by Pouya-moh** [comment]
I see your point. Thanks a lot @belak. I close the issue if you have no objection.

**Comment by srijanshetty** [comment]
@Pouya-moh: agree, that it's a bit convoluted for simple aliases.

> This is actually what I do in my config.

I follow this advice myself, I don't edit anything in prezto except zpreztorc so that merging is easy.
