### ISSUE TITLE
Multiple visual issues with prezto

### ISSUE THREAD

**Issue by anku94** [sorin-ionescu/prezto#1813]
# Description
My prezto setup on a remote server has multiple visual issues.

1. Tab completion introduces weird tabs
![Screen Shot 2020-04-01 at 10 19 41 PM](https://user-images.githubusercontent.com/1752503/78204191-f094ef00-7466-11ea-8eed-67f2a1af40e2.png)

2. Cursor randomly starts overlapping with the prompt after a failed command
![Screen Shot 2020-04-01 at 10 20 57 PM](https://user-images.githubusercontent.com/1752503/78204256-24701480-7467-11ea-9c49-7d35d38205e9.png)

3. At some point, autocomplete suggestions would start overlapping with my actual command. I can't seem to replicate that now.

4. Special characters do not appear correctly in tmux
![image](https://user-images.githubusercontent.com/1752503/78204479-9b0d1200-7467-11ea-9c41-fb999b14b3e4.png)

### Expected behavior

No visual artifact issues.

### Actual behavior

Weird visual artifacts. This started happening after the OS images on the compute cluster were updated.

I have tried installing fonts-powerline, both via apt and from the repo, but that doesn't seem to be fixing the problem

### Steps to Reproduce

Regular operation - use tmux, use autocomplete, or type a command with a non-zero return code.

### Versions

  - Prezto commit: 5b03d7fa32cae51cee7903d3338f87c2d7d89657
  - ZSH version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
  - OS information: Ubuntu 18.04.1 LTS

**Comment by belak** [comment]
Can you confirm what terminal you're using and what the value of $TERM is both inside and outside tmux? Mismatches there often cause glitches like these.

**Comment by belak** [comment]
Also which prompt is that?

**Comment by anku94** [comment]
Outside of tmux, TERM is `xterm-256color`, and inside it's `screen-256color`.

The prompt is `sorin`, I think? (`zstyle ':prezto:module:prompt' theme 'sorin'`)

**Comment by belak** [comment]
Which terminal are you actually using?

**Comment by anku94** [comment]
The actual terminal is iTerm2 on OSX Catalina 10.15. I use prezto locally as well, and never had a problem locally.

**Comment by anku94** [comment]
Also, I should've added that the remote image isn't vanilla Ubuntu 18.04, and might have undergone some modifications for deployment on the cluster.

**Comment by anku94** [comment]
I did a bunch of tinkering around with fonts, LOCALE etc, and it seems to have been fixed :) Closing.

**Comment by anku94** [comment]
Just something to make note of:

`oh-my-zsh` has a hint in its zshrc template to set the LOCALE appropriately. No such hint appears in any prezto docs, and may be useful for folks encountering similar issues.

    # You may need to manually set your language environment
    # export LANG=en_US.UTF-8
