### ISSUE TITLE
RFC: replace fasd with zoxide

### ISSUE THREAD

**Issue by vbauerster** [sorin-ionescu/prezto#1814]
I used to use `fasd` module until recently I discovered [zoxide](https://github.com/ajeetdsouza/zoxide) tool. It serves the same purpose as `fasd` and can replace built-in `cd`, so why not include it or replace `fasd` with `zoxide`?

**Comment by srijanshetty** [comment]
We're not adding new modules to prezto core, you're free to include in your own contrib folder.

**Comment by belak** [comment]
We would also accept this in the semi-official contrib repo. Thanks for bringing it up!

**Comment by vbauerster** [comment]
Adding it manually was pretty easy.
Can you please point where is that semi-official contrib repo?

**Comment by belak** [comment]
https://github.com/belak/prezto-contrib/

**Comment by huyz** [comment]
Now that `fasd` has been archived by the author, it might be a good idea to revisit the idea of replacing it
