### ISSUE TITLE
homebrew module regression

### ISSUE THREAD

**Issue by pmarschik** [sorin-ionescu/prezto#1815]
Commit f4ca9ebfc913453f98ba6912a8c42684fd742cc1 introduced a regression in the homebrew module where it won't load.

Originally the bail-out code was:
```zsh
if [[ "$OSTYPE" != (darwin|linux)* ]]; then
  return 1
fi
```

The regression is:
```zsh
if ! is-darwin || ! is-linux; then
  return 1
fi
```

Fix:
```zsh
if ! is-darwin && ! is-linux; then
  return 1
fi
```

**Comment by srijanshetty** [comment]
Ah! Thanks for pointing it out, will create a PR or do you want to do the needful?

**Comment by zmb3** [comment]
I'm still seeing:
```
command not found: is-darwin
command not found: is-linux
```

When loading the homebrew module.

I believe modules/homebrew/init.zsh is missing a `pmodload 'helper'`, so depending on which modules you're loading and the order you load them in, it's possible that the helper functions are not available when the homebrew module is loaded.
