### ISSUE TITLE
Command not found _m

### ISSUE THREAD

**Issue by Fenwick17** [sorin-ionescu/prezto#1817]
### Description
Every now and again I get a few issues with default commands not working with autocomplete, in this case `mv` leads me to get an error `command not found: _mv`
I have found a way round this issue by doing `rm -rf ~/.zcompdump*` but this is only temporary as the issue seems to just occur again

### Expected behavior
To be able to autocomplete file with `mv`

### Actual behavior
Throws error when pressing tab after `mv`

### Steps to Reproduce

1. In my terminal type `mv`
2. Press tab

### Versions

  - Prezto commit: 95ff0360aeef951111c5ca6a80939e9329ddb434
  - ZSH version: zsh 5.8
  - OS information: OSX Mojava 10.14.6

**Comment by srijanshetty** [comment]
I'm unable to reproduce the bug on my Ubuntu setup. What plugins have you enabled?

**Comment by Fenwick17** [comment]
Currently I have 
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt' \
  'ssh' \
  'homebrew' \
  'osx' \
  'git' \
  'syntax-highlighting' \
  'history-substring-search' \
  'contrib-prompt' \
```
If I run my fix the problem goes away, then just randomly shows up again so struggling to identify the cause

**Comment by srijanshetty** [comment]
I still haven't been able to repro the issue, but I do run `rm -f ~/.zcompdump; compinit` everytime I update all my dependencies including zsh and various completion files. I did it originally because newer completions weren't working and is related to #1778

**Comment by srijanshetty** [comment]
@Fenwick17 do you still have this issue, I did an upgrade and ran into it. This was a one time issue solved by removing `~/.caches/prezto/zcompdump*`
