### ISSUE TITLE
Theme 'sorin' after fresh zsh and prezto install not showing git info or user-,machine-name

### ISSUE THREAD

**Issue by DavidS3141** [sorin-ionescu/prezto#1818]
### Description
I just started using `zsh` and directly installed `prezto` before doing anything. Following this [page](http://jr0cket.co.uk/2013/09/hey-prezto-zsh-for-command-line-heaven.html) but also the README from this project!
Somehow both sources say, that I should end up with a more informative prompt than I am currently experiencing. Other users seem to have experienced this before mentioned in the issues #788, #882 but I found no useful information to fix this issue for me.

### Expected behavior

After doing the installation and adding the `git` module (see exact steps [below](#steps-to-reproduce)) I expected a prompt similar to the own shown in the README.
![https://camo.githubusercontent.com/612c6be742478221e06c64b66b896085f6e4af63/687474703a2f2f692e696d6775722e636f6d2f6e7247563670672e706e67](https://camo.githubusercontent.com/612c6be742478221e06c64b66b896085f6e4af63/687474703a2f2f692e696d6775722e636f6d2f6e7247563670672e706e67)

### Actual behavior

As both issues linked in the description, I also have the following prompts (first one outside of a git repo, second one inside a git repo):
![image](https://user-images.githubusercontent.com/6333870/78671648-d718fa80-78df-11ea-8e46-7f8b74ff8187.png)
![image](https://user-images.githubusercontent.com/6333870/78671701-ec8e2480-78df-11ea-8a63-650aecc8fbf9.png)
It seems like git information are missing, but more importantly, the user and machine name are not shown.

### Steps to Reproduce

As I did a clean install of prezto including zsh, these were the steps I did.
1. `sudo apt install zsh`
2. Following exactly the 5 steps from the README Installation part of this repo.
3. Setting the Gnome Ubuntu Terminal cmd for my profile to default to `zsh` instead of `bash`. (see image)
![image](https://user-images.githubusercontent.com/6333870/78672631-36c3d580-78e1-11ea-88e1-e96cb97d8b69.png)
4. Like mentioned on the linked article and also mentioned in your README under "Themes", I added the `git` module to the `.zpreztorc` file.

(5.) Now I was under the impression everything should work.

### Versions

  - Prezto commit: 95ff036
  - ZSH version: zsh 5.7.1 (x86_64-ubuntu-linux-gnu)
  - OS information: Ubuntu 19.10

**Comment by TLecailtel** [comment]
Hey David, the `git` information seems to display correctly on your screenshot. I believe the white square means that your `git status` is only mentioning some untracked file(s).

About the username and machine name, I believe the 'sorin' prompt theme is supposed to show them only when the `SSH_TTY` variable is set, i.e. when you're in an SSH session.

If you want to show them even when not in an SSH session, you can create your own theme in `~/.zprezto/modules/prompt/functions/`, copy all the code from `prompt_sorin_setup`, and only modify the `PROMPT` line by removing the `SSH_TTY` condition. Also make sure your `.zpreztorc` file uses your newly created theme.

I've just done it for myself [in this commit](https://github.com/TLecailtel/dotfiles/commit/b79fd5c42998778feee720e7a97656e03b4373ad) if you want an example.

**Comment by srijanshetty** [comment]
@DavidS3141, as @TLecailtel correctly mentions, the git information is contextual. If you're in a merge conflict it should show merge, and depending the state of your working copy it can show files which are not tracked, differ from stage, differ from HEAD etc.

@TLecailtel also correctly mentions that username and machine name are shown only when SSH_TTY is set. I used a hack to show it by `export SSH_TTY=1`.

In view of the above, I'll close this issue. Please re-open it if something is unclear!
