### ISSUE TITLE
Resetting the prompt

### ISSUE THREAD

**Issue by fniessen** [sorin-ionescu/prezto#1823]
Dear @sorin-ionescu , seeing the impressing Zsh config, and knowing that I also face the problem stated at https://stackoverflow.com/questions/61075356/zle-reset-prompt-not-cleaning-the-prompt, I'm wondering if you would have a solution for it?

Best regards,
Fabrice

**Comment by romkatv** [comment]
Try this: https://github.com/romkatv/zsh4humans/blob/2328d741e0d2987084e5f15b8bc91a1b909fed3f/z4h.zsh#L643-L651

**Comment by fniessen** [comment]
Dear @romkatv ,

    # Widgets for changing current working directory.
    z4h-redraw-prompt() {
        emulate -L zsh
        local f
        for f in chpwd $chpwd_functions precmd $precmd_functions; do
            (( $+functions[$f] )) && $f &>/dev/null
        done
        zle .reset-prompt
        zle -R
    }

    # C-M-u: up-directory
    up-directory() {
        builtin cd .. && z4h-redraw-prompt
    }
    zle -N up-directory
    bindkey '\e\C-u' up-directory

does exactly what I was asking for -- even if I don't understand most of it ;-)

Thanks A LOT!!!
