### ISSUE TITLE
cd tab not working

### ISSUE THREAD

**Issue by yakerw** [sorin-ionescu/prezto#1829]
After type cd and the click tab will get these errors:

```
cd ..._cd:73: bad math expression: operator expected at `tmpcdpath '  
_alternative:shift:14: shift count must be <= $#
_setup:64: bad output format specification
_cd:73: bad math expression: operator expected at `tmpcdpath '
_alternative:shift:14: shift count must be <= $#
_setup:64: bad output format specification
_cd:73: bad math expression: operator expected at `tmpcdpath '
_alternative:shift:14: shift count must be <= $#
```

use vi  + tab, it will have these errors:
```
vi ...(anon):4: command not found: _filedir_xspec    
(anon):4: command not found: _filedir_xspec
(anon):4: command not found: _filedir_xspec
```

other commands like cp/mv works fine

The problem is still there even I reinstall everything.
It starts from I forcefully restart my mac.

### Steps to Reproduce

1. [First Step] cd
2. [Second Step] tab

### Versions

  - Prezto commit: latest version
  - ZSH version: 5.8
  - OS information: mac Majove (Still same issue after I upgrade to mac Catalina)

**Comment by srijanshetty** [comment]
@yakerw does the issue still persist. Could you kindly provide the exact version of prezto and whether you have any alias defined for cd?

**Comment by yakerw** [comment]
Yes. It is still there. I used the latest version of prezto and the problem still there. I switched back to oh-my-zsh..

**Comment by vitorscassiano** [comment]
I have the same problem, it started when I updated my zsh to the current version (zsh 5.8 (x86_64-apple-darwin20.0)).

**Comment by srijanshetty** [comment]
@vitorscassiano @yakerw using 5.8.1 and I can't repro this. Can you update and try it out?
