### ISSUE TITLE
Replace or add new history module for mcfly history

### ISSUE THREAD

**Issue by muuvmuuv** [sorin-ionescu/prezto#1834]
### Description

I have recently discovered this shell script here which is awesome for history searching. I think this would be great to have as a prezto module.

https://github.com/cantino/mcfly

Maybe the current history module can be replaced with it or kept as a fallback for `history-advanced`

**Comment by srijanshetty** [comment]
Hey @muuvmuuv, we're currently not accepting new modules but you can always add them to [unofficial contrib modules](https://github.com/belak/prezto-contrib).

The plugin looks cool. I personally use [fzf](https://github.com/junegunn/fzf) and history-substring-search which have given me decent mileage hitherto.

I'll close this comment for now. Cheers!
