### ISSUE TITLE
Feature suggestion: git alias for pull with autostash

### ISSUE THREAD

**Issue by alextes** [sorin-ionescu/prezto#1835]
### Description
`alias gfma='git pull --autostash'`

I have been using this alias for years, and regularly use it.

Do other people maybe feel the same (👍)? Interested in having it in the git module's aliases?

**Comment by srijanshetty** [comment]
TIL. Added it to my personal aliases, I'm curious why you've name it `gfma`.

**Comment by alextes** [comment]
My thinking was `gfm`, the alias for `git pull`, plus `--autostash`, take the first letter from that flag and you have `gfma`.

I also realized I didn't explain at all what I use `git pull --autostash` for.

1. I have a dirty worktree, I want to continue work based on the latest version. Git doesn't let you pull in that state. Even if you're confident your changes won't conflict. In stead of having to stash, pull, unstash, or create a commit with your half-done work you can use autostash.

2. Dirty working tree, I do know my changes are going to conflict with what's been pushed, but rather than continuing my work and solving the conflicts in a later rebase or merge, I want to resolve the conflicts now and create commits or rather code, that doesn't conflict with anything.

**Comment by diraol** [comment]
Dude, I have to say that I loved knowing about this flag!!! Thanks for it!

Also, I have to say that I never liked `gfm` anyway. lol

Here it is the PR for this: https://github.com/sorin-ionescu/prezto/pull/1836

**Comment by srijanshetty** [comment]
I've been using `git pull --autostash` a lot and I think it's of great use. My only contention is what should be a good alias. I'm approving the commit.

**Comment by alextes** [comment]
Yea I'm guessing git fetch merge = git pull = 'gfm' but it appears more natural to have aliases like git pull is 'gp' and git pull autostash would be 'gpa'. The natural question becomes what do you do with conflicts. 'git push' in this case. 

Even the middleground option of sticking with the 'gf' is for actions to do with fetching and adding an 'a' for autostash leads to 'gfa' which is already 'git fetch --all'.

Perhaps there are better suggestions I've missed.
