### ISSUE TITLE
How can I unistall Prezto

### ISSUE THREAD

**Issue by wonderer007** [sorin-ionescu/prezto#1840]
Extremely sorry but this is one of the most shittest tools I ever used, can anyone let me know how to get rid of this ????????

#Shit

**Comment by belak** [comment]
Hello! Sorry to hear you had a bad experience. If you have more specifics about what you didn't like, I'd be interested to hear - we're always looking to improve the overall experience.

Thankfully, if you followed the installation method listed in the README, removing the following symlinks will uninstall prezto:

- `$HOME/.zshrc`
- `$HOME/.zpreztorc`
- `$HOME/.zprofile`
- `$HOME/.zlogin`
- `$HOME/.zlogout`
- `$HOME/.zshenv`
