### ISSUE TITLE
On Ubuntu 20.04 with pyenv, the system version has only pip2/pip3 and the Python module fails

### ISSUE THREAD

**Issue by jcassee** [sorin-ionescu/prezto#1846]
### Description
On Ubuntu 20.04, a globally installed `pip` command no longer points to Python 2's pip. Instead, there is only `pip2` and `pip3`. However, after installing pyenv, a shim is installed for `pip`. Running `pip` with the system interpreter selected will fail with a message to that effect. However, the command does technically exist so the check `$commands[pip]` will return true.

This causes [the pip command detection in the Python module](https://github.com/sorin-ionescu/prezto/blob/cb69d2d3e471726a76ac3e4e484deac52a2abf56/modules/python/init.zsh#L154) to select the wrong pip command.

### Expected behavior

The Python module works without errors and pip completion is loaded.

### Actual behavior

This error message:
```
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  [other versions]

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

And pip shell completion is not loaded.

### Steps to Reproduce

1. Install pyenv: `curl https://pyenv.run | bash`
2. Install any Python version through pyenv: `pyenv install 3.8.3`
3. Install shims: `pyenv rehash`
4. Set the system interpreter as default: `pyenv global system`
5. Restart zsh: `exec zsh`

### Discussion

We coulde change the glob pattern so `pip3` and `pip2` get preference. However, this seems just as bad in the opposite direction.

If pyenv is installed, `pyenv which` could be used instead as a test: `pyenv which pip >/dev/null` returns false. Pyenv will set `PYENV_ROOT` (if the user did not set it), so we know when to use it.

Would a PR be welcome to fix this?

### Versions

  - Prezto commit: cb69d2d3e471726a76ac3e4e484deac52a2abf56
  - ZSH version: 5.8 (x86_64-ubuntu-linux-gnu)
  - OS information: Ubuntu 20.04

**Comment by srijanshetty** [comment]
> We coulde change the glob pattern so pip3 and pip2 get preference. However, this seems just as bad in the opposite direction.

You're correct, this will break backwards compatibility and solving for Ubuntu 20.04 which will be a small fraction to begin with is not a good solution.

> If pyenv is installed, pyenv which could be used instead as a test: pyenv which pip >/dev/null returns false. Pyenv will set PYENV_ROOT (if the user did not set it), so we know when to use it.

The python module already checks for pyenv, so it makes sense to add the additional pyenv check in pip module completion.

A PR would be welcome :smile:
