### ISSUE TITLE
Prompt cannot change back after loading powerlevel10k

### ISSUE THREAD

**Issue by MaxNoe** [sorin-ionescu/prezto#1852]
### Description

Once prompt is set to `powerlevel10k`, loading other prompts has no effect.

### Expected behavior

The right prompt is loaded

### Actual behavior

Prompt stays powerlevel10k
### Steps to Reproduce

```
% prompt sorin
~ ❯❯❯ prompt adam1
maxnoe@max-nb-arch ~ % prompt off
% prompt sorin
~ ❯❯❯ prompt off
% prompt powerlevel10k                                                                      
❯ prompt off
❯ prompt sorin
```

### Versions

  - Prezto commit: ff91c8d410df3e6141248474389051c7ddcaf80a (current master)
  - ZSH version:  5.8
  - OS information: arch linux

**Comment by srijanshetty** [comment]
As mentioned in #1833, prompts usually set up additional variables and hooks. Considering ZSH doesn't have clean up mechanism for the same, some prompts may end up changing the system state.

**Comment by romkatv** [comment]
You can unload Powerlevel10k with this command:

```zsh
powerlevel10k_plugin_unload
```

`prompt` function doesn't invoke it though.

In general I would recommend to restart zsh (`exec zsh`) to unload a theme or a plugin.

**Comment by belak** [comment]
@romkatv So, I just learned about `prompt_cleanup` which it looks like is meant to be used during setup - the built-in bart theme uses it, but I wasn't able to get it to run... do you know anything about that?

**Comment by romkatv** [comment]
For the record: https://www.zsh.org/mla/workers/2020/msg01021.html
