### ISSUE TITLE
bump pure prompt

### ISSUE THREAD

**Issue by vbauerster** [sorin-ionescu/prezto#1862]
Can you please bump pure prompt to [latest](https://github.com/sindresorhus/pure/releases/tag/v1.13.0) release?

**Comment by mattmc3** [comment]
Can we do this? Every time someone mentions how stale Pure is, we have to point back to the vi mode bug. I tested with the latest Pure and can not reproduce the issue. Did it get silently fixed? Can we finally upgrade Prezto's Pure?

https://github.com/sindresorhus/pure/issues/485
https://github.com/sorin-ionescu/prezto/issues/1677
https://github.com/sorin-ionescu/prezto/issues/1641

**Comment by belak** [comment]
I'm happy to push that upgrade PR through and just watch for any vi related issues. Thanks for doing that!

**Comment by mattmc3** [comment]
@belak - Awesome! If there's something that comes up, "at" me and I'm happy to jump in there too and see if it's a thing we can power through and fix rather than roll back.

**Comment by belak** [comment]
Sounds good to me!
