### ISSUE TITLE
zprezto not completing file names and issues when logging in

### ISSUE THREAD

**Issue by umgupta** [sorin-ionescu/prezto#1863]
### Description
 
zprezto is not completing file/folder names when pressing tab after cat/cd. Moreover, when logging to zsh, I get output which looks like `cat <some file>`. Some part of output is copied in the end of this post

### Expected behavior
It should do completion and not print the file contents.

### Actual behavior
Already described 

### Versions

  - Prezto commit:38882275b8936218aabec7a7c760514187dd7fe9
  - ZSH version: 5.8
  - OS information:CentOS Linux release 7.6.1810 (Core)

Output when logging into zshell
```
add-zsh-hook () {
	emulate -L zsh
	local -a hooktypes
	hooktypes=(chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name) 
	local usage="Usage: add-zsh-hook hook function\nValid hooks are:\n  $hooktypes" 
	local opt
	local -a autoopts
	integer del list help
	while getopts "dDhLUzk" opt
	do
		case $opt in
			(d) del=1  ;;
			(D) del=2  ;;
			(h) help=1  ;;
			(L) list=1  ;;
			([Uzk]) autoopts+=(-$opt)  ;;
			(*) return 1 ;;
		esac
	done
	shift $(( OPTIND - 1 ))
	if (( list ))
	then
		typeset -mp "(${1:-${(@j:|:)hooktypes}})_functions"
		return $?
	elif (( help || $# != 2 || ${hooktypes[(I)$1]} == 0 ))
	then
		print -u$(( 2 - help )) $usage
		return $(( 1 - help ))
	fi
	local hook="${1}_functions" 
	local fn="$2" 
	if (( del ))
	then
		if (( ${(P)+hook} ))
		then
			if (( del == 2 ))
			then
				set -A $hook ${(P)hook:#${~fn}}
			else
				set -A $hook ${(P)hook:#$fn}
			fi
			if (( ! ${(P)#hook} ))
			then
				un
```

**Comment by belak** [comment]
Did you end up figuring out what the issue was, or are you dropping this for now?
