### ISSUE TITLE
Lazy load pyenv/rbenv etc.

### ISSUE THREAD

**Issue by xrisk** [sorin-ionescu/prezto#1867]
Could we try to lazy load these when the user calls `python`, `ruby`, etc for the first time? It would shave off startup time significantly (100ms for me).

**Comment by srijanshetty** [comment]
@xrisk how do you currently implement lazy loading?

**Comment by xrisk** [comment]
I’m using the code from here: https://github.com/davidparsson/zsh-pyenv-lazy/blob/master/pyenv-lazy.plugin.zsh

**Comment by belak** [comment]
We might be able to do this as an option, but I don't know how useful it is to lazy-load. I believe that would stop virtualenvs/python versions set via `pyenv local` (as well as `pyenv system`) from working as expected... I use this to make sure ansible command are available when I'm in my infra directories, my django env is loaded when working in a django project, etc. If pyenv was lazy-loaded, those wouldn't work as expected.

I've seen more complex versions where all the pyenv shims have stubs attached, but that starts getting complex really quick and still doesn't solve all use cases.

**Comment by srijanshetty** [comment]
I was going through the code and I do agree with @belak. 

Running `zprof` does not show any issues with `pyenv` in the current setup. (As a side note, `nvm` is horrible). And if you use pyenv, by definition a lot of your downstream tools will require it to be loaded.

**Comment by jottr** [comment]
@xrisk have a look at [zinit turbo mode](http://zdharma.org/zinit/wiki/INTRODUCTION/#turbo_mode_zsh_53).  
It might give you what you need.

**Comment by srijanshetty** [comment]
I'm closing this as issue for now as startup time of `pyenv` is a non issue.
