### ISSUE TITLE
Add 'history-substring-search' to default .zpreztorc

### ISSUE THREAD

**Issue by vytvir** [sorin-ionescu/prezto#1868]
It is an incredibly nifty feature to have and it is something that is enabled 'by default' on many other shells/extensions (oh-my-zsh, usr/bin/fish).

I believe it should also be included with prezto by default, here:

https://github.com/sorin-ionescu/prezto/blob/0a405494cae54e208ff550c1ba83380ed115410a/runcoms/zpreztorc#L32

**Comment by srijanshetty** [comment]
@vytvir, this is probably the most useful feature for me as well. @belak @imajes your views on the same?

**Comment by vytvir** [comment]
@srijanshetty Should I create a pull-request to include this? Maybe it will move things along.
