### ISSUE TITLE
Disable quotes

### ISSUE THREAD

**Issue by PhillipGabold** [sorin-ionescu/prezto#1871]
### Description
zsh is showing after every program a quote. How can i disable this feature?
(https://user-images.githubusercontent.com/65919733/97968383-dc2f2100-1dbe-11eb-905c-c8627d6d0434.png)

**Comment by srijanshetty** [comment]
@PhillipGabold you can edit them out of runcoms/zlogout.

**Comment by PhillipGabold** [comment]
can you please explain what you mean? im complete new at this shell 👍

**Comment by srijanshetty** [comment]
@PhillipGabold sorry if my reply was curt. If you go to `runcoms/zlogout` in a freshly installed version of Prezto, you'll see a variable called `SAYINGS` which controls this behaviour. You can safely delete lines `11 to 19` and this feature will be removed.
