### ISSUE TITLE
I installed prezto on my mac and succeed, but when I trying to add module git, there is not showing anything. May I miss something configuration?

### ISSUE THREAD

**Issue by arywidiantara** [sorin-ionescu/prezto#1873]
I installed prezto on my mac and succeed, but when I trying to add module git, there is not showing anything. May I miss something configuration?

this is my module ==> 

zstyle ':prezto:load' pmodule \
   'environment' \
   'terminal' \
   'editor' \
   'history' \
   'directory' \
   'spectrum' \
   'utility' \
   'completion' \
   'prompt' \
   'git'

**Comment by srijanshetty** [comment]
Was it related to not finding `git` and not having installed `xcode`?

**Comment by thewatts** [comment]
@arywidiantara do you remember what you did to fix this issue?
