### ISSUE TITLE
Consider adding theme `starship`?

### ISSUE THREAD

**Issue by singularitti** [sorin-ionescu/prezto#1887]
https://github.com/starship/starship

**Comment by mattmc3** [comment]
You can easily achieve this yourself without it being added to Prezto.

First, depending on your config, you may also need to add this line to your .zshrc:

```zsh
setopt prompt_subst interactive_comments
```

Then, start a new Zsh session and run this from your interactive Zsh prompt:

```zsh
# install starship if  we haven't already
command -v starship &>/dev/null || sh -c "$(curl -fsSL https://starship.rs/install.sh)"

# add prompt_starship_setup function to Prezto
ZPREZTODIR=${ZPREZTODIR:-${ZDOTDIR:-~}/.zprezto}
echo 'eval "$(starship init zsh)"' >! $ZPREZTODIR/modules/prompt/functions/prompt_starship_setup
```

Now, starship is setup as an available Prezto prompt. Feel free to then change to it in your .zpreztorc

```zsh
zstyle ':prezto:module:prompt' theme 'starship'
```

**Comment by singularitti** [comment]
Thank you! @mattmc3
