### ISSUE TITLE
I show an error message in Apple M1 chip environment.

### ISSUE THREAD

**Issue by tishiimnx** [sorin-ionescu/prezto#1891]
### Description
After installing protzo in my mac-mini (Apple M1 chip, macOS11.2.3) environment, I show the following error message when creating a new window in my Terminal application.

> zsh: locking failed for /Users/ishii/.zsh_history: interrupt

I don't show this error message on another mac (Intel Chip, macOS 11.2.3) which I'm using.

It seems that it occurs in $ HOME/.zprezto/runcoms/zlogin file.
Maybe in this "if" statement.
```
if [[-s "$ zcompdump" && (! -s "$ {zcompdump} .zwc" || "$ zcompdump" -nt "$ {zcompdump} .zwc")]]; then
```

### Versions

  - Prezto: v1.14.6
  - ZSH version: 5.8
  - OS information: macOS 11.2.3（20D91)

**Comment by jeffwidman** [comment]
If you can track it down further, we'd happily entertain a PR. But I don't have an M1 so can't repro/debug further.

**Comment by mattmc3** [comment]
I'm on an M1 MacBook Air and cannot reproduce this. Can you start with a clean Prezto install and see if that resolves it?

**Comment by belak** [comment]
Thanks for the report. Unfortunately without additional information we can't help debug this, so I'm closing it for now. We're happy to reopen this if you're still experiencing this issue and can debug with us though.
