### ISSUE TITLE
rsync and scp problems with tab filename completion

### ISSUE THREAD

**Issue by henrj** [sorin-ionescu/prezto#1894]
### Description
When pressing TAB for auto completing a filename that starts with A it suggests to install a package:

rsync AInstall package 'yp-tools' to provide command 'ypcat'? [N/y]

after this the terminal session freezes and gets stuck, but does not crash

### Expected behavior

To complete the filename: ADFD_MX-20210405_0503.iso

### Actual behavior

rsync AInstall package 'yp-tools' to provide command 'ypcat'? [N/y]

### Steps to Reproduce

1. write the command rsync and the first letter of the filename, in this case uppercase A
2. press TAB

While looking for similar problems I found out that scp also presents issues so I tried also with the scp command and it had the same outcome, suggest to install a package and freezes, slow down the current terminal session

### Versions

  - Prezto commit: d66041cdb7b992ceb1c4682d267f909d48723c8e
  - ZSH version: zsh 5.8 (x86_64-redhat-linux-gnu)
  - OS information: Fedora 34

**Comment by srijanshetty** [comment]
I couldn't repro this issue, could you update to latest and retry?
