### ISSUE TITLE
file tab completion colors are not matching ls colors, ls colors look incorrect

### ISSUE THREAD

**Issue by lhaus** [sorin-ionescu/prezto#1936]
### Description
file tab completion colors are not matching ls colors, ls colors look incorrect

### Expected behavior

![image](https://user-images.githubusercontent.com/18512463/119492258-22e66780-bd5f-11eb-9c4e-4598c3c19cca.png)

Environment:
![image](https://user-images.githubusercontent.com/18512463/119492338-3db8dc00-bd5f-11eb-828b-38125aeb56aa.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/18512463/119492294-2ed22980-bd5f-11eb-993f-c26dc336786a.png)

Environment:
![image](https://user-images.githubusercontent.com/18512463/119492378-4b6e6180-bd5f-11eb-8a28-e7d77e325b6b.png)

### Versions

  - Prezto commit: 53033bc5d9b279cc04e6c80eb5aa3070f9db7471
  - ZSH version: 5.8
  - OS information: macOS 11.4 / Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

**Comment by indrajitr** [comment]
@lhaus Is it possible to confirm if the proposed change (#1937) helps? If not, no worries.

**Comment by lhaus** [comment]
@indrajitr yep, fixes it. thanks!
