### ISSUE TITLE
Documentation on loading order of modules contradicts itself

### ISSUE THREAD

**Issue by Mr-Tao** [sorin-ionescu/prezto#1946]
Documentation on loading order of modules contradicts itself

1ff9421f7be has introduced some confusing changes to documentation. In Autosuggestions [README.md](https://github.com/sorin-ionescu/prezto/blob/master/modules/autosuggestions/README.md) it says:
> If this module is used in conjunction with the [_`syntax-highlighting`_][1] module, this module must be loaded after the syntax-highlighting module.
> If this module is used in conjunction with the [_`history-substring-search`_][2] module, this module must be loaded after the history-substring-search module.

It also states:
 > To elaborate, the relative order of loading the modules would be _`autosuggestions`_, _`syntax-highlighting`_ and _`history-substring-search`_.

While according to the former paragraph (and with respect to docs on [syntax-highlighting][1] and [history-substring-search][2]), the order should be:
1. syntax-highlighting,
2. history-substring-search,
3. autosuggestions.

The order of modules is correct in Syntax Highlighting [README.md][1], though it does not mention the position of the Autosuggestion module at all while it should.

[1]: https://github.com/sorin-ionescu/prezto/blob/master/modules/syntax-highlighting#readme
[2]: https://github.com/sorin-ionescu/prezto/blob/master/modules/history-substring-search#readme

**Comment by indrajitr** [comment]
@Mr-Tao thank you for pointing out the error. Does #1947 clarify better?
