### ISSUE TITLE
Git Symbols Documentation?

### ISSUE THREAD

**Issue by amadeus** [sorin-ionescu/prezto#1953]
This is less of a bug, and more of a question. On the readme there is this example screenshot of all the git symbols, and while most are self explanatory, some are a bit confusing:

![example](https://camo.githubusercontent.com/91f2c43c5676713987824150df33c52693ff103dd9c51441f0809519966c97d1/68747470733a2f2f692e696d6775722e636f6d2f6e7247563670672e706e67)

Is there any documentation for these symbols?

**Comment by indrajitr** [comment]
Hey @amadeus, this is a good call! We don't really have detailed docs for theme indicators. However, they can be identified by looking at the [relevant code](https://github.com/sorin-ionescu/prezto/blob/166cbe2fca25319db2551f0cc74a86c93259017d/modules/prompt/functions/prompt_sorin_setup#L131-L153).

That said PR to improve docs to add these would be welcome :)

**Comment by amadeus** [comment]
Ahah, Thank for the info!
