### ISSUE TITLE
[Question/FR] Add Dracula ZSH Theme

### ISSUE THREAD

**Issue by NovaViper** [sorin-ionescu/prezto#1960]
I'm triyng to add the [Dracula ZSH](https://draculatheme.com/zsh) theme to my install but there's no instructions on how to actually add themes that are hosted in github. Is it  possible to add the theme to my setup?

**Comment by FraBle** [comment]
+1

**Comment by mattmc3** [comment]
Sadly, this isn't really Prezto's fault, but more that the Dracula Zsh theme doesn't adhere to the `promptinit` standard, which comes with Zsh. It only provides an Oh-My-Zsh zsh-theme. You can read more about the proper way to set up a [Zsh prompt here](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/README.md).

However, it is possible to shoehorn this theme into Prezto. You will can add this snippet to your .zshrc prior to sourcing Prezto's init.zsh, or you can just run it once from an interactive Zsh session:

```zsh
# .zshrc
# get dracula theme
ZPREZTODIR=${ZPREZTODIR:-${ZDOTDIR:-~}/.zprezto}
if [[ ! -d $ZPREZTODIR/contrib/dracula ]]; then
  git clone https://github.com/dracula/zsh $ZPREZTODIR/contrib/dracula
  echo 'setopt prompt_subst' >! $ZPREZTODIR/contrib/dracula/init.zsh
  mkdir -p $ZPREZTODIR/contrib/dracula/functions
  echo '. $ZPREZTODIR/contrib/dracula/dracula.zsh-theme' >! $ZPREZTODIR/contrib/dracula/functions/prompt_dracula_setup
fi
```

Then, in your `.zpreztorc`, add 'dracula' to the module list, but do it **before** loading the 'prompt' module:

```
# .zpreztorc
zstyle ':prezto:load' pmodule \
  ... \
  'dracula' \
  'prompt' \
  ...
```

By doing this, I got it to work. It might be worth working with the Dracula theme folks to make a PR that adds a proper `prompt_dracula_setup` function, but for now, this seems to work.

Vote to close this issue.

**Comment by mattmc3** [comment]
After answering this question, I was inspired to make a prompt contrib that has some other popular prompts like starship, lean, and all the OMZ themes, with support for 3rd party OMZ themes like Dracula too. Feel free to grab it here: https://github.com/mattmc3/prezto-prompt-contrib

**Comment by srijanshetty** [comment]
The recommended suggestion for new modules is to use a custom `contrib-module` and keep the core of `prezto` tiny.
