### ISSUE TITLE
[Feat] : Add a fzf like search

### ISSUE THREAD

**Issue by Ierezell** [sorin-ionescu/prezto#1971]
### Description
Add a fzf like search capability to the classic search

Could be done with something like : https://github.com/joshskidmore/zsh-fzf-history-search 

### Expected behavior

When doing an history search use the power of fzf to show a list of possible commands 

### Actual behavior

Ctrl-r just shows one command and is not fuzzy found

I used it with zinit before changing for zprezto (which is simpler and nicer) and really liked this feature. 

Thanks in advance, 
Have a great day

**Comment by mattmc3** [comment]
This is a pretty cool plugin, but I'm not sure it really belongs in core Prezto. For features like this, it is usually preferable to add them yourself as a "contrib" in your own config. If you want to add this Zsh plugin as a Prezto contrib, you can run the following from your interactive Zsh terminal:

```zsh
repo=joshskidmore/zsh-fzf-history-search
git clone https://github.com/$repo ${ZPREZTODIR:-~/.zprezto}/contrib/${repo:t}
```

Then add the contrib to your `.zpreztorc`:

```zsh
zstyle ':prezto:load' pmodule \
  ... \
  zsh-fzf-history-search
```
