### ISSUE TITLE
Calling 'brew --prefix' is slow in the completions module - let's speed it up!

### ISSUE THREAD

**Issue by mattmc3** [sorin-ionescu/prezto#1978]
### Description

While profiling my prezto config, I noticed that the completions module was taking a bit longer than I felt it should (fractions of seconds, not whole seconds, but still it's slower than I wanted). After profiling, I determined that a subshell call to `$(brew --prefix)` was the culprit. I'm not the first to notice performance related to `brew --prefix`: https://github.com/Homebrew/brew/issues/3327

### Expected behavior

Since the completions module is one of the core Prezto modules and is enabled by default, I'd like to see it be as speedy as possible.

### Actual behavior

It's not speedy.

### Steps to Reproduce

1. On a Mac, install homebrew
2. Use brew to install curl (brew install curl)
3. Prezto now slows down because now the completions for curl are in a location managed by homebrew

### Versions

  - Prezto commit: latest (7884fb2271d131bb492fafc4eba1c537a821092b)
  - ZSH version: zsh 5.8 (x86_64-apple-darwin20.1.0) 
  - OS information: MacOS 12.2

### Potential solution

Current code:

```zsh
# Add completion for keg-only brewed curl when available.
if (( $+commands[brew] )) \
      && [[ -d "${curl_prefix::="$(brew --prefix 2> /dev/null)"/opt/curl}" ]]; then
  fpath=($curl_prefix/share/zsh/site-functions $fpath)
fi
unset curl_prefix
```

Proposed change (add a cache file):

```zsh
# Add completion for keg-only brewed curl when available.
if (( $+commands[brew] )); then
  # 'brew --prefix' is slow; cache its output
  cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/prezto/brew-cache.zsh"
  if [[ "${ZDOTDIR:-$HOME}/.zpreztorc" -nt "$cache_file" || ! -s "$cache_file" ]]; then
    mkdir -p "$cache_file:h"
    echo "brew_prefix=$(brew --prefix 2> /dev/null)" >! "$cache_file"
  fi
  source "$cache_file"
  if [[ -d "${curl_site_functions::=$brew_prefix/opt/curl/share/zsh/site-functions}" ]]; then
    fpath=($curl_site_functions $fpath)
  fi
  unset cache_file brew_prefix curl_site_functions
fi
```

I'm open to discuss other solutions or implementations, but this implementation is similar to what the Perl module does so I modeled off that. I'm currently using it as a .patch file in my personal $ZDOTDIR and this sped up loads by more than 1/10th of a second.

**Comment by mattmc3** [comment]
One alternative implementation that doesn't use a cache file would be to check the common homebrew dirs first. This has the disadvantage that there's still a execution path to running `brew --prefix` during every Zsh init which is what a cache file avoids.

```zsh
if (( $+commands[brew] )) && {
       [[ -d "${curl_prefix::=/opt/homebrew/opt/curl}" ]] ||
       [[ -d "${curl_prefix::=/usr/local/opt/curl}" ]] ||
       [[ -d "${curl_prefix::="$(brew --prefix 2> /dev/null)"/opt/curl}" ]]
    }
then
  fpath=($curl_prefix/share/zsh/site-functions $fpath)
fi
```

It's also worth noting that the node module also calls `brew --prefix`, but since it's not a default module I didn't change it. I'd be open to adding whatever we do in the completions module to the node one if that's helpful.

**Comment by jeffwidman** [comment]
Bumping this, as I agree it'd be nice to speed up the load time. But I'd like to see it done in a way that is consistent across all our modules, rather than re-patching this in completions-curl, perl, and other places that are affected.

I haven't put a lot of thought into this, and it may need to wait til #1986 is resolved before getting more attention, but it is worth fixing.
