### ISSUE TITLE
git branch doesn't appear

### ISSUE THREAD

**Issue by fabjesus** [sorin-ionescu/prezto#2020]
### Description
I have installed Prezto and I'm using the default configuration and I can't see the git branch name on my terminal.

### Expected behavior
See the branch name

### Actual behavior
Git branch name doesn't appear

### Steps to Reproduce
Run terminal

### Versions

  - Prezto commit:  current
  - ZSH version: zsh 5.8.1 (x86_64-apple-darwin21.0)
  - OS information: macOS Monterey 12.6

**Comment by jeffwidman** [comment]
This is theme-specific, try playing around with different themese to see if one shows the information you want. And if you have a theme you like that's missing the branch name, look at the source of another theme that has the branch name and see if you can hack it across... Feel free to also submit PR's back to the theme authors... it's all open source. 😀
