### ISSUE TITLE
@belak @indrajitr any thoughts on this PR?

### ISSUE THREAD

**Issue by Mztea928** [sorin-ionescu/prezto#2025]
@belak @indrajitr any thoughts on this PR?

_Originally posted by @Enzime in https://github.com/sorin-ionescu/prezto/issues/1982#issuecomment-1076909655_

**Comment by belak** [comment]
I'm guessing this was a mistake - the referenced PR was already merged a while back.

I'm closing for now but feel free to comment with more info and we can re-open it.
