### ISSUE TITLE
Searching using command prefix on up array

### ISSUE THREAD

**Issue by amokfa** [sorin-ionescu/prezto#2039]
### Description

If I have following commands in my history:

```
echo hello
grep echo
```

And I type `echo` and press up arrow, I want the prompt to jump to the first command. But in prezto it jumps to the second grep command. How do I get the behavior I need?

  - Prezto commit: e5126604d829c9fc77faa4b0cb9642f117b62b70
  - ZSH version: 5.8.1
  - OS information: popos

**Comment by brainsik** [comment]
This is supported in the current version of [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search), by setting `HISTORY_SUBSTRING_SEARCH_PREFIXED` (see [configuration docs](https://github.com/zsh-users/zsh-history-substring-search#configuration)).

#1957 would add support for this in prezto.

**Comment by indrajitr** [comment]
This is now supported via `zstyle` `:prezto:module:history-substring-search`.

**Comment by danilokleber** [comment]
Hi. This is not working for me. I have the new setting enabled in the `.zpreztorc` file but the behavior doesn't change.
