### ISSUE TITLE
hub slows down completion and prompt

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#242]
The [hub](http://defunkt.io/hub/) wrapper should only be active when `git` is manully typed when ZLE is active.

**Comment by bradfeehan** [comment]
Since `hub` is now [written in Golang][1] and seems to be much faster, any chance of this making it back in?

[1]: <https://github.com/github/hub#source>

**Comment by sorin-ionescu** [comment]
Yes, it will.
