### ISSUE TITLE
Double prompt on tty

### ISSUE THREAD

**Issue by MeisterP** [sorin-ionescu/prezto#263]
If I switch to tty (ctrl+alt+F2) the prompt is displayed twice after every command executed.

```
poncho@8540w ~ % ls [ENTER]
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
poncho@8540w ~ % 
poncho@8540w ~ %
```

before commit a5f8d04d34 the prompt was displayed correctly.

```
poncho@8540w ~ % ls [ENTER]
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
poncho@8540w ~ % 
```

This doesn't happen in gnome-terminal.

**Comment by crsmithdev** [comment]
seeing the same issue for the default theme, a new terminal session results in two prompts.

**Comment by temach** [comment]
Same issue, the prompt appears twice.
