### ISSUE TITLE
Convert the README files to man pages

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#276]
Investigate the possibility of converting the README files to man pages using @sunaku's [md2man](https://github.com/sunaku/md2man).

The files will look similar to bellow, inspired by Zsh and Git man pages.
- prezto.1
- prezto-all.1
- prezto-ruby.1
- prezto-git.1

Where will these man pages be stored?

If the README files can be successfully converted as they are or altered, should they be removed in favour of man pages only?

**Comment by belak** [comment]
Is this still something we plan to do? It seems a little out of scope for prezto.

**Comment by belak** [comment]
I'm going to close this for now because it hasn't been updated in almost 4 years and the original branch doesn't exist any more. If we decide to do it later, it can be reopened.
