### ISSUE TITLE
Tmux issue: zcompile error on .zlogin line 13

### ISSUE THREAD

**Issue by stephenmckinney** [sorin-ionescu/prezto#318]
When starting a tmux session with multiple panes, several of the panes have this error:

```
/Users/smckinney/.zlogin:zcompile:13: can't write zwc file: /Users/smckinney/.zcompdump.zwc 
```

https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zlogin#L13

**Comment by IanEdington** [comment]
This breaks scripts that setup my environment. I'm interested in finding a solution / workaround

**Comment by huyz** [comment]
It's now executed in the background, which doesn't affect performance (perhaps this was changed after this ticket was opened?), so why not modify `runcoms/zlogin` to just run `lsof` or just retry until it works?

**Comment by huyz** [comment]
> Since this only happens for tmux/screen

This affects any user of terminal programs or session managers that open multiple zsh shells at the same time. In my case it's iTerm2

**Comment by huyz** [comment]
@IanEdington check out https://github.com/sorin-ionescu/prezto/pull/2029
