### ISSUE TITLE
Bind only one key map

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#352]
Right now, both _emacs_ and _vi_ are mapped. This is useful for testing because one can switch between the two key maps using `bindkey -e` and `bindkey -v` without editing _zpreztorc_ and restarting the terminal, but for regular use, it's useless. The user chooses either emacs or vi and sticks with it.

Perhaps, only the one set in _zpreztorc_ should be bound. Nevertheless, it's doubtful that there will be a significant speed increase by only binding one key map. Thoughts?

**Comment by belak** [comment]
With the way the code works now, it would be pretty inconvenient to only set one of the keymaps.

I'm closing this for now because the work required probably wouldn't be worth the minimal startup time save.
