### ISSUE TITLE
git branch name disappears in sorin's theme

### ISSUE THREAD

**Issue by martco** [sorin-ionescu/prezto#369]
@sorin-ionescu hi thanks for maintaing this repo. prezto is great.

The sorin theme is my favorite theme. Sometimes, however, after some extended usage the branch name disappears from the theme. I've attached an image to illustrate:

![687474703a2f2f692e696d6775722e636f6d2f6e4245455a2e706e67](https://f.cloud.github.com/assets/420959/68317/750722b6-5f30-11e2-94c1-cbbdfe6b050a.png)

I have no clue where to start with this. I really want to be able to see my branch name. The repo i'm in has submodules, although i'm not sure that has anything to do with this. 

Do you (or anyone) have any quick ideas on what i'm doing wrong / how to fix this?

Thanks,
Martin

**Comment by samupl** [comment]
How to make the git status a part of the PS1 prompt like in the first message of this issue? Currently when using git module with the sorin theme, the git info goes to the RPROMPT.

**Comment by sorin-ionescu** [comment]
You'll have to revert the theme to commit https://github.com/sorin-ionescu/prezto/commit/087fce85486505443bfce24db5a9ab00ac27d52c. You'll lose asynchronicity, and the prompt will be slower.

**Comment by alvesadrian** [comment]
if you activate git module on .zprestorc and after that git-config on :+1:

**Comment by oblitum** [comment]
I'm on ArchLinux inside WSL (Windows Subsystem for Linux) and just updated prezto and now my git branch is not being shown in the sorin prompt anymore, does anyone have an idea why? All other prompts show it, and I have no problems with the same prezto setup on my bare metal ArchLinux, so I have no idea why it's not showing up on WSL anymore.

**Comment by oblitum** [comment]
Also, I tried executing `git-info on` but it had no effect.

**Comment by belak** [comment]
There are a few people who mentioned issues with zsh-async on Windows, but I didn't think WSL experienced those same problems. `git-info on` doesn't do anything as far as I know (though it may have in the past. Could you file a new issue (so we don't clutter this one) with the info requested in the template to make this easier to investigate?

**Comment by oblitum** [comment]
@belak OK.

**Comment by belak** [comment]
This does seem to be an issue with WSL as well (see https://github.com/sindresorhus/pure/issues/210). We might have to look into an alternate method of running tasks asynchronously (without using zpty)... which is unfortunate.

**Comment by tunttunen** [comment]
> How to make the git status a part of the PS1 prompt like in the first message of this issue? Currently when using git module with the sorin theme, the git info goes to the RPROMPT.

I would like to know this also! How can I get the information to the left side?
