### ISSUE TITLE
The notice about `path_helper` on OS X is incorrect

### ISSUE THREAD

**Issue by mislav** [sorin-ionescu/prezto#381]
This:

> If you have administrator privileges, you must fix an Apple-introduced problem in Mac OS X 10.5 Leopard by executing the following command, or BASH and Zsh will have the wrong PATH when executed non-interactively.
> 
> ```
> sudo chmod ugo-x /usr/libexec/path_helper
> ```

Is incorrect. Users shouldn't disable `path_helper`.

The problem is OS X is that it comes with `/etc/zshenv` that uses `path_helper`. However, `/etc/zshenv` gets sourced for every zsh shell, even non-interactive. To put a stop to that, simply:

```
sudo mv /etc/{zshenv,zprofile}
```

**Comment by pdemarti** [comment]
We are now in 2017, and running El Capitan, so this is probably not quite the right thread. But Googling '`prevent zprofile messing my path`' lands me here and I can see that the comments sound relevant.

Basically, I set `PATH` in `.zshenv`, as zsh intended.  The fact that `/etc/zprofile` is sourced after `.zshenv` messes up my path: it calls `path_helper -s`, which sneakily reorders my `PATH` in such a way that `/usr/local/lib` and other system dirs are placed before the ones in which I carefully override certain commands.  For example, I use Conda to manage Python and its modules. On all my other systems, `which python` yields the desired `$CONDA_HOME/bin/python`. On this mac, it is `/usr/bin/python`, which is not at all what I want.

So, I'd say this `path_helper` thing is quite intrusive.

**Comment by pdemarti** [comment]
Anyway, for anybody who'll land here too, here is a workaround:

in `.zshenv`: before customizing `PATH`:

```shell
# MacOS workaround sneaky path_helper in /etc/zprofile
if [ -x /usr/libexec/path_helper ]; then
  eval `/usr/libexec/path_helper -s`
fi
```

At the end of `.zshenv`:
```shell
# MacOS workaround sneaky path_helper in /etc/zprofile
export GOODPATH=$PATH
```

Create a `.zprofile` (I don't usually have one):
```shell
# MacOS workaround sneaky path_helper in /etc/zprofile
export PATH=$GOODPATH
```

Now everything works as intended.

**Comment by mitrx** [comment]
@pdemarti, if we consider [unix shell initialization](https://github.com/rbenv/rbenv/wiki/Unix-shell-initialization), then we may come to conclusion that /etc/zprofile is not called in some cases. At least in the case when we 

> Executing a command remotely with `ssh`

So, I suppose the correct solution would be not to include
`if [ -x /usr/libexec/path_helper ]; then
  eval `/usr/libexec/path_helper -s`
fi`
in `.zshenv`, but to save `PATH` at the end of `.zshenv`
`export GOODPATH=$PATH`, as you did.

Then, you just need to set `PATH`, such that it would be
`PATH=$GOODPATH:<PATH excluding those paths that are already in GOODPATH>`
