### ISSUE TITLE
Wrong cursor position and folder colors over SSH

### ISSUE THREAD

**Issue by y0ast** [sorin-ionescu/prezto#397]
![Screen Shot 2013-02-26 at 12 14 39 ](https://f.cloud.github.com/assets/485778/195990/ec7f9206-8005-11e2-8308-e9fad5e11739.png)

In the screenshot you can see that the cursor is 2 blocks to the left, it messes up autocompletion too. Also the folders have weird colors:

![Screen Shot 2013-02-26 at 12 18 35 ](https://f.cloud.github.com/assets/485778/195998/4c218b06-8006-11e2-9fb2-0a117df6a8cc.png)

I have no idea what causes this, as locally these problems don't exist and everything works smoothly 

Here is a screenshot from a local prompt.
![Screen Shot 2013-02-26 at 12 19 19 ](https://f.cloud.github.com/assets/485778/196004/6943262c-8006-11e2-9c76-33e6e87154a3.png)

I Remove %B and %b to make the colors work in my solarized scheme. As it is working locally too, this is not the cause of the problem.

**Comment by masterjedy** [comment]
I had such problem. It was a terminal problem, switching terminal font to monospace fixed it.
Find out what terminal you currently using, open its settings and switch font to monospace in that settings.
