### ISSUE TITLE
Removing cursor imprint? 

### ISSUE THREAD

**Issue by ghost** [sorin-ionescu/prezto#399]
Hi, I've been using Prezto for several months now and I love how faster it is compared to OMZ. 

I have a trivial issue though concerning how prezto handles commands.

Let's say I'm entering the command ls ~/.vim and have my cursor on . and I hit Enter. In OMZ, the cursor "imprint" will disappear. In Prezto, it stays there and sometimes, this can make the command hard to read on some terminal colorschemes. The cursor doesn't leave this imprint when I hit Ctrl-E to go to the end of the line and then press Enter but it always does when I don't go to the end of the line and hit Enter.

Is this intended or is it caused by something on my end? If it's intended, how can I change this so it doesn't leave the cursor imprint anymore if I hit enter when I'm in the middle of the line? If not, does anyone know what might have caused this? I have googled for hours but I haven't found anything. I know this is a trivial issue but I really don't like the imprint. 

To see what I mean, here is an image: 
![Screen Shot 2013-02-28 at 7 05 21 PM](https://f.cloud.github.com/assets/1159146/208277/9b6f5c4c-821d-11e2-92af-5c6d23ecf000.png)
See how the cursor imprint is there? I want to see if I can get rid of that. 

Thanks for any help, and thanks for creating Prezto!

**Comment by danielshahaf** [comment]
The upstream issue with the `cursor` highlighter has been fixed.  Although I see prezto now enables only the `main` highlighter by default.
