### ISSUE TITLE
How do you use the terminal auto-title feature?

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#401]
Lately, I have been toying with the terminal auto-title feature since I am not happy with it.

For **Terminal.app**, setting the window and tab titles to the current process name is not necessary because it sets the tab title by default. It can also set the window title if it is enabled in Preferences; it is enabled by default.

Furthermore, the window and tab titles also need not be set to the current working directory since Terminal.app has special support, set separately, which allows the user to open Finder windows.

In the case of terminal multiplexers, such as `screen`, `tmux`, and `dvtm`, auto-titling becomes complicated.

Since no multiplexer transmits the escape code to the parent terminal, the Terminal.app current working directory should be erased before starting a terminal multiplexer, for it goes out of sync causing confusion.

For `screen` and `tmux`, auto-title will override window titles set by the user in _screenrc_ and _tmux.conf_. This feature becomes more troubling for `tmux` windows with split panes. The window title will be set based on the last command run in a pane, which is not representative of all panes. So, auto-title, doesn't help the user distinguishing between windows causing confusion.

For `dvtm`, auto-titling split windows with the current process name is useful since there is no configuration file where the user can create profiles and title windows.

**iTerm.app** can show the current process name in both the window and tab titles by enabling it in Preferences. It cannot show the current working directory; auto-title is partially useful for iTerm users who need to know the current working directory outside of the prompt.

The information above about terminal multiplexers inside of Terminal.app also applies to terminal multiplexers inside of iTerm.app.

I do not remember how KDE and Gnome terminal emulators behave.

The auto-title feature should be more flexible. It should allow the user to set the environments where the feature is enabled or disabled. 

How do you use auto-title?

**Comment by beanaroo** [comment]
I thought I'd post this here for discoverability. 

I overcame this limitation by using a native title feature in tmux (disabled by default):
`set-titles [on|off]` and `set-titles-string <FORMAT>`

In my case, I have a dedicated tmux session for `irssi` and I would like to manipulate the window via the WM, for which I need a title. It also helps with the window switcher (rofi). This works nicely with the zsh terminal module's autotitiling.
