### ISSUE TITLE
Broken link in README.md for rsync module

### ISSUE THREAD

**Issue by chauncey-garrett** [sorin-ionescu/prezto#436]
[Bombich's rsync](http://www.bombich.com/rsync.html)

FIXME: broken link...as of 2013-05-22 @ 5:00 PM CST

**Comment by wadkar** [comment]
FWIW, here's the current link to the [diff file showing Bombich's modification to rsync-3.0.6](https://bombich.com/software/opensource/rsync_3.0.6-bombich_20150427.diff) . Does anyone know if those patches were accepted upstream?
Also, you can search for rsync in their help desk search pages and reach at following url which contains link to rsync credits and patches:
https://bombich.com/kb/ccc4/credits#rsync

**Comment by indrajitr** [comment]
@wadkar, they haven't been yet. If you install `rsync` via homebrew, you'll have the patched binary though.
