### ISSUE TITLE
Time to open a wiki?

### ISSUE THREAD

**Issue by ColinHebert** [sorin-ionescu/prezto#44]
With OMZ 2.0 a ton of new things have been added, it would be awesome to be able to document some parts of it with a wiki.

For example, I'll be glad to add some information on the git-plugin and how it works/should be used when you want to create your theme.

This way you don't have to read the source code to understand what to need to do.

And it could help to solve some other issues such as #25

**Comment by hijxf** [comment]
Wiki was disabbled?
