### ISSUE TITLE
Customize Prezto Without Forking Or Touching Prezto

### ISSUE THREAD

**Issue by simeonwillbanks** [sorin-ionescu/prezto#456]
I'd like to customize Prezto without forking the project or touching any projects files.  This way, upgrading is a simple pull. oh-my-zsh can be [customized](https://github.com/robbyrussell/oh-my-zsh#customization); YADR can be [customized](https://github.com/skwp/dotfiles#customizing-zsh--picking-a-theme).  Lets bring this to Prezto!

**Comment by Stelgard** [comment]
Why don't use something like [thoughtbot dotfiles](https://github.com/thoughtbot/dotfiles)?
If a .local file exists load it. Users can put customizations in these files and leave untouched the others.
