### ISSUE TITLE
sudo alias and nocorrect/noglob

### ISSUE THREAD

**Issue by Marsup** [sorin-ionescu/prezto#531]
Hello,

I was having an issue with aliases not working with sudo, so I found [this little trick](https://wiki.archlinux.org/index.php/Sudo#Passing_aliases) and it seemed to work fine, until I found it didn't work very well with aliases defined in the `utility` module.

So basically when the sudo alias is defined I get `sudo: nocorrect: command not found` on aliases with nocorrect/noglob but other aliases work fine, and if it's not, aliases are unknown when sudoing, is there a way to have both work ?

Any help appreciated, thanks.

**Comment by Enzime** [comment]
I have a cheap trick to solve this issue, what I did was create a shell file `/sbin/nocorrect`

```
#!/bin/sh
exec $*
```

and I added /sbin to the end of `$PATH` in `/root/.zshrc`.
