### ISSUE TITLE
Using zsh-autosuggestions with prezto?

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#532]
Fish-like autosuggestions for zsh: https://github.com/tarruda/zsh-autosuggestions

Is it possible to use this widget in tandem with prezto and, if so, How?

Sorry for the shallow question, but I'm not sure what to try. Thank you.

**Comment by breerly** [comment]
update here? would love love love fish-like autosuggestions in prezto

**Comment by sorin-ionescu** [comment]
I have not played with it. Try it and let me know.

**Comment by breerly** [comment]
This ticket seems to indicate that it works fine:

https://github.com/tarruda/zsh-autosuggestions/issues/37

**Comment by sorin-ionescu** [comment]
I will try the following and report.

```zsh
zstyle ':prezto:load' pmodule \
    "history" \
    "completion" \
    "history-substring-search" \
    "syntax-highlighting" \
    "autosuggestions"
```

**Comment by breerly** [comment]
:+1:

**Comment by breerly** [comment]
@sorin-ionescu how did it fare?

**Comment by breerly** [comment]
@sorin-ionescu I think you need history after syntax highlighting like so:

```bash
zstyle ':prezto:load' pmodule \
    "history" \
    "completion" \
    "syntax-highlighting" \
    "history-substring-search" \
    "autosuggestions"
```

**Comment by sorin-ionescu** [comment]
No, syntax-highlighting should be after history-substring-search since it modifies a function supplied by history-substring-search.

**Comment by breerly** [comment]
If there's anything I can do to help get movement here let me know - I'm kind of a shell noob but I'll do my best.

**Comment by sorin-ionescu** [comment]
#972 is a good alternative for this as well as zsh-history-substring-search for those who prefer more sophisticated history browsing.

**Comment by breerly** [comment]
@sorin-ionescu did you manage to get autocompletions working?

**Comment by sorin-ionescu** [comment]
It kind of works. There are coloring issues when combined with syntax-highlighting.

**Comment by breerly** [comment]
I can fiddle with it - what's the best way to install it?

**Comment by sorin-ionescu** [comment]
Just wait for me to push into master and update Prezto after this issue is closed.

**Comment by breerly** [comment]
Got it - I'll play around with it then and see how well I can get it working.

**Comment by sorin-ionescu** [comment]
I'm going to push it into a branch **module/autosuggestions** and let you play with it. Having been browsing its issue list and toying with it, I still think it has too many annoying bugs to be in master, and I identified a [multiline bug](https://github.com/tarruda/zsh-autosuggestions/issues/81) myself.

**Comment by sorin-ionescu** [comment]
How is the latest code in https://github.com/sorin-ionescu/prezto/compare/module/autosuggestions working for you?

**Comment by DeepAnchor** [comment]
@sorin-ionescu this is working great now, thanks!

**Comment by breerly** [comment]
Will try it out today!

**Comment by stefanosc** [comment]
@sorin-ionescu I just gave it a go, this looks great, thank you

**Comment by breerly** [comment]
works here too!

**Comment by sorin-ionescu** [comment]
There are still issues with it, which you can track on the project's page, but it's now stable enough, and it's been merged. Some may be disappointed that it took more than 2 years for me to merge it, but I prefer less features to lots of whining due to incompatibility bugs. It now plays nice with zsh-syntax-highlighting, zsh-history-substring-search, and a few other projects.

**Comment by nasedo** [comment]
Works great here, except one thing. The unused suggestion text doesn't clear after accepting the line. For example after executing `echo 'something'` and then just `echo` I'm left with:
`$echo 'something'`
`something`
`$echo ['something']`
Where ['something'] is the highlighted suggestion text. Shouldn't it disappear, leaving only the executed command? I couldn't find an issue about it on the project page.

**Comment by cazzerson** [comment]
It's working pretty well for me, but it does introduce a significant (5+ second) lag between commands for me. 

I'm also experiencing the issue that @nasedo describes.

**Comment by sorin-ionescu** [comment]
My part is done. Post issues on the project's page.

**Comment by sorin-ionescu** [comment]
@nasedo, I confirm that unused autosuggestions are not cleared. It seems to be caused by the editor module. Discuss in #1093.

**Comment by nasedo** [comment]
Can't reproduce @cazzerson's issue here.
