### ISSUE TITLE
Return values displayed

### ISSUE THREAD

**Issue by Thanatermesis** [sorin-ionescu/prezto#547]
I would suggest for RPROMPT to show the "error returned value", instead of only a single char (⏎), maybe in a red background and white foreground characters? or maybe like this? ⏎127

Unfortunately I'm not very familiar with the zsh syntax / prompt, I was trying to modify the source code but I was unable to do it so

**Comment by mralexgray** [comment]
+1

**Comment by ILI4S** [comment]
+1

**Comment by belak** [comment]
This was actually added as an option a while back: https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/README.md#display-return-value

It probably won't be on by default for the sorin prompt though.
