### ISSUE TITLE
Question: Local Modules without Forking

### ISSUE THREAD

**Issue by miseqs** [sorin-ionescu/prezto#586]
I apologize if this is answered in the documentation somewhere and I missed it - I've ready the docs thoroughly but haven't found an answer.

If I prefer not to fork prezto (compatibility issues with vcsh, which I use to manage my dotfiles), is it possible to load modules outside of the zprezto directory?

For example, if I set ZDOTDIR to ~/.zsh, which contains my zsh rc files that are stored in a git repository separate from prezto repository - can I put my own prompt module in this directory as well and load it?

**Comment by david-resnick** [comment]
@nfarrar what workaround did you work out? I'm at the same crossroads. Thanks!

**Comment by sorin-ionescu** [comment]
You'll have to modify the module load function to look for other locations.
