### ISSUE TITLE
Ctrl+r doesn't work

### ISSUE THREAD

**Issue by ruipacheco** [sorin-ionescu/prezto#596]
Not sure if this is a zsh issue or a oh-my-zsh customisation.

I had omz and with ctrl+r I could search in history. I've just tried to do that with Prezto and it didn't work.

**Comment by ootoovak** [comment]
Thanks @bcachet I was having the same issues as @ruipacheco and turns out it was because I had set my bindings to `vi` rather than `emacs`. :smile:

**Comment by lsd** [comment]
As stated above, if hitting ^R doesn't do anything (OS X) and hitting ^A or ^E display the literal characters instead of jumping to the beginning and end of the current cmd you're typing, respectively, you probably have `zstyle ':prezto:module:editor' key-bindings` set to `vi` instead of `emacs`. 

In `~/.zprezto/runcoms/zpreztorc`, set:
`zstyle ':prezto:module:editor' key-bindings 'emacs'`

**Comment by zoeesilcock** [comment]
This [article](http://dougblack.io/words/zsh-vi-mode.html) has workarounds for the keybindings in case you want to continue using the ```vi``` bindings.

**Comment by gabamnml** [comment]
I fix with this key bindings in `,zshrc`
```
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward
```

**Comment by soooooot** [comment]
thanks @gabamnml !! you saved my life!
I'm working on iterm2 with oh-my-zsh and I enabled `set -o vi`,  your solution works for me.
btw, I'm not using `presto`, so I think it's not a presto issue.

**Comment by gabamnml** [comment]
@soooooot mmm.. freak, because to my left me to work when installed Prezto because before with Oh My Zsh works. I'm glad you now work. I went also to be happy after doing this.

**Comment by fisherMartyn** [comment]
I solve the problem by deleting `vi-mode` in my .zshrc, with these codes, ctrl + r not work:
`plugins=(git autojump tmux vi-mode)`

**Comment by theduke** [comment]
For anyone wondering how to make `Ctrl-N` and `Ctrl-P` work again also in vi mode:

```zsh
bindkey '^N' down-line-or-history
bindkey '^P' up-line-or-history
```

**Comment by ccwanggl** [comment]
Add 'bindkey -e' to zshrc file to solve ctrl + a command does not work issue.
