### ISSUE TITLE
Issues with DEL and BackSpace (^? or ^H)

### ISSUE THREAD

**Issue by ColinHebert** [sorin-ionescu/prezto#61]
Before everybody forget about this issue (mostly discussed on the commit related to it):

https://github.com/sorin-ionescu/oh-my-zsh/commit/9c611ce7e52ce128dbd9763aac9e8526b62e5fa4

Here is the original issue fixed by the said commit (#45)

Some documentation on the subject:
- http://www.ibb.net/~anne/keyboard.html
- http://www.ibb.net/~anne/keyboard/keyboardprev
- http://www.acm.uiuc.edu/workshops/cool_unix/stty.html

---

For Mac Users:

If you're on Mac OS, with [iTerm2](http://imgur.com/a/NRmxs#1) or [Terminal.app](http://imgur.com/a/NRmxs#3), by default your terminal type will be `xterm-256color`.
In [Terminfo](http://linux.die.net/man/5/terminfo), the setting for `kbs` is `^H`*, this mean that with this terminal, BackSpace is _expected_ to send `^H`.

For some reason, iTerm2 and Terminal.app don't send the correct code when you type backspace, ie `^?` instead of `^H`.
You can check that by typing `^V` followed by backspace.

To fix this, you have to ask to [iTerm2](http://imgur.com/a/NRmxs#0) or [Terminal.app](http://imgur.com/a/NRmxs#2) to send `^H` when you hit backspace.

Beware, iTerm2 users, if you do a `^Backspace`, you will send `^?` (even if you've set "Delete key sends `^H`)!

Notes:
- `infocmp xterm-256color | grep kbs`

**Comment by userx-bw** [comment]
in what files does this
keyinfo=(
  'Backspace' "^?�"
  'Delete'    "^[[3~"
)
go into exacly?

**Comment by sorin-ionescu** [comment]
@userx-bw, see https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh#L36-L37.

**Comment by brian-lamb-software-engineer** [comment]
i had this problem recently, and had to add in `.vimrc` `set term=builtin_xterm` to resolve this.
