### ISSUE TITLE
Ctrl + R history search

### ISSUE THREAD

**Issue by teburd** [sorin-ionescu/prezto#615]
The history reverse search that I have used for year with zsh doesn't seem to work when I use prezto, do I need to do something funny here?

**Comment by smldis** [comment]
This is where it is overrided in favor of redo.
I will rebind it back to the original since I don't use redo a lot and typing `?` in normal mode is kind of a pain apparently.
https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh#L271
