### ISSUE TITLE
Terminal window and tab titles not working in Mac OS X 10.9

### ISSUE THREAD

**Issue by jimothyGator** [sorin-ionescu/prezto#644]
There seem to be several pull requests to fix this, but they look to have all been rejected. I'm not sure what the status of this is, but it's still broken as of this filing.

**Comment by amir20** [comment]
I am completely new to zsh and prezto. But I did search for this for hours and found this ticket finally. I tend to agree with @jimothyGator here as well. I am not a power user. I don't use tmux. Terminal.app only allows me to keep the process name. Which looks like this 

![screen shot 2015-06-29 at 2 17 28 pm](https://cloud.githubusercontent.com/assets/260667/8418677/a6b88764-1e69-11e5-91f8-e353c83abc94.png)

I think it would make sense to enable this feature. I work with multiple rails projects and it is pain to switch between all the different tabs.
