### ISSUE TITLE
git ls-files in prompt

### ISSUE THREAD

**Issue by bmatheny** [sorin-ionescu/prezto#668]
1c136faf734166242b10491218d01ed33aa7fd68 removed some basic git result caching because it wasn't accurate. Unfortunately on the repository I work in, calling `git ls-files` on every command introduces a ~1 second delay (this is on a flash disk, it's due to repository size).

oh-my-zsh has a config it respects to do caching, that is off by default. I would be happy to put up a diff to re-introduce the caching removed in 1c136faf734166242b10491218d01ed33aa7fd68 but controlled by a prezto config (off by default).

For new I've just reverted the relevant parts of `modules/prompt/functions/prompt_steeef_setup` so it behaves how I want.

**Comment by sorin-ionescu** [comment]
#796 is a better way around slow Git prompts.
