### ISSUE TITLE
Move prompt_sorin_pwd out of sorin theme

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#701]
The function is used by other themes. Remove duplication by extracting it into its own function file.

**Comment by Eriner** [comment]
Done.

https://github.com/Eriner/prezto/commit/8a3bedb0b4d91d464dc3be0d8bb62a9a0dfb01f4.patch

**Comment by jeffwidman** [comment]
@belak is this closed by your modified version of #1016 that you merged into master?

**Comment by belak** [comment]
Yep, good catch
