### ISSUE TITLE
'no session' with tmux on auto start locks me out of server

### ISSUE THREAD

**Issue by ianks** [sorin-ionescu/prezto#709]
When I set the tmux settings to auto-start a Tmux session, I have been getting this bug that locks me out of my server

```
no sessions
Connection to 127.0.0.1 closed.
```

Not sure why this fails, should it not create a new session if there is not one already there?

**Comment by amitkot** [comment]
I'm getting this behaviour on OS X.
Right after boot, when I open the terminal (or iTerm) app, I get the "no sessions" error, and no shell is opened.

A workaround I found is to start tmux manually, and then start the terminal app.

**Comment by ianks** [comment]
Have you checked to see if there is a syntax error in any of your tmux configs?
