### ISSUE TITLE
ssh module: Why is it disabled on OSX? (ssh-agent/ssh-add)

### ISSUE THREAD

**Issue by ralph** [sorin-ionescu/prezto#718]
Hi,

I've recently switched from oh-my-zsh to prezto, and first of all, I have to thank you for putting this much work in this incredible software. I have this one minor problem. though: Unlike you could assume from the config, my ssh identities are not added to ssh-agent.

So I looked up the module source, and saw a check for OSX operating systems. Removing the `[[ "$OSTYPE" == darwin* ]]` check from the beginning of `ssh/init.zsh` resolves the problem for me, identities are added and ssh connects to servers they way I'm used to.

But I was curious why the check is there, so I looked up the ssh module on Github, and clearly it states:

"This module is disabled on Mac OS X due to custom Apple SSH support rendering it unnecessary."

OK - could you give me any pointer to those custom Apple SSH support methods, so I can use those instead? I really have no idea what this is, and how to use it. I'd also appreciate if you'd put a link to more information info the ssh module source or into the readme, so other's having the same issue can quickly help themselves.

**Comment by phretor** [comment]
@sorin-ionescu unfortunately this does not handle the use case where one uses the GPG module with enable-ssh-support. Indeed, the GPG module (which in turns handles the identities) needs to load the 'ssh' module to correctly set the `$SSH_AUTH_SOCK` env variable (see the `if grep 'enable-ssh-support' "$_gpg_agent_conf" &> /dev/null; then` branch).

In my use case, I'm using a Yubikey to handle SSH-through-GPG authentication.
