### ISSUE TITLE
just updated every new tab I see "Couldn't read file ...functions/prompt_agnoster_setup containing theme agnoster." etc..

### ISSUE THREAD

**Issue by stefanosc** [sorin-ionescu/prezto#726]
As per subject.

Couldn't read file /Users/stefano/.zprezto/modules/prompt/functions/prompt_agnoster_setup containing theme agnoster.
Couldn't read file /Users/stefano/.zprezto/modules/prompt/functions/prompt_powerline_setup containing theme powerline.
Couldn't read file /Users/stefano/.zprezto/modules/prompt/functions/prompt_pure_setup containing theme pure.

It looks like after the update there is a reference to some themes that changed location.
Any suggestion about how to go about this?
Thank you.

**Comment by skwp** [comment]
I'm still having this issue after upgrading prezto recently. inside prezto dir I ran `git submodule update --recursive`. anything else you had to do @stefanosc ?

**Comment by skwp** [comment]
ah, problem solved. had to follow this:
https://github.com/sorin-ionescu/prezto#updating

i.e. ` git pull && git submodule update --init --recursive`
