### ISSUE TITLE
Zsh fails with python plugin

### ISSUE THREAD

**Issue by lsmag** [sorin-ionescu/prezto#739]
Hi,

I just installed prezto and added the Python plugin. I had no problem installing a new python, but after I installed virtualenvwrapper I can no longer open zsh, everytime I open a new shell it closes immediately. I switched back to bash and started zsh with debug output, `$ zsh -xe &> trace.log`, and this is what I got:

```
#
# Enables local Python package installation.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Sebastian Wiesner <lunaryorn@googlemail.com>
#

# Load manually installed pyenv into the shell session.
if [[ -s "$HOME/.pyenv/bin/pyenv" ]]; then
  path=("$HOME/.pyenv/bin" $path)
  eval "$(pyenv init -)"

# Load package manager installed pyenv into the shell session.
elif (( $+commands[pyenv] )); then
  eval "$(pyenv init -)"

# Prepend PEP 370 per user site packages directory, which defaults to
# ~/Library/Python on Mac OS X and ~/.local elsewhere, to PATH. The
# path can be overridden using PYTHONUSERBASE.
else
  if [[ -n "$PYTHONUSERBASE" ]]; then
    path=($PYTHONUSERBASE/bin $path)
  elif [[ "$OSTYPE" == darwin* ]]; then
    path=($HOME/Library/Python/*/bin(N) $path)
  else
    # This is subject to change.
    path=($HOME/.local/bin $path)
  fi
fi
+/home/lsmag/.zprezto/modules/python/init.zsh:10> [[ -s /home/lsmag/.pyenv/bin/pyenv ]]
+/home/lsmag/.zprezto/modules/python/init.zsh:11> path=( /home/lsmag/.pyenv/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ) 
+/home/lsmag/.zprezto/modules/python/init.zsh:12> pyenv init -
+/home/lsmag/.zprezto/modules/python/init.zsh:12> eval 'export PATH="/home/lsmag/.pyenv/shims:${PATH}"
export PYENV_SHELL=zsh
source ''/home/lsmag/.pyenv/libexec/../completions/pyenv.zsh''
pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`pyenv "sh-$command" "$@"`";;
  *)
    command pyenv "$command" "$@";;
  esac
}'
+(eval):1> export 'PATH=/home/lsmag/.pyenv/shims:/home/lsmag/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
+(eval):2> export 'PYENV_SHELL=zsh'
+(eval):3> source /home/lsmag/.pyenv/libexec/../completions/pyenv.zsh
if [[ ! -o interactive ]]; then
    return
fi
+/home/lsmag/.pyenv/libexec/../completions/pyenv.zsh:1> [[ ! -o interactive ]]

compctl -K _pyenv pyenv
+/home/lsmag/.pyenv/libexec/../completions/pyenv.zsh:5> compctl -K _pyenv pyenv

_pyenv() {
  local words completions
  read -cA words

  if [ "${#words}" -eq 2 ]; then
    completions="$(pyenv commands)"
  else
    completions="$(pyenv completions ${words[2,-2]})"
  fi

  reply=(${(ps:\n:)completions})
}
+(eval):4> pyenv rehash

# Return if requirements are not found.
if (( ! $+commands[python] && ! $+commands[pyenv] )); then
  return 1
fi
+/home/lsmag/.zprezto/modules/python/init.zsh:33> ((  ! 1 && ! 1  ))

# Load virtualenvwrapper into the shell session.
if (( $+commands[virtualenvwrapper.sh] )); then
  # Set the directory where virtual environments are stored.
  export WORKON_HOME="$HOME/.virtualenvs"

  # Disable the virtualenv prompt.
  VIRTUAL_ENV_DISABLE_PROMPT=1

  source "$commands[virtualenvwrapper.sh]"
fi
+/home/lsmag/.zprezto/modules/python/init.zsh:38> ((  1  ))
+/home/lsmag/.zprezto/modules/python/init.zsh:40> export 'WORKON_HOME=/home/lsmag/.virtualenvs'
+/home/lsmag/.zprezto/modules/python/init.zsh:43> VIRTUAL_ENV_DISABLE_PROMPT=1 
+/home/lsmag/.zprezto/modules/python/init.zsh:45> source /home/lsmag/.pyenv/shims/virtualenvwrapper.sh
#!/usr/bin/env bash
set -e
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:2> set -e
[ -n "$PYENV_DEBUG" ] && set -x
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:3> [ -n '' ']'

program="${0##*/}"
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:5> program=virtualenvwrapper.sh 
if [ "$program" = "python" ]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_DIR="${arg%/*}"
        break
      fi
      ;;
    esac
  done
fi
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:6> [ virtualenvwrapper.sh '=' python ']'

export PYENV_ROOT="/home/lsmag/.pyenv"
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:20> export 'PYENV_ROOT=/home/lsmag/.pyenv'
exec "/home/lsmag/.pyenv/libexec/pyenv" exec "$program" "$@"
+/home/lsmag/.pyenv/shims/virtualenvwrapper.sh:21> /home/lsmag/.pyenv/libexec/pyenv exec virtualenvwrapper.sh environment terminal editor history directory python spectrum utility completion prompt
```

The complete log is over 1200 lines long, so if you need it, you can read it [here](http://pastebin.com/EEdQXd2V). Any idea of what might be going on? I'll set up pyenv manually later to inspect virtualenvwrapper (which seems to be the culprit) in detail, but right now I had to disable the Python plugin (=S).

**Comment by oldcai** [comment]
@akrawchyk I've tried to reinstall pyenv and cleaned ```~/.pyenv``` and ```~/.virtualenvs```, and use pyenv-virtualenvwrapper instead of virtualenvwrapper, the problem is still not solved.

Anyone have any knowledge how to make prezto work with python on OS X?

**Comment by pradeepcheers** [comment]
I have the same problem. I don't couldn't find any solution but switched to bash unfortunately!

**Comment by geoelectric** [comment]
You or @sorin-ionescu should consider re-opening this, as it's still a blocking issue running pyenv and virtualenvwrapper with zsh.

One solution would be to split the python module up so that the sourcing virtualenvwrapper is kept separate from init'ing pyenv (which is still useful).

A more seamless solution would be for the module to check whether virtualenvwrapper.sh is actually a shim, and execute pyenv virtualenvwrapper instead if so. 

To detect, the fully-qualified pathname is probably going to always include "shim", and that would be a relatively easy solution that would work strictly off the $commands strings. Also,  the shim file contains PYENV_ROOT as a string whereas the original does not contain PYENV at all, so a quick grep could disambiguate.

**Comment by geoelectric** [comment]
I have a patch running locally that covers the four possibilities (no virtualenvwrapper, vew+no pyenv, pyenv-virtualenvwrapper extension, and pyenv + manual install of vew), but want to exercise it a bit more. Look for a PR this weekend.

**Comment by facastagnini** [comment]
@geoelectric the only person with commit right on this repo is not active (please read #1239 for more details). Please open your PR in the community maintained fork of this repo.

zsh-users is an organization dedicated to host Zsh community projects and therefore became the rational home for a community maintained version of prezto.

Your contribution is greatly appreciated!

https://github.com/zsh-users/prezto

**Comment by geoelectric** [comment]
@facastagnini ah, cool, thanks for pointing me in the right direction there. I'll doublecheck that it hasn't already been fixed in that fork and then will contribute accordingly.
