### ISSUE TITLE
git related error

### ISSUE THREAD

**Issue by michaelaye** [sorin-ionescu/prezto#755]
I am using this setting for git:

``` bash
zstyle ':prezto:module:git:status:ignore' submodules 'none'
```

to not ignore any submodules.
I now get the following error message whenever I enter a git repo and change folder inside the git repo:

``` bash
error: invalid option: --ignore-submodules=dirty
```

Version infos:

``` bash
± uname -a
Linux maven-iuvs-itf.lasp.colorado.edu 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
error: invalid option: --ignore-submodules=dirty
klay6683@maven-iuvs-itf|~/src/iuvs/iuvs on master+
± print $TERM
linux
error: invalid option: --ignore-submodules=dirty
klay6683@maven-iuvs-itf|~/src/iuvs/iuvs on master+
± print $OSTYPE
linux-gnu
error: invalid option: --ignore-submodules=dirty
```
- zprezto: 9539341 from Nov 24
- zsh: 5.0.7

**Comment by nachocab** [comment]
@sorin-ionescu I'm still getting this error, even after deleting the three lines you mentioned. Is there anything else I'm missing. I use `vcs_info` in my [prompt](https://github.com/johan/zsh/blob/master/Functions/Prompts/prompt_bart_setup), could that be it?

**Comment by sorin-ionescu** [comment]
That zstyle only affects the Prezto Git status implementation, `git-info`, not `vcs_info`.

**Comment by nachocab** [comment]
@sorin-ionescu I know, it's just that I can't figure out for the life of me what is adding that submodules option to the git status call.
