### ISSUE TITLE
cp -f does not work

### ISSUE THREAD

**Issue by yuantaotao** [sorin-ionescu/prezto#769]
I've installed prezto by the default way.

When I doing "cp -rf foo/* bar/", it keep asking me to confirm weather overwrite the file or not.

But since I've typed the "-f" parameter in the command, it should just do the overwrite.

Is there anything I'm wrong? or some thing should be changed?

**Comment by sorin-ionescu** [comment]
`\cp -rf` will call `cp` directly avoiding the alias.
