### ISSUE TITLE
Prezto attempts to create symbolic links on shell initialization

### ISSUE THREAD

**Issue by adamweld** [sorin-ionescu/prezto#770]
Hi, whenever I start a new shell I get a number of errors as prezto tries to replace my existing zsh rc files:

    ln: failed to create symbolic link ‘/home/adamweld/.zlogin’: File exists
    ln: failed to create symbolic link ‘/home/adamweld/.zlogout’: File exists
    ln: failed to create symbolic link ‘/home/adamweld/.zpreztorc’: File exists
    ln: failed to create symbolic link ‘/home/adamweld/.zprofile’: File exists
    ln: failed to create symbolic link ‘/home/adamweld/.zshenv’: File exists
    ln: failed to create symbolic link ‘/home/adamweld/.zshrc’: File exists

I didn't find the code responsible for this in prezto's runcom files, how can I stop it from happening?

**Comment by yecine06** [comment]
Hello,

I have the same issue and haven't found how to fix it even searching other issue on the project didn't lead me to a solution.

Can someone point me to the right direction ?
