### ISSUE TITLE
"fatal: This operation must be run in a work tree"

### ISSUE THREAD

**Issue by xpe** [sorin-ionescu/prezto#771]
I'm getting this error after changing into the `.git` directory in a git project

> fatal: This operation must be run in a work tree

I can help track down more details a bit later. I expect that the git module is causing this.

**Comment by sorin-ionescu** [comment]
It should not run if it's not in the work tree.

**Comment by Bose90** [comment]
I am kind a newbee in github and trying to push my local code in to my repo.
repo = https://github.com/Bose90/C-_Code.git

what i did ?
1. I did the code changes locally.
2. used this command git remote add origin https://github.com/Bose90/C-_Code.git
3. Now i want to push my code to github but it says 
susbose@N-20HEPF13YD28 MINGW64 ~/.git/cpp_code (GIT_DIR!)
$ git add .
fatal: this operation must be run in a work tree

Hi i am also getting the same error.
