### ISSUE TITLE
nicoulaj prompt does not use the color it is supposed to use

### ISSUE THREAD

**Issue by xuhdev** [sorin-ionescu/prezto#773]
the nicoulaj prompt has a screenshot which shows green PROMPT if last command is successful, otherwise red. However, in the default install, nicoulaj simply shows a white prompt. The content of `prompt_nicoulaj_setup` also indicates the PROMPT should have some color.

I tried a few other prompts, they are not affected.

**Comment by sorin-ionescu** [comment]
Check your terminal emulator theme.

**Comment by xuhdev** [comment]
@sorin-ionescu I found the issue: zsh does not know that my terminal supports 256 color.

For the sake of compatibility with those terminals which really do not support 256 color, can we replace `%F{071}` and `%F{124}` with `%F{green}` and `%F{red}` in the theme? I don't really see any visual difference.

**Comment by sorin-ionescu** [comment]
Your terminal settings are the problem. What does $TERM say?

**Comment by xuhdev** [comment]
$TERM says `xterm`. Has to change to `xterm-256color` to make zsh recognize it. I have already fixed this problem for my terminal emulator in X, but if I switch to the "real" terminal (Ctrl + Alt + F2), there is no 256 color.

**Comment by xuhdev** [comment]
Sorry for the confusion, what I meant was actually to change the colors to the close common used colors to improve compatibility. It's not a problem for me, but may be useful for many people who prefer text mode.

**Comment by sorin-ionescu** [comment]
The last I recall, [framebuffer](
http://en.m.wikipedia.org/wiki/Linux_framebuffer) does not support 256
colours.

This is not my theme. It's up to @nicoulaj to alter it.
