### ISSUE TITLE
RVM GEM_HOME

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#774]
The latest version of RVM is throwing a warning:

```
Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p247'.
```

More info: https://github.com/wayneeseguin/rvm/issues/3212
Related file: https://github.com/sorin-ionescu/prezto/blob/master/modules/ruby/init.zsh#L15

**Comment by sorin-ionescu** [comment]
I do not know. I do not use RVM. They may have changed it recently. Execute the given instructions and compare the modified files to how the Ruby module initialises it.

**Comment by mpapis** [comment]
@leoj3n check this issue https://github.com/robbyrussell/oh-my-zsh/pull/1359/files - it looks like you might have done something similar yourself, check `~/.zprofile` for `path=(...)` or `PATH="..."`

**Comment by leoj3n** [comment]
I'm not having any real issues with RVM. Is this a non-issue?

**Comment by mpapis** [comment]
this is an issue as the RVM warnings state - but it's nothing on RVM / Prezto site, it's most likely your shell configuration files - make sure to fix them and try again.

**Comment by leoj3n** [comment]
FWIW, misusing `sudo` with `rvm` is what caused the warning for me. It might be worth throwing an error suggesting `rvmsudo` instead as this warning was a bit of a false flag.

**Comment by leoj3n** [comment]
At any rate, thanks for your attention @mpapis and @sorin-ionescu.

**Comment by mpapis** [comment]
Open a ticket for RVM to extend the warning when in sudo.

**Comment by jaythaceo** [comment]
Solved for me:
export PATH=/path/to/something

into

export PATH=$PATH:/path/to/something

source http://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm

**Comment by leoj3n** [comment]
Followup backlink: https://github.com/wayneeseguin/rvm/pull/3272
