### ISSUE TITLE
Vim mode: edit inner word

### ISSUE THREAD

**Issue by Schabernack** [sorin-ionescu/prezto#778]
Suppose the following situation with your cursor between 3 and 4: `123|456`

Expected behavior when pressing `diw` when using vim mode: all numbers get deleted. We stay in command mode.

Actual behavior: when `i` is pressed, the terminal switches to insert mode.

**Comment by sorin-ionescu** [comment]
Zsh emulates vi, not Vim, and it's not a full implementation.

**Comment by Schabernack** [comment]
I wasn't aware this is a vim feature. Too bad.

**Comment by leoj3n** [comment]
I also wish it was a more full implementation; there's a lot missing.

**Comment by sorin-ionescu** [comment]
It's a shell, not a text editor.

**Comment by kyounger** [comment]
You can always use vim to edit your command line: http://unix.stackexchange.com/questions/6620/how-to-edit-command-line-in-full-screen-editor-in-zsh

**Comment by leoj3n** [comment]
@kyounger Great! Thank you

**Comment by leoj3n** [comment]
For anyone else, pressing <kbd>ESC+V</kbd> is already implemented by [modules/editor/init.zsh](https://github.com/sorin-ionescu/prezto/blob/master/modules/editor/init.zsh#L244)

**Comment by PaBLoX-CL** [comment]
Isn't this somewhat closer to what you are trying? #636 (https://github.com/hchbaw/opp.zsh).
