### ISSUE TITLE
Fuzzy history search for zsh?

### ISSUE THREAD

**Issue by zkanda** [sorin-ionescu/prezto#782]
As what the title says,
Can this be done with zsh? I kind miss this feature like ctrlp.vim

**Comment by leoj3n** [comment]
I use https://github.com/junegunn/fzf#useful-examples and just typ `fh` at the command line.

**Comment by zkanda** [comment]
Whoah, amazing. Hmm Thank you very much, you can close this issue if you like but this would be helpful plugin for prezto.
:+1:

**Comment by sorin-ionescu** [comment]
That's useful, but it says TODO under Zsh.
