### ISSUE TITLE
Why default sorin theme had no git info?

### ISSUE THREAD

**Issue by leopku** [sorin-ionescu/prezto#788]
I used antigen ealier (and oh-my-zsh more ealier) and transformed to prezto just now.
I used prezto with default sorin theme. And It seems so simple especially no git info like below:

```
~/.z/m/p/functions ❯❯❯
```

But ![sorin theme](https://camo.githubusercontent.com/7ce78ae9a06575f026e4f9b79a09ceb1f7bb107b/687474703a2f2f692e696d6775722e636f6d2f417a6a6d70774d2e706e67) are more complex.

What's wrong with my configuration?

**Comment by henriiik** [comment]
You have to enable the git module in your zpreztorc.

Here's a link to the correct place to do it:
https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zpreztorc#L24

**Comment by crsmithdev** [comment]
Seeing the same issue, and I have enabled git:

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt'

zstyle ':prezto:module:prompt' theme 'sorin'
```

Resulting prompt:

```
~/p/repo❯❯❯
```
