### ISSUE TITLE
Terminal Module Seems to Break FAT32 Filesystem Calls

### ISSUE THREAD

**Issue by iwoloschin** [sorin-ionescu/prezto#792]
This is an odd issue on OS X 10.10.2.  I've got a FAT32 USB Stick that I'm using to update a server BIOS.  When I mount the USB stick with the "terminal" module loaded I can't read the directory:

/Volumes ❯❯❯ ls
2GB       computer
/Volumes ❯❯❯ cd 2GB
/V/2GB ❯❯❯ ls
.
/V/2GB ❯❯❯ cd ..
/Volumes ❯❯❯ ls 2GB
BIOS.ROM AFUDOS.EXE   AUTOEXEC.BAT COMMAND.COM  KERNEL.SYS   LOCALE       autorun.ico  autorun.inf

If I remove the "terminal" module from ~/.zpreztorc then I can read the FAT32 file system no problem:

/V/2GB ❯❯❯ ls
BIOS.ROM AFUDOS.EXE   AUTOEXEC.BAT COMMAND.COM  KERNEL.SYS   LOCALE       autorun.ico  autorun.inf

I'm not familiar enough with ZSH or what this module is doing to know where to start looking, but I may try to explore a bit this weekend.

**Comment by sorin-ionescu** [comment]
The terminal module has no control over system calls. It is shell code, not a kernel module or system driver.

**Comment by iwoloschin** [comment]
I agree, but that doesn't change the fact that with the terminal module loaded, trying to "ls" a FAT32 directory fails.  I've tried this on both OS X and Funtoo Linux with similar results.  I suspect something is getting hung up on FAT's emulated permissions, but I'm not sure.

**Comment by sorin-ionescu** [comment]
The module doesn't do anything related to permissions. You'll have to go line by line to figure out what's causing it.

**Comment by honnix** [comment]
Sorry to bring this up. This is actually very reproducible. The cause I could find was setting window title `print -Pn "\e]2;%s\a"`. Yes, very strange.

It's a combination of iTerm2 (maybe other emulators as well) + zsh + "setting window title" + FAT32 + "executing `ls` inside the mounting point".

Not sure whose problem it is.
