### ISSUE TITLE
Fresh install on debian missing themes seen in OS X?

### ISSUE THREAD

**Issue by dijikul** [sorin-ionescu/prezto#793]
Installed using these instructions yesterday on OS X and was thrilled.  Attempted to replicate setup on debian (Linux cloud 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux) and only seeing _some_ prompt themes:

Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram

Missing steeef and sorin, plus potentially others.

**Comment by sorin-ionescu** [comment]
You didn't install it properly. Try again from scratch.

**Comment by dijikul** [comment]
@sorin-ionescu: after re-following the instructions here: https://github.com/sorin-ionescu/prezto and reviewing here: https://wiki.archlinux.org/index.php/Zsh#Prompts and here: http://linhmtran168.github.io/blog/2013/12/15/ditching-oh-my-zsh-for-prezto/ , the output of `prompt -l` only shows 16 themes...  What am I doing wrong?


>cloud% prompt -l
>Currently available prompt themes:
>adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram
>cloud%
