### ISSUE TITLE
How can I restore the default behavior for `cat >> filename` in my config?

### ISSUE THREAD

**Issue by johnstephens** [sorin-ionescu/prezto#794]
Hi! One thing I miss using Prezto is the ability to instantly create and write to a new text file with the command `cat >> {filename}`. In addition to using `cat >>` on its own, I sometimes put it at the end of a pipe to dump the output of another script into a temporary file.

When I enter that command now, I get an error message: "zsh: no such file or directory: {filename}". In order to do what I used to do takes three steps now (because my brain is stubborn):

1. `cat >> {filename}` -- fails.
2. `touch {filename}`
3. `cat >> {filename}` -- success.

I realize I could simply launch Vim following a similar pattern, ie. `vi {filename}`, but I'm accustomed to using the cat command faster.

I searched Prezto's directories, but I can't find where `cat`'s behavior is redefined. I verified that using `cat` in zsh without Prezto works like I'm used to.

I'd love to learn the use cases that Prezto's definition of `cat` is meant to support.

Is there anything I can add to my .zshrc to restore the default behavior?

**Comment by sorin-ionescu** [comment]
You have to use `>>!` instead of `>>`. This is a protection from overwriting existing files. To disable it, see the directory module.

**Comment by johnstephens** [comment]
Thank you!
