### ISSUE TITLE
Clarify globbing magic in README

### ISSUE THREAD

**Issue by mralexgray** [sorin-ionescu/prezto#805]
I know I am probably just dumb...  but I tried to find, and could not.. what the following constructs are doing... (from the README)

`(.N)` and `:t`

    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"

I know this is just simple parameter expansion... but it would be great if these could be elaborated upon, and would provide a good example of what parameter expansion _IS_, and _how to use it_, lol

**Comment by sorin-ionescu** [comment]
You found the answer, and anyone who cares can do so as well with `man zshexpn`.
