### ISSUE TITLE
Git module not loading properly with iterm2 and osx 10.10.3

### ISSUE THREAD

**Issue by dougpiston** [sorin-ionescu/prezto#809]
When I enable the git module I have to hit ctrl+c after every command to get back to a prompt. Also I have to do this once the terminal is started. Judging by the iterm title it seems curl is starting? Attached a screen shot of what I see once first opening the terminal. If there is more info needed please let me know. Almost certain this is a user error issue as my googlefu return 0 results.

https://www.dropbox.com/s/ypcsxn6er2vsiz4/Screenshot%202015-02-17%2020.52.10.png?dl=0

**Comment by sorin-ionescu** [comment]
The Git module does not use `curl`.
