### ISSUE TITLE
Break out core presto configuration from customizations

### ISSUE THREAD

**Issue by rchady** [sorin-ionescu/prezto#812]
Just tossing this out as an idea.  One thing I've noticed about Prezto is it has all types of really nice things in the modules that are shipped with it, but if you want to make any changes you have to go in and directly make changes to the shipped modules.

I'd like to suggest that things be broken out a little more so you have the core features driven by variables and then aliases and other behavioral changes can be set elsewhere, in a more user controlled space. 

The purpose is to allow for easy following of Prezto's awesomeness without having to have your own fork to update it for your own settings.  Instead people would be able to check out Prezto itself and then only make changes in the user specific area.  That way trying to make a change to an alias doesn't get clobbered (or worse yet, result in a merge conflict) when you try to update.

**Comment by sorin-ionescu** [comment]
This has been discussed a few times. Please use the search bar. Prezto is designed to be modified in place and managed via Git. Separate customisation can and will go out of sync with Prezto causing problems and more open issues on this project's tracker.
