### ISSUE TITLE
Use Git aliases + branch name completion?

### ISSUE THREAD

**Issue by jasonlong** [sorin-ionescu/prezto#815]
When using explicit `git` commands, you can get completion options for branch names.

E.g. `git branch -d my` + `<Tab>` would complete the branch name to `mybranch`

However if you use `gbx my` + `<Tab>` completion options seem to be limited to files in the current directory. Is there a way of having the git aliases attempt branch names?

Thanks for all your work on prezto @sorin-ionescu!

**Comment by sorin-ionescu** [comment]
It works fine for me.
![screen shot 2015-02-22 at 22 02 10](https://cloud.githubusercontent.com/assets/93816/6322265/8572270c-bade-11e4-89b4-e3c374505b14.png)

**Comment by jasonlong** [comment]
Thanks @sorin-ionescu, I'm happy to know that this **should** work and that it's just something on my end.

I haven't messed with anything with the completion module that I know of. Here is my module section from `zpreztorc`:

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'syntax-highlighting' \
  'editor' \
  'history' \
  'history-substring-search' \
  'homebrew' \
  'directory' \
  'osx' \
  'spectrum' \
  'utility' \
  'completion' \
  'ruby' \
  'git' \
  'prompt'
```

I've tried moving the completion module around (including at the end), but that doesn't seem to matter.

We do use `hub` at work and I have these lines in my `zshrc`:

```
# This is needed for hub/git autocompletion
setopt complete_aliases
```

I tried commenting the `setopt` out, but it didn't seem to help. Do you think this or the hub usage could be a problem?

**Comment by sorin-ionescu** [comment]
That option ought to already be enabled. Some of your modules are loaded too early like syntax-highlighting and history-substring-search.

```sh
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'git' \
  'archive' \
  'osx' \
  'perl' \
  'python' \
  'ruby' \
  'fasd' \
  'node' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt'
```

**Comment by sorin-ionescu** [comment]
That option will cause problems when Zsh sees `gbx` as a distinct command instead of `git branch -d`. By default, Zsh will complete files for commands that have no completion defined.

> COMPLETE_ALIASES
>              Prevents aliases on the command line from being internally  sub-
>              stituted  before completion is attempted.  The effect is to make
>              the alias a distinct command for completion purposes.

You load some modules, like *syntax-highlighting* and *history-substring-search*, too early; they use a lot of ugly ZLE (Zsh Line Editor) hacks to work; so, they should be loaded as late as possible, right before *prompt*.

```sh
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'git' \
  'archive' \
  'osx' \
  'python' \
  'ruby' \
  'fasd' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt'
```

**Comment by jasonlong** [comment]
Thanks again. I'm still not having any luck, but I'll continue to play with it. Seems like this might be related https://github.com/github/hub/issues/363

**Comment by sorin-ionescu** [comment]
Remove hub; does it work?

**Comment by jasonlong** [comment]
It doesn't seem to help. Still digging...
