### ISSUE TITLE
[behavior] diff defaults to git-diff even when not in repository

### ISSUE THREAD

**Issue by abraithwaite** [sorin-ionescu/prezto#818]
I was trying to recursively diff a directory when I discovered that `diff` is a function defined in prezto.

Is there any interest in adding a check to the function to see if there's a git path up the tree before using `git-diff`?  I realize that git-diff can be used outside of git repos, but I was surprised by this behavior.

**Comment by sorin-ionescu** [comment]
This was just discussed in #813, #814. Install `colordiff` or disable colour using `zstyle ':prezto:module:utility:diff' color 'no'` in *zpreztorc*.

**Comment by abraithwaite** [comment]
Sorry, I'm an idiot.  I had a typo when searching the issues.

Thanks for pointing me in the right direction and sorry for the bother.
