### ISSUE TITLE
prepending variables triggers errors

### ISSUE THREAD

**Issue by Thanatermesis** [sorin-ionescu/prezto#821]
I get errors in my terminal when I run something like this:

~ ❯❯❯ TEST=1 echo
~ ❯❯❯ ^C
TEST=1:  comand not found
~ ❯❯❯

(explanation:  prepend a variable to a command and hit enter, in the returned prompt press Ctrl - C, it returns an error message)

This is caused by the 'command-not-found' module, if you disable it it doesn't happens

**Comment by sorin-ionescu** [comment]
What's your question? `command-not-found` is sourced by Prezto but is not inside of Prezto; so, if it is causing problems, notify its developer.
