### ISSUE TITLE
Readme theme

### ISSUE THREAD

**Issue by ephexeve** [sorin-ionescu/prezto#822]
I wonder what's the theme being used in the Readme.md?
![Theme](https://camo.githubusercontent.com/7ce78ae9a06575f026e4f9b79a09ceb1f7bb107b/687474703a2f2f692e696d6775722e636f6d2f417a6a6d70774d2e706e67)

```
~/W/dotfiles git:master ❯❯❯ prompt -l
Currently available prompt themes:
agnoster cloud damoekri giddie kylewest minimal nicoulaj paradox peepcode powerline pure skwp smiley sorin steeef adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram```

**Comment by sorin-ionescu** [comment]
My theme, the default theme: sorin.
