### ISSUE TITLE
Completion hangs

### ISSUE THREAD

**Issue by oblitum** [sorin-ionescu/prezto#824]
Hi, I found completion buggy in two situations, and it's quite annoying since the shell gets completely stalled and I have nothing to do except wait or terminate it.

It's quite simple to reproduce, first case is when you're passing flags and don't provide a space character between the flag and the directory, if you happen to press tab, completion gets stuck:

```
❯❯❯ clang++ -F/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/... (some other flags)
```

Another situation for a long hang is when you navigate a git repository directory that's full of submodules, like the current C++ Boost from GitHub. It hangs for a while but the first situation is the most annoying one.

While I've written this, my CPU is still 100% with terminal stuck because I've pressed tab for completion.

**Comment by sorin-ionescu** [comment]
I confirm, but I'm speculating that this is an upstream bug in the clang completion, which is not part of Prezto.

**Comment by oblitum** [comment]
OK, interesting since I didn't know it was something clang specific or that prezto was being so clever. One thing to note though is that, generally for any tool, trying to complete a directory after a flag without putting a space for separation is broken. May if this could get fixed at a high level, everything would work.
