### ISSUE TITLE
cant update submodule

### ISSUE THREAD

**Issue by sosia** [sorin-ionescu/prezto#839]
`git pull && git submodule update --init --recursive

> Already up-to-date.
Cloning into 'modules/prompt/external/agnoster'...
fatal: unable to access 'https://gist.github.com/3712874.git/': Failed to connect to gist.github.com port 443: Operation timed out
Clone of 'https://gist.github.com/3712874.git' into submodule path 'modules/prompt/external/agnoster' failed

**Comment by wd** [comment]
me too, seems the website is down.

**Comment by wd** [comment]
It's ok now. I can clone now.

**Comment by sosia** [comment]
still cant update submodule agnoster, why?
` git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" `

> Cloning into '/Users/dony/.zprezto'...
remote: Counting objects: 8482, done.
remote: Total 8482 (delta 0), reused 0 (delta 0), pack-reused 8482
Receiving objects: 100% (8482/8482), 1.69 MiB | 201.00 KiB/s, done.
Resolving deltas: 100% (3749/3749), done.
Checking connectivity... done.
Submodule 'modules/completion/external' (https://github.com/zsh-users/zsh-completions.git) registered for path 'modules/completion/external'
Submodule 'modules/history-substring-search/external' (https://github.com/zsh-users/zsh-history-substring-search.git) registered for path 'modules/history-substring-search/external'
Submodule 'modules/prompt/external/agnoster' (https://gist.github.com/3712874.git) registered for path 'modules/prompt/external/agnoster'
Submodule 'modules/prompt/external/powerline' (https://github.com/davidjrice/prezto_powerline.git) registered for path 'modules/prompt/external/powerline'
Submodule 'modules/prompt/functions/pure' (https://github.com/sindresorhus/pure.git) registered for path 'modules/prompt/external/pure'
Submodule 'modules/syntax-highlighting/external' (https://github.com/zsh-users/zsh-syntax-highlighting.git) registered for path 'modules/syntax-highlighting/external'
Cloning into 'modules/completion/external'...
remote: Counting objects: 2235, done.
remote: Total 2235 (delta 0), reused 0 (delta 0), pack-reused 2235
Receiving objects: 100% (2235/2235), 888.25 KiB | 159.00 KiB/s, done.
Resolving deltas: 100% (1288/1288), done.
Checking connectivity... done.
Submodule path 'modules/completion/external': checked out 'ed964013e290677c866a055e1c1ece6f33f64151'
Cloning into 'modules/history-substring-search/external'...
remote: Counting objects: 253, done.
remote: Total 253 (delta 0), reused 0 (delta 0), pack-reused 253
Receiving objects: 100% (253/253), 71.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... done.
Submodule path 'modules/history-substring-search/external': checked out '9f9fc7d550cc547737f4c686591cbbf07e7470b0'
Cloning into 'modules/prompt/external/agnoster'...
fatal: unable to access 'https://gist.github.com/3712874.git/': Failed to connect to gist.github.com port 443: Operation timed out
Clone of 'https://gist.github.com/3712874.git' into submodule path 'modules/prompt/external/agnoster' failed

**Comment by sorin-ionescu** [comment]
Duplicate of #830.
