### ISSUE TITLE
How to manage the dotfiles

### ISSUE THREAD

**Issue by lazywei** [sorin-ionescu/prezto#840]
Hi,

Currently, prezto asks us to symlink the dotfiles provided in the repo into our $HOME. However, what if I customize my `.zshrc`? If I make some customization, it will be a conflict with upstream (i.e., this repo) `.zshrc`. How should I resolve such issue? I don't want to resolve conflict everytime upstream update.
Or is there any guarantee that at least the `.zshrc` in this repo will not be modify in a regular basis?

Thanks

**Comment by PaBLoX-CL** [comment]
That's the whole point of prezto. Be managed via git. There exists a lot, lot of issues trying to create zshrc local and stuff like that, all of them have been systematically rejected by the author. The idea of prezto is that you maintain your own fork and it's your task to solve the conflicts when they arise.

PS.- @sorin-ionescu, maybe it's a good idea to create a wiki page, so we don't have to explain the same thing every time.

**Comment by lazywei** [comment]
Is agree we should manage dotfiles through git. In fact, i've host a dotfiles github repo for myself. However, I don't really like to maintain a fork myself. Also, I have already had a dotfiles repo, and that means I would need to use submodule for prezto, which I don't really like.
What I imagine is prezto being non intrusive. That is, prezto doesn't provide zshrc. Instead, prezto should let me include the init.sh manually. In this way, I can commit my zshrc while updating prezto without contaminate my repo.



-- Chih-Wei

**Comment by sorin-ionescu** [comment]
@PaBLoX-CL, it is expected of GitHub users to search issues before opening a new one.
@lazywei, use Git.

**Comment by lazywei** [comment]
You are not answering the question... the problem isn't git, I AM USING THE GIT ALREADY.



-- Chih-Wei

**Comment by lazywei** [comment]
that's why FAQ exists in the world...

**Comment by sorin-ionescu** [comment]
Prezto is dotfiles. It's not a framework that can be installed globally without modification. So, add it to your dotfiles repository as a submodule or subtree.
