### ISSUE TITLE
prompt_preview_theme parse error when previewing the adam2 theme

### ISSUE THREAD

**Issue by irwincong** [sorin-ionescu/prezto#841]
To be clear, this issue is with previewing the adam2 theme and not with using the theme itself. I personally do not feel the need to preview themes often, so I would consider this to be a low priority issue anyways. Also, the parse error does not come up when previewing other themes. Parse error message when previewing the adam2 theme is copied below.

~/.zprezto ❯❯❯ uname -a; git pull && git submodule update --init --recursive; prompt -p adam2
Linux awl 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Already up-to-date.

adam2 theme:
prompt_preview_theme:14: parse error
.-(~/.zprezto)-------------------------------------------------------------------------------------------------------------------------(iong-local@awl)-
`--> command arg1 arg2 ... argn

**Comment by sorin-ionescu** [comment]
That theme comes with Zsh, not Prezto; so, it's not a Prezto issue.
