### ISSUE TITLE
Fresh install today did not work

### ISSUE THREAD

**Issue by maxmx** [sorin-ionescu/prezto#842]
Installed a few hours ago on a colleague's computer, ran the script from readme.md

It was at this commit. (4 commits back)
c34098af20cafdf016f68f3e7f612ed60ca93aa1

After install it refused to load any modules. Never figured out why. Deleted the files, reset hard to a commit from march 2014 which I had on my computer and knew was working, reinstalled and it worked.

This may mean that the current master is broken for fresh installs.

**Comment by maxmx** [comment]
It would not recognise the prompt command (or any) + there seemed to be a little ascii guy with !1 in the bottom corner.

**Comment by sorin-ionescu** [comment]
I use the latest on my system; if it were broken, I would see it immediately. Some Chinese users had trouble installing due to the Great Firewall of China.

**Comment by maxmx** [comment]
Allright, we get new hires next week, when I install it on their brand new computers I'll see if I can reproduce consistently

**Comment by sorin-ionescu** [comment]
Try to paste the code in a file and execute said file. Make sure that there are no `.z*` files present in the home directory. 

I have avoided adding an installer because I want advanced users to use it to keep the number of issues low.

**Comment by maxmx** [comment]
Thanks will do! And thanks for Prezto!
