### ISSUE TITLE
Remove interactive commands by default

### ISSUE THREAD

**Issue by pickfire** [sorin-ionescu/prezto#843]
I thinks that **interactive** commands should be *disable* by default and it should be set in `.zshrc` with

```bash
alias cp='cp -i
alias rm='rm -i'
alias mv='mv -i'
```

Should interactive commands be enabled by default?

**Comment by sorin-ionescu** [comment]
What do you mean?

**Comment by pickfire** [comment]
I mean that the *commands* should not be executed with **interactive options**. Example:

```bash
# Wrong
rm -i
# Correct
rm
```

**Comment by sorin-ionescu** [comment]
Prezto is used interactively. Hence why it protects you from shooting your own feet.

**Comment by pickfire** [comment]
> Prezto is used interactively. Hence why it protects you from shooting your own feet.

But shouldn't it be in `.zshrc` template?

**Comment by sorin-ionescu** [comment]
No.

**Comment by pickfire** [comment]
Thank you.
