### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by pcragone** [sorin-ionescu/prezto#844]
Hi there -

Hopefully you can point me in the right direction.  I was a longtime oh-my-zsh user, heard about prezto and figured I'd give it a try.  Took a little while to get everything set up the way I had it with oh-my-zsh, no biggie (for some reason prompt colors are completely different between the two).  However, the biggest difference is that prezto is *extremely* slow.  This seems to be exclusively a rendering thing; running `time` on a command returns values sub-0.01s.  However, it clearly takes 1-2 seconds to display anything.  If I were to, say, press enter 10 times in a row, it takes prezto about 20 seconds to catch up.

Any thoughts on where i can get started diagnosing this?

Edit: This seems as though it may be related to the size of the git repository in the current folder (alternatively, it could be the size of the current folder I suppose)

**Comment by sorin-ionescu** [comment]
Type* prompt off*. Is it still slow? Is it slow in Git repositories or
everywhere? If it is slow in only Git repositories, do you have any Git
wrappers installed, for example, *hub*? Do you have any processes running
that are trashing the disk?

**Comment by pcragone** [comment]
It is not slow after I turn off the prompt with `prompt off`.

It appears to only be slow in git repositories.  Interestingly, it appears to only be an issue with my dotfiles repository.  Possibly something to do with having my vim config in there (which is rather large, and made up of many repositories itself), as well as prezto...?

I have no git wrappers installed.

I have no processes running that are trashing the disk.

**Comment by sorin-ionescu** [comment]
That's probably it. You can disable checking submodule status, see the Git README.

#796 will help. I'll push it today.

**Comment by diegocaro** [comment]
If you are in OS X, try doing 
sudo xcode-select -s /Library/Developer/CommandLineTools

This should be faster than loading the git command from Xcode.app
