### ISSUE TITLE
Tab complete doesn't work with relative paths

### ISSUE THREAD

**Issue by pzuraq** [sorin-ionescu/prezto#848]
When I try to tab complete on a relative path, zsh inserts the full path of the relative path. Examples:

```
cd ~/
# press tab
cd ~//Users/pzuraq/

cd ../../
# press tab
cd ../..//Users/pzuraq/
```

**Comment by sorin-ionescu** [comment]
It works fine here. I cannot reproduce.

**Comment by pzuraq** [comment]
Completely removed prezto and reinstalled, same issue. Any idea how I can troubleshoot?

**Comment by pzuraq** [comment]
Issue solved, the home directory was improperly set. It was set to `/users/pzuraq` instead of `/Users/pzuraq` and the mismatch between the casing was causing the bug.
