### ISSUE TITLE
nicoulaj theme doesn't differentiate between vi normal/insert mode

### ISSUE THREAD

**Issue by cflewis** [sorin-ionescu/prezto#850]
I really like the `nicoulaj` theme, but it's missing an indicator to show me whether it's using vi normal or insert mode when using the vi key bindings. All it would need to do is switch from the `>` prompt to `<`.

I tried hacking in the logic from the `sorin` theme which does this, but failed miserably :(

**Comment by sorin-ionescu** [comment]
Ask @nicoulaj if he wants that; it's his theme.
