### ISSUE TITLE
[enhanchement] add bookmarks from Vincent Bernat

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [sorin-ionescu/prezto#852]
Vincent Bernat wrote a nice directory bookmarking function.

https://github.com/vincentbernat/zshrc/blob/9a890371f41b0285fd3a9e8a262aa31b94dedf40/rc/bookmarks.zsh

**Comment by sorin-ionescu** [comment]
How is this superior to `fasd` or `z`?

**Comment by Alessandro-Barbieri** [comment]
Author blog about
http://vincent.bernat.im/en/blog/2015-zsh-directory-bookmarks.html

I'm trying z and fasd (with prezto)
z seems to only "cd directories"
fasd in prezto have only "j" command and is a "cd directory"

How i use a bookmark in a command with fasd?

**Comment by sorin-ionescu** [comment]
`fasd` can do what bookmarks does without having to manually set bookmarks. I've only used it for directory jumps; read its [site](https://github.com/clvv/fasd) for the rest of its features.

**Comment by leoj3n** [comment]
Here's another a less dynamic approach: https://github.com/x0054/hyperjump

**Comment by Alessandro-Barbieri** [comment]
I close this, was stupid to think that others bookmarks plugins didn't exist.
