### ISSUE TITLE
Backslash (/) and period (.) cannot be typed on OSX Yosemite over VNC

### ISSUE THREAD

**Issue by ghostoy** [sorin-ionescu/prezto#857]
I'm working on Windows 8.1 and connect my Mac through VNC. With iTerm 2, the two keys cannot be typed in prezto. With default terminal app, backlash works but period (.) cannot be typed. And when switched to another shell, like bash, the problem is gone. Both keys works with iTerm2 and default terminal app.

**Comment by ghostoy** [comment]
And hyphen (-) is same as period (.) key. I guess there are many keys not working correctly through VNC in prezto.

**Comment by sorin-ionescu** [comment]
How does it behave in pure Zsh, no Prezto?

**Comment by ghostoy** [comment]
It's odd. I can't reproduce it any more. Just close it.

**Comment by jethrolarson** [comment]
I just got this issue too. If I remove prezto it fixes it. I'm going to try restarting my machine.

**Comment by jethrolarson** [comment]
Though I'm not using VNC

**Comment by jethrolarson** [comment]
Nope. Updating OSX and restarting did not resolve. I don't really want to disable prezto. You have any tips on troubleshooting?

**Comment by sorin-ionescu** [comment]
Do you have dot-expansion enabled in zpreztorc? Try disabling it.

**Comment by jethrolarson** [comment]
I gave it a go, but it didn't work.

**Comment by sorin-ionescu** [comment]
Try a different program.
