### ISSUE TITLE
[Question] How to prevent keyboard input while prezto is logging in?

### ISSUE THREAD

**Issue by babygau** [sorin-ionescu/prezto#864]
Hi guys,

Because the `prezto` modules take about 2-3 seconds to load, I find it somehow quite annoying when I type commands while terminal is loading zsh shell. And the terminal (iTerm2) is gonna look like the below pic (notice the second line `it%`). 

![zsh-bug](https://cloud.githubusercontent.com/assets/1514823/7413000/4e03109c-ef8b-11e4-86b7-84441a73a8b4.png)

How to prevent keyboard input while logging zsh shell?

**Comment by sorin-ionescu** [comment]
You can't. #796 will improve usability.
