### ISSUE TITLE
Can't log in with SDDM when prezto is installed.

### ISSUE THREAD

**Issue by akuntsch** [sorin-ionescu/prezto#865]
As soon as I install prezto I can't log in with SDDM. I can still enter my password but it will stay at the login screen and I can't do anything but log in to a tty and remove prezto to get it working again.
This doesn't happen with a clean zsh config or oh-my-zsh.

If there's any way I can help debugging this, let me know.

**Comment by sorin-ionescu** [comment]
Perhaps you have not linked the runcom files correctly.

**Comment by akuntsch** [comment]
Well, I just copy & pasted them into the terminal.

This is how it looks in my home directory:
```
-rw-r--r-- 1 alex alex 36K May  1 09:32 .zcompdump
-r--r--r-- 1 alex alex 78K May  1 09:41 .zcompdump.zwc
-rw------- 1 alex alex 585 May  1 09:53 .zhistory
lrwxrwxrwx 1 alex alex  34 May  1 09:48 .zlogin -> /home/alex/.zprezto/runcoms/zlogin
lrwxrwxrwx 1 alex alex  35 May  1 09:48 .zlogout -> /home/alex/.zprezto/runcoms/zlogout
lrwxrwxrwx 1 alex alex  37 May  1 09:48 .zpreztorc -> /home/alex/.zprezto/runcoms/zpreztorc
lrwxrwxrwx 1 alex alex  36 May  1 09:48 .zprofile -> /home/alex/.zprezto/runcoms/zprofile
lrwxrwxrwx 1 alex alex  34 May  1 09:48 .zshenv -> /home/alex/.zprezto/runcoms/zshenv
lrwxrwxrwx 1 alex alex  33 May  1 09:48 .zshrc -> /home/alex/.zprezto/runcoms/zshrc

.zprezto:
total 20K
drwxr-xr-x 1 alex alex  152 May  1 09:30 .git
drwxr-xr-x 1 alex alex  548 May  1 09:30 modules
drwxr-xr-x 1 alex alex  100 May  1 09:30 runcoms
-rw-r--r-- 1 alex alex   36 May  1 09:30 .gitignore
-rw-r--r-- 1 alex alex  877 May  1 09:30 .gitmodules
-rw-r--r-- 1 alex alex 1.6K May  1 09:30 CONTRIBUTING.md
-rw-r--r-- 1 alex alex 3.6K May  1 09:30 README.md
-rw-r--r-- 1 alex alex 2.9K May  1 09:30 init.zsh

```

As soon as I delete the symbolic links, I can log in again.

**Comment by sorin-ionescu** [comment]
Go file by file to find which one is causing the problem.

**Comment by akuntsch** [comment]
It's the zprofile file causing the issue.

**Comment by sorin-ionescu** [comment]
I can't see anything in zprofile that would cause Zsh to hang.

**Comment by akuntsch** [comment]
Found the problem. SDDM switches to sh emulation before sourcing the zprofile file and because it contains zsh specific syntax there are problems. See for some more information https://github.com/sddm/sddm/issues/352.

**Comment by sorin-ionescu** [comment]
Thank you.
