### ISSUE TITLE
merge upstream conflict pure and external submodules

### ISSUE THREAD

**Issue by calvinchoy** [sorin-ionescu/prezto#867]
Hi allm

I forked this project, and wanted to update to the latest version. I did this before without problem using git fetch upstream and then merge into my own master branch. However, this time I get the following conflict:

```
git fetch upstream
git checkout master
git merge upstream/master
```

warning: Failed to merge submodule modules/prompt/external/pure (commits don't follow merge-base)
warning: Failed to merge submodule modules/completion/external (commits don't follow merge-base)
Auto-merging modules/prompt/external/pure
CONFLICT (submodule): Merge conflict in modules/prompt/external/pure
Auto-merging modules/completion/external
CONFLICT (submodule): Merge conflict in modules/completion/external
Automatic merge failed; fix conflicts and then commit the result.

Anyone know how to fix this?

Thanks

**Comment by sorin-ionescu** [comment]
Use `gSu`.  I have already updated it.
