### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by nxion** [sorin-ionescu/prezto#868]
Maybe it is just me but I don't exactly understand step 3. Is it a case that this is a script that needs to be run? This is what I get when trying to run it. If that is not the correct way to do it please let me know.

```
./zsh: line 2: setopt: command not found
./zsh: line 3: syntax error near unexpected token `('
./zsh: line 3: `for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do'
```

**Comment by nasenatmer** [comment]
Are you executing the 3rd step in `zsh`?

**Comment by nxion** [comment]
I dinally figured out to do that but now when running zsh after making a `.zshrc` with the info from step 3 I get this `ln: /Users/username/.zshrc: File exists`

**Comment by nxion** [comment]
I have fixed the issue. I had to mauanly add a symlink to `.zprezto/init.zsh`. I found the [answer here.](https://github.com/sorin-ionescu/prezto/issues/231)
