### ISSUE TITLE
DNF Support

### ISSUE THREAD

**Issue by blopker** [sorin-ionescu/prezto#873]
DNF has replaced yum now that Fedora 22 has dropped.

Running `yumU` in 22 reports:
```bash
Yum command has been deprecated, use dnf instead.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run 'dnf migrate'Redirecting to '/usr/bin/dnf upgrade'
```

Seems like #407 already discussed this.

Cheers! :beers:

**Comment by sorin-ionescu** [comment]
Thanks. They have not renamed it?

**Comment by blopker** [comment]
They have not. Looks like they're trying for a clean break.

**Comment by sorin-ionescu** [comment]
Eh. They should rename it to something that makes sense.

**Comment by blopker** [comment]
Heh, yeah, I agree. Guess it means [Dandified Yum](https://dnf.readthedocs.org/en/latest/cli_vs_yum.html) 
However, it is better than yum in every way. It's certainly faster.

**Comment by blopker** [comment]
More context: http://dnf.baseurl.org/2015/05/11/yum-is-dead-long-live-dnf/

**Comment by sorin-ionescu** [comment]
Reopened #407.
