### ISSUE TITLE
The order matters. 

### ISSUE THREAD

**Issue by shawnbon206** [sorin-ionescu/prezto#875]
The readme of some plugins clearly state what order they need to be loaded in, and others dont. Does the order only matter sometimes?

For example, the git plugin's readme does not describe when it should be loaded. Does that mean I can put it after 'prompt' if I want to?

Somewhere in the documentation should be a complete list of the plugins, in order they should appear in.

**Comment by skarfacegc** [comment]
afaik only some things matter.  The READMEs in each module usually tell you (i.e. https://github.com/skarfacegc/prezto/tree/master/modules/history-substring-search)  

I've been using prezto for a while and haven't really worried about order unless there's a note in the readme.

**Comment by sorin-ionescu** [comment]
The order matters only for the stated modules. You should load prompt last.
