### ISSUE TITLE
ZSH using 95-99% CPU on OSX 10.10/Yosemite

### ISSUE THREAD

**Issue by JodiWarren** [sorin-ionescu/prezto#879]
I'm not entirely sure how long this has gone on, but the zsh process is using between 95 and 99% CPU constantly. Sometimes it happens very soon after I open the terminal, and sometimes it can take a little longer to happen. But when it does, it seems to be stuck like that. It's usually hovering between 98 and 99.5%, but does fluctuate a little.

![image](https://cloud.githubusercontent.com/assets/1337003/7654306/08951eb2-fb14-11e4-9362-e0de1caa6775.png)

If I kill that process, another one starts up almost instantly with almost exactly the same amount of usage.

I have it running in iTerm2.

I'm using the `sorin` theme, and my module setup is:
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'osx' \
  'ruby' \
  'rails' \
  'homebrew' \
  'git' \
  'node' \
  'syntax-highlighting' \
  'history-substring-search' \
  'prompt' \
```

Any advice would be gratefully received.

**Comment by JodiWarren** [comment]
FWIW, I have come across similar issue in zsh-autosuggestions, but I can't find that being used in any of my Prezto modules:
https://github.com/tarruda/zsh-autosuggestions/issues/24

**Comment by sorin-ionescu** [comment]
Are you using zsh-autosuggestions? It's not part of Prezto due to bugs.

**Comment by JodiWarren** [comment]
No, I just brought it up as it's the only related result I can find on Google. I thought maybe it's being used in Prezto in a way I don't understand.

**Comment by sorin-ionescu** [comment]
Z is not in Prezto either.

**Comment by JodiWarren** [comment]
Absolutely, it's something that I installed separately. Sorry, I should've removed it and tested to eliminate possibilities. I'm guessing you're not aware of this issue occuring with any of the Prezto modules I listed above.

**Comment by sorin-ionescu** [comment]
`syntax-highlighting` is not bug free.

`completion` may cause a temporary freeze, but that is dependent on the completion for a particular command, not every command.

**Comment by JodiWarren** [comment]
Turns out it was a symptom of this issue: http://apple.stackexchange.com/questions/146919/zsh-using-100-of-cpu-during-iwork-install | http://superuser.com/questions/803713/zsh-process-taking-95-of-my-cpu

I had a Keynote update trying to automatically update. Nosing around, there appear to be some hardcoded bash calls in the install script. I changed my shell back to bash, restarted, updated, and changed it back to zsh. It's been behaving perfectly since.

Thank you for trying to help, and apologies for dragging you into something not Prezto related.

**Comment by oblitum** [comment]
Well, autosuggestions is now a supported plugin and recently it has been eating 100% CPU on one of my cores. I couldn't figure out exactly why/when it happens, but it enters a tight loop random, the only fix is `kill -9`. For the moment I've stopped using autosuggestions. I'm on ArchLinux.

**Comment by oblitum** [comment]
My bad, it's not autosuggestions, it's something in my prezto conf, I guess some of the plugins, but dunno what.... Still trying to figure out.

**Comment by johnpneumann** [comment]
If you post your config files it would be helpful given that this issue is 3 years old and much has changed. Or a link to your dotfiles. Thanks!

**Comment by oblitum** [comment]
@johnpneumann it has been like one day I don't see it, so it may have been a zsh bug, I just dunno. My dotfiles are here https://github.com/oblitum/dotfiles.

**Comment by oblitum** [comment]
@johnpneumann and thanks for trying to help. As I can reproduce it lately, it's hard to declare a fix. I was happening quite frequently past days, then stopped. Just mysterious....

**Comment by oblitum** [comment]
@johnpneumann I run ArchLinux.

**Comment by johnpneumann** [comment]
Glad I refreshed before I posted because most of your config is setup for arch so I was quite confused. The original issue here was for OSX, thus the reason I asked. Your configs look sane, so nothing to see there. There's another bug I'm going to look at that was reported for Arch (though it does not appear to be limited to it), so I'll give this a run through to see what I can find. Did the issue come up when it was headless or with a UI?

**Comment by oblitum** [comment]
@johnmaxwelliv while using UI. It was specific, it happened when I left a tmux pane idle, while focusing another one. It was weird because the affected pane with Zsh running was not blocked, but it was consuming 100% of a core, I tried a bit to debug but didn't figure it out.

**Comment by oblitum** [comment]
@johnpneumann I've never gone through this, so I suspected it was related to recent submodule updates on master that I have picked in a recent dotfiles update.

**Comment by johnpneumann** [comment]
@oblitum - Yeah I'm not sure. I spent some time checking this out this morning and am not seeing any anomalies. If you happen to see it again, open a new issue and we can check it out from there.

**Comment by SyfiMalik** [comment]
Unsubscribe

* John P. Neumann <notifications@github.com> [181129 19:55]:

**Comment by oblitum** [comment]
@johnpneumann OK. Thanks anyway for your help :)
