### ISSUE TITLE
git not working since last update (after ca03fd6)

### ISSUE THREAD

**Issue by stefanosc** [sorin-ionescu/prezto#883]
I just pulled the latest changes eager to try the new asynchronous improvements https://github.com/sorin-ionescu/prezto/issues/796  
However after updating git no longer works.  
I spent quite some time debugging and it seems I have something in one of [my runcoms files](https://github.com/stefanosc/prezto/tree/master/runcoms) that is now incompatible.  
Does anyone know if I am doing something wrong?  

Thank you so much for the great work always!

**Comment by srijanshetty** [comment]
Is git not working or git in the prompt not working?

**Comment by stefanosc** [comment]
oops sorry for the confusion, I meant the git module for prezto.  
I played around with the recent commits and if I use upstream any commit works as expected.  
The problem seems to be in one of my runcoms

**Comment by sorin-ionescu** [comment]
I don't see anything that may cause the Git module to fail.

**Comment by stefanosc** [comment]
Thank you @sorin-ionescu for having a look, this is really strange, there must be something else in my fork that broke with the latest updates. I will trying diffing more in depth to see if I spot any difference, let me know if you have any other insight and thanks again!

**Comment by stefanosc** [comment]
Found the issue!
Something didn't merge in the update yesterday, this is the diff that caused the issue:

```diff
-    'prompt' ' $(coalesce "%b" "%p" "%c")%s' \
-    'rprompt' '%A%B%S%a%d%m%r%U%u'
+    'status' '$(coalesce "%b" "%p" "%c")%s%A%B%S%a%d%m%r%U%u'
```

in: **modules/prompt/functions/prompt_sorin_setup**

**Comment by sorin-ionescu** [comment]
It looks fine, see [line 51](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L51).

**Comment by stefanosc** [comment]
I was missing the diff.
So in my prompt_sorin_setup I had the old version:

```
'prompt' ' $(coalesce "%b" "%p" "%c")%s' \
'rprompt' '%A%B%S%a%d%m%r%U%u'
```
after I merged the above diff it started working.
Thanks again @sorin-ionescu 
And by the way the new async works great :smile:
