### ISSUE TITLE
elegantly disable "^I" bind

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [sorin-ionescu/prezto#884]
In order to get https://github.com/tarruda/zsh-autosuggestions/issues/14 working we need to comment these lines:
https://github.com/sorin-ionescu/prezto/blob/a84ac5b0023d71c98bb28a68c550dc13f6c51945/modules/editor/init.zsh#L303-L304

There is a way to achieve the same without commenting the code?

**Comment by sorin-ionescu** [comment]
If you load auto-suggestions after editor, it should override it.

**Comment by Alessandro-Barbieri** [comment]
I load autosuggestion after prezto.

**Comment by sorin-ionescu** [comment]
`bindkey -rM "$keymap" "$key_info[Control]I"` ought to work.
