### ISSUE TITLE
Blinking Cursor in Emacs

### ISSUE THREAD

**Issue by gmmeyer** [sorin-ionescu/prezto#887]
I use in terminal emacs. For some reason, even though my cursor does not blink in urxvt, it blinks in emacs. This only happens with Prezto and it happens in terminals emulators other than urxvt--like Terminator. (This is with Linux.) This also happens with various themes, and even without a theme and without any addons.

Has anyone else encountered this?

**Comment by sorin-ionescu** [comment]
Is this occurring since #796?

**Comment by gmmeyer** [comment]
I'm not sure, what git commit should I checkout to see?

**Comment by sorin-ionescu** [comment]
I just noticed to that you said it happens with many themes, not just my own; so, #796 is not the problem, but your issue is also discussed there at the bottom; it includes an example GIF.

**Comment by gmmeyer** [comment]
![optimised](https://cloud.githubusercontent.com/assets/3253673/7818914/7bca1216-03ac-11e5-8826-f1a48587cafc.gif)

This is my error, it's slightly different, though. It's not erratic cursor behavior, it's certainly unwanted, though.

**Comment by gmmeyer** [comment]
It's not supposed to be blinking at all and it doesn't blink in the normal console or in VIM, just in emacs.

**Comment by sorin-ionescu** [comment]
I do not use Emacs. I do not know what is causing it.

**Comment by gmmeyer** [comment]
I figured it out, which is why I closed this out, it was an emacs issue, but it oddly only started when I installed Prezto.

**Comment by ecraven** [comment]
sorry to revive this, but *how* did you fix this? I seem to have the same problem :(

**Comment by gmmeyer** [comment]
http://www.gnu.org/software/emacs/manual/html_node/emacs/Cursor-Display.html

"Some terminals offer two different cursors: a “visible” static cursor, and a “very visible” blinking cursor. By default, Emacs uses the very visible cursor, and switches to it when you start or resume Emacs. If the variable visible-cursor is nil when Emacs starts or resumes, it uses the normal cursor."

So, in your emacs.el file (or wherever you store your settings) add the following: `(setq visible-cursor nil)`

**Comment by ecraven** [comment]
thank you very much for elaborating on this!
