### ISSUE TITLE
Running Prezto from Emacs

### ISSUE THREAD

**Issue by galderz** [sorin-ionescu/prezto#891]
Hi, I'm trying to run a prezto terminal session from Emacs, but when I execute `M-shell`, a normal ZSH gets loaded. How can I get prezto to kick in? 

Bonus q: Also, how to avoid *Completions* buffer appearing and instead get autocomplete to execute like it does with ZSH or Prezto?

**Comment by sorin-ionescu** [comment]
If Prezto is loaded when you open a terminal program, then it should load in Emacs.

I do not understand your second question.

**Comment by galderz** [comment]
> If Prezto is loaded when you open a terminal program, then it should load in Emacs.

^ Doesn't seem to load it. What can I do to debug this further? Can you give some tips?

The second question I guess it's more of a Emacs question. If you type a folder name partially and you hit TAB, different folder names get autocompleted when running with ZSH + Presto in command line. But, in my current set up on Emacs, instead of autocompleting folder names, it opens a new buffer with completions suggestions which sucks.

**Comment by sorin-ionescu** [comment]
I don't use Emacs. I don't know.

**Comment by galderz** [comment]
`M-x shell` creates an Emacs shell, to get Prezto, you need to run the terminal emulator, with `M-x ansi-term`. More information on the difference between them two [here](https://www.masteringemacs.org/article/running-shells-in-emacs-overview).
