### ISSUE TITLE
prompt pure 1.0.0 requires async

### ISSUE THREAD

**Issue by mafredri** [sorin-ionescu/prezto#892]
Hi,

[sindresorhus/pure](https://github.com/sindresorhus/pure) was updated to 1.0.0 with the commit https://github.com/sorin-ionescu/prezto/commit/f7ea78078f81d2d6fbe71d73274926a3f756a586. Problem is that there was a breaking change, and pure now depends on two files, not just one. `async.zsh` is now a dependency.

Any thoughts on how to solve the problem? Would adding the [mafredri/zsh-async](https://github.com/mafredri/zsh-async) plugin be a plausible solution?

**Comment by sorin-ionescu** [comment]
`ln -s modules/prompt/external/pure/async.zsh modules/prompt/functions/async` fixes it.

I would rather add `zsh-async` as an external module since it's useful in other places. It will have to be loaded like all other modules by adding it in *zpreztorc* since *pure* does not know to use `pmodload async`.

**Comment by sorin-ionescu** [comment]
Your `async` is quite a lot of code. If I were to add it as another module, why should I change https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L62-L92 to use it, my theme would know to `pmodload 'async'`?

Can you comment on #796's rendering issues and #888's freezing issues? Thank you.

**Comment by Stelgard** [comment]
If this can help u, I've solved the problem installing the pure-prompt with npm. But I think the best solution is to add zsh-async as an external module.

**Comment by mafredri** [comment]
Is there a good way of detecting that pure is being used within prezto? If so, I could add that check to pure, and instead of doing `autoload -Uz async && async`, it would do `pmodload 'async'`. Does this sound reasonable?

@sorin-ionescu if you were to use it, one benefit of my `async` library is that it does not rely on files for communication, it all happens within the shell. So no race-conditions should happen and there is nothing that needs to be cleaned up. Other than that it can manage unique jobs (no multiple jobs) and you can tell it to kill of all current jobs if they are no longer relevant. The notifying via `WINCH` is also optional, you can resort to polling for results if you please.

**Comment by Stelgard** [comment]
@mafredri maybe, instead of add that check to pure, we can use a conditional `prompt -c` inside .zpreztorc to check if the selected theme is pure?

**Comment by mafredri** [comment]
@Stelgard mm, I agree that it would be preferable to keep framework specific stuff out of pure, I guess your idea would work just fine as long as the async module get's initialized before the pure `precmd`.

**Comment by sorin-ionescu** [comment]
A check could be added to *modules/prompt/init.zsh*. It would have to keep track of all a sync themes in an array that will require manual updating. It's dirty and error prone.

**Comment by mafredri** [comment]
Cheers :beers:!

**Comment by arthurvr** [comment]
Woohoo! :tada: Thanks!

**Comment by sorin-ionescu** [comment]
I would still like async as an external module though.

**Comment by mafredri** [comment]
You could replace the symlink to prompt_pure_setup with a file, with this contents:
```zsh
local current_dir
current_dir="$(dirname "${(%):-%x}")"

prompt_pure_setup() {
    pmodload 'async'
    source "$current_dir/../external/pure/pure.zsh"
    prompt_pure_setup "$@"
}

prompt_pure_setup "$@"
```

**Comment by sorin-ionescu** [comment]
Why didn't I think of that?

```zsh
pmodload 'async'
source "${0:h}/../external/pure/pure.zsh" || return 1
```

**Comment by mafredri** [comment]
Wouldn't your example get evaluated at run time, even if pure is selected
or not? I wrote mine like I did because I thought it would get initialized
by the command `prompt pure`. I could be wrong and in that case go ahead
with your terser version :-).

**Comment by sorin-ionescu** [comment]
It should not. The contents of the file is wrapped in an auto-loadable function with the name of the file whose body is loaded on first run. You execute it manually with `prompt_pure_setup "$@"` because you are redefining it.
