### ISSUE TITLE
Can't use command `prompt`

### ISSUE THREAD

**Issue by blaisck** [sorin-ionescu/prezto#894]
I've just installed prezto, and when I want to use `prompt` command, it says `zsh: command not found: prompt`, I've check the module and the prompt module is already installed, Did I miss something?

**Comment by sorin-ionescu** [comment]
The prompt module should be last in the module loading list in *zpreztorc*. It doesn't look like you installed it properly. Check the rc files.

**Comment by blaisck** [comment]
Here is my rc
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt'
```

**Comment by sorin-ionescu** [comment]
Is it in your home directory?

**Comment by blaisck** [comment]
yes, all of `.z*` are in home directory, include `.zprezto directory

**Comment by sorin-ionescu** [comment]
Ensure that you don't have old files. Check to see if the runcoms were linked properly.

**Comment by blaisck** [comment]
I reinstall it and everything goes well, thanks Sorin.

**Comment by ruthmpardee** [comment]
Hi @sorin-ionescu I'm facing this same issue. In the troubleshooting tips duplicated at the top here, I also don't understand where to point the `PATH` to. I'm using Mac OS X.

How do I ensure I don't have any old files? I don't know what `Check to see if the runcoms were linked properly` means.

Thanks for any help!
