### ISSUE TITLE
Updating to latest zprezto causes my Right prompt to not appear

### ISSUE THREAD

**Issue by wonbyte** [sorin-ionescu/prezto#895]
I just did an update for zprezto and I am no longer seeing my right side prompt. I have tried rebuilding the zcomp but no luck. Here is what my .zshrc looks like:

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#----- Make the prompt actually look cool (emoji, yay!)
zstyle ':prezto:module:editor:info:keymap:primary' format ''
zstyle ':prezto:module:git:info:branch' format '%b%f'
zstyle ':prezto:module:git:info:clean' format '%F{113}'
zstyle ':prezto:module:git:info:ahead' format ' %%B%F{yellow}⬆ %%b%F{yellow}%A%f%%b'
zstyle ':prezto:module:git:info:behind' format ' %%B%F{yellow}⬇ %%b%F{yellow}%B%f%%b'
zstyle ':prezto:module:git:info:stashed' format ' %%B%F{cyan}💼 %f%%b'
zstyle ':prezto:module:git:info:modified' format ' %%B%F{blue}🔨 %f%%b'
zstyle ':prezto:module:git:info:untracked' format ' %%B%F{white}🚧 %f%%b'
zstyle ':prezto:module:git:info:unmerged' format ' %%B%F{yellow}⚡ %f%%b'
zstyle ':prezto:module:git:info:keys' format \
  'prompt'  ' %F{242}±%f$(coalesce "%C%b" "%p" "%c")%s' \
  'rprompt' '%A%B%S%a%d%m%r%U%u'
PROMPT_PATH_MAX_LENGTH=30
PROMPT='%F{242}${SSH_TTY:+%n@%m }%F{cyan}%$PROMPT_PATH_MAX_LENGTH<…<%~%<< %F{113}%(?::%F{red})%(!.%B❯❯❯%f%b.%B❯%f%b) '
RPROMPT='%F{242}%* ${_brew_info}${editor_info[keymap]}${editor_info[overwrite]}%(?:: %F{red}⏎%f)${VIM:+" %B%F{green}V%f%b"}%f${git_info:+${(e)git_info[prompt]}}${git_info[rprompt]}'

# Customize to your needs...
alias cls='clear'
alias hist='history 1 | less'
alias lsdirs='ls -d */'
alias vi='vim'

# Source program specific files
if [ -e $HOME/.profile.d ]; then
    for i in $HOME/.profile.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    done
    unset i
fi

**Comment by wonbyte** [comment]
just as a sanity check, I removed all of zprezto and reinstalled. I don't get the right prompt for the default Sorin theme either.

**Comment by wonbyte** [comment]
~/dotfiles ❯ echo $RPROMPT
${editor_info[overwrite]}%(?:: %F{1}⏎%f)${VIM:+" %B%F{6}V%f%b"}${git_info:+${(e)git_info[status]}}

However I don't get a right prompt

**Comment by wonbyte** [comment]
I tried changing the theme, I had zstyle ':prezto:module:prompt' theme 'sorin' in my zpreztorc file. Using a different theme seems to show the right prompt now. Was something changed in the default sorin theme?

**Comment by wonbyte** [comment]
i've isolated it to this line:
zstyle ':prezto:module:git:info:keys' format \
  'prompt'  ' %F{242}±%f$(coalesce "%C%b" "%p" "%c")%s' \
  'rprompt' '%A%B%S%a%d%m%r%U%u'

Any help is appreciated

**Comment by stefanosc** [comment]
@wonbyte have a look at https://github.com/sorin-ionescu/prezto/issues/883 I believe it is related.
I am not so sure, as I never got much into shell coding, but I do know that in one of the last updates the following diff was introduced:

```diff
-    'prompt' ' $(coalesce "%b" "%p" "%c")%s' \
-    'rprompt' '%A%B%S%a%d%m%r%U%u'
+    'status' '$(coalesce "%b" "%p" "%c")%s%A%B%S%a%d%m%r%U%u'
```

**Comment by wonbyte** [comment]
@stefanosc I check that module and it looks correct. I'm still having issues with the line above. Something with the latest updates is causing it to not render.

**Comment by wonbyte** [comment]
@sorin-ionescu oddly if I revert to the odd of the box sorin theme all works fine. Seems like one of the latest changes has caused my customizations to fail.

Seems to be this line:

zstyle ':prezto:module:git:info:keys' format \
'prompt' ' %F{242}±%f$(coalesce "%C%b" "%p" "%c")%s' \
'rprompt' '%A%B%S%a%d%m%r%U%u'

**Comment by stefanosc** [comment]
@wonbyte I believe something changed in the last release of soring theme and `rprompt` no longer works as expected from previous releases.

**Comment by sorin-ionescu** [comment]
Do a clean install on a new user account. If it works, then you didn't merge it properly.

**Comment by wonbyte** [comment]
@sorin-ionescu I did a clean presto install so there was no need to merge. I don't understand what it is about the above line that seems to be causing issues.

**Comment by sorin-ionescu** [comment]
Are you sure? Those lines no longer exist, see https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L128-L129.
