### ISSUE TITLE
weird behavior when copy paste words

### ISSUE THREAD

**Issue by seansay** [sorin-ionescu/prezto#897]
When I ssh into a server and logout, my terminal has this werid behavior:

when copy a word like `github`, and paste in to command line, I get `00~github01~`, which means extra chars in frond and in end, any idea how this hapends? 

my loaded module is

```
zstyle ':prezto:load' pmodule \
  'environment' \
  'git' \
  'tmux' \
  'ruby' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt'
#
```

**Comment by sorin-ionescu** [comment]
I don't think this is Prezto's fault. Those chars could be parts of broken escape codes. If you try to execute it, does it say `github` not found or `00~github01~` not found?

**Comment by seansay** [comment]
@sorin-ionescu 
hey it's `00~github01~` not found..not sure what's the problem..

**Comment by sorin-ionescu** [comment]
It looks like you're copying escape codes.

**Comment by derykfoote** [comment]
@seansay Where are you copying the text from? Maybe try pasting it to your terminal as plain text (Ctrl + Shift + v)? Open a bash shell and see if the issue continues?
