### ISSUE TITLE
add support for reattach-to-user-namespace (also a question on how I could do it)

### ISSUE THREAD

**Issue by skarfacegc** [sorin-ionescu/prezto#899]
On OSX, when you're within a tmux session you don't have a valid user session to the layer of the OS that runs the UI.  Full explanation of the issue (along with the solution) is [here](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard).

Short answer is, if you want to run some kinds of gui type stuff from the command line within tmux you need to run the command with `reattach-to-user-namespace`.  So far I know of 3 command line tools that have this problem.
- pbcopy
- pbpaste
- subl (the sublimetext command line interface).

I'm sure there are others.  I'd love to have access to some global setting that is true when running under tmux and reattach-to-user-namespace is in the path.  I'm not super familiar with the best way to do this under zsh.  

Set a zstyle in zpreztorc  if under $TMUX is set and the reattach-... is in the path?

**Comment by zmwangx** [comment]
Well, I think a better place for that might be `tmux.conf`. I have the following line in there:

    set-option -g default-command "reattach-to-user-namespace -l zsh"

**Comment by skarfacegc** [comment]
While that works, I generally prefer to keep my default shell out of my tmux config.  I may use the same tmux config on devices that don't have zsh.  prezto deals with configuring zsh, tmux deals with configuring terminal multiplexing.  Separation of concerns ...

**Comment by sorin-ionescu** [comment]
Does it support variables? `set-option -g default-command "reattach-to-user-namespace -l $SHELL"`
This is the best option.

**Comment by zmwangx** [comment]
> Does it support variables?

Yes it does.

**Comment by zmwangx** [comment]
> prezto deals with configuring zsh

But `pbcopy` and `pbpaste` doesn't work in any shell out of the box, not only Zsh. So if you might use multiple shells, it makes even more sense to put it in `tmux.conf`.

**Comment by skarfacegc** [comment]
pbcopy and pbpaste (at least under mavericks) work fine outside of tmux.

**Comment by zmwangx** [comment]
I meant, `pbcopy` and `pbpaste` don't work in any *tmux shell* out of the box.

**Comment by skarfacegc** [comment]
I didn't know about using the $SHELL var, that covers part of my concern about putting it into the tmuxconf.  I use the same tmux (and the same zprezto) on 5 or 6 boxes running OSX/linux/freebsd.  Only the OSX side of things needs the reattach.  In my mind, what I want to do is change the way I'm calling a command.  To me, that's a function of shell level aliases, not a function of tmux.  

That said, I'm probably just going to fork my tmux.conf and add the reattach-to-user-namespace as suggested on the OSX fork.  It's much easier :)  just wanted to explain where I was coming from.

**Comment by zmwangx** [comment]
Good point, I haven't used tmux on Linux for a long time and I haven't even noticed my `tmux.conf` (which is shared in dotfiles) doesn't work ;) Anyway, I suppose this should be cross-platform (can you confirm?):

    if-shell "test $OSTYPE = darwin" "set-option -g default-command 'reattach-to-user-namespace -l $SHELL'"

I'm using `test` for compatibility.

**Comment by zmwangx** [comment]
Second attempt:

    if-shell "type reattach-to-user-namespace" "set-option -g default-command 'reattach-to-user-namespace -l $SHELL'"

This hopefully work in quite a few shells with the `type` builtin.

**Comment by skarfacegc** [comment]
works great.  thanks.
