### ISSUE TITLE
Sorin prompt and aliased directories

### ISSUE THREAD

**Issue by quicknir** [sorin-ionescu/prezto#900]
As far as I can tell, sorin prompt seems to ignore hashed directories. Example:

     hash -d z=/home/nir/Downloads
    cd /home/nir/Downloads

And I see:
    ~/Downloads ❯❯❯

I don't know whether or not this behavior is intentional. Intuitively though it seems to me that if you alias a directory you'd like to see it on the left as e.g. ~z. This issue could basically be solved by doing something like:

    local pwd=$(print -P '%~')

in the function prompt_sorin_pwd. That print command will expand the current path taking directory aliases (and home) into account. From there, some slightly modified logic could do the correct first letter only parsing.

Thoughts? I'll also mention that I plan to submit a theme soon that is basically a branch of sorin, so if people don't want to change the behavior of sorin, I could put this behavior in my branch instead.

**Comment by sorin-ionescu** [comment]
I never liked hashed directories. They are not descriptive enough.
