### ISSUE TITLE
Sorin RPROMPT is being overwritten

### ISSUE THREAD

**Issue by domoritz** [sorin-ionescu/prezto#903]
Adding for example the virtualenv to https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L135 does not work because it is being overwritten in https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L83

Btw, is there any reason not to include the vitualenv by default? It seems like something a lot of people use.

**Comment by zmwangx** [comment]
`RPROMPT` here has to be overwritten for async rendering.

Nothing prevents you from adapting the theme for your own need. On the other hand, stuffing things into the shipped default theme is not a good idea — okay, say we added `virtualenv`, then what about `rvm`? `nvm`? `pyenv`? Whatever other version manager? The theme quickly gets unnecessarily bloated, and someone who unsuspectingly installs, say, `rvm` would suddenly get a persistent version string in his prompt wherever he goes, whether he's a Ruby dev or not. Not a pleasant experience.

**Comment by domoritz** [comment]
Fair enough. It;s just that the instructions in https://github.com/sorin-ionescu/prezto/blob/master/modules/python/README.md don't really work because any change to the RPROMPT variable in line 135 get overwritten.

**Comment by zmwangx** [comment]
Okay. The README isn't that up-to-date and precise; a quick blame shows that the "theming" section was written in 2012, when async prompts weren't so popular yet. Async was added to Prezto this year.

**Comment by sorin-ionescu** [comment]
Line 135 exists to override a previous theme's `RPROMPT` when one switches from one theme to another via the `prompt` function since it fails to clear it. I suppose `unset RPROMPT` would be more descriptive.
