### ISSUE TITLE
zsh crashes when completion list doesn't fit on screen

### ISSUE THREAD

**Issue by shanky061** [sorin-ionescu/prezto#907]
removing `zstyle ':completion:*:default' list-prompt` line saves it from crash.

**Comment by sorin-ionescu** [comment]
Can you give an example?

**Comment by shanky061** [comment]
when i type `ls /bin/` and press `tab`, it show me files that can shows up on the screen and when i press any key other than `Enter` it crashed with core dumped.

**Comment by sorin-ionescu** [comment]
I cannot reproduce. It doesn't not crash here with the latest Zsh.

**Comment by shanky061** [comment]
after updating zsh to 5.0.8 from 5.0.7 its fixed!!! thanks.

**Comment by shanky061** [comment]
It still crashes when pressing any arrow key, PgUp, PgDn or any special key that send more than 1 char to terminal.

**Comment by m45t3r** [comment]
I was having segfaults using some keys during auto complete too, but I discovered it was the fault of running both prezto and grml-zsh-config at the same time (in Arch Linux, grml-zsh-config is a package that when installed its location is /etc/zsh/zshrc, so it is sourced by every user). Putting ``unsetopt GLOBAL_RCS`` inside ``~/.zshenv`` solved the problem for me.

**Comment by shanky061** [comment]
Removing the package `grml-zsh-config` from my Arch Linux fixes the issue. thanks @m45t3r
