### ISSUE TITLE
How could we integrate this with Mackup?

### ISSUE THREAD

**Issue by ccorcos** [sorin-ionescu/prezto#912]
https://github.com/lra/mackup

**Comment by sorin-ionescu** [comment]
It's [integrated](https://github.com/lra/mackup/blob/master/mackup/applications/prezto.cfg).

**Comment by ccorcos** [comment]
Ah. "prezto" not "zprezto". Thanks!

**Comment by sorin-ionescu** [comment]
The name of the project is Prezto. We add *z* in front file names to follow the Zsh standard; so, that you can easily `mv z* dst/`.

**Comment by ccorcos** [comment]
oh, your right!
