### ISSUE TITLE
Disabling completions for a particular command

### ISSUE THREAD

**Issue by ryankask** [sorin-ionescu/prezto#925]
When I try to run tests with Django's `manage.py` and want to complete a path to the test, I only see "no matches found" and a blank line is inserted above my prompt each time I hit tab.

I realise the problem may be in zsh-completions or my own configuration but is there a way in my prezto setup to stop completing `manage.py` and treat all completions like `ls` or something that will simply complete a path?

Example output:

TAB

```sh

$ ./manage.py test
 -- no matches found --
```
TAB again

```sh


$ ./manage.py test
 -- no matches found --
```

**Comment by sorin-ionescu** [comment]
You can delete the completion file or you can find the function name(s) and add `unfunction _django_*` late in your zshrc.

**Comment by ryankask** [comment]
Thanks. I tried adding the `unfunction` but I still got some errors. 

This worked: `compdef -d manage.py`
