### ISSUE TITLE
themes not working

### ISSUE THREAD

**Issue by covici** [sorin-ionescu/prezto#927]
If I try to load a theme and start a new zsh, all I get is % for the prompt.

However, if I have 
prompt gentoo in my zshrc that works.

**Comment by sorin-ionescu** [comment]
Is the prompt module listed in the modules list in zpreztorc?

**Comment by covici** [comment]
Yes, it was there.


Sorin Ionescu <notifications@github.com> wrote:

> Is the prompt module listed in the modules list in zpreztorc?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-136174583
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by sorin-ionescu** [comment]
Do `print -l $fpath`. See if the prompt module functions directory is listed.

**Comment by covici** [comment]
Here is the result of that

print -l $fpath
/home/covici/.zprezto/modules/helper/functions
/home/covici/.zprezto/modules/utility/functions
/home/covici/.zprezto/modules/prompt/functions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.8/functions/Calendar
/usr/share/zsh/5.0.8/functions/Chpwd
/usr/share/zsh/5.0.8/functions/Completion
/usr/share/zsh/5.0.8/functions/Completion/Base
/usr/share/zsh/5.0.8/functions/Completion/Linux
/usr/share/zsh/5.0.8/functions/Completion/Unix
/usr/share/zsh/5.0.8/functions/Completion/X
/usr/share/zsh/5.0.8/functions/Completion/Zsh
/usr/share/zsh/5.0.8/functions/Exceptions
/usr/share/zsh/5.0.8/functions/MIME
/usr/share/zsh/5.0.8/functions/Misc
/usr/share/zsh/5.0.8/functions/Newuser
/usr/share/zsh/5.0.8/functions/Prompts
/usr/share/zsh/5.0.8/functions/TCP
/usr/share/zsh/5.0.8/functions/VCS_Info
/usr/share/zsh/5.0.8/functions/VCS_Info/Backends
/usr/share/zsh/5.0.8/functions/Zftp
/usr/share/zsh/5.0.8/functions/Zle


Sorin Ionescu <notifications@github.com> wrote:

> Do `print -l $fpath`. See if the prompt module functions directory is listed.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-136421465
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by sorin-ionescu** [comment]
If you type prompt sorin manually, what happens?

**Comment by covici** [comment]
Well, my current directory is /audio/waves and after typing that I get
/a/waves for a prompt -- I think I tried other prompts and got strange
results.

Sorin Ionescu <notifications@github.com> wrote:

> If you type prompt sorin manually, what happens?
> On Wed, Sep 2, 2015 at 05:37 covici <notifications@github.com> wrote:
> 
> > Here is the result of that
> >
> > print -l $fpath
> > /home/covici/.zprezto/modules/helper/functions
> > /home/covici/.zprezto/modules/utility/functions
> > /home/covici/.zprezto/modules/prompt/functions
> > /usr/local/share/zsh/site-functions
> > /usr/share/zsh/site-functions
> > /usr/share/zsh/5.0.8/functions/Calendar
> > /usr/share/zsh/5.0.8/functions/Chpwd
> > /usr/share/zsh/5.0.8/functions/Completion
> > /usr/share/zsh/5.0.8/functions/Completion/Base
> > /usr/share/zsh/5.0.8/functions/Completion/Linux
> > /usr/share/zsh/5.0.8/functions/Completion/Unix
> > /usr/share/zsh/5.0.8/functions/Completion/X
> > /usr/share/zsh/5.0.8/functions/Completion/Zsh
> > /usr/share/zsh/5.0.8/functions/Exceptions
> > /usr/share/zsh/5.0.8/functions/MIME
> > /usr/share/zsh/5.0.8/functions/Misc
> > /usr/share/zsh/5.0.8/functions/Newuser
> > /usr/share/zsh/5.0.8/functions/Prompts
> > /usr/share/zsh/5.0.8/functions/TCP
> > /usr/share/zsh/5.0.8/functions/VCS_Info
> > /usr/share/zsh/5.0.8/functions/VCS_Info/Backends
> > /usr/share/zsh/5.0.8/functions/Zftp
> > /usr/share/zsh/5.0.8/functions/Zle
> >
> >
> > Sorin Ionescu <notifications@github.com> wrote:
> >
> > > Do `print -l $fpath`. See if the prompt module functions directory is
> > listed.
> > >
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > >
> > https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-136421465
> > > ----------------------------------------------------
> > > Alternatives:
> > >
> > > ----------------------------------------------------
> >
> > --
> > Your life is like a penny. You're going to lose it. The question is:
> > How do
> > you spend it?
> >
> > John Covici
> > covici@ccs.covici.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-136999690>
> > .
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-137134596
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by computergeek125** [comment]
What kind of terminal were you running in?
You can find out by typing `echo $TERM`

**Comment by covici** [comment]
Terminal is linux.

Ryan Smith <notifications@github.com> wrote:

> What kind of terminal were you running in?
> You can find out by typing `echo $TERM`
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-152332915
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by Eriner** [comment]
@covici If you are interested, I have a `debug` module in my fork of prezto. If you add 'debug' to your list of modules in your .zpreztorc, then run `trace-prezto` and send me the archive it produces (create an issue in my fork's tracker), I'll do my best to figure out what is going awry.

**Comment by covici** [comment]
OK, what is your fork address?  Maybe I can try it.

Matt Hamilton <notifications@github.com> wrote:

> @covici If you are interested, I have a `debug` module in my fork of prezto. If you add 'debug' to your list of modules in your .zpreztorc, then run `trace-prezto` and send me the archive it produces (create an issue in my fork's tracker), I'll do my best to figure out what is going awry. 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sorin-ionescu/prezto/issues/927#issuecomment-155003568
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by Eriner** [comment]
@covici https://github.com/Eriner/prezto
