### ISSUE TITLE
Confusing readme file

### ISSUE THREAD

**Issue by hotpxl** [sorin-ionescu/prezto#929]
Hi,

In [README.md](https://github.com/sorin-ionescu/prezto/blob/master/modules/history-substring-search/README.md) for `history-substring-search`, it says "it must be loaded after it". Could you specify what those "it"s refer to?

**Comment by stefanosc** [comment]
This is the complete sentence, I highlighted in bold the answer for your question:  
"If this module is used in conjuncture with the **syntax-highlighting module**, it must be loaded after it."

**Comment by hotpxl** [comment]
the first **it** means **this module** and the second **it** means **syntax-highlighting module**?

**Comment by stefanosc** [comment]
yes, and by the way this is perfectly clear English. 
To remove any doubt whatsoever: 
the  history-substring-search module must be loaded after the syntax-highlighting module. This only applies if you use them both.

**Comment by hotpxl** [comment]
Cool! It's like a string interpolation applied by the order of arguments. This way it makes sense. LOL

**Comment by sorin-ionescu** [comment]
English majors who want to improve the diction of the various READMEs are free to send pull requests.

**Comment by hotpxl** [comment]
Haha. I wonder if english majors would want to spend time on github.
