### ISSUE TITLE
Ruby module looking in the wrong place for rbenv executable

### ISSUE THREAD

**Issue by mecampbellsoup** [sorin-ionescu/prezto#931]
The module currently performs the following check:

``` ruby
elif [[ -s "$HOME/.rbenv/bin/rbenv" ]]; then
```

Since rbenv namespaces executables according to this pattern:

``` ruby
vim ~/.rbenv/versions/2.2.2/
```

... this module should probably perform a check more like this:

``` ruby
elif [[ -s "$HOME/.rbenv/versions/{some_version_number}/bin/rbenv" ]]; then
```

Thoughts?

**Comment by sorin-ionescu** [comment]
How do I find the version number?

**Comment by mecampbellsoup** [comment]
I think we would be able to simply read the contents of the files located here:

```bash
 ❯ cat ~/.rbenv/version                                                                                                [19:06:09]
2.2.2
```

... but I'm not exactly sure what "version" that file is talking about. I think it's present iff someone has set `rbenv global 2.2.2` in this example, but I would have to investigate further.

**Comment by sorin-ionescu** [comment]
Let me know when you figure it out.

**Comment by ressu** [comment]
I'm not sure what the original bug is really about, but the rbenv executable is only present in the bin directory of rbenv root. The ruby binaries on the other hand are present under the various ruby version directories.

So if we are looking for the rbenv executable, then prezto is looking for it in the correct location.

**Comment by belak** [comment]
From my limited understanding of rbenv, the above comment stating that we're checking the right location is accurate.

If this is causing problems for anyone, please let me know and I can reopen the issue.
