### ISSUE TITLE
Update completions submodule

### ISSUE THREAD

**Issue by Soliah** [sorin-ionescu/prezto#933]
Be great to update this. Been a bunch of changes since it was last updated.

https://github.com/zsh-users/zsh-completions/compare/68c949470eaa87c5d67080d32fb2b69c8b837eb4...master

**Comment by sorin-ionescu** [comment]
All Git submodules are updated periodically.

**Comment by Soliah** [comment]
What is the period that they are updated? Been 7 months since the last update.
