### ISSUE TITLE
Update to Sorin theme retaining git branch and symbols after closing

### ISSUE THREAD

**Issue by parnmatt** [sorin-ionescu/prezto#935]
I'm using urxvt, should that help.

MWE:
I change into a git repo

``` zsh
cd ~/.dotfiles
```

My bar indicates the branch at the end (I presume this change was on purpose), along with the standard symbols. In this case: `master ✱ ◼`

I close the terminal using `^D`, and the next terminal I open, which is of course located at my home directory, now has the same information `master ✱ ◼` at the end of the line; though I am not in that directory.

I disappears after a command, or even a simple return, or close `^D` and reopen again.

Now I do not believe it just to be an issue with the EOL character I am using to close; as if I was to close the terminal through the traditional TUI/GUI way, with the 'x' at the top, [well I'm using i3-wm, so `$mod+Shift+q`], has the same behaviour.

**Comment by sorin-ionescu** [comment]
The stale Git status bug has been fixed on my local machine. I'll push it.

**Comment by belak** [comment]
This should have been fixed with the async rewrite a while back.
