### ISSUE TITLE
colordiff doesn't work under Mac OS X

### ISSUE THREAD

**Issue by hotpxl** [sorin-ionescu/prezto#938]
With module `utility` enabled, I see that `diff` is now a function, that will pipe `diff` result to `colordiff`.

The problem is that providing a `difftype` to `colordiff` seems to break it. The result is there is no output at all even if the two files are different. In `colordiff`'s manpage, it says it could determine diff-type automatically, and the example with unified output from `diff` doesn't have an option given to `colordiff`. So I removed `difftype` option to `colordiff` and everything works like a charm.

I'm on Mac OS X 10.10.4 with MacPorts.

**Comment by adriaant** [comment]
Works fine on my 10.10.4, except I use homebrew, not MacPorts.

**Comment by hotpxl** [comment]
As said by `colordiff`, it is OK to directly invoke it on two files. Is there any reason to use `diff` and pipe the result?

Nevertheless, I found something relevant in `colordiff`. I don't know Perl so I'm not sure if it is a bug. But I think many Macports users could be affected by this. Using `colordiff` directly on files won't cause this problem. So I wonder if there is any specific reason not to.

**Comment by hotpxl** [comment]
I have my version of `colordiff` attached. Unzip by `pbpaste | base64 -D | gunzip > colordiff`. Could you try this one for me? See if it's something with my `colordiff`?

H4sIAMPmvFUAA9Vae1fbyBX/n08xMd7aBhsD2WzTGAhpHruck0IOkG63IfGRpbGtIktejRSvG7yfvb87D2kkywZKcrp1chJ75s6dO/c19zGbj7qpiLsDP+xOeRywzmxjY/MrfTY22Vf5EKKXURDFr/zhkHWYw2axMwW53ZhPA8flEx4mbBjFrOEBosGmceSlrh+OKhDZHxdI03iYBixKk2ma3Iuir/JRR5vOY380TljzZWt/d3e/s7+794S9cj5z9nrmxBj38J0fizQcOQnfcaOd9Lr17Sj6A4r/cuwLEusodiYMX4cx50xEwwT84T02j1LmOiGLueeLJPYHacKZnzAn9LpQi0kEvZhLRBhMQ4/HLBlzlvB4Ilg0lD9+PH3PfuQhj52AvUsHge+yt77LQ8GZg71pRIy5xwYKES15Q1RcaCrYmwiYncSPwh7jPuZj9pnHAr/ZvtlEY2wzUKWP1nQSoj9m0ZTWtkD0nAWQc7Z85248+mbMznnqMT+U5xhHU7BvDNLB0JkfBGzAWSo4bKmdI8IS9vPJ5U9n7y/Zi9Nf2M8vzs9fnF7+0sOSZAybY/wzVwj9yTTwgR+cjJ0wmRPDckR/e33+8iesfPHXk7cnl78Q996cXJ6+vrhgb87O2Qv27sX55cnL929fnLN378/fnV28BtMuOJe4LURrhDyUigI5ejxx/ECs5vof0dY2wHxGYnKTnvz+I0+gUM+evY3gBn+dNZ+5UTj0R2zqCNFPxnGUjsYsjPpOmuCfwSDmn1u9jY3JnNXhW/uhM1GMO2QNcpOx9Kw9OW+02szv7ezu7D3Rk8A3VsqtJnM3VgDo8wmYTAAVvs1Ago7ZbJahGifJ9Fm3i6GdjKSdKB51NbybOVIFb7tTDSLG0aw/cEJoAIHsmYXA1p86iTum0V01Suj77sTT29fodw0s2oQuX5wwwX9NeehyITVHXSWCFn6nvvc26urLl9nYT/giY0ntavfx4w97vcd/ntRyoDkPgmi2WAJ6bAON4HDCCkz7NtAgSLPdbKDvbSB37oRVQD/YQHCnGYwNtGcDTZwRrl9nUQZ6UqTJca8rCN+1gTwnvs54ZYB2S3wioIxXFtDjMlDGKwtovwyU8coC+r4MlPHKAvqhDJTxygLaKwNlvLKAnizTpHllARX4FA2Hy2LZ7UkYaOcrPnTSIDEqyfwh68IVdIPIdYIuT9xuZj2xS6709+6OPeJF8Atwzb/B7UtDQIzlh/2E/5Zgt6JSK0sZ+gHvR4EnybGVx5oO+awwLTlvGZpIUgR3+bxhlbbQz0JDWCBKwvLMb3E2uj2VMSI0FFEIF4/7n4m5SPikM/M9rlnClCtMY7VEbvDT2d9eK/pen/79C/3SO4Nfnh+TOykyUTmUZl3wJEGk2YZbdHCklhw+Vjv06eQCa5s1jcdmfQ2w01SMWbMA3ma1nIaCZGotkmXT40M/xFWZQ7WMG8uwWIxN5riqQX4aXofRLGxIfr2MQnjxhCXOQLAkYmKKMFpsiHQAuU/Btj7N9HE1qBkctMW+bJDCqVO3gPK435MjUIWAs2aTtvQx7iPA+o2AcJSrpNZqsSPW2TPr6YN9cFexZjZAH4Kv+222JyOITYY4YMSJOB3lF4CbDdZg2OQp8oEmdv2OPW21Wnol3YO49fKlMt4orG8p0hcbaufexmJDnt4dc/e6DyWSbOw78Sil7ELkh6+HUQhNEOqiMIOe50CScsjmibzG4hEmxNgfJjYPSJRyjv/Kap1OzZ6TRBmUe73CeAg7zEcWRXxqzc0NyzEvI9YH2N6+B2JC9+h31v3U6d4FX8VqdcwxD6a1IoEdHU+Uhj/fifCFJcaYJ2kcZmCZTBHQcTfp59ag0CLQnUWIhxDlAiAWz/Qo7RRzF1anTyBYAIOj0BdSRYjgMEJFnmaCAHjsSAsacL0P9yw8Dl1Ucue5TFsCZ0Tm4ZO3gobOxlzmCRmAk68tfeDTJn5CIbjcnM6RKZ+mVitZrpT27tmkOTsF+RNnLn09iAf+IaiHOSFGSuHL4S/DhNKmSSQS8NYhlzoI5nq9Or2hR0hXKyMouBEN8j70h34OEKtoPAqDOTHiM3nisfOZ+NDY3t6GPVMG3+l0WEMjAHdphUgoCUZC4EhBbGRqZc5Netm82qY/7IYQ3Bwfs1ZBUbVuyAJB2rCNXzpDebndgc6tra07EMcDsUTf1Rb9WUmTW6LpHd25mqIxhdCn7mmbnXqnktGnzinDhbKzcrcPu52/tD9uf3Bc76P+Xl+5d2nrNyf/wF3YURqCv6QgMNE5LgnuQqJumwkfga88fsxH8PUTJXhcrNAcjQYK44ODcgo4wo7UW1Vo2dEwP0UzZIBxm418lQiCqTOuDkzbznmicXsyLdZZ9FZEVrMl2aMxkT3g/kikVsscADo9iiKP8ZBSHQWmgc9ItFPfvTaGR3TFyjozf2DsFMcSkc1o8me2YcFDt9if/lSUQPNKXN1cCfw9qOOfoytB+rhKAvOSCGaSVx4PQIjXdTyPS+MCVQhXFIi2UieQ5ukEM2cupB07fjzzBX++SjeuPnR2tp53rj52RcG7kvO1wb5cbQMONrXoiiq6Z3dQHYcNfPgOX1zP27IaAGK0fMNGSbQkUo0m83BUbJEihZWNuBavdMapSCGEuSUkjdeg4ANL31baCZl+HAVMRl7PJGqhvTwt53G10Sjk2eHt28eKsxYqnebkNnkfeg5vOok8HZxpa+Ke1CM6bc8GHzrXHCF44mYLVJZKCCjop7wd8T7S/DNZNxJNffJOR2Ho5Bvq0pK8geBjwS15+ww4uTVZehqyLM407m0EBwTNAudDZCWeXKUckoSo5ehr7PCIXS2fs60A7ZMUQe0ZDWx4cSg06DKbNKQkOAPLmWPut7NXZ9BEGc8px5JhUqoFZiBi9702vomUU+UpJK5AR+B6NqgYUoi2l47XyuKIn8dwXnDXao7Js1NMwEORxpR1hAK5FBWpdZ0ZuupFZAEC3HcNyWQGuIdg5EhddLlGpwQiojVU1xmkfpB06G5QaZ7IFnsEAl9hshwQQP+ZS5nAlvISHQaXKyA65CyXS3alTkOFuAM4O98o5TCGNcTAaArmNF+evT07f3Xy5s35S2QFB/ZaShByG9OB84G14KgcCBprSGNIUEc05uOOo+lyXCsp6X7a7JKb637CXViEEd0rsd3tjoqjy9kdhVHTAD6t2ThslHDQFo8yddHwRcLpM0VukrCLy1evz89Z7SSUSlhMSZWLa9b7LdIqm1dXYa23hLEYuNNnsUSYOQnF1g0l0UYVdRJW0i4hw6gSij4F5chyodVU/FeUWnrJxV0Inq8AkxTbWr6UV30lik3VsJKKvKZ4qDXk/tLMdsMFlsTdF51/dp3Ov7vFJZojbC0Q0V4UNkL6AITDRorjIW+0Ks+jgA5ZI8quwzV80tC/s0mXgtKP212Km/TwEXTI+nlwyPafPKnadJOdIiePfVfdWRUa0cyQsKdsrTZID2IX2upf5MrFpMLOlrVDhhTWbntP7rfdX2psB3zRe+K6etrCQO3Om/N7ne1p70nv7ucr/tLBk3ZvTVOCUydfVCuHTURpwTpVWXGuVX5T3nUmNVHuk4IcYyWZuTSNS/4mLlXWSKttvqp8Ku+tW7ld2CEKPMJRvUdWgX3IDiGf3bIDFXEfsoMMH6mMu8Y7lgrB/8Uu7mexZpO8lHyPPW5XyPcq7M9C7aKSPcv0cEnd8r3yb24QYUsrBDKZxoKKt52Oin1x18mwz/wOI9WKjRCHxlTuply5cIMaq5CRrZ1QUMUN6LKS2/JVuchYXVoWRqtWqXBxk52YNIxibkSljoxqEdTOfALE1WF6FW2WhggfReHib9AyEN4GKpWaZQm+l8oCscWAASctyEJ9LDnngcwPAacbiIN0JHaQw/lOKNuH7sjv0AMYjMd8GsXJDkae49fh4z8/ffLDY8mtZmdIsj57f6mT/cJZcdjMB9oGT1ejvhftLsnSsOqO2MOWLdjDViPEHl6xpd0wUsNSIK98QbmMkcogpUwXfNtRibusbghWU89oEN3d5NkhvpOAaiq7kLk1lXriwAec6errahlAZo6vX+YYZA0axiXii/HOhuAB1RwVX3sb9Rula1LHv95HJXLFeFUWbZS8inacd7+zPnfTdKJbmfGW1uSdZ93ebhf73FehXKkLAsiIYln/7U84YDzwdjTX6ebK/kPz+MX5j3/PlawSiWQf1Y90DU3leQ4VNUcmiXTAcEeo2tnC9m0rUe4TyjAqYFM5qVohH8hgEpmrPuKxH0IzRIJEcaIfFciRMdyVaU5Nfa+nBLNiX0tEm+wNR1IlEg9+1S5WSJUzejyMo4n0eXJGP2DR9uHT1UipaNOmBKlo56ZGHTcTmOOHYnSvxBxrFTBdbUH2J6fGwdEcU8eV/YAB5/QYyYFvRihBFYcImb0zkW0Eshj8pm5BLEdkOQKnUgdSottRXAsckVAyqFimKlflwsRyhSRTErsBWFlwUsxVhUwiVFBZO+DYlSHoV3koaA2i6BozWU5vITbX+rwh7yIkrdjrwGbXUSE6lB1PWz9gKv1CM86cmWjuE4ctMVB3m5oseYmwnTdPshaJBDWFhCIpd6NkiXnlFhKO2YZ65tBENLHGWoUTWMXAdQfUBiJwZ/etSO7re0L4wk12QXqAoHwa8w6MxIU7J28tg2ZQ0BnMO/S/rvXB9KguIS8LFug2u7RBuCV6RjVx4mvqnpHlCZ49BnNk2Yu7aeLDEeH6xhr5bI7ezMF+00lIlVauuy1DPxbyvR7VeGPPFLR16Yz2041oBcKBCsij0DMgQjVsMsA2axw08M+R0svGTcO8bNMtDYft7e5+h2PECbVaZC1aFal1ab3UQDAN9Xlf8GkfJ7CeClENPvCveYDJdKLbwCsNJfdqp6a1gntw5ISJ2t+LKFwBU/4VDVRxS7qCKBxxkfSzZl9nL+v0fQeSHPhQXBuaMFPZk++RwADfg5+umKxPI4ifCpuYK/a0j+VdpIIDXWRr2mPtgvFQaaxZtCYbuFXsixemLJuU3kM2Kkvb39VoaX31CwYCy+BINgEPR7g8ZJntqMzfqpIjvW0oi2FbWqkNuSwoa6Ni6K+ZAcQHS5grc5eCmL/U/UV1GatekLiGqyjQ1f3yGwA7Gcm+kmfIHnfssh59OSjyr8P2W3Jie7tMeFZ+raKe4uYV1VoSpWzsntBzkmfs5vDL9+3FzfnLC6YyqpuYJ7HPZah5I++DVrmsK/ss6YAeARxmj07IddM7k/2K+q2BpqcO7ANr3hwcfVx68LBSFBUsVhnTkjiOcO5VtZuCRXY696vT2Ic4lIdYfYQlssrasOYAdnS2/gRVSFedYFG0UPbIdgJLpTVZcL8lEALhFRWZos/ThcfKOx5isu/x1WWLdYFCWcfpQ0HAbRUmc7JbgyrzUd6x4KNt77i8SzkWKUJpcVTbf9nPwQVUeIDVhr+kPitNpXS9rpRB4Wau+xX+bumeLkOVizGmsX0yzHt2kAniE7gTP5FZdHY6HdbQ1R3qdTPeQPSDKGtAT2fYxBf6WY1sQ9K7d5k66HzMvK25QELtjk1CITuxuved+EhM+W9ukHrk9uxFlJcxo9kUrbnRxHorU2SQdLwWH9fG1adnl6XYWmuFbAM2i1FAUTb3t407BdK2gBZfP0be0BezqXarsMI+J3tuohR78Bn4nBkURZ3l5CMzWtWO/KsfOgj+VF7d3NlqqRSKvqjXB8U3O6roUCusyqpK9T27CER4sspSfd+eUpgLZci82r1Yl+I1yobd/XSwdLNoIjO6amWJ0UeXErufjtavB/Hr18s20koceQ1tPZb7hRgrNssqc+v3km+P/PABNJdr0WZlLuOllepfU8BdlqxbIdoOe6Bsr7ZvwXCrdK+2SB4PFu/DWW7IoT9MtS7buoN5L6T0qU70b9/2gdKAX/sGlO/euucDVeDR0nqpwkuUrAhH1/CouKHedHWfp5LgIo7/mWf5Bh4hrfIID3YID/UHx38YX/AHF+wm+zmKr4Uqj09jTs/8RDDvWNGnDlbdKKT6l+zX6NJ5x4SUVmQ7xheXXsnfojfzgt7cUo4xYMvVmHK8uo1svaokg3kiTZTT+8LqVam+WUu0s4PK3O6+/qMC8c1axCud7V1QH91O8zp/pRGv83mVilbE8v8Q48yWwldVXRLdJj2H3qbn0K2uHUtbnVP7VWC+jJ5Hb8vn0WYhRdqVC9f6Wv2U+H9Lm+jWu4VZNWm43s97l+a5rrr779i+oy4wdeCoDdc2MUOG6rD+nB0dsae0R9WLW/uVsMFIv9X7AktZ5GA9fzS92PgPGhStk95CAAA=

**Comment by hotpxl** [comment]
OK. I got hold a version of HomeBrew `colordiff`. It doesn't seem there is a difference at all. I'll look into this problem further.

**Comment by hotpxl** [comment]
I guess this is a `colordiff` bug. I had no problem with 1.0.13 (version on Homebrew) but have this problem with 1.0.15.

**Comment by chulkilee** [comment]
#923 worked for me even with colordiff 1.0.15
