### ISSUE TITLE
update the remote url of agnoster to new repo

### ISSUE THREAD

**Issue by pandada8** [sorin-ionescu/prezto#940]
https://github.com/agnoster/agnoster-zsh-theme

**Comment by pandada8** [comment]
btw. as `gist.github.com` is MITMed in the china, using original gist would cause a error when git cloning.
Hope to see the update!
Thanks

**Comment by Lumuy** [comment]
thks. This solved my problem.

**Comment by kaluzki** [comment]
Why is this fix still not merged?

**Comment by Eriner** [comment]
see: https://github.com/sorin-ionescu/prezto/pull/922

**Comment by kaluzki** [comment]
@Eriner Thanks for info. Did I understand this correctly, you would take care of the pull request?

**Comment by Eriner** [comment]
https://github.com/Eriner/prezto/commit/0d3448a881e5fb83df1a8a42839556e1be601e3f
