### ISSUE TITLE
Arch Linux + KDE + zsh + prezto = black screen

### ISSUE THREAD

**Issue by slester** [sorin-ionescu/prezto#944]
On a fresh install of Arch Linux, I more or less just had KDE, zsh, prezto, and git/Firefox etc. After rebooting, I was greeted with a blank screen. I tried for two hours to diagnose the problem, but everything ended up working once I commented out the path variables in prezto's config.

I came to this conclusion because /usr/bin/startkde couldn't find sed, systemctl, mkdir, etc.

**Comment by sorin-ionescu** [comment]
What version of Zsh do you have? What does `print -l $path` say?

**Comment by slester** [comment]
5.0.8 (64 bit)
```
/usr/local/sbin
/usr/local/bin
/usr/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
```
(This is without using prezto at all.)

**Comment by sorin-ionescu** [comment]
What's the path after using Prezto?

**Comment by bananaoomarang** [comment]
If anyone still has problems with this, it's SDDM's fault and I have come across it a few times. See:

https://github.com/sddm/sddm/issues/352

**Comment by PaBLoX-CL** [comment]
I'm not sure, but maybe has to do something related to #500
