### ISSUE TITLE
Problem with git-info in sorin theme

### ISSUE THREAD

**Issue by sajadabedi** [sorin-ionescu/prezto#945]
Hi. i recendly install prezto and active Sorin theme.
But it's don't show git-info like Branch name and etc. ( git plugin is active )
How i can solve this issue?
![image](https://cloud.githubusercontent.com/assets/5726597/9080095/c3b4a064-3b65-11e5-9ac2-a232cb31fb8d.png)

**Comment by sorin-ionescu** [comment]
Type `git-info` manually. Is the function there?

**Comment by songgao** [comment]
I'm seeing the same issue. No `git-info` doesn't seem available. Any ideas?

**Comment by songgao** [comment]
Ah, never mind. I didn't have `git` enabled in `':prezto:load'`.
