### ISSUE TITLE
zsh prezto do not uses LS_COLORS for tab-completion

### ISSUE THREAD

**Issue by djadmin** [sorin-ionescu/prezto#950]
zsh prezto do not uses LS_COLORS for tab-completion. Or please let me know any alternative to change the completion color for now.

Thanks

**Comment by sorin-ionescu** [comment]
[It does](https://github.com/sorin-ionescu/prezto/blob/a275db55d6fdc8bf92a4722e95196bbfbf44cfae/modules/completion/init.zsh#L79).
