### ISSUE TITLE
Double process in ps

### ISSUE THREAD

**Issue by cheshirecatalyst** [sorin-ionescu/prezto#951]
Fresh install upon new session on osx, two processes are started within microseconds of each other, is this the expected behavior?

**Comment by cheshirecatalyst** [comment]
it's a `cat` and it appears to leave behind process too when exiting out

```
| |-+= 10824 root login -fp emris
 | | \-+= 10825 emris -zsh
 | |   |-+= 10893 emris pstree
 | |   | \--- 10894 root ps -axwwo user,pid,ppid,pgid,command
 | |   \-+= 10890 emris -zsh
 | |     \--- 10892 emris cat
 | |-+= 10647 emris /bin/zsh --login
 | | \-+= 10712 emris /bin/zsh --login
 | |   \--- 10714 emris cat
 | \-+= 09525 root login -fp emris
 |   \-+= 09526 emris -zsh
 |     \--= 09582 emris weechat
```

**Comment by sorin-ionescu** [comment]
I don't know. See https://github.com/sorin-ionescu/prezto/search?utf8=%E2%9C%93&q=cat.

**Comment by cheshirecatalyst** [comment]
right what  pattern would i grep through the code base to find something that is starting another -zsh

**Comment by sorin-ionescu** [comment]
If it's not casing 100% CPU, don't worry about it.

**Comment by cheshirecatalyst** [comment]
It's a problem because i have like 12 shells open, which results in 24 processes, so when i do a generic ps, it looks like this now

```
43314 ttys000    0:03.05 -zsh
43380 ttys001    0:00.18 -zsh
43382 ttys001    0:00.01 cat
13855 ttys002    0:07.61 -zsh
39361 ttys002    0:02.64 node /usr/local/bin/nodemon
40058 ttys002    0:00.91 node index.js
13920 ttys003    0:00.49 -zsh
13922 ttys003    0:00.01 cat
26517 ttys004    0:00.63 -zsh
26583 ttys005    0:00.01 -zsh
26585 ttys005    0:00.00 cat
14176 ttys006    0:02.52 -zsh
14241 ttys007    0:00.14 -zsh
14243 ttys007    0:00.01 cat
43581 ttys008    0:07.45 -zsh
43646 ttys009    0:00.26 -zsh
43648 ttys009    0:00.01 cat
88070 ttys010    0:00.77 -zsh
88135 ttys011    0:00.04 -zsh
88137 ttys011    0:00.00 cat
24254 ttys012    0:00.54 -zsh
24319 ttys013    0:00.01 -zsh
24321 ttys013    0:00.00 cat
24330 ttys014    0:01.44 -zsh
24395 ttys015    0:00.09 -zsh
24397 ttys015    0:00.01 cat
22048 ttys016    0:26.47 node /usr/local/bin/nodemon
33563 ttys016    0:02.66 -zsh
33631 ttys017    0:00.13 -zsh
33633 ttys017    0:00.01 cat
28812 ttys018    0:01.82 -zsh
28877 ttys019    0:00.04 -zsh
28879 ttys019    0:00.00 cat
```

**Comment by sorin-ionescu** [comment]
I know not why this is happening to you. You'll have to track it down yourself.

**Comment by cheshirecatalyst** [comment]
I traced this to the pure theme.

**Comment by sorin-ionescu** [comment]
What's wrong with it?

**Comment by cheshirecatalyst** [comment]
I'm not sure exactly. I'm going to track it down in there here in a few, I will get back with you.

**Comment by cheshirecatalyst** [comment]
Commenting out [async line 27](https://github.com/sindresorhus/pure/blob/master/async.zsh#L27) to [async line 33](https://github.com/sindresorhus/pure/blob/master/async.zsh#L33) removes the perpetual cat process. Not sure what to look for to find why is it spawning a duplicate zsh process.

**Comment by cheshirecatalyst** [comment]
So to be honest, I'm not very skilled when it comes to shell scripting, any sort of hint about what i could be looking for that would spawn another shell?

**Comment by cheshirecatalyst** [comment]
nvm located it in [async.zsh](https://github.com/sindresorhus/pure/blob/master/async.zsh#L57) this whole function if commented out, leaves only one zsh process and no cat however it seems to be fairly core to how the whole thing works

**Comment by sorin-ionescu** [comment]
Contact its author.
