### ISSUE TITLE
After prezto git commit uses nano

### ISSUE THREAD

**Issue by jrock2004** [sorin-ionescu/prezto#956]
So I just started using Prezto and in my .zshrc I set my editor to be vim. When I do a git commit it brings up nano instead of vim. Any ideas what I am doing wrong?

**Comment by nfnty** [comment]
From `git-commit(1)`:

```
ENVIRONMENT AND CONFIGURATION VARIABLES
       The editor used to edit the commit log message will be chosen from the GIT_EDITOR environment variable, the core.editor configuration
       variable, the VISUAL environment variable, or the EDITOR environment variable (in that order). See git-var(1) for details.
```

**Comment by jrock2004** [comment]
Should I put that in zshrc or the zprestorc?

**Comment by nfnty** [comment]
zprofile

**Comment by jrock2004** [comment]
gotcha, then what is the zshrc file used for?

**Comment by nfnty** [comment]
https://github.com/sorin-ionescu/prezto/tree/master/runcoms
