### ISSUE TITLE
setting tmux autostart yes, disables 256 color

### ISSUE THREAD

**Issue by atomi** [sorin-ionescu/prezto#957]
```
%echo $TERM
screen-256color

%tmux a
```
first tmux window 256 color is working 

now I set auto-start to yes
```
set zstyle ':prezto:module:tmux:auto-start' local 'yes'
```

and open a new terminal window.
This new tmux session does not have 256 color. But the first tmux session still does.

```$TERM``` remains ```screen-256color```

**Comment by atomi** [comment]
Fixed my issue by appending 
```export TERM='screen-256color'```

to my ``` .zpreztorc``` file

**Comment by tasmo** [comment]
I does not work when I open a new tmux window with `tmux neww` within an existing tmux session.
