### ISSUE TITLE
add directions for pre-existing .zshrc files

### ISSUE THREAD

**Issue by torsday** [sorin-ionescu/prezto#961]
Currently if you already use zsh, there is nothing to say that you need to rename your pre-existing ```.zshrc``` file for installation to work.

**Comment by hugdru** [comment]
There is something that grml zsh does that I like.
From https://github.com/grml/grml-etc-core/blob/master/etc/zsh/zshrc#L14 :
# If you are using this file as your ~/.zshrc file, please use ~/.zshrc.pre
# and ~/.zshrc.local for your own customisations. The former file is read
# before ~/.zshrc, the latter is read after it.

**Comment by sorin-ionescu** [comment]
Your previous zshrc can conflict with Prezto. There are also many Zsh configuration file, and Prezto adds another one: zpreztorc.

**Comment by sorin-ionescu** [comment]
@hugdru The grml zshrc is huge and dangerous to modify. It make sense to have a pre and post in that case. The Prezto zshrc is tiny, safe to modify in place.
