### ISSUE TITLE
Few seconds of freeze when going back to terminal after a while

### ISSUE THREAD

**Issue by Pouya-moh** [sorin-ionescu/prezto#962]
This is a little difficult to explain, but here it is: 
I am having a problem that I didn't have with oh-my-zsh (hence I think it's a prezto issue not zsh). When I'm on command line working with przto everything is fine. Then I switch to e.g., my browser or IDE and work for while while my terminal is sitting on the background doing nothing. When I switch back to terminal and start to type, everything is frozen for few seconds and then goes back to normal. Once it starts to respond again, it shows all of the keys that I have pressed when the terminal was frozen. 
I have this issue with all of my terminal emulators. Any ideas?

**Comment by sorin-ionescu** [comment]
No idea.

**Comment by ff2000** [comment]
Do you use a rotating HDD or an SSD? How much RAM do you have?
It might be tat you visited some websites that used up a lot of RAM, so your system starts to swap. Then moving back to your terminal will have to load resources from swap to ram which might take some time. You usually would hear/see your HDD working in that case.

But I have to say I THINK I saw this or a similar issue myself (~3 times), where I did have some disc activity after switching back to my terminal (it felt too short for being actually loaded from swap, my HDD is.... slow...), but it did not respond immediately after disc went quiet and system activity went to idle, there were another 5-10 seconds where the terminal was unusable. I thought this probably was an issue with tmux - @Pouya-moh do you use tmux, too? But I also used OMZ+tmux before and never saw this issue with that setup (after swapping back I could use it immediately)

**Comment by Pouya-moh** [comment]
@ff2000, I have a HDD. In terms of Ram I have 8 on a linux machine. It is not really a mater of memory or page swap issue since I didn't have this problem with oh-my-zsh. I also constantly check my ram usage (important for my work). I had it the issue with xfce-terminal and now that I'm testing konsole for couple of days, I see it less frequently.

**Comment by dude051** [comment]
I have this same issue on a newly re-imaged retina macbook pro (SSD with 16GB ram) so I don't think its hardware.I too recently switched from OMZ.

On another note when I have my terminal open now it freezes at random times just as described here and its almost as if finder is crashing as the date, user, finder and notification center disappear from the top status bar and when they pop back in thats when the freezing stops. The load on my box also jumps to like 7.

Trying to trace and look through the logs for an explanation but so far nothing.

**Comment by Eriner** [comment]
@dude051 is the problem reproducible? What I mean is, are there a set of steps that you can take to *always* reproduce the problem?

**Comment by dude051** [comment]
So I may have narrowed it down to a notifyd issue with OS X. Sorry to have pointed at prezto as the issue, but it looks like tmux is the culprit and my issues may be unrelated to the OP.

https://github.com/tmux/tmux/issues/108
