### ISSUE TITLE
Pure and zstyle ':prezto:module:editor:info:keymap:primary'

### ISSUE THREAD

**Issue by ahmedelgabri** [sorin-ionescu/prezto#965]
I'm using Pure theme and I tried to [show current mode when using vi keybindings](https://github.com/sindresorhus/pure/wiki#show-current-mode-when-using-vi-keybindings)

After following the steps I can't see the `❯` anymore and in tmux I get this error `editor-info:9: bad math expression: illegal character: ^"` but if I do this for example `zstyle ':prezto:module:editor:info:keymap:primary'   format "test"` it works and I can see `test`.

Any idea where is the problem?

**Comment by simonbcn** [comment]
Similar problem. I have _paradox_ theme activated. I execute: `prompt -p pure` and:
```
pure theme:

~
❯ command arg1 arg2 ... argn


 juan@gentoo  ~
 ❯                           
editor-info:9: bad math expression: operand expected at `%B%F{blue}...'
```
After running this I get the error every time I press `ENTER`.

I've installed `prezto` today following the instructions in main page. 
`zsh 5.1.1 (x86_64-pc-linux-gnu)`

**Comment by sorin-ionescu** [comment]
I started with the **sorin** prompt in emacs mode then did the following and it works.

```sh
prompt pure
bindkey -v
zstyle ':prezto:module:editor:info:keymap:primary' format "❯%f"
zstyle ':prezto:module:editor:info:keymap:alternate' format "❮%f"
PROMPT='%(?.%F{magenta}.%F{red})${editor_info[keymap]} '
```
