### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by ghost** [sorin-ionescu/prezto#967]
I have a problem with some fonts for example Terminus.
Basically my sorin prompt looks like this
![2015-09-06-125459_129x33_scrot](https://cloud.githubusercontent.com/assets/10209103/9704274/92dd85ce-54a0-11e5-9c65-12f9e47c4d78.png)
and not like this (arch fallback font):
![2015-09-06-125816_297x47_scrot](https://cloud.githubusercontent.com/assets/10209103/9704279/da5969d6-54a0-11e5-8ab8-1311271bba9d.png)
I think this first occured after i tried the tamzen font.
Anybody knows what's going there?

!Xft settings:
Xft.antialias:		true
Xft.autohint:		false
Xft.dpi:			96
Xft.hinting:		true
Xft.hintstyle:		hintfull
Xft.rgba:	    		rgb

!Font (where cjb_font/fontsize are my currently defined font and fontsize)
URxvt\*font: xft:cjb_font:medium:pixelsize=cjb_fontsize
URxvt\*boldFont: xft:cjb_font:bold:pixelsize=cjb_fontsize
URxvt\*italicFont: xft:cjb_font:italic:pixelsize=cjb_fontsize
URxvt\*boldItalicFont: xft:cjb_font:bold:italic:pixelsize=cjb_fontsize

**Comment by jeffcox** [comment]
That is the default Terminus tilde character's position.  There is a variant which places it more in line with other fonts.  See the "Character variants" section here: http://terminus-font.sourceforge.net
