### ISSUE TITLE
Unconventional zsh configuration files source

### ISSUE THREAD

**Issue by hugdru** [sorin-ionescu/prezto#969]
I do not understand why in prezto environment variables that should be available to all programs are placed in .zshprofile. .zshprofile should only have login related stuff, pre .zshrc source, like scripts. Since .zshenv is sourced by all terminals types why not place them there?

https://wiki.archlinux.org/index.php/Zsh#Configuration_files
https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout

**Comment by sorin-ionescu** [comment]
It's a workaround against a Mac OS X problem, see #500.
