### ISSUE TITLE
Cursor and command prompt is not placed correctly in ssh-sessions

### ISSUE THREAD

**Issue by tomprogrammer** [sorin-ionescu/prezto#970]
At first the software I used while the problem occured:
Prezto is installed on the server with the sorin theme enabled. The problem occurs only when I connect over ssh to this server. The terminal used on the client is urxvt, terminfo files for it are installed on the server. Using xterm doesn't solve the problem.

As you can see on the first image the input is placed two characters before the actual editing position. After pressing <Enter> the complete prompt line is reformatted and displayed correctly. Especially while editing longer commands the 2-character shift is annoying, because I can't see what I'm editing. 
![misplaced_prezto](https://cloud.githubusercontent.com/assets/57975/9836740/db841340-5a24-11e5-908c-7ab6a808d75a.png)

You can see another example in the second image. The prompt was filled with `openssl x509 -in my-certificate.crt -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64`, then I typed `clear` at the beginning of the prompt.
![misplaced_prezto2](https://cloud.githubusercontent.com/assets/57975/9836788/c68ea20a-5a26-11e5-8754-b10f8c7c0aea.png)

These are just two examples, I'd like to provide some technical information but I don't know the shell and prezto well. If you need more information just ask, I try to collect information.

Thanks!

**Comment by sorin-ionescu** [comment]
Do other prompt themes have this problem? Look in *modules/prompt/functions/* for another theme. Try them out.

**Comment by tomprogrammer** [comment]
I tried the themes `minimal`, `peepcode`, `steeef` and `pure`. All of them don't show the errorneous behaviour I've seen with `sorin`.

 Additionally after switching to `pure` I got the error `editor-info:9: bad math expression: operand expected at `%B%F{1}\M-b\M-^]\M-/...'`. This maybe only outdated code?

**Comment by clempat** [comment]
I got the same problem. I solved it setting ```LC_CTYPE=UTF-8 ``` in ```/etc/locale.conf```

I personally have: 
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en_GB:en
LC_CTYPE=UTF-8
```

**Comment by tomprogrammer** [comment]
The problem persists with my configuration:
```
~ ❯❯❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
~ ❯❯❯ localectl
   System Locale: LANG=en_US.UTF-8
```
My version of the zsh is `5.1.1`.

**Comment by clempat** [comment]
With LC_CTYPE=UTF-8 without the language... Not sure it will help

**Comment by tomprogrammer** [comment]
I didn't have a proper `LANG` set on the server, which caused the problem shown in the description of this issue. That one is solved for me.

The second problem, when switching to the `pure` theme isn't solved though. It makes no difference whether I use `LC_CTYPE=en_US.UTF-8` or `LC_CTYPE=UTF-8`.

Should I open another issue covering that issue and close this, to keep a one-to-one relationship between problem and issue report?

**Comment by sorin-ionescu** [comment]
I can't reproduce.

**Comment by jbbr** [comment]
I had this problem too. Simply adding "LANG" to locale settings did work for me.
Adding "LC_CTYPE=UTF-8" without language identifier caused an error on (ssh) login.

My locale.conf is as simple as:
```LANG=en_US.UTF-8```

Thanks.
