### ISSUE TITLE
prompt_sorin_setup with user@hostname

### ISSUE THREAD

**Issue by nono21** [sorin-ionescu/prezto#971]
Hey there... How can I add the user@hostname to the sorin theme like in the picture attached?
![sorin](https://cloud.githubusercontent.com/assets/8270225/9839285/4eec58d0-5a4b-11e5-90c5-0185ccae5a1d.png)

Mine is like this now:
![screen shot 2015-09-13 at 19 12 24](https://cloud.githubusercontent.com/assets/8270225/9839289/70e2ef12-5a4b-11e5-9dd6-addfdad5a757.png)

**Comment by sorin-ionescu** [comment]
It only appears when you SSH.

**Comment by sjackman** [comment]
How do I get user@hostname to appear when I ssh? It doesn't automagically.
