### ISSUE TITLE
Consider icdiff instead of colordiff

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#973]
[icdiff](http://www.jefftk.com/icdiff) may be a good alternative to the `diff` function that wraps `colordiff` and `git diff`.

**Comment by chauncey-garrett** [comment]
I think `icdiff` is a great tool and I really appreciate its 2 column view but I wouldn't want it to override the conventional in-line diff view that comes (and would be expected) from typing `diff` out on the command line.

One the other hand, `git diff` would greatly benefit from [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy).

**Comment by mmlb** [comment]
+1 to the diff-so-fancy suggestion

**Comment by belak** [comment]
For now I believe we'll stick with colordiff.

icdiff does seem like a useful tool, but it shouldn't replace the default diff command because of how different it is. This is part of the reason we removed the git diff hack.
