### ISSUE TITLE
PROMPT remote vs local

### ISSUE THREAD

**Issue by alaricljs** [sorin-ionescu/prezto#982]
Please feel free to punt me to the right place, but I had zero luck googling up relevant docs much less the answer.

I am using a modified sorin theme for my prompt.  When I ssh into a server the prompt properly recognizes that I am connected remotely.  If I `su -` into another user with the same zsh/prezto config the prompt is `local` rather than `remote`.  

How is `local or `remote` determined so I can look into whether it can be changed to correctly deal with this situation?

**Comment by sorin-ionescu** [comment]
It [detects](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L134) the `$SSH_TTY` variable.
