### ISSUE TITLE
Disable auto-jump to a directory for a certain pattern

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#984]
Everytime I type `gulp` it automatically jumps me into the gulp sub-directory but I want to run the gulp command which exists in the path.

Prezto should exist whether the command exists in the path before jumping to the directory

```
~/D/smx3-frontend ❯❯❯ which gulp
node_modules/.bin/gulp
```

**Comment by Eriner** [comment]
what modules do you have enabled in your .zprestorc?

**Comment by binarykitchen** [comment]
```
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'ssh' \
  'git' \
  'node' \
  'syntax-highlighting' \
  'history-substring-search' \
  'completion' \
  'prompt'
```

**Comment by Eriner** [comment]
read https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/README.md

There are options to solve your problem. It is likely `CDABLE_VARS`. See if disabling that OPT fixes your issue, if not, remove the 'directory' module. That will fix your problem for sure.

**Comment by Eriner** [comment]
These set **zsh** options, so this is **not an issue specific to prezto**. This issue can be closed.

**Comment by binarykitchen** [comment]
thanks. unsetting AUTO_CD did the trick.
