### ISSUE TITLE
Configure sorin theme to display full directory names

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#985]
Currently it abbreviates, i.E. `~/D/smx3-frontend` where D should be Development.

How can this be adjusted?

**Comment by Eriner** [comment]
Read the prompt code, or use a different prompt. There is documentation available. This is not an issue with Prezto. Please close.

**Comment by binarykitchen** [comment]
Had a look at https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup and it looks like there is no simple way to alter that. And couldn't find any related documentation.

**Comment by Eriner** [comment]
You have two clear options. Modify the code to display the directories as you want, or use a different prompt that displays the full path.

**Comment by binarykitchen** [comment]
@Eriner thanks, I figured that out too. Do not want to use a different prompt as I think it's the prettiest of all of them.

Modifying the code? How does this work? All is managed with git and if I change one, then it gets overwritten on the next git pull.

**Comment by Eriner** [comment]
learn to use git stash, or fork the project.

**Comment by Eriner** [comment]
This issue should be closed, as it is not a problem with prezto.

**Comment by tiffwu** [comment]
I've landed on this place twice in the past couple years, looking for this information. 

In case anyone has the same question, this is what worked for me:

In `prompt_sorin_setup`, approximately line 135, change this:
```PROMPT='${SSH_TTY:+"%F{9}%n%f%F{7}@%f%F{3}%m%f "}%F{4}${_prompt_sorin_pwd}%(!. %B%F{1}#%f%b.)${editor_info[keymap]} '```
...to this:
```PROMPT='${SSH_TTY:+"%F{9}%n%f%F{7}@%f%F{3}%m%f "}%F{4}%~%(!. %B%F{1}#%f%b.)${editor_info[keymap]} '```

**Comment by indrajitr** [comment]
@tiffwu, Mangling isn't recommended, instead use [Prompt Display Length](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt#prompt-display-length-1) configuration.

**Comment by tiffwu** [comment]
That's odd -- even when I set it to 'long', I still get the short names.

**Comment by belak** [comment]
I'm seeing that as well. Looks like there's a bug in that handling.

**Comment by binarykitchen** [comment]
yes, i can confirm, i have it set to `long` but it's not working. must be a bug.

**Comment by thor85** [comment]
I have it set to full with the pure prompt, but it's not expanding ~

**Comment by jeffwidman** [comment]
@thor85 open a new bug report, including details to reproduce. Chiming in on old issues unfortunately most of the time just gets lost in teh noise.
