### ISSUE TITLE
git-info disapeared, git-info on doesn't work

### ISSUE THREAD

**Issue by mischaboldy** [sorin-ionescu/prezto#987]
My git information is no longer showing in my terminal. I know this issue has been reported in #369. However the `git-info on` cmd does not work for me. I get a terminal reply `zsh: command not found: git-info`. I also have git enabled in `zstyle ':prezto:load' pmodule \`.
Not sure if an issue is the right way to ask this question but I figured i'd give it a try. (i'm a bit of a newb)

**Comment by andzno1** [comment]
I love how you shared your solution with others.

**Comment by mischaboldy** [comment]
Not sure if you wanted me to explain my solution or this was just a sarcastic comment.
It's been a while but I'm pretty sure I just made a typo in my .zshrc file or a similar file used for terminal settings.

**Comment by andzno1** [comment]
It was both actually ;)

**Comment by tamoyal** [comment]
I actually had to edit the `zpreztorc` adding the `git` line to fix this:

```
zstyle ':prezto:load' pmodule \
...
  'git' \
...
```
