### ISSUE TITLE
Avoid calling ypcat if not installed

### ISSUE THREAD

**Issue by gdetrez** [sorin-ionescu/prezto#990]
On fedora 22, each time I try to auto-complete a hostname (e.g. `ssh ` + TAB), I get ` Install package 'yp-tools' to provide command 'ypcat'? [N/y]` printed 3 times in the middle of my command prompt. This is a minor annoyance, and I should probably just install yp-tools and move on but ideally zsh should only call `ypcat` if it is present in the system.

**Comment by laytoneverson** [comment]
+1

**Comment by sorin-ionescu** [comment]
The [completion module](https://github.com/sorin-ionescu/prezto/blob/master/modules/completion/init.zsh#L97) is your problem. Just install it. It's found by default on other systems.

**Comment by bsidhipong** [comment]
That's not a reasonable solution, Sorin.  These days, it's perfectly reasonable to leave out any trace of NIS, and not having ypcat installed while tabbing through hostname completion in scp is fairly invasive.

**Comment by jpts** [comment]
+1 Just come across this whilst trying to debug the ypcat error. I have no use for NIS, especially in a home environment.

**Comment by meghprkh** [comment]
This issue is ocurring again. (Though I just installed `yp-tools`)

**Comment by bruteforks** [comment]
this is still an issue

**Comment by leppaott** [comment]
Same issue. Seemed that it would start looping the "do you want to install yp-tools..." and it will cause unstable/slow terminal even after it seems it would've been terminated.
