### ISSUE TITLE
"Command not found" - but it is in my current directory?

### ISSUE THREAD

**Issue by binarykitchen** [sorin-ionescu/prezto#992]
This is weird. When I have a certain command in my current directory, it won't find nor execute it. But with `./` it does. Here an example with `gulp`:

```
~/D/s/n/.bin ❯❯❯ gulp
zsh: command not found: gulp
~/D/s/n/.bin ❯❯❯ ./gulp
[14:02:53] Requiring external module coffee-script/register
... // it works
```

**Comment by binarykitchen** [comment]
btw: `ls -la` shows gulp in this directory

**Comment by Eriner** [comment]
This is intended, as it is not in your path. This is also not a prezto issue. You need to stop making issues on the prezto issue tracker for things that are not specific to prezto. This is the fourth time you have done this.

**Comment by Eriner** [comment]
`export PATH=$PATH:.`

**Comment by binarykitchen** [comment]
thanks - yeah i know i ask a lot but the problem is that i often do not know what really caused it. never had the above issue before i installed prezto, that's why my initial guess.

**Comment by PaBLoX-CL** [comment]
That's a potential security issue to add the current directory in your `PATH`, never do that.

**Comment by Eriner** [comment]
Exactly my point
