### ISSUE TITLE
Opening specific file or directory in Sublime Text using iTerm2 & Prezto

### ISSUE THREAD

**Issue by brianjking** [sorin-ionescu/prezto#997]
I just switched over about an hour ago from oh-my-zsh to Prezto and am trying to get everything situated and am hoping you can help me out!

I was using Oh-My-Zsh and was able to navigate to a given directory and execute ```stt ``` to open that directory in Sublime Text. Is there a way to configure this setup with Prezto that I may be missing?

I'm on OS X 10.11 using iTerm2 and Sublime Text 3.

Thanks!

**Comment by tycooon** [comment]
Does `stt .` work? What's the output of `which stt` command?

**Comment by brianjking** [comment]
@tycooon 

````
 brianjking@bk-mbp13  ~  stt
zsh: correct 'stt' to 'stty' [nyae]? n
zsh: command not found: stt
 ✘  brianjking@bk-mbp13  ~  stt .
zsh: correct 'stt' to 'stty' [nyae]? n
zsh: command not found: stt
````

**Comment by brianjking** [comment]
@tycooon -- I wouldn't expect this to work right now as it was a plugin file I had to add to my old ```.zshrc``` file when using oh-my-zsh.

**Comment by tycooon** [comment]
Well, all you have to do is symlink `/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl` as `stt` somewhere in out `PATH` or create an alias.

**Comment by sorin-ionescu** [comment]
Use `subl`.

**Comment by brianjking** [comment]
@sorin-ionescu Ok, how can I set this up?

```
brianjking@bk-mbp13  ~/documents/dev/dockdogs/dd-scheduling   master ± subl
zsh: correct 'subl' to 'ul' [nyae]? n
zsh: command not found: subl
 ✘  brianjking@bk-mbp13  ~/documents/dev/dockdogs/dd-scheduling   master ±
```

**Comment by sorin-ionescu** [comment]
@brianjking, read https://www.sublimetext.com/docs/3/osx_command_line.html.

**Comment by brianjking** [comment]
@sorin-ionescu I"m using Sublime Text 3 and attempted to run that symlink and here's what I got:

```
 brianjking@bk-mbp13  ~  ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" ~/bin/subl
ln: /Users/brianjking/bin/subl: No such file or directory
```

**Comment by sorin-ionescu** [comment]
That was an example. You can install it in any location on the path, for example, /usr/local/bin.

**Comment by brianjking** [comment]
Got it working, thanks.
